### ISSUE TITLE
Technitium just to buggy for real use

### ISSUE THREAD

**Issue by GChester** [TechnitiumSoftware/DnsServer#10]
I have been using Technitium in our development environment for months now and I think it is just to buggy for real use.

There are Constant Lockups.  For example, right now I came to my computer in the morning and DnsService is running at 15% with over 3Gb of memory.

Most of the time you can not even kill the task in TaskMan.  The DnsService.exe is very difficult to kill when it has bugged out.

It requires Admin CMD prompt and a taskkill /f with the PID.

**Comment by ShreyasZare** [comment]
Hi @GChester 

Thanks for the feedback. Technitium DNS Server is indeed not ready for production use and thus still in beta. Right now its good for using directly on your laptop or on a small network with few users.

I would really like to know a bit about your setup to understand the load on the server. Can you give a brief info on the hardware you have and also the number of users that are using the DNS server? These details will be useful to understand and fix issues.

Regards,
Shreyas Zare

**Comment by GChester** [comment]
Shreyas,

Going back and forth for detailed information like this on Github is just so inefficient.

Is there another way to contact you so I can let you remote into the PC to have a look at whatever you need?

**Comment by ShreyasZare** [comment]
Hi @GChester,

We can schedule a short 30min Skype call this weekend. Let me know if Saturday or Sunday 14:00 IST works for you. You can email me for anything on shreyas@technitium.com.

Regards,
Shreyas Zare
