### ISSUE TITLE
bug: DnsServer tries to occupy all available UDPs port on Windows

### ISSUE THREAD

**Issue by garylavayou** [TechnitiumSoftware/DnsServer#1005]
## Brief Description of the Problem

DnsServer tries to occupy all available UDP ports on Windows. As far as I know, the only necessary UDP port required is `53` for the DNS service.

### DNS Server

```shell
Technitium DNS Server
Version 12.2.1

Server up since Aug 19, 2024 8:29 AM (5 minutes ago)
```

### Windows Version

```shell
OS Name:     Microsoft Windows 10 Professional
OS Version:  10.0.19045
```

## Related Snapshot

The following snapshots from Windows Resource Monitor show that `DnsService.exe` tries to occupy all available UDP ports.

![image](https://github.com/user-attachments/assets/73279790-32fe-40db-99ce-fd509cbe24a5)

![image](https://github.com/user-attachments/assets/28bb9d77-85e0-49e0-9d67-1004de6d3dea)

**Comment by ShreyasZare** [comment]
Thanks for the post. This is done for security reasons and the same is done by Microsoft DNS server. Please read issue https://github.com/TechnitiumSoftware/DnsServer/issues/782 for details.
