### ISSUE TITLE
DNS Server received a request that failed TSIG signature verification (RCODE: NotAuth; TSIG Error: BADKEY)

### ISSUE THREAD

**Issue by ghost** [TechnitiumSoftware/DnsServer#1009]
1. Setup example zone `domain.lan.` 
2. created tsig key with blank password for auto generation
3. edited zone to allow updates (dynamc&zone transfer) using tsig
4. Ran Terraform zone update
5. Receive Error

https://registry.terraform.io/providers/hashicorp/dns/latest/docs
```terraform
provider "dns" {
  update {
    server        = "192.168.1.4"
    key_name      = "domain.lan."
    key_algorithm = "hmac-sha256"
    key_secret    = "hmldGqDRUSxJWvMyiLKm5kgs3bJc2+xJh2FyN/jOJgk="
  }
}
resource "dns_a_record_set" "test" {
        zone = "domain.lan."
        name = "test"
        addresses = ["10.0.10.0"]
}
```

![image](https://github.com/user-attachments/assets/7a83e042-adee-49b9-a611-e8ad9e5bae64)
![image](https://github.com/user-attachments/assets/78cd7095-5976-4e71-82b5-c9f11ce97505)
![image](https://github.com/user-attachments/assets/695554a5-0f96-496f-9f07-f8648052bfac)

> 2024-08-19T17:15:15.936-0400 [INFO]  Starting apply for dns_a_record_set.test
> 2024-08-19T17:15:15.936-0400 [DEBUG] dns_a_record_set.test: applying the planned Create change
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: 2024/08/19 17:15:15 [DEBUG] Sending DNS message to server (192.168.1.4:53):
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; opcode: UPDATE, status: NOERROR, id: 26909
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; flags:; ZONE: 1, PREREQ: 0, UPDATE: 1, ADDITIONAL: 1
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; ZONE SECTION:
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;domain.lan.    IN       SOA
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; UPDATE SECTION:
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: test.domain.lan.        3600    IN      A       10.0.10.0
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; ADDITIONAL SECTION:
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; TSIG PSEUDOSECTION:
> 2024-08-19T17:15:15.938-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ; domain.lan.   0       CLASS255        TSIG     hmac-sha256. 20240819211515 300 0  26909 0 0
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: 2024/08/19 17:15:15 [DEBUG] Receiving DNS message from server (192.168.1.4:53):
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; opcode: UPDATE, status: NOTAUTH, id: 26909
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; flags: qr; ZONE: 1, PREREQ: 0, UPDATE: 0, ADDITIONAL: 1
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; ZONE SECTION:
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;domain.lan.    IN       SOA
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; ADDITIONAL SECTION:
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ;; TSIG PSEUDOSECTION:
> 2024-08-19T17:15:15.941-0400 [DEBUG] provider.terraform-provider-dns_v3.4.1_x5: ; domain.lan.   0       CLASS255        TSIG     hmac-sha256. 20240819211515 300 0  26909 17 0
> 2024-08-19T17:15:15.941-0400 [ERROR] provider.terraform-provider-dns_v3.4.1_x5: Response contains error diagnostic: tf_req_id=3c5852d7-1076-b4db-f011-a4c69004cea3 @caller=github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto tf_proto_version=5.4 diagnostic_summary="Error updating DNS record: dns: bad authentication" tf_provider_addr=registry.terraform.io/hashicorp/dns tf_resource_type=dns_a_record_set tf_rpc=ApplyResourceChange diagnostic_detail="" diagnostic_severity=ERROR timestamp=2024-08-19T17:15:15.941-0400
> 2024-08-19T17:15:15.946-0400 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
> 2024-08-19T17:15:15.946-0400 [ERROR] vertex "dns_a_record_set.test" error: Error updating DNS record: dns: bad authentication

**Technitium Log:**

> [2024-08-19 21:15:16 UTC] [192.168.1.146:50272] [UDP] DNS Server received a request that failed TSIG signature verification (RCODE: NotAuth; TSIG Error: BADKEY)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The issue seems to be due to the period `.` char at the end of the Key Name that you have entered on the DNS Server GUI. Removing the period char, and updating the zone's update security policy should fix this issue.

Will get validation code added for this in the upcoming update.

**Comment by ShreyasZare** [comment]
It seems my earlier response was not clear. You should continue to use FQDN domain ending with period `.` in your terraform config. But in Technitium DNS server, you need to use the full domain name without the ending period `.` char. 

This is how Technitium DNS server's GUI is designed to avoid use of relative domain names which may cause confusion for some users. The GUI always takes full domain name without need to add period `.` char. In almost all places, the ending period char gets removed but in the TSIG case, this was missing which is why you are seeing this issue.
