### ISSUE TITLE
Timezone for logs

### ISSUE THREAD

**Issue by jbhardman** [TechnitiumSoftware/DnsServer#1011]
I am running Technitium DNS in Podman container. I set the container to use my local timezone, America/Denver.

When I connect to the terminal in the container, and run the command `date`, it shows MDT.

All logs still show UTC.

How do I get it to recognize my timezone? OS is already set...

**Comment by ShreyasZare** [comment]
Thanks for asking. There is an option to use Local Time in Settings > Logging which you can enable for logs to be in the same time zone that you have in the container.

**Comment by jbhardman** [comment]
Thank you! I kept doing a text search on every page for "zone" and "timezone". Somehow missed it. Thanks a million.
