### ISSUE TITLE
Forwarded query fails due to RSSIG missing despite Allowed tab entry

### ISSUE THREAD

**Issue by dl12345** [TechnitiumSoftware/DnsServer#1014]
I'm running a docker instance of Technitium on a hosted virtual machine. This instance serves as the forwarder for my local network Technitium server and in turn forwards to Cloudflare and Quad9.

The Technitium instance on the VM is setup to use blocklists.

I have DNSSEC enabled on both servers, local network and hosted VM.

If I attempt to whitelist a site using the Allow tab, the query will still fail. I tested with only Quad9 as well as with both Cloudflare and Quad9 acting as forwarders and the result is the same.

The server on the VM (IP showing below as 192.168.1.1) resolves the query to a valid IP. However, the query forwarded and resolved by my local network Technitium fails due to the RRSIG missing).

I can only effect a whitelist in this scenario by adding the site to the Allowed tab AND adding a conditional forwarding zone switching off DNSSEC validation on my local server.

I suspect this issue may be related to [issue 890](https://github.com/TechnitiumSoftware/DnsServer/issues/890)

```user@host:~$ dig t.co

; <<>> DiG 9.21.0-1+ubuntu22.04.1+deb.sury.org+1-Ubuntu <<>> t.co
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 5058
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; EDE: 15 (Blocked): (source=block-list-zone; blockListUrl=https://easylist.to/easylist/easylist.txt; domain=t.co)
; EDE: 15 (Blocked): (t.co was blocked by 192.168.1.1)
; EDE: 10 (RRSIGs Missing): (co/SOA)
; EDE: 13 (Cached Error)
;; QUESTION SECTION:
;t.co.				IN	A

;; Query time: 119 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
;; WHEN: Mon Sep 02 17:36:06 BST 2024
;; MSG SIZE  rcvd: 184

user@host:~$ dig t.co @192.168.1.1

; <<>> DiG 9.21.0-1+ubuntu22.04.1+deb.sury.org+1-Ubuntu <<>> t.co @192.168.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1006
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;t.co.				IN	A

;; ANSWER SECTION:
t.co.			97	IN	A	172.66.0.227

;; Query time: 15 msec
;; SERVER: 192.168.1.1#53(192.168.1.1) (UDP)
;; WHEN: Mon Sep 02 17:37:03 BST 2024
;; MSG SIZE  rcvd: 49
```

Cache record on the VM server 192.168.1.1

```
[
  {
    "name": "t.co",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "172.66.0.227"
    },
    "dnssecStatus": "Insecure",
    "responseMetadata": {
      "nameServer": "9.9.9.9:853",
      "protocol": "Tls",
      "datagramSize": "49 bytes",
      "roundTripTime": "1.2 ms"
    },
    "lastUsedOn": "2024-09-02T16:37:03.1551922Z"
  },
  {
    "name": "t.co",
    "type": "DS",
    "ttl": "91 (1 min 31 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "NegativeCache: NoError; DnssecBogus: ; ldc0c7m112348qmhs09hokrvkepgubv6.co.  588       IN  NSEC3         1 1 0 - LDC4LEP8QU156F8RL7HUF2CRKB495JBF NS SOA RRSIG DNSKEY NSEC3PARAM, ldc0c7m112348qmhs09hokrvkepgubv6.co.  588       IN  RRSIG         50 8 2 900 1727384291 1724789030 19065 co. I4y0kMX7aW0JDQFxqUgyzcv1dv3pyCAk5JFe9ubr3gA/hP2yCgWA1JL8V+9pdoWYPpFw4njpggqGzMYRo3yDO9dTD9eezCUgYx5GB3+97++taPr3UTSRpC4PvKBWeLh5GcKJbUJyb5YgA9XIuytkoH6bBh+WgCJ3Xj82EIz+DrCaiROHmOrgs5DO01eOa1WkaAySGd/8X0uMl1VI5I3JVw==, co.                   722       IN  SOA           ns1.cctld.co. admin.tldns.godaddy. 1725294264 1800 300 604800 1800, co.                   722       IN  RRSIG         6 8 1 900 1727886264 1725290664 19065 co. CsrgQg2tyomtx0O6tN9jMX5/WSOsbrxLGIO7SwKc1rQNgCn7m3KHgqRo2f4MuhAENHK16U5mhpms74VLSfdU/QEwTPEpfM5ZY1zTG+aNZM7MocXaTa+aC/4J9AXOdgPJ6O/WNozFVxv/Ct142GjtRWSlFozTwZDs6U3u0LKrzG8K9wwRKLDxUIOxQk1sYNUYKdRCZiEqBgswiWveKBym4w==, 2b641mh1010thv3i41629d59t4grvmb5.co.  427       IN  NSEC3         1 1 0 - 2B6HQ4NNBNBQV6AICCD8CMBBKJJAFMSA NS DS RRSIG, 2b641mh1010thv3i41629d59t4grvmb5.co.  427       IN  RRSIG         50 8 2 900 1727534918 1724941360 19065 co. XDUsSvwMaqdNIW1p+1sJdVrcpUUbcav7mCdW0kASXr+CIEAPgECW44TVeiGaUG+tMaJ3Z+H5kFAZ0bCI/f4Q89Q5liUuBOdyLOcpSJVoEAMgUx8pQXb6vlTjnlQMtHkwpL6mQH9goJ9Du23Yr4dJ2TvPU8DGONr3JJx7z5F/2EIqsB1oG+I2uloeYrCfsmsiZLmNIDZFbjMX+v+OcxotLQ=="
    },
    "dnssecStatus": "Unknown",
    "responseMetadata": {
      "nameServer": "9.9.9.9:853",
      "protocol": "Tls",
      "datagramSize": "845 bytes",
      "roundTripTime": "1.14 ms"
    },
    "lastUsedOn": "2024-09-02T16:35:45.6754827Z"
  }
]
```

Cache record on the local network server

```[
  {
    "name": "t.co",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Blocked: source=block-list-zone; blockListUrl=https://easylist.to/easylist/easylist.txt; domain=t.co, Blocked: t.co was blocked by 10.100.0.1, RRSIGsMissing: co/SOA"
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2024-09-02T16:36:06.4937894Z"
  },
  {
    "name": "t.co",
    "type": "DS",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "BadCache: NxDomain; Blocked: source=block-list-zone; blockListUrl=https://easylist.to/easylist/easylist.txt; domain=t.co, Blocked: t.co was blocked by 10.100.0.1, RRSIGsMissing: co/SOA; co.                   60        IN  SOA           kz3.uk. hostadmin.kz3.uk. 1 14400 3600 604800 60"
    },
    "dnssecStatus": "Unknown",
    "responseMetadata": {
      "nameServer": "192.168.1.1",
      "protocol": "Udp",
      "datagramSize": "182 bytes",
      "roundTripTime": "26.89 ms"
    },
    "lastUsedOn": "2024-09-02T16:36:06.4903776Z"
  }
]```

**Comment by ShreyasZare** [comment]
Thanks for the post with details. 

> t.co was blocked by 10.100.0.1

The cache record on the local DNS server says that the domain `t.co` was blocked by 10.100.0.1 however, your upstream is 192.168.1.1. So this is kind of confusing info here.

> The server on the VM (IP showing below as 192.168.1.1) resolves the query to a valid IP. However, the query forwarded and resolved by my local network Technitium fails due to the RRSIG missing).

It seems that you need to do a bit more test queries to find out the issue since the info here does not seems sufficient. Do post any more details you find.

**Comment by dl12345** [comment]
> 
> The cache record on the local DNS server says that the domain `t.co` was blocked by 10.100.0.1 however, your upstream is 192.168.1.1. So this is kind of confusing info here.

That's because I failed to properly sanitise ALL the IP addresses when I manually edited the details. 192.168.1.1 = 10.100.0.1

**Comment by dl12345** [comment]
> > The cache record on the local DNS server says that the domain `t.co` was blocked by 10.100.0.1 however, your upstream is 192.168.1.1. So this is kind of confusing info here.
> 
> That's because I failed to properly sanitise ALL the IP addresses when I manually edited the details. 192.168.1.1 = 10.100.0.1

My upstream is over a wireguard link, hence the 10.0.0.0/8 address space.

**Comment by ShreyasZare** [comment]
Oh ok. I am not really sure what is happening here since your upstream is blocking the domain as per EDE in response but then it also answers when queried directly. This will need more debugging since the info here is limited.

**Comment by dl12345** [comment]
> Oh ok. I am not really sure what is happening here since your upstream is blocking the domain as per EDE in response but then it also answers when queried directly. This will need more debugging since the info here is limited.

Yes, that's correct. It's DNSSEC related - if I switch off DNSSEC on the downstream or put in a conditional forwarding zone that switches it off, then the problem resolves. 

Let me know what you need. Happy to run further tests

**Comment by ShreyasZare** [comment]
> > Oh ok. I am not really sure what is happening here since your upstream is blocking the domain as per EDE in response but then it also answers when queried directly. This will need more debugging since the info here is limited.
> 
> Yes, that's correct. It's DNSSEC related - if I switch off DNSSEC on the downstream or put in a conditional forwarding zone that switches it off, then the problem resolves.
> 
> Let me know what you need. Happy to run further tests

This issue is weird since your upstream DNS server has data in cache and your local DNS server says the upstream is blocking the domain in question. I would suggest that you flush the cache on both the DNS servers, check the upstream DNS server's forwarder settings once to confirm if it indeed is using Quad9 with DoT. Then check your local DNS server's forwarders and confirm if its using the correct IP address of your upstream.

Once you have inspected the config and flushed the cache then use the DNS Client tool on your local DNS server's admin panel to test the domain again. Repeat the same test on the DNS client on your upstream server's admin panel. Share the outputs of both the tests here.

**Comment by dl12345** [comment]
> > > Oh ok. I am not really sure what is happening here since your upstream is blocking the domain as per EDE in response but then it also answers when queried directly. This will need more debugging since the info here is limited.
> > 
> > 
> > Yes, that's correct. It's DNSSEC related - if I switch off DNSSEC on the downstream or put in a conditional forwarding zone that switches it off, then the problem resolves.
> > Let me know what you need. Happy to run further tests
> 
> This issue is weird since your upstream DNS server has data in cache and your local DNS server says the upstream is blocking the domain in question. I would suggest that you flush the cache on both the DNS servers, check the upstream DNS server's forwarder settings once to confirm if it indeed is using Quad9 with DoT. Then check your local DNS server's forwarders and confirm if its using the correct IP address of your upstream.
> 
> Once you have inspected the config and flushed the cache then use the DNS Client tool on your local DNS server's admin panel to test the domain again. Repeat the same test on the DNS client on your upstream server's admin panel. Share the outputs of both the tests here.

Prior to reporting this, I did of course flush the cache on both servers before doing the query.

I confirm the upstream forwarder is quad9 using DoT. I confirm the local server's forwarder is the upstream (10.100.0.1 is the correct address - it's a wireguard tunnel).

Output below. Domain names have been sanitised to local.dns and forwarder.dns

DNSSEC enabled on both local.dns and forwarder.dns. Both local.dns and forwarder.dns have t.co added on the "Allowed" tab.

Query performed on local DNS admin panel client to {this-server}

```
{
  "Metadata": {
    "NameServer": "local.dns (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "184 bytes",
    "RoundTripTime": "130.75 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 4096,
    "ExtendedRCODE": "ServerFailure",
    "Version": 0,
    "Flags": "None",
    "Options": [
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "93 bytes",
        "Data": {
          "InfoCode": "Blocked",
          "ExtraText": "source=block-list-zone; blockListUrl=https://easylist.to/easylist/easylist.txt; domain=t.co"
        }
      },
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "32 bytes",
        "Data": {
          "InfoCode": "Blocked",
          "ExtraText": "t.co was blocked by 10.100.0.1"
        }
      },
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "8 bytes",
        "Data": {
          "InfoCode": "RRSIGsMissing",
          "ExtraText": "co/SOA"
        }
      },
      {
        "Code": "EXTENDED_DNS_ERROR",
        "Length": "2 bytes",
        "Data": {
          "InfoCode": "CachedError",
          "ExtraText": null
        }
      }
    ]
  },
  "DnsClientExtendedErrors": [
    {
      "InfoCode": "NetworkError",
      "ExtraText": "local.dns (127.0.0.1) returned RCODE=ServerFailure for t.co. A IN"
    }
  ],
  "Identifier": 51982,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "ServerFailure",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "t.co",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "4096",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "151 bytes",
      "RDATA": {
        "Options": [
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "93 bytes",
            "Data": {
              "InfoCode": "Blocked",
              "ExtraText": "source=block-list-zone; blockListUrl=https://easylist.to/easylist/easylist.txt; domain=t.co"
            }
          },
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "32 bytes",
            "Data": {
              "InfoCode": "Blocked",
              "ExtraText": "t.co was blocked by 10.100.0.1"
            }
          },
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "8 bytes",
            "Data": {
              "InfoCode": "RRSIGsMissing",
              "ExtraText": "co/SOA"
            }
          },
          {
            "Code": "EXTENDED_DNS_ERROR",
            "Length": "2 bytes",
            "Data": {
              "InfoCode": "CachedError",
              "ExtraText": null
            }
          }
        ]
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

Query subsequently performed on upstream DNS admin panel client to {this-server}

```
{
  "Metadata": {
    "NameServer": "upstream.dns (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "49 bytes",
    "RoundTripTime": "0.85 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 4096,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "Identifier": 0,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 1,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "t.co",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "t.co",
      "Type": "A",
      "Class": "IN",
      "TTL": "40 (40 sec)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "172.66.0.227"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "4096",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

Flush cache on both servers. Disable DNSSEC on local DNS server. 

Repeat the query on local DNS admin panel client.

```
{
  "Metadata": {
    "NameServer": "local.dns (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "49 bytes",
    "RoundTripTime": "35.85 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 4096,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "Identifier": 0,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 1,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "t.co",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "t.co",
      "Type": "A",
      "Class": "IN",
      "TTL": "300 (5 mins)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "172.66.0.227"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "4096",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

**Comment by ShreyasZare** [comment]
Thanks for the details. I tested this and there is a bug in the code that checks if the domain is allowed for this case. Its since the request from the local DNS server tries to resolve DS record for t.co, while the domain is allowed, the DS record resides in the parent zone and thus the code would respond differently for this DS request causing it to be blocked. This in turn caused the local DNS server to fail to validate DNSSEC response.

Will get this bug fixed in the upcoming update. Will post here when the update is available.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 is now available that fixes this issue. Do update and let me know your feedback.
