### ISSUE TITLE
Feature request:  Support for DHCP-Relay and/or DHCP Hook Scripts

### ISSUE THREAD

**Issue by the-moog** [TechnitiumSoftware/DnsServer#1018]
I have a situation where I moved away from the very basic DNS/DHCP in a Mikrotik Router to Technitium.  That fixed all my DNS related issues and brought far better and easier to manage control over the local DNS.  But it has introduced another issue.

It is great that TN (approved abbreviation??) does DHCP with dynamic updates and auto-reverse IP, so I would not want to loose that, but it seems the lack of ARPs on the router for the generated IP is breaking things.  I think the switch between the DNS and the LAN is trying to be clever and blocking 'unknown broadcasts' and as DHCP uses broadcasts for discovery some hosts (but not all) struggle to resolve the IP address of the DHCP/DNS and so fail lookups and DHCP lease extensions.

I think having the ARP table up to date on the router would fix that, as once there is an ARP there can be a directed response and once the host makes a non-broadcast request to the DNS, then the switch will learn that MAC and stop blocking it's broadcasts.

And yes, I have tried turning off that feature in the switch, but I am fairly sure it also has bugs and though off still does this.  Methinks as a way to reduce the load on a 'cheap' managed switch. 

I was thinking that there needs to be a way for TN to either use an external DHCP server via a built in Relay, while maintaining consistency with it's own tables, or a way to call external scripts (e.g. a command over ssh) to update a remote DHCP server with additions, extensions and deletions.  This could be a very simple SSH or REST like call. e.g. "add|remove|query|update" address=1,2,3,4 mac=12:23:56:78 host="name" until|for=<time>"  Unless there exists some protocol for this?  Is RDHCP or DDHCP a thing?

**Comment by ShreyasZare** [comment]
Thanks for the post. DHCP Relay Agent feature is already found in most routers (not home ones) and thus there is no point in having such a feature implemented with the DNS server.

I am not sure about how your network is setup. Is there routing being done between multiple subnets? If yes, then you would need to configure DHCP Relay agent for DHCP to work well on all the subnets. 

I do not think there is any issue with ARP or broadcasts with the switch. If the switch indeed has such issues then its unusable and would need to be replaced.
