### ISSUE TITLE
Question: How to replace Primary DNS Server

### ISSUE THREAD

**Issue by tango38317** [TechnitiumSoftware/DnsServer#1019]
Hello,
i love you product, it´s working amazing.
but i have one question regarding replacing primary DNS Server.

We have one Primary DNS and a few Secondary DNS Server. What is the simplest way to replace the primary DNS Server?

is there a way to "promote" one to new primary or is it necessary to install a new server, import configuration and change the primary DNS server on all secondary DNS Server?

many thanks
Chris

**Comment by ShreyasZare** [comment]
Thanks for the post and compliments. Currently there is no option to do that automatically so, you will need to manually create a new primary server and re-configure all secondary zones.

The next update will have support for [Catalog Zones](https://bind9.readthedocs.io/en/latest/chapter6.html#catalog-zones) which will allow you to do that with a bit of ease. The next major update is planned to have full clustering support where this will be automatically handled.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 is now available that adds support for Catalog Zones.

There is another option if you wish to migrate your primary zones to another server. You can use the Backup Settings option where you select just the zones to include in the backup and then use the Restore Settings option in your target DNS server and select only zones to restore. You can test this once on a test setup on your laptop before trying it in production.
