### ISSUE TITLE
Custom Text/Logo?

### ISSUE THREAD

**Issue by kmorales026** [TechnitiumSoftware/DnsServer#1020]
Hello, It is possible to custom this Text and Logo?

![header](https://github.com/user-attachments/assets/584364b7-1836-4580-907d-0b3383799804)

**Comment by ShreyasZare** [comment]
Thanks for asking. There is no option to do that and white-labeling feature is not planned.

You can still do it by manually changing the image/html in the installation folder but you will need to change it each time after the DNS server is updated.
