### ISSUE TITLE
"Last year" graph is mislabeling the months

### ISSUE THREAD

**Issue by cob-web-corner** [TechnitiumSoftware/DnsServer#1023]
Small thing I found it's not major but figured I would report it. The metrics graph on the dashboard does not show the proper months for the metrics and it's missing the most recent month's data when selecting "Last Year" tab.

It looks like all of the months are 1 off

Picture from one of my instances:
![image](https://github.com/user-attachments/assets/af7986bc-eebe-47be-bb68-f3ba4521b848)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is due to time zone issue in the js code which is generating the custom API call. If you set your system's time zone to UTC then both the numbers would match.

Will get this fixed to match the values as expected.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The query count should match now but I am not able to reproduce the label issue for "Last Year" stats. I am getting the most recent month in all of my deployments:

![image](https://github.com/user-attachments/assets/5862d14f-8d90-4712-b689-5fffb6aae891)

Please let me know what timezone you have configured on your client and will try to have the same to see if this can be reproduced.

**Comment by ShreyasZare** [comment]
> This appear to be happening in UTC -4, UTC -7, and UTC -10. I dont have any clients conntected to this test server outside of those timezones so it could be happening in others as well. The server is currently configured to UTC-4 America/New_York

I was able to reproduce it. Will get it updated in the next update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.0.2 is now available that fixes this issue. Do update and let me know your feedback. Note to use Ctrl+F5 to reload admin panel after upgrade so that browser does not use cached pages.

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
