### ISSUE TITLE
[Feature Request]: Finer control over forwarders

### ISSUE THREAD

**Issue by dl12345** [TechnitiumSoftware/DnsServer#1029]
It would be very nice to have some additional finer control over forwarding behaviour. The first two of these options are similar to ones found in dnsmasq.

1. A toggle to force strict, sequential use of the forwarders instead of random (this is useful in a fault-tolerant use-case where the primary forwarder is only accessible over a network connection that fails and the secondary forwarder is accessible over the secondary link that remains, or where one forwarder consistently resolves faster than the other). This would equate to the dnsmasq option --strict-order.

2. A toggle to force simultaneous use of all forwarders and choose the fastest response (yes, this creates more network traffic, but can result in appreciably faster responses when one forwarder has the answer cached and the other doesn't). This would equate to the dnsmasq option --all-servers.

3. A toggle to allow fall-back to recursive resolution if none of the forwarders are available.

4. The ability to select the forwarder protocol on a per-forwarder-basis rather than globally for all forwarders.

**Comment by ShreyasZare** [comment]
Thanks for the request. 

The feature to have sequential use of forwarders is already implemented in the development code and will be available soon in the upcoming update. The new option "Concurrent Forwarding" when disabled will make the DNS server to do sequential forwarding.

The concurrent forwarding support is already available and you can set the Forwarder Concurrency option in settings to match the number of forwarders you have to allow querying them all at once and use the fastest response.

The option to fallback to recursive resolution is also implemented and will be available in the upcoming release. To configure this, you will need to create a Conditional Forwarder zone for `.` i.e. the root zone, and add FWD records which now support Priority option. With this, you can configure required forwarders to have higher priority and then add another FWD record which uses This Server as the forwarder with lower priority.

The ability to use different forwarder protocol is already available using the Conditional Forwarder zone for `.` i.e. the root zone. You can add FWD records in the root zone with different forwarders and different protocols as required.

Let me know if you have any more queries.

**Comment by dl12345** [comment]
Fabulous, that's great news. I didn't expect such instant gratification when requesting feature updates. Looking forward to the next release. Thanks again for a great piece of software.

**Comment by dl12345** [comment]
Fabulous, that's great news. I didn't expect such instant gratification when requesting feature updates. Looking forward to the next release. Thanks again for a great piece of software.
