### ISSUE TITLE
Real-time log viewer & query monitoring

### ISSUE THREAD

**Issue by ZzZombo** [TechnitiumSoftware/DnsServer#103]
I'd like to ask for a proper customized log viewer, updated in real time. Its options should include maximum displayed lines, search and filtering. The current is cumbersome to use, and should remain separate as is simply for displaying archived logs.

I'm also disappointed that it's not possible to see all queries and responses neatly in a nice GUI. You can enable logging of all queries and collect them manually, but I feel because it's such an important part of the whole thing, it should also get its own dedicated real time monitor.

**Comment by KaiGartenschlaeger** [comment]
I would prefer to have an extendable interface to use storages like [graphite](https://graphiteapp.org) to display the metrics in tools like [grafana.](https://grafana.com/).

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will try to get some good UI to view logs. However, there are some core DNS features that are still pending which will be implemented with priority.

**Comment by echodreamz** [comment]
Ill +1 my vote for this as well :)

**Comment by Cossey** [comment]
I second @KaiGartenschlaeger 's suggestion about being able to have stats show on Grafana if possible. 

Seeing real time queries would be awesome too.

**Comment by DRSDavidSoft** [comment]
Here's a list of what I'm interested to see in real time log:
1. Client IP
2. Request DNS
3. Type of response (e.g. A, hinfo, etc)
4. Time of request

**Comment by kopacko** [comment]
If you are wanting real-time data on DNS queries. Setup filebeat (does this in real-time) and pipe the logs to an ELK stack server.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with a new Query Logs (Sqlite) DNS App that now supports logging with a GUI on the DNS web panel to query the app. Do update and let me know if any changes are required. Closing this issue for now.

**Comment by ZzZombo** [comment]
@ShreyasZare: I've tried your application, and found that it's not a real time request monitor, just a log viewer with better UI.

**Comment by ShreyasZare** [comment]
> @ShreyasZare: I've tried your application, and found that it's not a real time request monitor, just a log viewer with better UI.

Its not exactly real-time but you get data in there with a max delay of 10 seconds. This delay is due to batching all the data before writing it to the sqlite database. Writing to sqlite without batching affects the performance severely.

**Comment by ZzZombo** [comment]
Sorry, but it's not a real time monitor by any measure. You have to hit the "Query" button every so often if you want to emulate that experience. Did you ever use say, Sysinternals Process Monitor? Every new event is displayed right away, you can filter the output and so on. Something like that is what I want but for DNS lookups.

**Comment by ShreyasZare** [comment]
> Sorry, but it's not a real time monitor by any measure. You have to hit the "Query" button every so often if you want to emulate that experience. Did you ever use say, Sysinternals Process Monitor? Every new event is displayed right away, you can filter the output and so on. Something like that is what I want but for DNS lookups.

I agree its not real time. Making something like the sysinternal tool over web will be extensive work requiring making new backend and frontend that works over websocket to relay real time data. That would be time consuming to implement and since there are many features already in pipeline, such a feature will come only later.
