### ISSUE TITLE
Question: How to set up custom TLD Resolvers?

### ISSUE THREAD

**Issue by luigiminardim** [TechnitiumSoftware/DnsServer#1035]
I'm trying to configure the Technitium DNS Server to resolve queries for a custom top-level domain, `.custom-tld`. I've added entries to the named.root file to point to my custom resolver, but I'm unsure if this is the correct approach.

```zone
# DnsServerCore/named.root

# ...
CUSTOM-TLD.                              3600000      NS   CUSTOM-TLD.
CUSTOM-TLD.                               3600000      A     0.0.0.0 # localhost
#...
```
## Questions

1. Is this the correct way to configure Technitium DNS Server for a custom TLD?
2. I've found the zone file to configure the roots (`DnsServerCore/named.root`) but I wasn't able to figure out where it is being used in source code. so, how can I ensure that the custom resolver is used only for .custom-tld queries and not for other domains?
3. Are there any specific settings or configurations using Docker-Compose for Technitium DNS Server that I need to adjust for this?

## Desired Archtecture

```mermaid
sequenceDiagram
    participant Technitium
    participant custom_tld as Custom TLD
    participant root as Root Server
    Technitium->>custom_tld: Quering any-label.custom-tld
    Technitium->>root: Quering any-label.not-custom-tld
```

**Comment by ShreyasZare** [comment]
Thanks for asking. You just need to create a Stub zone for your custom TLD which will allow you to resolve and domain names under it. 

You can read issue #272 which shows stub zone creation for OpenNIC TLD.

**Comment by luigiminardim** [comment]
Thanks for your help! @ShreyasZare! I don't know what I'm doing wrong, but I'm getting this error when I try to add my localhost server as a stub server:

![image](https://github.com/user-attachments/assets/2297fbbc-e5bb-4652-93f5-33f77f949a16)


It's still not clear how I could turn my local server a TLD nameserver.

**Comment by ShreyasZare** [comment]
Thanks for the screenshot. You cannot run a custom domain or TLD on non-standard port number. You must configure your DNS server running the TLD zone to use port 53. Once its done, you should be able to create the Stub zone for it. The reason for this is that recursive resolution uses only port 53 and will not work with any non-standard port.

Also note that the primary server for which you enter the  IP address for must be authoritative for that domain/TLD. It cannot be just a forwarder/DNS proxy. I am assuming that `0.0.0.0` is just a placeholder IP address for this screenshot.

**Comment by luigiminardim** [comment]
@ShreyasZare, the 0.0.0.0 IP I used is my local host server but not just a forwarder/DNS proxy. I'm building my own TLD server and would like to test it. My TLD server is using an internal logic to produce the DNS records. To be more precise, I'm fetching some data stored in a blockchain to derive the DNS zones and records covered by the `.custom-tld` domain. So, I just wanted the Technitium server to query from my local server when it resolves from `.custom-tld` domains.

Thanks a lot for your help so far. I appreciate your cordiality.

**Comment by ShreyasZare** [comment]
> @ShreyasZare, the 0.0.0.0 IP I used is my local host server but not just a forwarder/DNS proxy. 

If you are using `0.0.0.0` literally then its not going to work since its not a valid IP address. You need to use `127.0.0.1` to connect to your locally running server.

> I'm building my own TLD server and would like to test it. My TLD server is using an internal logic to produce the DNS records. To be more precise, I'm fetching some data stored in a blockchain to derive the DNS zones and records covered by the `.custom-tld` domain. So, I just wanted the Technitium server to query from my local server when it resolves from `.custom-tld` domains.

That's nice but since you need the TLD to be able to allow recursive resolution, the TLD server must run on port 53. In that case, there will be port conflict since both your local TLD server and the Technitium DNS server would want to use same port. So, you will need to run both of them on separate servers.

Note that you cannot just use Conditional Forwarder zones in such case if you are planning to delegate subdomain zones on your custom TLD to different servers. Which is why Stub zone is needed in such case.

> Thanks a lot for your help so far. I appreciate your cordiality.

You're welcome.
