### ISSUE TITLE
Notify failed for all domains

### ISSUE THREAD

**Issue by zs311521** [TechnitiumSoftware/DnsServer#1036]
Hi,

It says notify failed for all of my domains. I have a secondary dns set up via KJSL. 

I have Allow Both Zone Name Servers And Specified Name Servers and Both Zone Name Servers And Specified Name Servers enabled with KJSL IPs specified. 

On the dns client it picks up KJSL as a successful secondary dns resolver so it seems fine from a testing point of view.  All other logs seem ok. Could it be a UI bug?

**Comment by ShreyasZare** [comment]
Thanks for the post. You need to use the "Allow Only Specified Name Servers" option here and enter the IP addresses of all your name servers along with KJSL one.

The reason for this is that the KJSL name server does not accept NOTIFY requests and needs you to configure a separate IP address to notify. And your current config will try to notify the KJSL name server and will mark it as Notify Failed.

**Comment by zs311521** [comment]
> Thanks for the post. You need to use the "Allow Only Specified Name Servers" option here and enter the IP addresses of all your name servers along with KJSL one.
> 
> 
> 
> The reason for this is that the KJSL name server does not accept NOTIFY requests and needs you to configure a separate IP address to notify. And your current config will try to notify the KJSL name server and will mark it as Notify Failed.

Fixed!! Thanks a million.
