### ISSUE TITLE
Querying for a list of all SRV resource record types for a domain? Is this possible?

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#1037]
Apologies if these are not a DnsServer-specific questions... 

1. Is it possible to query for a list of all the SRV resource records for a particular domain?

2. If a name starts with an underscore (e.g. _foo.bar.com) and let's say it is an A records, these records (starting with an underscore) don't seem to be returned in an ANY query?  Is this expected behavior? Is it possible retrieve a list of these without specifically querying for each specific name?

Thank you

**Comment by ShreyasZare** [comment]
Thanks for asking. DNS does not have any mechanism to do that. The ANY query is also not guaranteed to return all records. Its supposed to return "any" records it has for the domain and not "all" records. So, a non-authoritative DNS server, i.e. a resolver, may return just the records it has in its cache.
