### ISSUE TITLE
TOR

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#1039]
Hi, after the update i cant query cloudflares hidden dns anymore. Serv fail. Happens on both my dns servers. Had to change forwarders to normal cloudflare. Both servers runs their own tor proxies and both are still up.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. It seems that the changes broke this somehow. Will get that fixed and release an update as soon as possible and let you know here.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.0.1 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by ChristoffBo** [comment]
Hi, works perfectly. Thank you very much. And thank you for this wonderfull
software.

**Comment by ShreyasZare** [comment]
Thanks for the feedback and compliments!
