### ISSUE TITLE
How to configure a local DnsServer to support TLS on Windows 10?

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#104]
I'm guessing this is a bit of a "newbie" DNS question.

I can successfully query my `localhost` DnsServer instance to resolve `apple.com` over `Udp` and `Tcp` ...but it fails when I try to use `Tls` as a protocol.  

What do I need to go to my local (localhost) configuration to get queries over `Tls` to work on Windows 10?

Thank you, Michael

**Comment by ShreyasZare** [comment]
Thanks for the post. You will need to configure TLS only if you have any clients or software that support DNS-over-TLS or DNS-over-HTTPS protocols. For all common use cases, there is no need to have TLS configured.

To configure TLS, you will need to get a domain validated SSL/TLS certificate. Either you can purchase a certificate or you can get it for free from Lets Encrypt (which needs to be renewed every 3 months).

In the Settings tab on the DNS server web console, you will find section to enable DNS-over-TLS and DNS-over-HTTPS. There you can specify the certificate file (in pfx format) and enable the protocols using the checkbox. Once done, restarting the DNS Server will enable those protocols.

To generate pfx file format from the usual .crt file (PEM format) you can use the following command:
`openssl pkcs12 -export -out "example.com.pfx" -inkey "private.key" -in "certificate.crt" -certfile "ca_bundle.crt"
`

As of now, the DNS Server does not support automatic renewal of Lets Encrypt certificates but this feature is planned for future release. For now, if you want automatic renewal for Lets Encrypt, then you can use nginx webserver and configure it with SSL/TLS TCP termination which forwards the connection to the DNS server's TCP port. With nginx, you can setup automatic Lets Encrypt certificate renewal using certbot or similar software depending on your OS platform.
