### ISSUE TITLE
DNS-over-HTTPS settings not respected in 13.0

### ISSUE THREAD

**Issue by hcuk94** [TechnitiumSoftware/DnsServer#1040]
My instances updated automatically last night to the latest Docker Hub image published yesterday, and have since stopped working.
On investigation, it seems that the forwarder settings are no longer being respected. Instead, the server is attempting to use root hints over UDP 53 (perhaps the default behaviour?) to resolve queries.
Including a screenshot of my settings page below.
The proxy settings appear to be respected but not the Forwarder settings, as currently I see UDP 53 attempts being denied in my proxy logs:
`1727074958.534      0 10.110.20.10 TCP_DENIED/403 3770 CONNECT 202.12.27.33:53 - HIER_NONE/- text/html
1727074958.536      0 10.110.20.10 TCP_DENIED/403 3770 CONNECT 193.0.14.129:53 - HIER_NONE/- text/html
1727074958.538      0 10.110.20.10 TCP_DENIED/403 3768 CONNECT 199.7.83.42:53 - HIER_NONE/- text/html
1727074958.541      0 10.110.20.10 TCP_DENIED/403 3768 CONNECT 192.33.4.12:53 - HIER_NONE/- text/html`

![technitium_settings](https://github.com/user-attachments/assets/6977180a-af5f-41f5-9a7e-a76dc7999dec)

**Comment by hcuk94** [comment]
Just to add, I did try rolling back to the 12.2.1 tag from Docker Hub, but got an error about my config version mismatching, so I guess that has been upgraded with the new image. If there is no immediate fix I can restore my previous config from server backups but wanted to report this first.

**Comment by ShreyasZare** [comment]
Thanks for reporting this. Will try to reproduce this issue and get an update available as soon as possible.

**Comment by ShreyasZare** [comment]
I think I have found the issue and there is a workaround for it. You can try to resolve the `<subdomain>.cloudflare-gateway.com` independently using [dnsclient.net](https://dnsclient.net/) tool and put its IP address in the forwarder config in round brackets like below: 

`https://<subdomain>.cloudflare-gateway.com/dns-query (a.b.c.d)`

Where `a.b.c.d` is the IP you resolved separately.

Let me know if this workaround fixes this issue for now.

**Comment by hcuk94** [comment]
Thanks - yep, that's working as a workaround for now - I don't get all the features of the Cloudflare service as it won't tie the queries to my account without the domain name, but as a temporary solution to get DoH its working for sure. Thanks 👍

**Comment by ShreyasZare** [comment]
> Thanks - yep, that's working as a workaround for now - I don't get all the features of the Cloudflare service as it won't tie the queries to my account without the domain name, but as a temporary solution to get DoH its working for sure. Thanks 👍

Thanks for confirming, an update with this fix will be done soon. You would still be using the same subdomain name in the DoH URL so it should work to map to your account.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.0.1 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by hcuk94** [comment]
Thanks! The update is working perfectly for me. Really appreciate the swift response.

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
