### ISSUE TITLE
How Can I use the DnsServer in the windows 10

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#105]
How Can I use the DnsServer in the windows 10 can you make a video because I make everything but it's not working

**Comment by ShreyasZare** [comment]
If you have installed the DNS server setup then you will find DNS Server Tray App which you can use to auto configure your computer to use the DNS server. 

Just start the app and you will find its icon in the Windows 10 system tray. Right click on the icon and click on the **Network DNS > Technitium** menu item. This will automatically configure your computer to use the locally running DNS server.

If you have any more queries do send an email to support@technitium.com.
