### ISSUE TITLE
Invalid character in DHCP Hostname request causes DNS to not create for PRIMARY region when DHCP is created

### ISSUE THREAD

**Issue by BoGs** [TechnitiumSoftware/DnsServer#1051]
I have some HP iLo management that seem to be offering their hostname that have special characters in the hostname offered to the DHCP server. It shows up in the logs like `^@` which does create the lease properly for `example.home.internal` but the DNS A record for the `example` in the `home.internal` PRIMARY zone is not created since the `if` statement might not be matching. 

```
[2024-09-26 17:55:19 UTC] [192.168.1.100:68] DHCP Server leased IP address [192.168.1.100] to EXAMPLE^@ [AA-AA-AA-AA-AA-AA] for scope: home internal
[2024-09-26 17:55:19 UTC] [192.168.1.1:67] DHCP Server leased IP address [192.168.1.100] to EXAMPLE^@ [AA-AA-AA-AA-AA-AA] for scope: home internal
```

It seems the tcpdump is showing the client offer an invalid hostname (I changed the hostname to EXAMPLE so length will not match)

```
Hostname (12), length 14: "EXAMPLE^@"
```

The hostname is filtered properly for the DHCP lease list to show `example.home.internal` with the proper ip address.

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS entry for the client will be made only if the hostname does not have invalid characters that DNS does not support. If the DNS entry is still not being made after changing the hostname then the DHCP packet will needs to be checked. I possible do share the pcap file that you captured with tcpdump to support@technitium.com. This will allow understanding the issue better.

**Comment by BoGs** [comment]
I changed the DHCP to be a reservation on the mac address and it worked fine, my point was just that if the option exists for DHCP advertised hostnames to be automatically added to the DNS zone, that process should sanitize the hostname to ensure that only valid characters for DNS are making it through. As I think the DHCP lease does as the special characters are not showing up. 

The invalid characters come all the way from client -> relay -> dhcp server -> relay -> client based on the advertised hostname the client sends out. I am guessing that might be a bug in the client code as the special characters do not show up in the ui but regardless.

**Comment by ShreyasZare** [comment]
What special character you see in there may not be the exact same characters but just a representation. The hostname shown in lease are not modified and if you do not see those special chars in there then its just that those non-printable characters are not rendering in the HTML.

Will get the code updated to remove invalid characters.
