### ISSUE TITLE
DHCP

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#1057]
Hi, for some odd reason my servers decided to renew the DHCP leases to random once not the static ones set in the reserved list.

Is there a command i can run to release all ip addresses leases without removing the set reserved ones?

**Comment by ShreyasZare** [comment]
Thanks for asking. There is no such option to remove leases in bulk. You will need to manually remove them or use a script with HTTP API for the task.

I would suggest to enable "Ignore Client Identifier (Option 61)" option in your DHCP scope to avoid such issues in future.

**Comment by ChristoffBo** [comment]
thank you very much as always sir.

**Comment by ShreyasZare** [comment]
You're welcome.
