### ISSUE TITLE
DHCP Reserved Hostnames modified after last update

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/DnsServer#1058]
I've been trying to figure out why a bunch of my cameras went offline Monday morning.
I have finally narrowed it down to the DHCP reservation was modified on the most recent update.

Previously I had `192.168.2.10` as `garage.cam.net.domain.com`
After the update, it was modified to `garagecam.net.domain.com`

Not a huge deal, but unfortunately I cannot modify the reservation without deleting an re-creating it.

**Comment by ShreyasZare** [comment]
Thanks for reporting this. The last update added code to remove invalid characters from hostname and looks like its removing the `.` char too. Will get this fixed with an update soon and let you know.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.1 is now available that fixes this issue. Do update and let me know your feedback.

Note that the new lease will get the hostname with the `.` char like before.

**Comment by djarbz** [comment]
Can confirm, is working.

Thanks

**Comment by ShreyasZare** [comment]
Thanks for confirming.
