### ISSUE TITLE
[BUG] groups permissions not working properly 

### ISSUE THREAD

**Issue by rana-Alotaibi1** [TechnitiumSoftware/DnsServer#1059]
Hello, I upgraded to version 13.0.2

when creating a new group with specific permissions , in my case 

Zone admins where the group members will only handle zones only 

the users added to the group will not have the permissions to view, modify, delete zones

**Comment by ShreyasZare** [comment]
Thanks for the post. This is by design and a group/user need to have zone level permissions to be able to access it. The Zones section permission just allows the user/group to be able to view/create/modify/delete the zones for themselves.

**Comment by rana-Alotaibi1** [comment]
many thanks , clear now 

closing
