### ISSUE TITLE
Validate port numbers in settings

### ISSUE THREAD

**Issue by IngmarStein** [TechnitiumSoftware/DnsServer#1062]
I recently needed to change the DNS-over-HTTPS port number due to port conflict and accidentally entered "80443" which is not a valid port number. This saved successfully, but when I restarted the container, it started crashlooping because of the error produced in https://github.com/TechnitiumSoftware/DnsServer/tree/master/DnsServerCore/Dns/DnsServer.cs:4428 (`serverOptions.Listen(localAddress, _dnsOverHttpsPort, delegate (ListenOptions listenOptions)`) .

This is all expected, but really hard to fix. Essentially, I used a hex editor to change the port number in `dns.config`. Ideally, it should not have been possible to store the invalid number in the first place. Alternatively, it could be possible starting the server without the optional services if one of them fails.

**Comment by ShreyasZare** [comment]
Thanks for reporting this issue. Will get this fixed in the next update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.1 is now available that fixes this issue. Do update and let me know your feedback.
