### ISSUE TITLE
Settings do not appear

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#1066]
OS : ubuntu 18.04
Version : 13.0.2

![image](https://github.com/user-attachments/assets/26934402-b6cc-442f-9771-2fcf8dffd009)

**Comment by ShreyasZare** [comment]
Thanks for the post. If you have just upgraded the DNS server then press Ctrl+F5 key to force refresh the page to load the new page and js code.

If its still not working then try using it in private/incognito mode or in a different web browser.

**Comment by muhanadali100** [comment]
it's working thanx
