### ISSUE TITLE
When using Forwarders, the initial resolution of a CNAME record with DNSSEC may fail

### ISSUE THREAD

**Issue by 9bingyin** [TechnitiumSoftware/DnsServer#1068]
Without caching, the resolution of `www.ip.sb` fails with `EDE: 10 (RRSIGs Missing): (www.ip.sb/CNAME)` on the first attempt, but succeeds on subsequent attempts. It seems that this issue does not occur when there is no CNAME record present.
Additionally, I use https://gcore.com/public-dns as my upstream DNS provider.

```
root@localhost:~/test# dig @127.1 www.ip.sb +dnssec

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> @127.1 www.ip.sb +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 23937
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
; EDE: 10 (RRSIGs Missing): (www.ip.sb/CNAME)
;; QUESTION SECTION:
;www.ip.sb.                     IN      A

;; Query time: 44 msec
;; SERVER: 127.0.0.1#53(127.1) (UDP)
;; WHEN: Mon Oct 07 17:54:08 CST 2024
;; MSG SIZE  rcvd: 59

root@localhost:~/test# dig @127.1 www.ip.sb +dnssec

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> @127.1 www.ip.sb +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61604
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;www.ip.sb.                     IN      A

;; ANSWER SECTION:
www.ip.sb.              366     IN      CNAME   www.ip.sb.cdn.cloudflare.net.
www.ip.sb.              366     IN      RRSIG   CNAME 13 3 600 20241017000000 20240926000000 10506 ip.sb. aFaMncnM5+cPTY2FlAC+vx65tXFDqkmQMsc47i04Ku+cbDikOhPlWTMx aEXVanoXxVUy4WUOWacKF60flFUevQ==
www.ip.sb.cdn.cloudflare.net. 66 IN     A       104.26.12.31
www.ip.sb.cdn.cloudflare.net. 66 IN     A       172.67.75.172
www.ip.sb.cdn.cloudflare.net. 66 IN     A       104.26.13.31
www.ip.sb.cdn.cloudflare.net. 66 IN     RRSIG   A 13 6 300 20241008105015 20241006085015 34505 cloudflare.net. hO+DP+dhmpxP+BbGUHIIB7Nq4wNXnKlxAUVQOGHcGztyKqstOKsRRm8M 8P+S6h7VCDkTqe3c6GlH+ab9FtrLyw==

;; Query time: 24 msec
;; SERVER: 127.0.0.1#53(127.1) (UDP)
;; WHEN: Mon Oct 07 17:54:09 CST 2024
;; MSG SIZE  rcvd: 339
```

**Comment by ShreyasZare** [comment]
Thanks for the post. This is mostly an issue with the upstream that you are using. The DNS server returns the same response that was received by the upstream. Please try changing the upstream server and see if the error reproduces.

I would also suggest that you check the DNS logs from the admin panel and find the error log related to your query. Please share the error log here so that I can understand the issue better.

**Comment by ShreyasZare** [comment]
Thanks for the details. This seems to be related to earlier issues like #1002. The upstream rarely returns a response with missing RRSIG and causes issues with validation. There is mitigation implemented to retry again but sometimes the retry attempt also get a response with missing RRSIG. These issues happen rarely and are not reproducible when you try again. It has been observed with Cloudflare and Quad9 too but not with Google DNS yet. If you configure another DoH upstream then the DNS server will try to get the response from the second upstream in such cases and that will mitigate this issue from coming up again.
