### ISSUE TITLE
Add to reverse zone while DHCP is turned on?

### ISSUE THREAD

**Issue by tcox2** [TechnitiumSoftware/DnsServer#107]
If you turn on DHCP, you can no longer edit the reverse zone

I'd like to add the server that runs Technitium to it.  That server doesn't use DHCP, but it should be added to the reverse zone.  I am unable to add it.

Other than this, Technitium is cool :-)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The forward and reverse zones created by DHCP server are marked as internal and thus they are not stored on disk and making changes to the zone is not permitted.

There is a workaround for this though. Disable the DHCP scope for a moment, restart the DNS server and then create the forward and reverse zones yourself. Once you have the zones created, these will be stored on disk and wont be marked as internal. Now, enable the DHCP scope and it will use the existing zones to add records while you can manually add your own records.

**Comment by tcox2** [comment]
Thanks for this Shreyas.

Unfortunately this is what happens when I disable the DHCP scope:

2019-12-30 16:41:00 UTC] Logging started.
[2019-12-30 16:41:00 UTC] [10.1.1.116:60893] [admin] Log file was
deleted: 2019-12-30
[2019-12-30 16:41:05 UTC] [10.1.1.3:67] DHCP Server failed to
deactivate scope: Default
System.NullReferenceException: Object reference not set to an instance
of an object.
   at TechnitiumLibrary.Net.Dns.DnsClient.IsDomainNameValid(String
domain, Boolean throwException)
   at DnsServerCore.Dns.Zone.ConvertDomainToPath(String domainName)
   at DnsServerCore.Dns.Zone.GetZone(Zone rootZone, String domain,
Boolean authoritative)
   at DnsServerCore.Dhcp.DhcpServer.UpdateDnsAuthZone(Boolean add,
Scope scope, Lease lease)
   at DnsServerCore.Dhcp.DhcpServer.DeactivateScope(Scope scope)
[2019-12-30 16:41:05 UTC] [10.1.1.116:60893]
DnsServerCore.WebServiceException: Failed to disable DHCP scope,
please check logs for details: Default
   at DnsServerCore.WebService.DisableDhcpScope(HttpListenerRequest request)
   at DnsServerCore.WebService.ProcessRequestAsync(Object state)

**Comment by ShreyasZare** [comment]
Thanks again for the details. This is a known bug in DHCP code which occurs when any of the client's hostname is invalid or null. 

This has already been fixed and an update is scheduled to be released by this weekend.

**Comment by tcox2** [comment]
Makes sense.  It started happening when I introduced a new client.  I look
forward to the new release.  :-)

**Comment by ShreyasZare** [comment]
@tcox2 : new update v4.1 is now available. Do try the workaround mentioned earlier with this new release.

**Comment by tcox2** [comment]
Thanks Shreyas - I will try it out today or tomorrow and will let you know.

**Comment by tcox2** [comment]
All good now :-)

I'm really happy to have found Technitium.

**Comment by ShreyasZare** [comment]
Issue fixed in new release.

**Comment by darthpale** [comment]
That is currently broken again in 14.3 running under docker

**Comment by ShreyasZare** [comment]
> That is currently broken again in 14.3 running under docker

@darthpale Please describe the exact issue and steps to reproduce it.
