### ISSUE TITLE
Docker tags when a new "major" version is out

### ISSUE THREAD

**Issue by EHRETic** [TechnitiumSoftware/DnsServer#1088]
Hi there,

No a big issue (more a request), but when a new major version like 13.1 is published, can you also add a docker tag 13.1.**0**?

It is not much, but 13.1 without any sub-version will be valid for 13.1.1, 13.1.2, etc. and if we want to control the version, the ".0" is missing (and important)

Thanks in advance! 😊

PS: still loving your DNS server!

**Comment by ShreyasZare** [comment]
Thanks for the post and compliments. Software version comparison will always tell that 13.1.1 > 13.1. Can you describe where you are seeing this issue so that I can understand it better.

**Comment by EHRETic** [comment]
Yes, indeed, and I think that if I pull the original 13.1 image again when 13.1.1 has already been published, it's always 13.1.1 that will be pulled and not the original 13.1.0.

This can be problematic in case you need to rollback and one way to solve it is to publish each major version with a supplmentary .0 tag... I hope, I'm not confusing you 😊

PS: I mainly use Portainer and not Docker directly, so it might be related to its own behavior, but it is also not hard/dangerous to solve this with an extra tag😉

**Comment by ShreyasZare** [comment]
Thanks for the details. I tried with docker and it seems to work as expected so looks like its something related to Portainer.

Anyways, will keep the docker tags to use the full version number from the next update.
