### ISSUE TITLE
Issues with logging page

### ISSUE THREAD

**Issue by TheZLabs** [TechnitiumSoftware/DnsServer#109]
I really love this so far with the exception of logging. The web gui seems to work fine on every tab except the logging tab. The page will consistently hang on the logs page with the Wait/Kill option for the page popping up after a short time. I have checked RAM resources and usage and this does not seem to be an issue. This server has 16GB of RAM total and doesnt seem to be using over 10GB. I generally experience this is as soon as I go to the tab for logging, can't even click "Download" to view the logs locally. This has been happening in Chrome browser on Windows 10. I cannot seem to replicate using Firefox so far. 

When checking the browser console when the page hangs I see:  
[Violation] 'setInterval' handler took 135ms
[Violation] 'setInterval' handler took 239ms -

 It would also be nice to be able to see the log requests one by one a little cleaner in the gui similar to how PiHole displays the request logs. If those things were resolved this would easily be a 10/10 for DNS software. Very happy with how this works otherwise.

**Comment by TheZLabs** [comment]
Browser Console Output when errors occur:
[Violation] 'setInterval' handler took <N>ms
[Violation] 'setInterval' handler took 135ms
[Violation] 'setInterval' handler took 239ms
[Violation] 'setInterval' handler took 227321ms
[Violation] 'setInterval' handler took 610ms
[Violation] 'setInterval' handler took 123ms
[Violation] 'setInterval' handler took 122ms

[Violation] Forced reflow while executing JavaScript took 486ms

**Comment by ShreyasZare** [comment]
Thanks for the feedback and compliments. The logging UI is quite basic right now. There are plans to move query logs to something like sqlite which will make it queryable and will help in making better UI.

The issue that you are facing seem to be specific to your chrome instance. The logging UI with logs for the entire last year each in multiple MBs are loading well here in Chrome, Firefox and Edge on Windows 10 machine with 16GB RAM with a slight delay of around 2-3 seconds when shifting to Logs tab with log data loaded. I am even able to use the logging UI even on a mid range mobile phone web browser without issues.

**Comment by TheZLabs** [comment]
I appreciate the reply! I have no issue using another browser when needing to look through logs if the issue is specific to my chrome instance. It just seemed odd to me that I could not replicate in Firefox, so I thought I would mention it in case others experienced the same issue and could also add info. Love the software! Keep up the great work!
