### ISSUE TITLE
Is the DNSCrypt protocol supported? As in https://github.com/DNSCrypt/dnscrypt-protocol

### ISSUE THREAD

**Issue by Wabuo** [TechnitiumSoftware/DnsServer#1096]
As the title says, does the Technitium DNS server support,
the DNSCrypt protocol, specifically the Anonymized DNSCrypt extension?

https://github.com/DNSCrypt/dnscrypt-protocol
https://github.com/DNSCrypt/dnscrypt-proxy

> The Anonymized DNSCrypt extension prevents DNS servers from associating queries with client IP addresses.

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS server does not support DNSCrypt protocol and currently there is no plan to implement it.

**Comment by Wabuo** [comment]
Cherrs

**Comment by Wabuo** [comment]
Cheers for the quick answer

**Comment by ShreyasZare** [comment]
Anyways, you can still use it by running the DNSCrypt proxy and use it as your forwarder in the DNS server.
