### ISSUE TITLE
Allow custom IP range for PROXY Protocol

### ISSUE THREAD

**Issue by skedastically** [TechnitiumSoftware/DnsServer#1101]
Similar to [Traefik](https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol), enable users to set specific trusted IPs and reject remote address replacement if traffic doesn't come from them. This seems to be more granular than just limiting to private network.

It can be quite a niche feature and I'm happy to wait/fine if not implemented since there are bigger priorities. Thanks!

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Yes, making the option granular will help. Will let you know when the option is available.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.2 is now available which adds new Reverse Proxy Network ACL option. Do update and let me know your feedback.

**Comment by skedastically** [comment]
Updated and confirmed working with my reverse proxies' IPs. Thank you!

**Comment by ShreyasZare** [comment]
Thanks for confirming!
