### ISSUE TITLE
curl missing in docker image

### ISSUE THREAD

**Issue by jasonyang-ee** [TechnitiumSoftware/DnsServer#1102]
We used to be able to do docker container health check with curl
```
healthcheck:
      test: curl --fail http://dns:5380 || exit 1
```

But since a recent update on image, both curl and wget are not in the container for use to use for health check. Can you include one of those in the image?

**Comment by ShreyasZare** [comment]
Thanks for the request. Will get that added in the next update.

**Comment by IngmarStein** [comment]
As an alternative, you could use dig to test if the server responds to DNS requests like this:

```
healthcheck:
  test: ["CMD", "dig", "+short", "+norecurse", "+retry=0", "@127.0.0.1", "cloudflare.com"]
```

**Comment by jasonyang-ee** [comment]
@ShreyasZare Yes, the solution worked good. Especially, the `@` to force non-cache DNS result should be enough for checking service health.

**Comment by ShreyasZare** [comment]
Thanks for confirming. Closing this issue.
