### ISSUE TITLE
How to set up so that your own authoritative server is 1

### ISSUE THREAD

**Issue by 350887156** [TechnitiumSoftware/DnsServer#1108]
```
{
  "Metadata": {
    "NameServer": "c20241101183798 (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "53 bytes",
    "RoundTripTime": "0.51 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 4096,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "Identifier": 0,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 1,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "sample.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "sample.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "3600 (1 hour)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "127.0.0.2"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "4096",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}

```

**Comment by ShreyasZare** [comment]
Thanks for the post. Please describe your question in details so that I can understand it.

**Comment by 350887156** [comment]
First of all, thank you for your reply. I heard what you said before about running the DNS server without any forwarders. However, without a forwarder, my zone resolution result will not be considered authoritative, while the bind setting is OK, which is the difference of NSCOUNT. This has been posted in json. How can I set up my DNS server to change the number of my resolution responses to be authoritative from 0 to 1? Or how to configure Authority

**Comment by 350887156** [comment]
> 谢谢你的详细信息。
> 
> > 首先，感谢您的回复。我之前听说过您说的在没有任何转发器的情况下运行 DNS 服务器。但是，如果没有转发器，我的区域解析结果将不被视为权威，而绑定设置则没问题，这是 NSCOUNT 的区别。这已发布在 json 中。我该如何设置我的 DNS 服务器，将我的解析响应数量从 0 更改为 1 以使其具有权威性？或者如何配置 Authority
> 
> 如果您询问的是`AuthoritativeAnswer`DNS 响应中的 (AA) 标志，则该标志仅针对本地托管的区域设置。对于来自转发器或使用递归解析的任何响应，都不具有权威性，因此 AA 标志将为 false。这就是 AA 标志的定义方式。

Thank you
