### ISSUE TITLE
13.2 broke Real IP header for DNS-over-HTTPS

### ISSUE THREAD

**Issue by IngmarStein** [TechnitiumSoftware/DnsServer#1113]
After updating from 13.1.1 to 13.2, my DoH setup stopped working, presumably because https://github.com/TechnitiumSoftware/DnsServer/commit/50276dc2166d1500565aea058c15356e3253f50e changed the behavior to only read the header for plain HTTP connections. My CloudFlare tunnel can use HTTP/2, so I'd like to continue using HTTPS. Would it be possible to make this configurable?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get that updated in the next release. The secure DoH was earlier not intended to be used with reverse proxy but with the new ACL option now available, I guess it can be included with that.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.2.1 is now available that fixes this issue. Please upgrade and let me know your feedback.

**Comment by IngmarStein** [comment]
The fix is working as expected, thanks!

**Comment by ShreyasZare** [comment]
Thanks for confirming!
