### ISSUE TITLE
DoQ stops accepting queries randomly. 

### ISSUE THREAD

**Issue by 32bitx64bit** [TechnitiumSoftware/DnsServer#1114]
Hi, currently having this weird issue where all but DoT will stop accepting DNS queries.
I'm on the latest technitium dns server build.
Running on Debian 12. 
It only fixes itself when I restart the server completely.
[2024-11-18(1).log](https://github.com/user-attachments/files/17803634/2024-11-18.1.log)
Here's the latest log if it helps.

**Comment by ShreyasZare** [comment]
Thanks for the post. The logs shared do not have any error log related to the issue you are mentioning. The errors in there are related to failure to resolve a specific domain name due to some network issues.

I am not sure why this could happen since I have these deployed in production and its working well on Debian 12. I would suggest that you debug the issue when it occurs. 

To do that, you should first check if the service ports are open using `sudo netstat -nlptu` command which should list all the open ports. If you see the ports are open then the services are running. If not, then check the DNS logs to see if there are any error logs.

If ports are open, try using the DNS Client tool on the admin panel to test if the DNS server responds over the selected protocol. Since these are encrypted DNS services, you will need to use the full DoH URL with the domain name used to generate the TLS certificate. To test DoH/3, use `h3` as the URL scheme instead of `https`. Test all the services, DoH, DoH/3, DoQ, and DoT and share your results here.

**Comment by 32bitx64bit** [comment]
Alright I'll give it a shot

**Comment by 32bitx64bit** [comment]
Hm weird. All the UDP ports aren't listening anymore. That explains why protocols but TLS is failing. Would you happen to know anyway to fix this?

**Comment by ShreyasZare** [comment]
> Hm weird. All the UDP ports aren't listening anymore. That explains why protocols but TLS is failing. Would you happen to know anyway to fix this?

If you do not see any port belonging to the DNS server listening then the server may have stopped working. Do post the output of command you ran so that I can understand it better.

**Comment by 32bitx64bit** [comment]
> > Hm weird. All the UDP ports aren't listening anymore. That explains why protocols but TLS is failing. Would you happen to know anyway to fix this?
> 
> If you do not see any port belonging to the DNS server listening then the server may have stopped working. Do post the output of command you ran so that I can understand it better.

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:853             0.0.0.0:*               LISTEN      402/dotnet          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      424/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      402/dotnet          
tcp6       0      0 :::443                  :::*                    LISTEN      402/dotnet          
tcp6       0      0 :::853                  :::*                    LISTEN      402/dotnet          
tcp6       0      0 :::53443                :::*                    LISTEN      402/dotnet          
tcp6       0      0 :::80                   :::*                    LISTEN      402/dotnet          
tcp6       0      0 :::22                   :::*                    LISTEN      424/sshd: /usr/sbin 
tcp6       0      0 :::53                   :::*                    LISTEN      402/dotnet          
udp        0      0 0.0.0.0:53              0.0.0.0:*                           402/dotnet          
udp        0      0 159.100.250.108:68      0.0.0.0:*                           363/systemd-network 
udp6       0      0 :::853                  :::*                                402/dotnet          
udp6       0      0 :::443                  :::*                                402/dotnet          
udp6       0      0 :::53                   :::*                                402/dotnet          
udp6       0      0 :::53443                :::*                                402/dotnet

**Comment by ShreyasZare** [comment]
Thanks for the details. It looks like all the services ports are open indicating that DoH. DoT, DoQ, and plain DNS over TCP/UDP is all working. Try testing with the DNS Client tool on the admin panel and see if the service is responding to queries for all protocols.

If you see an error anywhere, just check the DNS Logs on the admin panel and share the complete error log entry so that I will be able to understand the error better.

**Comment by ShreyasZare** [comment]
> > Thanks for the details. It looks like all the services ports are open indicating that DoH. DoT, DoQ, and plain DNS over TCP/UDP is all working. Try testing with the DNS Client tool on the admin panel and see if the service is responding to queries for all protocols.
> > If you see an error anywhere, just check the DNS Logs on the admin panel and share the complete error log entry so that I will be able to understand the error better.
> 
> It works just fine on server. No errors. Issue it outside the web server, outside connections.

Then it seems that the DNS server is working well but there is some network issue that you need to figure out. It could be an issue with Firewall on the server or on the network preventing clients from accessing those services.

**Comment by 32bitx64bit** [comment]
Ima just upload a bunch of logs from my NA server to see if theirs any useful information, as this is deff a technitium issue, it happens on two separate VPS providers 
[2024-11-19.log](https://github.com/user-attachments/files/17851222/2024-11-19.log)
 
[2024-11-20.log](https://github.com/user-attachments/files/17851223/2024-11-20.log)

[2024-11-18(2).log](https://github.com/user-attachments/files/17851221/2024-11-18.2.log)

**Comment by ShreyasZare** [comment]
> Not sure what the issue is, but I came here to report this bug. ~It affects every socket except the webserver, not just secure services~. It is worth noting that I am running the app in the container, so it could perhaps be a configuration issue with the container. That said, using an older version (i.e. 13.1) resolves the issue.
> 
> Logs currently provide no useful information; system, podman, container, or app - but I may not be looking in the right places.
> 
> This graph demonstrates the issue occurring. Restarting the container resolves it temporarily, but it keeps happening at this point.
> 
> Edit: An important clarification - DNS resolutions is what stops functioning; the DoH/DoQ servers are live, they just do not respond to queries (and the DNS server does not respond on 53).

Thanks for the feedback. I am not sure what could be the issue since there was no significant change in the way the DNS server works in between 13.1 and current release. The change were a few bug fixes and other minor things that should not have any such effect.

From the screenshot, it looks like you are hosting zones. Do you have any of the zones signed with DNSSEC? If yes, are you using NSEC3?

**Comment by ShreyasZare** [comment]
> Ima just upload a bunch of logs from my NA server to see if theirs any useful information, as this is deff a technitium issue, it happens on two separate VPS providers [2024-11-19.log](https://github.com/user-attachments/files/17851222/2024-11-19.log)
> 
> [2024-11-20.log](https://github.com/user-attachments/files/17851223/2024-11-20.log)
> 
> [2024-11-18(2).log](https://github.com/user-attachments/files/17851221/2024-11-18.2.log)

Thanks for the logs. The errors in these logs are just related to network unreachable issue which means that the network was down and thus the DNS server failed to resolve domain names. Also, it seems you have enabled Prefer IPv6 option. Do you have IPv6 connectivity? If no, then disable that option since it will cause issues with resolution.

**Comment by AceBlade258** [comment]
> Do you have any of the zones signed with DNSSEC? If yes, are you using NSEC3?

Yes to both questions.

**Comment by 32bitx64bit** [comment]
> > Ima just upload a bunch of logs from my NA server to see if theirs any useful information, as this is deff a technitium issue, it happens on two separate VPS providers [2024-11-19.log](https://github.com/user-attachments/files/17851222/2024-11-19.log)
> > [2024-11-20.log](https://github.com/user-attachments/files/17851223/2024-11-20.log)
> > [2024-11-18(2).log](https://github.com/user-attachments/files/17851221/2024-11-18.2.log)
> 
> Thanks for the logs. The errors in these logs are just related to network unreachable issue which means that the network was down and thus the DNS server failed to resolve domain names. Also, it seems you have enabled Prefer IPv6 option. Do you have IPv6 connectivity? If no, then disable that option since it will cause issues with resolution.

Yes ipv6 is available.

**Comment by 32bitx64bit** [comment]
Idk what's wrong. Might just be Debian 12?

**Comment by AceBlade258** [comment]
Update to note I am now experiencing this on all 13.x builds. Config is not backwards compatible, so I cannot check further back.

**Comment by ShreyasZare** [comment]
> > Do you have any of the zones signed with DNSSEC? If yes, are you using NSEC3?
> 
> Yes, to both questions - all of them.

There have been similar feedback from a few people but the issue is such that I am unable to reproduce it at all. Its also rare so only a handful installations are reporting it. Will see if I can find more clues on it.

**Comment by ShreyasZare** [comment]
> Idk what's wrong. Might just be Debian 12?

I think its something related to network connectivity on your server due to all those errors that are there in the logs. I am running DNS instances on Debian 12 in production so there is no issue with the OS. 

I would suggest that you get some server monitoring self hosted tool that monitors DNS service as well as uses ping to check for connectivity and see how it goes.

**Comment by 32bitx64bit** [comment]
> > Idk what's wrong. Might just be Debian 12?
> 
> I think its something related to network connectivity on your server due to all those errors that are there in the logs. I am running DNS instances on Debian 12 in production so there is no issue with the OS.
> 
> I would suggest that you get some server monitoring self hosted tool that monitors DNS service as well as uses ping to check for connectivity and see how it goes.

I highly doubt its a network connectivity issue, when its happening to my two may i remind, separately hosted on two different VPS provider. Not to mention other people having the same issue.... 100% some issue with Technetium.
Might be DNSSEC related, disabling this to see.

**Comment by 32bitx64bit** [comment]
> > I highly doubt its a network connectivity issue, when its happening to my two may i remind, separately hosted on two different VPS provider. Not to mention other people having the same issue.... 100% some issue with Technetium. Might be DNSSEC related, disabling this to see.
> 
> The logs you shared earlier had "network unreachable" error logs so that's already happened and also could be cause of the current issue.
> 
> > Edit : So far so good, disabling DNSSEC may have worked? I'll keep this updated.
> > Edit 2 : DoQ and DoH/3 is still working, possible DNSSEC issue.
> 
> If you see DNSSEC Validation failure errors in DNS logs then that's could be the reason. In that case, you should change your upstream/forwarder to another provider that supports DNSSEC so that you do not need to disable an useful security feature.

I don't use a upstream forwarder, so this wouldn't really change much. It seems to be indeed a dnssec validation issue. I'm going to keep this disabled, as I'd much rather have reliable dns querying rather than constant cutouts for security.

**Comment by ShreyasZare** [comment]
> I don't use a upstream forwarder, so this wouldn't really change much. It seems to be indeed a dnssec validation issue. I'm going to keep this disabled, as I'd much rather have reliable dns querying rather than constant cutouts for security.

If you are running it as a recursive resolver then your ISP is most probably hijacking your DNS requests which will cause DNSSEC validation errors (which is how DNSSEC protects from forged responses). Disabling DNSSEC will fix this issue but you are just using your ISP's DNS resolvers anyways and not really doing recursive resolution. In such case, I would suggest that you use encrypted DNS protocol with any public DNS provider or run your own encrypted DNS resolver on a VPS and use it.

**Comment by 32bitx64bit** [comment]
> If you are running it as a recursive resolver then your ISP is most probably hijacking your DNS requests which will cause DNSSEC validation errors (which is how DNSSEC protects from forged responses). Disabling DNSSEC will fix this issue but you are just using your ISP's DNS resolvers anyways and not really doing recursive resolution. In such case, I would suggest that you use encrypted DNS protocol with any public DNS p

That's what I'm doing. I'm not running Technetium on my local network, its in a VPS... Disabling DNSSEC fixed the issue on my VPS... So might wanna look into it. I'm going to close this issue.

**Comment by 32bitx64bit** [comment]
Just happened again, took way longer when DNSSEC was disabled. Happens more often when DNSSEC is enabled, I checked to make sure the UDP port for 853 is open, which it is.
udp               UNCONN             0                  0                                           0.0.0.0:53                                 0.0.0.0:*                                  
udp               UNCONN             0                  0                              159.100.250.108%eth0:68                                 0.0.0.0:*                                  
udp               UNCONN             0                  0                                                 *:853                                      *:*                                  
udp               UNCONN             0                  0                                                 *:443                                      *:*                                  
udp               UNCONN             0                  0                                              [::]:53                                    [::]:*                                  
udp               UNCONN             0                  0                                                 *:53443                                    *:*                                  
tcp               LISTEN             0                  4096                                        0.0.0.0:853                                0.0.0.0:*                                  
tcp               LISTEN             0                  4096                                        0.0.0.0:53                                 0.0.0.0:*                                  
tcp               LISTEN             0                  128                                         0.0.0.0:22                                 0.0.0.0:*                                  
tcp               LISTEN             0                  4096                                           [::]:853                                   [::]:*                                  
tcp               LISTEN             0                  512                                               *:443                                      *:*                                  
tcp               LISTEN             0                  512                                               *:80                                       *:*                                  
tcp               LISTEN             0                  4096                                           [::]:53                                    [::]:*                                  
tcp               LISTEN             0                  128                                            [::]:22                                    [::]:*                                  
tcp               LISTEN             0                  512                                               *:53443                                    *:*                                  

This is 100%, a issue with Technitium just refusing to listen to requests anymore, this seems to only happen with DoH/3 and DoQ and DoH. DoT is unaffected... Which I still don't get why.

This happens on both my VPS servers, two different providers
One being  DigitalOcean, other being Exoscale.

And as per usual, logs don't provide any detail on wdf is happening.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Please share the average requests/min or /hour that you get on the server. When you say "refusing to listen" you mean you get "connection refused" error when you test it using DNS Client tool?

I am not sure what could be the reason here. I am running multiple DNS server on Digital Ocean VPS too without any issues here.

**Comment by 32bitx64bit** [comment]
> > Thanks for the feedback. Please share the average requests/min or /hour that you get on the server. When you say "refusing to listen" you mean you get "connection refused" error when you test it using DNS Client tool?
> > I am not sure what could be the reason here. I am running multiple DNS server on Digital Ocean VPS too without any issues here.
> 
> Usually about 10 - 500 queries a minute. Seems like running "sudo systemctl disable systemd-resolved sudo systemctl stop systemd-resolved" And restarting dns.service has fixed the issue. Though I hope I don't jinx it now.
> 
> And connection would just refuse. That's the error I was getting when trying to send a DNS query.
> 
> About 24/h after the 'fix?' was applied, still working, no connection refused, usually it would break after about 11 - 15 hours w/ DNSSEC on... If it continues to work might wanna update install instructions for Debian 12 systems to use the above commands.

Doing this **seems** to have been the solution... No idea why it fixed the issue, but I'm just happy to have reliable DNS.
Hopefully this helps anyone else.

**Comment by 32bitx64bit** [comment]
Revising. Seems like down is only affected. I accidentally forgot to put /dns-query for doh and doh/3 which are both unaffected.

Reopening as DoQ doesn't seem to work reliably

**Comment by ShreyasZare** [comment]
There was a bug identified for DoQ service code a few days ago. It may be that this bug is causing the issue you see. The next update is planned for the coming weekend so you can update and see if that fixes the issue you see.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.3 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by 32bitx64bit** [comment]
V13.3 has indeed seemed to have fixed the DoQ issue.  ^-^

**Comment by ShreyasZare** [comment]
Thanks for confirming.
