### ISSUE TITLE
weird behaviour when resolving wildcard subdomains that start with the letter 'g'

### ISSUE THREAD

**Issue by 666damo** [TechnitiumSoftware/DnsServer#1117]
v13.2 in docker
network_mode: "host"
Apps: Query logs, Split Horizon, What is my IP

When playing around with a test zone I created, I noticed a weird behaviour.
I can resolve any subdomain in the zone via a wildcard entry, except for subdomains beginning with the letter 'g'.

There is a good chance that I am doing something out of spec, but felt it was worth reporting.

Here are the steps to recreate:
1) create a new primary zone: **example.com**
2) add an A record: **int** > **192.168.0.1**
3) add a CNAME record: **\*** > **int.example.com**
4) test `nslookup games.example.com` - this works, as well as other subdomains

5) add an A record: **ssh.git** > **192.168.0.2**
6) test `nslookup games.example.com` - this now fails, as well as other subdomains beginning with 'g'
7) test `nslookup ssh.git.example.com` - this works as expected
8) test `nslookup notgames.example.com` - this works, as well as other subdomains that do not begin with 'g'

9) add a CNAME record: **git** > **int.example.com**
10) test `nslookup games.example.com` - this works again, as well as other subdomains

The trigger seems to be adding the **ssh.git** record. Adding also a **git** record seems to negate the weird effect.
Maybe having the sub.subdomain without explicitly defining the subdomain is causing an issue, but why only with subdomains starting with 'g'?

**Comment by ShreyasZare** [comment]
Thanks for reporting this. I am able to reproduce this issue and seems to be some bug in processing wildcard for Empty Non-Terminal (ENT) record cases. Will get this fixed soon.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.2.1 is now available that fixes this issue. Please upgrade and let me know your feedback.
