### ISSUE TITLE
Cannot resolve host

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#112]
Hi!
I cannot understand why DNSServer cannot resolve host farline.net
I have dns server on 10.10.10.2(win7 with dns 10.10.10.2 in network settings) and notebook in same network. When I try to ping host farline.net I got an error `cannot resolve host ...`
If I do `nslookup farline.net 10.10.10.2` I get request timeout.
But `nslookup farline.net 10.10.10.1` return IP address.
10.10.10.1 is a router IP with configured dns 8.8.8.8

Where I'm wrong?

PS! My ISP block connections to farline.net. But why dns?

**Comment by ShreyasZare** [comment]
Thanks for the post. Please let me know if your are currently using any forwarder or the DNS server is directly doing recursive resolution. 

Also, do a query to the server for the domain name and when it fails just look at the logs to find what error is being logged and post it here.

**Comment by Globulopolis** [comment]
I'm using CF resolver.

[2020-01-13 08:48:30 UTC] [10.10.10.10:58479] [UDP] QNAME: farline.net; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []

**Comment by ShreyasZare** [comment]
It could be related to the issue #113 where SSL connection to the DoT server is failing. Do try another forwarder or try DoT and see if that works.

**Comment by Globulopolis** [comment]
I think no. Tested with DNS Client for A farline.net
Dyn (UDP), Ultra (UDP), Level3 (UDP), OpenDNS (UDP), Quad9 Unsecure (UDP), Quad9 Secure HTTPS, Quad9 Secure TLS, Quad9 Secure (UDP), Google (8.8.8.8) (UDP), Recursive Query (recursive-resolver)
All DNS above response with no errors and return valid IP for host.

All other DNS servers throwing an errors about TLS/SSL and HTTPS.
For Google DNS I cannot understand why one is working, but other no. Same with CF

**Comment by ShreyasZare** [comment]
Probably your ISP is blocking CF and Google for DoT and DoH. Try running Wireshark on your machine and then use the DNS Client to make a query to CF DoT. My guess is that you may receive a random TCP RST packet that will force the socket to close causing the SSL/TLS error.

**Comment by Globulopolis** [comment]
I'm not familiar with Wireshark. Session ended up with TCP spurious retransmission.
![Clipboard01](https://user-images.githubusercontent.com/740757/72373840-205f1100-371a-11ea-9844-b048d2bc3794.jpg)

**Comment by ShreyasZare** [comment]
What is the host OS for the DNS server?

**Comment by Globulopolis** [comment]
Win 7 x64 with latest updates.

**Comment by ShreyasZare** [comment]
Windows 7 does have some issues with TLS that I have seen while tests. It may be that it does not support some newer protocol cipher options. Anyways Win7 is out of service since yesterday and it would be good to have upgraded OS considering the fact that there is latest vulnerability affecting all Windows version causing the OS to fail validation of SSL certificates.

**Comment by Globulopolis** [comment]
Digging more deeper in that error I found that my ISP block all connections to farline.net.
And I thinking that the problem isn't in Windows 7. I host own site with TLS 1.3 with modern list of cyphers and have A+ on ssllabs.
