### ISSUE TITLE
Not an issue more of question

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#1136]
Hi,

Do you perhaps have a list of QUICK providers? It only has adguard?

Apologies

**Comment by ShreyasZare** [comment]
Thanks for asking. There are not many popular providers for DoQ. AdGuard was first to have a public DoQ service. I guess NextDNS and ControlD too support it.

**Comment by ChristoffBo** [comment]
Thank you, will check if they have ones i can use.
