### ISSUE TITLE
Yaml or Charts for k8s

### ISSUE THREAD

**Issue by KerimNar** [TechnitiumSoftware/DnsServer#1145]
Hi. I must say, very good work.
Is it possible to run in kubernetes? if you have already tried, is it possible to use .yaml or Charts?

**Comment by ShreyasZare** [comment]
Thanks for the post and compliments. I do not have any experience working with kubernetes so wont be able to answer that. I would suggest that you post this on reddit.com/r/technitium so that it reaches more people.

**Comment by KerimNar** [comment]
I did something like this, everything starts, but I don’t know if this is the right approach

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-server
  namespace: prod-util
  labels:
    app: dns-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-server
  template:
    metadata:
      labels:
        app: dns-server
    spec:
      containers:
      - name: dns-server
        image: technitium/dns-server:latest
        ports:
        - name: web-http
          containerPort: 5380
          protocol: TCP
        - name: dnsudp
          containerPort: 53
          protocol: UDP
        - name: dnstcp
          containerPort: 53
          protocol: TCP
        envFrom:
        - configMapRef:
            name: dns-server-env
        volumeMounts:
        - name: config-volume
          mountPath: /etc/dns
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: dns-server-config-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-server-env
  namespace: prod-util
data:
  DNS_SERVER_DOMAIN: "dns-server"
  # Uncomment and modify values as needed:
  # DNS_SERVER_ADMIN_PASSWORD: "password"
  # DNS_SERVER_FORWARDERS: "1.1.1.1, 8.8.8.8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-server-config-pvc
  namespace: prod-util
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  namespace: prod-util
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.12.53
  ports:
  - name: web-http
    port: 5380
    targetPort: 5380
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  selector:
    app: dns-server

**Comment by KerimNar** [comment]
> Можно запустить его в кластере K8s, делаю это уже несколько месяцев. Пока никаких проблем, также стабильно.
> 
> Чтобы запустить его без прав root, мне пришлось изменить порты и выполнить некоторые настройки портов.

Have you run Deployments or Statefulsets?

**Comment by xlemassacre** [comment]
I use flux and the bjw-s helm chart for apps that don't have their owm chart.

This is the deployment with a dns and a root server

`---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: technitium
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 1002
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: "Always"      

    controllers:
      main:
        nameOverride: primary
        enabled: true
        type: deployment
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 0

        containers:
          main:
            image:
              repository: &repo technitium/dns-server
              tag: &tag 13.2.2
              pullPolicy: IfNotPresent

            env:
              DNS_SERVER_DOMAIN: dns.domain.com

            envFrom:
              - secretRef:
                  name: secret-admin

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: true
              startup:
                enabled: false
            securityContext:
              privileged: false
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 3Gi

      root:
        nameOverride: root
        enabled: true
        type: deployment
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 0

        containers:
          main:
            image:
              repository: *repo
              tag: *tag
              pullPolicy: IfNotPresent

            env:
              DNS_SERVER_DOMAIN: dns-root.domain.com

            envFrom:
              - secretRef:
                  name: secret-admin

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: true
              startup:
                enabled: false
            securityContext:
              privileged: false   
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 3Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: 5380

      root:
        primary: true
        controller: root
        ports:
          http:
            port: 5380
            protocol: TCP

      root-dns:
        controller: root
        ports:
          dnstcp:
            port: 53
            targetPort: 1026          
            protocol: TCP
          dnsupd:
            port: 53
            targetPort: 1026            
            protocol: UDP

      main-dns:
        controller: main
        externalTrafficPolicy: Local
        type: LoadBalancer
        loadBalancerIP: 192.168.1.1
        ports:
          dnstcp:
            port: 53
            targetPort: 1025
            protocol: TCP
          dnsupd:
            port: 53
            targetPort: 1025
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: nginx

        hosts:
          - host: dns.domain.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

          - host: dns-root.domain.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: root
                  port: http

        tls:
          - secretName: secret-dns.domain.com
            hosts:
              - dns.domain.com
          - secretName: secret-dns-root.domain.com
            hosts:
              - dns-root.domain.com

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: hostpath
        accessMode: ReadWriteOnce
        size: 2Gi
        advancedMounts:
          main:
            main:        
            - path: /etc/dns/
              subPath: config
          root:
            main:        
            - path: /etc/dns/
              subPath: config-root            
`
