### ISSUE TITLE
Can I generate .dll configuration files myself?

### ISSUE THREAD

**Issue by KerimNar** [TechnitiumSoftware/DnsServer#1148]
Hi. I have a question. Here it is:
https://github.com/TechnitiumSoftware/DnsServer/blob/c873a5c4a9f2638ae78b7d7cd961423d553dee72/DnsServerApp/Program.cs#L54
Download the configurations from this link:
https://download.technitium.com/dns/apps/apps2.json
and inside the .zip there are .dll files.
Can I generate these .dll files myself?

**Comment by ShreyasZare** [comment]
Thanks for the post.

> Can I generate these .dll files myself?

By that, if you mean to ask if you can develop your own DNS app, then yes, you can do that and use the "Install" button in the Apps section on the admin panel to add your app in the DNS server.
