### ISSUE TITLE
Not able to download Log files via API

### ISSUE THREAD

**Issue by Ente** [TechnitiumSoftware/DnsServer#1149]
## Description

I am unable to download a log file via the API. As in the APIDOCS.md `Content-Type: text/plain` and `Content-Disposition` header these are not returned as they should be. The Content-Type is set to `application/json` and the Content-Disposition header is not returned at all.

The API response only contains the usual JSON response:
```json
{"response":{},"status":"ok"}
```

I tried through this with a php library, a API client and within my browser.
Maybe I am just doing it wrong? Using DnsServer 13.1 / EDIT: and 13.2.2

## How to reproduce

- Connect to `dnsserver:5380/api/admin/logs/download?token=XXX=fileName=2024-12-09`
- Response only contains JSON and not the expected log file

**Comment by ShreyasZare** [comment]
Thanks for the post. The URL you are trying is incorrect. You need to remove the "admin" part from the URL for it to work. Check the [APIDOCS](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md#download-log) once.

**Comment by Ente** [comment]
yes, you are totally right. sorry for that. should have read the docs better ^^
