### ISSUE TITLE
DNS protocol on top of Bedrock

### ISSUE THREAD

**Issue by pherbel** [TechnitiumSoftware/DnsServer#115]
Hi,
That's cool stuff.
As I see you have a bunch of network code and protocol implementation in this repo and your https://github.com/TechnitiumSoftware/TechnitiumLibrary repo.
Which is great.

Maybe you heard about @davidfowl's Bedrock project which aims to unify the network stack and protocols implementations. https://github.com/davidfowl/BedrockFramework

I just recommend to check and consider move your implementation top of Bedrock.

That would be great if we have DNS, DHCP, etc implementation on top of Bedrock.

**Comment by ShreyasZare** [comment]
Thanks for the suggestion and compliments. Its quite late to consider this though which requires a complete rewrite of the project and secondly, the project also targets .NET Framework apps apart from a .NET Core app.
