### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by mikemilligram** [TechnitiumSoftware/DnsServer#1153]
Hi, I only just set this up yesterday and I'm very happy with it so far!

I ran into an issue that had me pulling my hair out last night, but it seems to come and go seemingly at random:

Every now and then when I access services on my network I get this error message back `ERR_QUIC_PROTOCOL_ERROR`.
I can access devices in my network as well as the internet without issue, it only seems to happen with services behind my personal domain (let's call it mydomain.com).

I set up a conditional forwarder zone for mydomain.com and requests are forwarded properly to the correct server.

I can easily reproduce this issue by opening an incognito tab. When I do this, I immediately get the correct response, however once I close the incognito session and launch a new one, and try to access the same service, I do not get forwarded to the correct service, but get the error mentioned above.
If I then leave the page open for a longer amount of time, maybe 5-10 minutes, it automatically refreshes and it shows me the correct page. 

The query logs look like this for a successful request:
Client IP Address | Protocol | Response Type | RCODE | Domain | Type | Class | Answer
-- | -- | -- | -- | -- | -- | -- | --
192.168.178.38 | Tcp | Authoritative | NoError | service.mydomain.com | A | IN | 192.168.178.211

And like this when I get the error message:
Client IP Address | Protocol | Response Type | RCODE | Domain | Type | Class | Answer
-- | -- | -- | -- | -- | -- | -- | --
192.168.178.38 | Tcp | Cached | NoError | service.mydomain.com | HTTPS | IN | 1 . alpn=h3,h2 ipv4hint=104.x.x.195,172.x.x.159 ech=xx:xx ipv6hint=xx:xx

I redacted part of the answer in the second example, since I have no idea how sensitive that information might be.

If you need more information, please let me know and I'll do my best to provide it!

Hopefully you can help me out with this, thanks in advance!

**Comment by ShreyasZare** [comment]
Thanks for the post. This issue is not related to DNS since the domain is resolving correctly. Its an issue with the web server that is hosting your service. 

From the HTTPS record details you shared, it includes `h3` protocol so your web browser is going to try to use HTTPS/3 protocol which uses QUIC as transport protocol. If you do not have your web server configured to accept HTTPS/3 requests then that could explain why you see this issue. If your web server does not support `h3` then remove that from the HTTPS record you have configured and it should fix this issue.

**Comment by mikemilligram** [comment]
Thanks so much for the reply! Is this a setting I need to adjust within Technitium? If so, could you point me in the right direction? Thanks!

**Comment by ShreyasZare** [comment]
> Thanks so much for the reply! Is this a setting I need to adjust within Technitium? If so, could you point me in the right direction? Thanks!

Are you seeing this error when accessing DNS server's admin panel? Or is it some other service in your LAN network?

**Comment by mikemilligram** [comment]
So the conditional forward zone directs requests to domain.com to a reverse proxy server in my network, which then forwards to the respective service. It is those services that I encounter the error message on, not the admin panel itself or any other services in my network or on the internet.

**Comment by ShreyasZare** [comment]
> So the conditional forward zone directs requests to domain.com to a reverse proxy server in my network, which then forwards to the respective service. It is those services that I encounter the error message on, not the admin panel itself or any other services in my network or on the internet.

You need to either enable HTTP/3 support on your reverse proxy or edit your HTTPS record in your forwarder zone and remove `h3`. If you do not have HTTPS record in your forwarder zone then you can either add one that works for your local network. or install the "NO DATA" DNS app and add an APP record in the forwarder zone with "HTTPS" type so that the DNS server record does not resolve.

**Comment by mikemilligram** [comment]
I'm trying out the first suggestion to enable HTTP/3 on my reverse proxy, so far with no success, but I'll keep trying and get back to you once I've either gotten it to work, or unsuccessfully tried all those options. Thanks so much for taking the time, really appreciate it!

**Comment by mikemilligram** [comment]
Okay that ended up working quite quickly!
I run my reverse proxy behind Cloudflare, so I was getting a new error message after enabling HTTP/3, and exposing 443/udp as well: `ERR_ECH_FALLBACK_CERTIFICATE_INVALID`

I found this [comment](https://www.reddit.com/r/technitium/comments/1fe36rg/comment/lndklxi/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) on a reddit thread mentioning that disabling TLS 1.3 on Cloudflare fixed this issue for them and it did for me as well!

Thank you so much for your help, and the very quick responses, this kind of support is invaluable!

**Comment by ShreyasZare** [comment]
Good to know you got it working.
