### ISSUE TITLE
Technitium is non-compliant with RFC 1035 when conditional forwarding (DNS Rewrite) with only an `A` record defined, returns `NXDOMAIN` instead of `NODATA` when querying for `AAAA`

### ISSUE THREAD

**Issue by vincejv** [TechnitiumSoftware/DnsServer#1154]
**Repro:**
1. Create a conditional forwarding zone (example: `lan.homenetwork.com`)
2. Set FWD Record as `this-server`
3. Define a custom A record (example: `router.lan.homenetwork.com`)
4. Perform `nslookup router.lan.homenetwork.com`
5. nslookup returns the following
```
/ # nslookup router.lan.homenetwork.com
Server:         127.0.0.1
Address:        127.0.0.1:53

** server can't find router.lan.homenetwork.com: NXDOMAIN

Name:   router.lan.homenetwork.com
Address: 172.16.0.1
```

As explained by a serverfault question: https://serverfault.com/questions/1121447/nslookup-finds-ip-address-but-still-claims-nxdomain

> nslookup makes two queries: one for A records and another for AAAA records (IPv6 addresses). Normally, both queries should either succeed or fail equally (regardless of what kind of addresses the domain has – no IPv6 addresses just means an empty successful answer).
> 
> But some resolvers (and in particular, some ad blockers) misunderstand the DNS protocol and reply with NXDOMAIN whenever the requested record type doesn't exist, even though the name exists in general. (In fact, I think I remember Adguard doing so deliberately, in order to "block IPv6 leaks" or something.)
> 
> Use nslookup -q=A and nslookup -q=AAAA to compare the results.

on the same serverfault post, it references the RFC, Technitium should comply by RFC 1035 that it should return `NODATA` when requesting for AAAA record, and not `NXDOMAIN` as the "domain" does exist, it simply does not have an AAAA record.

**IMPACT**
Some dual stack IPv6 setups or programs written on nodejs (and possibly more..) **fail to resolve** `router.lan.homenetwork.com` since it assumes `router.lan.homenetwork.com` **does NOT EXIST** even if the A record does exist since Technicium returns NXDOMAIN on the AAAA query and does not proceed to retry querying for the A record

**Comment by vincejv** [comment]
Additional note, I was not able to repro this issue when the Zone is a "Primary" Zone, only when the zone is a "Forwarder" or Conditional Forwarder zone

**Comment by vincejv** [comment]
I'm closing the issue as Step #2 was not a faithful reproduction step and I think it is the expected behavior....

I didn't setup the FWD Record as `this-server` but instead forwarded it to another DNS server which caused the AAAA lookup to be forwarded to that server. When the request was forwarded that upstream DNS server does not have a record for the `router.lan.homenetwork.com` hence returned `NXDOMAIN`

**Comment by ShreyasZare** [comment]
Thanks for the post. The Conditional Forwarder zone is a proprietary type of zone and what you observed is really a feature. 

The forwarder zone allows you to forward requests using FWD records and returns whatever the upstream returns. It also allows you to add records to "override" the actual domain name. For non-existent domain name, the NO DATA app is needed for it to return NODATA response for type queries for which there is no record available.
