### ISSUE TITLE
Catalog Zones do not work with Bind 9 as secondary

### ISSUE THREAD

**Issue by FlossFarrier** [TechnitiumSoftware/DnsServer#1156]
Hi there. 

I am trying to use Technitium DNS as a hidden primary and Bind 9 on the other side as secondary DNS server with zone updates via catalog zones. 

The Bind 9 secondary logs:

`14-Dec-2024 14:31:29.077 notify: info: client @xxxxx 10.x.x.x#xxxx: received notify for zone 'my.catzone'`
`14-Dec-2024 14:31:29.077 xfer-in: info: zone my.catzone/IN: notify from 10.x.x.x#xxxx: no serial`
`14-Dec-2024 14:31:29.080 xfer-in: debug 3: zone my.catzone/IN: soa_query: remote server current address index 0 count 1`
`14-Dec-2024 14:31:29.183 xfer-in: info: zone my.catzone/IN: refresh: non-authoritative answer from primary 10.x.x.x#53`

The zone transfer is not being performed. 

On the primary it is added in the ACL and has correct TSIG Keys.

I think Bind 9 cannot perform the zone transfer because it does not get the serial...

Is it a bug or a feature? ;-) Do catalog zones only work from Technitium DNS to Technitium DNS right now?

Greetings, 
Magnus.

**Comment by FlossFarrier** [comment]
Even when I try to query the catalog zone from localhost (the technitium DNS primary host), I am getting an empty answer...

`; <<>> DiG 9.20.3 <<>> @10.x.x.x my.catzone SOA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13445
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;my.catzone.              IN      SOA

;; Query time: 3 msec
;; SERVER: 10.x.x.x#53(10.x.x.x) (UDP)
;; WHEN: Sat Dec 14 14:57:10 CET 2024
;; MSG SIZE  rcvd: 45`

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The catalog zone is failing to return SOA causing this issue with bind. I just tested it with a test fix and it seems to be working with bind now. Will get this fix available in the next update. Will let you know here when the update is available.

**Comment by FlossFarrier** [comment]
This would be amazing, thank you Shreyas!

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13.3 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by FlossFarrier** [comment]
Hey Shreyas, 

it now works perfectly fine. All zones transferred and up to date within Bind. 

Thank you very much! 👍🏽😃

**Comment by ShreyasZare** [comment]
Thanks for confirming!
