### ISSUE TITLE
Feature Request: Allow enabling useSoaSerialDateScheme per zone via API

### ISSUE THREAD

**Issue by natecoffey** [TechnitiumSoftware/DnsServer#1157]
Looking through the API documentation, it seems that the only place we can set useSoaSerialDateScheme is during creation of a Primary zone or the DNS server as a whole, but not if we're updating an SOA record.  Serial is a required field and it appears to only accept an integer, and setting it to anything (even something that's an increment of the current data scheme) disables the feature entirely.  Because there's no server-wide options for default refresh/retry/expiration/minimum (afaik, please correct me if I'm wrong), I had to update all those timings via API but then had to go back to manually re-enable useSoaSerialDateScheme afterwards on each zone via webUI.

Is this something I can do via API that isn't documented or is it something that can be added?

**Comment by ShreyasZare** [comment]
Thanks for asking. The option already exists for updating SOA record but is missing in the API docs. You can use the `useSerialDateScheme` boolean option while updating the SOA record in the zone. 

Will get the docs updated soon.

**Comment by natecoffey** [comment]
Oh great, that makes sense.  I was trying it as a Zone Option, though thinking about it now it should definitely be a Record Modify.  I was able to verify that this does indeed work and set the serial as expected to current date regardless of what serial is set to in the URI.  Thanks for getting back to me so quickly!

**Comment by ShreyasZare** [comment]
You're welcome! Just one hint, you can always check how the GUI is calling these APIs using web browser's dev tools if there is any issue with the API docs.
