### ISSUE TITLE
DoT is not listening on port 853 (or any port)

### ISSUE THREAD

**Issue by demanuPL** [TechnitiumSoftware/DnsServer#1158]
Hello, I'm trying to set up my DoT through Traefik. I've set up entrypoint in Traefik and router for my DoT:

``     - "traefik.tcp.routers.dot.entrypoints=dot"
      - "traefik.tcp.routers.dot.rule=HostSNI(`dns1.mydomain.com')"
      - "traefik.tcp.routers.dot.service=dot-service"
      - "traefik.tcp.routers.dot.tls=true"
      - "traefik.tcp.services.dot-service.loadbalancer.server.port=853"
      - "traefik.docker.network=proxy" ``
 
but Traefik cannot connect to Technitium DNS Server:

`2024-12-19T00:09:00Z ERR github.com/traefik/traefik/v3/pkg/tcp/proxy.go:48 > Error while dialing backend error="dial tcp 172.18.0.12:853: connect: connection refused"
`

DoT is configured in DNS Server on port 853 but it looks like its not listening at all. Docker tells me that container is listening on 853.

**Comment by ShreyasZare** [comment]
Thanks for the post. Since you are using docker, make sure that the container is mapping the port to the host OS. You can also run the container in "host" network mode to make it easier to configure.

This is docker config issue so nothing to do with the DNS server's DoT service.

**Comment by demanuPL** [comment]
no, its not working like this through traefik, traefik doesn't need to have redirected port as its communicating through docker network directly (both dns server and traefik are in the same network). But its working through pointing to 53 port of the dns server, I have no idea why. Does technitium can recognize handshake on port 53 and redirects this to DoT?

also I have another problem: Technitium DNS Server cannot receive source IP address sended by ProxyProtocol, I can see only IP address of Traefik container (ProxyProtocol on Traefik entrypoint is enabled)

**Comment by ShreyasZare** [comment]
> no, its not working like this through traefik, traefik doesn't need to have redirected port as its communicating through docker network directly (both dns server and traefik are in the same network). But its working through pointing to 53 port of the dns server, I have no idea why. 

Do you mean that traefik is doing TLS termination? If yes then you need to forward to the TCP port 53 on the DNS server.

If traefik is receiving on TCP and forwarding as-is then it should forward to DoT port on DNS server.

> Does technitium can recognize handshake on port 53 and redirects this to DoT?

There is no provision to do forwarding in these protocols so not technically possible.

> also I have another problem: Technitium DNS Server cannot receive source IP address sended by ProxyProtocol, I can see only IP address of Traefik container (ProxyProtocol on Traefik entrypoint is enabled)

If you are using PROXY PROTOCOL with traefik then you need to enable "Enable DNS-over-TCP-PROXY" optional protocol in settings and do TLS termination at Traefik and forward to this optional protocol port. When you do this setup, you will see the actual client's IP address on DNS logs and dashboard.

**Comment by shalafi99** [comment]
> `2024-12-19T00:09:00Z ERR github.com/traefik/traefik/v3/pkg/tcp/proxy.go:48 > Error while dialing backend error="dial tcp **172.18.0.12**:853: connect: connection refused" `
> 
> DoT is configured in DNS Server on port 853 but it looks like its not listening at all. Docker tells me that container is listening on 853.

In this setup, would traefik be attempting to reach the DoT service using a FQDN (the common name in the TLS certificate configured in Technitium DNS for DoT) or the DNS container's IP?

I hope @ShreyasZare will correct me if I'm wrong here, but I think it would not be possible to attempt DoT queries using the DNS's server IP address.

**Comment by demanuPL** [comment]
Ok, its working, I've switchet to DNS over TCP Proxy and started to work. Thank you for your help. That was my lack of knowledge that its not listening directly on port 853 and I need to redirect my traefik to TCP Proxy port

**Comment by ShreyasZare** [comment]
> Ok, its working, I've switchet to DNS over TCP Proxy and started to work. Thank you for your help. That was my lack of knowledge that its not listening directly on port 853 and I need to redirect my traefik to TCP Proxy port

You're welcome.
