### ISSUE TITLE
Support record type SSHFP

### ISSUE THREAD

**Issue by ghost** [TechnitiumSoftware/DnsServer#1161]
SSHFP - type id 44
Definition: https://datatracker.ietf.org/doc/html/rfc4255
RR Paramters: https://www.iana.org/assignments/dns-sshfp-rr-parameters/dns-sshfp-rr-parameters.xml

RR Parm Updates:
- https://datatracker.ietf.org/doc/rfc7479/
- https://datatracker.ietf.org/doc/rfc8709/
- https://datatracker.ietf.org/doc/rfc6594/

It would be nice to have a defined record type for this. I'm currently using the "unknown" type with RR type and RDATA manually defined which has been working fine for the most part. The only issue I've run into is automating servers to update their host FPs in DNS. I had to create a proxy program in the middle to translate it to technitium's API because there is no defined type for this.

**This is not of immediate need, just throwing this on the board**

**Comment by ShreyasZare** [comment]
Thanks for the post. The SSHFP record type is already supported. The record type is only available when you sign the zone with DNSSEC since that's the requirement for the record type.
