### ISSUE TITLE
how to keep the config and running data when I update it?

### ISSUE THREAD

**Issue by xgocn** [TechnitiumSoftware/DnsServer#1167]
When I  update an existing container which started with `docker run -d --name Mydns -p 53:53/udp -p 5380:5380 technitium/dns-server`, run the following commands:
```
docker compose down
docker image rm technitium/dns-server
docker compose up -d
```
Reference :  `https://blog.technitium.com/2017/11/running-dns-server-on-ubuntu-linux.html`

then，my dns server reinitialized to the default state. 

how to keep the config and running data when I update it?

**Comment by ShreyasZare** [comment]
Thanks for the post. The instructions in the blog post work only if you use the docker compose file to create the container. This is since the compose file contains config to declare the volume to allow persistence. When you run the container directly without any volume, the config wont persists.

**Comment by xgocn** [comment]
can I use `-v /path/to/your/config:/etc/dns/config`, and what's the correct parameters？

**Comment by ShreyasZare** [comment]
> can I use `-v /path/to/your/config:/etc/dns/config`, and what's the correct parameters？

Yes, you can do that. The path inside the volume must be `/etc/dns` so it will be `-v /path/to/your/config:/etc/dns`.

**Comment by xgocn** [comment]
thank you for your answer
