### ISSUE TITLE
The type or namespace name 'TechnitiumLibrary' could not be found (are you missing a using directive or an assembly reference?) 

### ISSUE THREAD

**Issue by barron9** [TechnitiumSoftware/DnsServer#117]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'TechnitiumLibrary' could not be found (are you missing a using directive or an assembly reference?)	DnsServerCore	C:\Users\berkin1\Downloads\DnsServer-master (1)\DnsServer-master\DnsServerCore\Dhcp\DhcpMessage.cs	26	Active

**Comment by ShreyasZare** [comment]
You just need to clone TechnitiumLibrary repo in the same directory where you have DnsServer repo. Once done the project will compile.
