### ISSUE TITLE
"DNS CLient" menu doh protocol cannot be resolved

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#122]
`Error! Name server returned error. DNS RCODE: ServerFailure (ServerFailure)`

"DNS CLient" menu doh protocol cannot be resolved, dot protocol resolution is normal。
![g](https://user-images.githubusercontent.com/17548936/74710318-4b2e0f00-525c-11ea-8681-97474189a94e.png)
![f](https://user-images.githubusercontent.com/17548936/74710322-4e28ff80-525c-11ea-8bf6-b9590679edaf.png)

**Comment by thb007** [comment]
![w](https://user-images.githubusercontent.com/17548936/74710441-a52ed480-525c-11ea-93a9-16efa7f3a319.png)

**Comment by ShreyasZare** [comment]
Check logs for details on this error. It seems that your server is failing to resolve domain name of the DoH server. This has something to do with your local network.

For that TLS query, there is no resolution done since its IP address is already given in brackets which is used.

**Comment by thb007** [comment]
> Check logs for details on this error. It seems that your server is failing to resolve domain name of the DoH server. This has something to do with your local network.
> 
> For that TLS query, there is no resolution done since its IP address is already given in brackets which is used.

`[2020-02-18 14:19:04 UTC] Logging started.
[2020-02-18 14:19:04 UTC] [113.12.163.202:58630] [admin] Log file was deleted: 2020-02-18
[2020-02-18 14:19:04 UTC] [127.0.0.1:44304] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:05 UTC] [127.0.0.1:46945] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:06 UTC] [127.0.0.1:59373] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:07 UTC] [127.0.0.1:55870] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:08 UTC] [127.0.0.1:36013] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:09 UTC] [127.0.0.1:46491] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:10 UTC] [127.0.0.1:38012] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:11 UTC] [127.0.0.1:44500] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:12 UTC] [127.0.0.1:38779] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:13 UTC] [127.0.0.1:56808] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:14 UTC] [127.0.0.1:42431] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:15 UTC] [127.0.0.1:48661] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:16 UTC] [127.0.0.1:59734] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:17 UTC] [127.0.0.1:33355] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:18 UTC] [127.0.0.1:46253] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:19 UTC] [127.0.0.1:45209] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:20 UTC] [127.0.0.1:44926] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:21 UTC] [127.0.0.1:37841] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:22 UTC] [127.0.0.1:56654] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:23 UTC] [127.0.0.1:56824] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:24 UTC] [127.0.0.1:49856] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:25 UTC] [127.0.0.1:51844] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:26 UTC] [127.0.0.1:55463] [UDP] QNAME: a.root-servers.net; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [198.41.0.4]
[2020-02-18 14:19:27 UTC] [127.0.0.1:46856] [UDP] QNAME: cloudflare-dns.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
[2020-02-18 14:19:27 UTC] [113.12.163.202:58672] TechnitiumLibrary.Net.Dns.DnsClientException: Name server returned error. DNS RCODE: ServerFailure (ServerFailure)
   at TechnitiumLibrary.Net.Dns.DnsClient.ParseResponseA(DnsDatagram response) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 755
   at TechnitiumLibrary.Net.Dns.DnsClient.ResolveIP(String domain, Boolean preferIPv6) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsClient.cs:line 1282
   at TechnitiumLibrary.Net.Dns.NameServerAddress.ResolveIPAddress(NameServerAddress[] nameServers, NetProxy proxy, Boolean preferIPv6, Int32 retries, Int32 timeout, DnsTransportProtocol protocol) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\NameServerAddress.cs:line 386
   at DnsServerCore.WebService.ResolveQuery(HttpListenerRequest request, JsonTextWriter jsonWriter) in Z:\Technitium\Projects\DnsServer\DnsServerCore\WebService.cs:line 3002`

**Comment by thb007** [comment]
I see this shows an error code "[2020-02-18 14:19:27 UTC] [113.12.163.202:58672] TechnitiumLibrary.Net.Dns.DnsClientException: Name server returned error. DNS RCODE: ServerFailure (ServerFailure) "

**Comment by thb007** [comment]
I can ping cloudflare-dns.com normally

**Comment by ShreyasZare** [comment]
Recursive resolution is failing on your Internet and thus the DNS Client is unable to recursively resolve the domain name in the DoH url. 

You can paste this exact text in the DNS Client server field and it should work: "Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))"

**Comment by thb007** [comment]
> Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))

ok, can use "Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))" normally, so can this feature be added in the next version, Bootstrap DNS servers are used to resolve IP addresses of the DoH / DoT resolvers you specify as upstreams.

**Comment by thb007** [comment]
Because our country's firewall has blocked a lot of domain names, recursive resolution of some domain names will cause errors. If you can add, for example, Bootstrap DNS servers to let it resolve blocked domain names, I think it is a good idea

**Comment by ShreyasZare** [comment]
> 
> 
> > Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))
> 
> ok, can use "Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))" normally, so can this feature be added in the next version, Bootstrap DNS servers are used to resolve IP addresses of the DoH / DoT resolvers you specify as upstreams.

Sure, will add the default IP addresses to the DoH url settings in next release.

**Comment by thb007** [comment]
> > > Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))
> > 
> > 
> > ok, can use "Cloudflare HTTPS (https://cloudflare-dns.com/dns-query (1.1.1.1))" normally, so can this feature be added in the next version, Bootstrap DNS servers are used to resolve IP addresses of the DoH / DoT resolvers you specify as upstreams.
> 
> Sure, will add the default IP addresses to the DoH url settings in next release.

"This Server (this-server)" cannot resolve some domain names, but "recursive resolution" can resolve normally. What is the problem?
![r](https://user-images.githubusercontent.com/17548936/74827323-30d15f80-5348-11ea-86a5-5de8faaabc45.png)
![t](https://user-images.githubusercontent.com/17548936/74827330-34fd7d00-5348-11ea-8f08-d466b365dcfb.png)

**Comment by thb007** [comment]
![2020-02-19_184902](https://user-images.githubusercontent.com/17548936/74827519-8c9be880-5348-11ea-944f-f1a41ab1396f.png)
![I@9N5U5NF)8RN0N@({5S NJ](https://user-images.githubusercontent.com/17548936/74827531-91609c80-5348-11ea-8406-88d92d9153d2.png)

**Comment by ShreyasZare** [comment]
> "This Server (this-server)" cannot resolve some domain names, but "recursive resolution" can resolve normally. What is the problem?

This server query will resolve from the forwarder that you may have configured. If no forwarder is configured then it will do recursive resolution. Check logs to see what error it shows.

**Comment by thb007** [comment]
> > "This Server (this-server)" cannot resolve some domain names, but "recursive resolution" can resolve normally. What is the problem?
> 
> This server query will resolve from the forwarder that you may have configured. If no forwarder is configured then it will do recursive resolution. Check logs to see what error it shows.

It seems the problem is also unable to resolve the domain name in the forwarder.The SSL connection could not be established.
[2020-02-20.log](https://github.com/TechnitiumSoftware/DnsServer/files/4230656/2020-02-20.log)

**Comment by ShreyasZare** [comment]
> It seems the problem is also unable to resolve the domain name in the forwarder.The SSL connection could not be established.
> [2020-02-20.log](https://github.com/TechnitiumSoftware/DnsServer/files/4230656/2020-02-20.log)

The forwarder is failing with SSL auth error and thus you are seeing ServerFailure response for This Server in the DNS Client. You need to change forwarder to something that works on your internet connection that is not blocked.

**Comment by thb007** [comment]
> > It seems the problem is also unable to resolve the domain name in the forwarder.The SSL connection could not be established.
> > [2020-02-20.log](https://github.com/TechnitiumSoftware/DnsServer/files/4230656/2020-02-20.log)
> 
> The forwarder is failing with SSL auth error and thus you are seeing ServerFailure response for This Server in the DNS Client. You need to change forwarder to something that works on your internet connection that is not blocked.

`root@www:~# curl -s "https://dns.bentasker.co.uk/dns-query?name=google-analytics.com&type=A" | python -m json.tool
{
    "AD": false,
    "Answer": [
        {
            "Expires": "Thu, 20 Feb 2020 13:15:58 UTC",
            "TTL": 300,
            "data": "172.217.14.68",
            "name": "google-analytics.com.",
            "type": 1
        }
    ],
    "CD": false,
    "Question": [
        {
            "name": "google-analytics.com.",
            "type": 1
        }
    ],
    "RA": true,
    "RD": true,
    "Status": 0,
    "TC": false
}
root@www:~#
`

**Comment by thb007** [comment]
![{5}GKG}8K52XK4N9RP4_RP3](https://user-images.githubusercontent.com/17548936/74937207-9431bf00-5426-11ea-9e69-e42e40ba4af1.png)

**Comment by thb007** [comment]
![t](https://user-images.githubusercontent.com/17548936/74937306-c0e5d680-5426-11ea-9d6e-5676f2157e89.png)

**Comment by thb007** [comment]
![260UM 0NR}I~_3506L_3}YN](https://user-images.githubusercontent.com/17548936/74937444-03a7ae80-5427-11ea-9380-e1619ba22b20.png)

**Comment by ShreyasZare** [comment]
> 
> 
> ![t](https://user-images.githubusercontent.com/17548936/74937306-c0e5d680-5426-11ea-9d6e-5676f2157e89.png)

From the error it seems that the DoH server is not responding fast enough causing timeout errors.

**Comment by ShreyasZare** [comment]
@SeriousHoax Thanks for asking. Technitium DNS Server comes with a built-in recursive resolver so there is no need for any bootstrap option as it can resolve any domain name on its own. The recursive resolution will work over plain text DNS protocols but if you have DoH configured, the certificate is validated when querying it so its not an issue.

The other software you mentioned can only do forwarding and thus requires a bootstrap to work.

Its still better to avoid resolving the IP for DoH URLs so you can configure the forwarders with the syntax as shown below:
```
https://security.cloudflare-dns.com/dns-query (1.1.1.1)
https://dns.quad9.net/dns-query (9.9.9.9)
```
The DNS server will use the IP address you specify in round brackets to connect to the DoH server and wont require any separate resolution.

**Comment by SeriousHoax** [comment]
@ShreyasZare WoW! That was such a quick reply. 
Thank you very much for the explanation. 

But one thing that I have noticed in the cache is that in my current setup without specifying the IP address, it uses Quad9 the most out of these two and Quad9's other IP address 149.112.112.112 is what I see in the cache. How does it determine the IP address automatically? Pinging both addresses in my Windows terminal gives me similar pings. Would giving the IP address (only one like 9.9.9.9) manually unintentionally disrupt something? 

Another question is, if I use DoT and use the quick add option to add Quad9, it adds it like this,

```
dns.quad9.net (9.9.9.9:853)
dns.quad9.net (149.112.112.112:853)

```
So both IP addresses are given. But I want to use both of Cloudflare and Quad9 concurrently. In that case, I added 

```
security.cloudflare-dns.com (1.1.1.2:853)
security.cloudflare-dns.com (1.0.0.2:853)
dns.quad9.net (9.9.9.9:853)
dns.quad9.net (149.112.112.112:853)

```
But when I set it up like this, I saw that all queries were getting solved by Cloudflare while in my current DoH setup that I mentioned in my previous comment, 9/10 queries were being handled by quad9. Why is that? What would be the ideal way for me to use Cloudflare & Quad9 DoT? Do I need to change the default concurrent forwarder setting? 

I would appreciate your explanation and guidance.

**Comment by ShreyasZare** [comment]
@SeriousHoax You're welcome. 

If you do not specify IP addresses for the DoH URL or DoT domain name then it is resolved recursively. The IP address you see is what they provide when doing recursive resolution so its what is used by the DNS server. The fancy IP addresses (i.e. 1.1.1.1 or 9.9.9.9) are Anycast addresses and they do not provide it when resolving domain name for some reason. It really does not matter what IP is being used since its the IP they want to you use when you resolve it from your server. Using either the resolved IP address or specifying the Anycast IP address will work with no issues.

When you have multiple forwarders configured, the DNS server uses machine learning algorithm to find out which one performs better and then uses it for most of the time. So what you observe is due to that algorithm deciding that a specific upstream server is faster and thus being used for most queries. You do not have to do anything here as its automatic and will keep learning how all of the upstream servers respond to give you fastest answer.

**Comment by ShreyasZare** [comment]
> So whether I use 4 entries like above,
> Or just two like below, it doesn't really matter.

You can add any number of entries for forwarder and let the algorithm choose the best one to use. You do not need to think which one is better to use here and let it be done automatically.

> Though I must say that when I use an app to check connections made by Technitium, when 4 is used, I see all 4 connections So I think I will just skip one for each and use 1.1.1.2 and 9.9.9.9 since using four doesn't have any benefit.

It will show 4 connections since the algorithm will be testing all of them at some random interval. But, it will remember which one was faster and gave answers without any errors and use it most of the times.

> When you release the next version, consider adding Cloudflare Security and Family DNS in the quick add section.

Since each public DNS provider has too many combinations based on the type of service they provide, its not feasible to add all of those combinations in the list to prevent it from being too large to become a problem to use.

But, you can already customize the list for your setup if you have the latest version running. Check the instructions given in the second point in the [change log](https://github.com/TechnitiumSoftware/DnsServer/blob/master/CHANGELOG.md#version-136).

**Comment by SeriousHoax** [comment]
@ShreyasZare 
> You can add any number of entries for forwarder and let the algorithm choose the best one to use. You do not need to think which one is better to use here and let it be done automatically.
> 
Does this cause multiple, like 4 DNS query (A) for the same domain in the beginning while the algorithm is still testing and learning? Asking because I think this is what I saw in the query log. 
> Since each public DNS provider has too many combinations based on the type of service they provide, its not feasible to add all of those combinations in the list to prevent it from being too large to become a problem to use.

Oh yeah, you are right. The current list is already big enough, so not adding more makes sense indeed.

> 
> But, you can already customize the list for your setup if you have the latest version running. Check the instructions given in the second point in the [change log](https://github.com/TechnitiumSoftware/DnsServer/blob/master/CHANGELOG.md#version-136).

Thanks for this. I will definitely check this out tonight. 

BTW, what's the best place to ask you random questions like this to better understand the product? I commenting on an issue created by another user which is not ideal and I probably shouldn't ask too many questions here. 

So one last question is, for your personal usage what value do you use for minimum cache TTL? I have been using it with 86400, so 24 hours which is a pretty big number I assume but everything has been smooth so far.

**Comment by ShreyasZare** [comment]
@SeriousHoax 
> I see, thank you. I will lower the value of minimum cache. Yesterday, I saw two errors from the upstream forwarder, which were cached and kept serving those errors from the cache. One of which was Microsoft SmartScreen related on the Edge browser. I had to manually delete the cache to fix that. This kind of issue may arise with such a huge value like mine I assume.

Ya, such issues are possible so the default values are recommended as they work well for most scenarios very well.

> Thanks, really appreciate your help. You are definitely not one of those devs who show a lot of ego and get mad when a few questions are asked. Very humble and helpful. Keep up the good work 👏

Thanks for the kind words and compliments.
