### ISSUE TITLE
Access Dashboard from Client Computer

### ISSUE THREAD

**Issue by jre08** [TechnitiumSoftware/DnsServer#124]
I can't believe how good this works; and thank you for your such a great product (at a great PRICE!)  

I was wondering if there is a way to access the Dashboard page from a separate client computer.  I am able to access the GUI page on the local server.  However when I try to access the dashboard (gui) from another client it gives me a 

> Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.

**Comment by jre08** [comment]
Right after posting the original post  I discovered I can only access the dashboard on the Server using Localhost:5380 (local browser).  So is the server only listening for the localhost header request or something?  I tried using my root home network name to access the page from the server (local browser) and received the same error from original post 

> Bad Request - Invalid Hostname
HTTP Error 400. The request hostname is invalid.

**Comment by ShreyasZare** [comment]
Thanks for the compliments. The DNS server tries to listen on all interfaces (using 0.0.0.0) and if that fails (usually due to permission issues) it will listen only on localhost. If you are on Windows, just running the server as elevated administrator will fix this issue. Do check logs as it will give hints on why it failed to bind to 0.0.0.0 address.

**Comment by jre08** [comment]
Thank you sir for the reply; Yes I am using Windows 10 Home Edition (Server).  This did fix my problem; for anyone else that has this issue.

I am now able to access the dashboard (GUI) on the server from a client by running the DnsServerApp on the 'server' as admin.  (Run as administrator by right click; or one of the many others ways)

**Comment by ShreyasZare** [comment]
I would suggest that you install the setup instead of using the standalone portable app. The setup will install the DNS server as a service and that will keep running in background automatically.
