### ISSUE TITLE
What if cache is lost after reboot?

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#128]
After the system restarts, all cached data is lost, resulting in longer parsing time.

**Comment by thb007** [comment]
After I added the doh address, I found it impossible to use! It seems that recursive resolution cannot resolve the domain name I added! Can I increase the upstream DNS to resolve the doh domain name?

**Comment by Globulopolis** [comment]
See https://github.com/TechnitiumSoftware/DnsServer/issues/41#issuecomment-470054939

**Comment by thb007** [comment]
> See [#41 (comment)](https://github.com/TechnitiumSoftware/DnsServer/issues/41#issuecomment-470054939)

After I added the doh address, I found it impossible to use! It seems that recursive resolution cannot resolve the domain name I added! Can I increase the upstream DNS to resolve the doh domain name?

**Comment by ShreyasZare** [comment]
> 
> 
> > See [#41 (comment)](https://github.com/TechnitiumSoftware/DnsServer/issues/41#issuecomment-470054939)
> 
> After I added the doh address, I found it impossible to use! It seems that recursive resolution cannot resolve the domain name I added! Can I increase the upstream DNS to resolve the doh domain name?

Regarding cache, the comment linked gives the reason for not storing cache on disk. Cache and DoH are not directly related to each other.

For DoH url that you are using, you need to check if that url is accessible from your network as in some regions certain domain names are blocked by ISPs. 

To check the DoH url, use the built in DNS Client tab and put the url in there and select protocol as HTTPS. Now try to resolve any domain name and see if that is working. If its working then it should also work when you set that url as DoH forwarder. If its not working then your ISP is probably blocking that domain name in the url. In such case, you can explicitly specify the IP address to be used by the DNS server. To do that, just find the IP address of the domain name and put it in a bracket after url with a space in between like this:

`https://cloudflare-dns.com/dns-query (1.1.1.1)`

To find IP address use any DNS tool website like [dnsclient.net](https://dnsclient.net/) and get the IP address.

**Comment by thb007** [comment]
> > > See [#41 (comment)](https://github.com/TechnitiumSoftware/DnsServer/issues/41#issuecomment-470054939)
> > 
> > 
> > After I added the doh address, I found it impossible to use! It seems that recursive resolution cannot resolve the domain name I added! Can I increase the upstream DNS to resolve the doh domain name?
> 
> Regarding cache, the comment linked gives the reason for not storing cache on disk. Cache and DoH are not directly related to each other.
> 
> For DoH url that you are using, you need to check if that url is accessible from your network as in some regions certain domain names are blocked by ISPs.
> 
> To check the DoH url, use the built in DNS Client tab and put the url in there and select protocol as HTTPS. Now try to resolve any domain name and see if that is working. If its working then it should also work when you set that url as DoH forwarder. If its not working then your ISP is probably blocking that domain name in the url. In such case, you can explicitly specify the IP address to be used by the DNS server. To do that, just find the IP address of the domain name and put it in a bracket after url with a space in between like this:
> 
> `https://cloudflare-dns.com/dns-query (1.1.1.1)`
> 
> To find IP address use any DNS tool website like [dnsclient.net](https://dnsclient.net/) and get the IP address.

thanks
