### ISSUE TITLE
[request] implementing WFP for dns intercepting

### ISSUE THREAD

**Issue by cubakcabak** [TechnitiumSoftware/DnsServer#13]
[Windows Filtering Platform](https://docs.microsoft.com/en-us/windows/desktop/fwp/windows-filtering-platform-start-page) is used by adguard to intercept dns request, users doesnt need to made adjustment/change to every (multiple) network interface on their pc/laptop.

it will be nice if you can implement the feature so it will be fully automatically ready to use on get go.

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. It looks interesting thing to implement. 

It will help users on Windows to quickly get things running, however the option wont look transparent enough like what it looks now. Right now the user has option to configure it manually and to remove using it temporarily if required.

It would be much better to configure the DNS in the network adapter either automatically or from additional option in the panel than using the filtering option. I can think of having network settings option for such usage in the web console in future release.

Any such auto configuration options are difficult to implement when the design goal is to have cross-platform implementation.

**Comment by cubakcabak** [comment]
an option knobs enabling and disabling dns per interface inside the panel would be the best options, i guess.

taken example from simplednscrypt apps, that exactly do that.

so user didn't need to "go out" from single main portal panel to configure things.

thank you for your wonderful software, best of luck.

**Comment by ShreyasZare** [comment]
@cubakcabak : I think this issue can be closed now since we got some features that cover it partly:
- System Tray App to control the DNS service and manage the system's network DNS server config.
![image](https://user-images.githubusercontent.com/10008172/52176217-a61dd100-27d5-11e9-9a4e-a55471467fe9.png)
