### ISSUE TITLE
Feature: Limit requests

### ISSUE THREAD

**Issue by telehost** [TechnitiumSoftware/DnsServer#130]
Hi there. Thanks for this great project.

There should be a possibility to handle number of requests per source, per domain, total. I know I can handle external but it would be cool to have this directly via GUI.

Thank you!

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Can you help me understand how do you plan to use this feature?

**Comment by Globulopolis** [comment]
> 
> 
> Thanks for the feature request. Can you help me understand how do you plan to use this feature?

It's is useful in commercial setups. Like on dnsmadeeasy to limit requests per month/per user.

**Comment by ShreyasZare** [comment]
I have already implemented this feature now and will be available in a week. This feature is designed to limit requests from IP addresses in order to stop abuse of service or prevent amplification attacks.

**Comment by ShreyasZare** [comment]
New version 6.3 is now available with support for limiting requests.
