### ISSUE TITLE
Blocklist Urls Quick Add

### ISSUE THREAD

**Issue by Cossey** [TechnitiumSoftware/DnsServer#131]
It appears that all the `hosts-file.net` block lists no longer exist so they should be removed from the _Quick Add Dropdown_ in Settings.

[Firebog](https://firebog.net/) seems to have a collection of block lists from themselves and other people - maybe some of these lists could be included in the _Quick Add Dropdown_ instead?

_I think in the future it may be beneficial moving away from the Quick Add Dropdown and instead show a Bootstrap Model which contains block lists, grouped by categories with either add buttons or a checklist which you can then add to the Block List URLs en masse._

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will remove those block list urls from the quick add dropdown. As you suggested, having a model popup that allows you to manage urls would be much better way for sure.

**Comment by ShreyasZare** [comment]
Dead block lists now have been removed.
