### ISSUE TITLE
Listening on a port other than port 53

### ISSUE THREAD

**Issue by rlagmlah** [TechnitiumSoftware/DnsServer#132]
Hello.
I am currently using TechnitiumDNS in FreeNAS jail. So far, TechnitiumDNS has been run as the root user, but I think this is undesirable.
So, I tried to run TechnitiumDNS as a non-root user, but I couldn't use DNS server because I couldn't bind to port 53.
The workaround for this is to use mac_portacl or add the variable 'net.inet.ip.portrange.reservedhigh = 0' to sysctl, but in FreeNAS mac_portacl does not work and 'net.inet.ip.portrange.reservedhigh = 0' Commands are a security risk.
So, TechnitiumDNS wants to listen to a non-privileged port such as 5353 and forwards 53 ports to 5353 using a firewall such as ipfw, but currently TechnitiumDNS does not support this function.
So, can you add a setting that allows TechnitiumDNS to listen to a port other than port 53?
Thanks.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will add option to change the port.

**Comment by rlagmlah** [comment]
Great! Thank you. Will it apply to the next release?

**Comment by ShreyasZare** [comment]
This should not take much time to add so mostly will get it in next release itself.

**Comment by ShreyasZare** [comment]
New release now has support to configure local IP addresses and ports.

**Comment by rlagmlah** [comment]
The port change worked fine. However, using port forwarding, I was unable to receive udp responses from DNS servers. (tcp works) Thanks anyway.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Just found a bug in the built in DNS Client tab which causes it to always use port 53 with "This Server" for querying. If you manually enter address with the changed port, like 127.0.0.1:5353 then it is working. This will get fixed in next update.
