### ISSUE TITLE
Fail to install on Xubuntu 20.04

### ISSUE THREAD

**Issue by iwillneverstop** [TechnitiumSoftware/DnsServer#135]
Could you update the installation for Ubuntu (https://blog.technitium.com/2017/11/running-dns-server-on-ubuntu-linux.html) to be compatible with the latest Ubuntu 20.04?

Currently, when I run "curl -sSL https://download.technitium.com/dns/install-ubuntu.sh | sudo bash" as suggested from the link above, it is stuck at "Trying again ..." infinite times.

Thank you for your time.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. It seems that Microsoft has not made dotnetcore available for Ubuntu 20.04 yet. 

Here is the issue being tracked: [https://github.com/dotnet/docs/issues/18084](https://github.com/dotnet/docs/issues/18084)

**Comment by iwillneverstop** [comment]
Thanks for your reply. I got it. Waiting for them to fix the problem.

**Comment by ShreyasZare** [comment]
This issue is fixed now.
