### ISSUE TITLE
Make the list of resolvers the same

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#138]
Because list in `DNS Client` is much bigger than in `Settings - Forwarders`. ;)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The forwarder list is pretty much the same that you have in the DNS Client. Only lesser known providers like Ultra, Level3, and Dyn are not listed.

**Comment by Globulopolis** [comment]
> Thanks for the feedback. The forwarder list is pretty much the same that you have in the DNS Client. Only lesser known providers like Ultra, Level3, and Dyn are not listed.

Quad9 unsecure not listed too.

**Comment by ShreyasZare** [comment]
Will add Quad9 unsecure to the list. Do you wish to add any other provider?

**Comment by Globulopolis** [comment]
> Will add Quad9 unsecure to the list. Do you wish to add any other provider?

Thanks.
Imo... How about to add possibility to user for edit this list? Something like a typical txt file with list of resolvers separated by comma, new line, etc. And if file is not found or parsing error when use predefined hardcoded list of resolvers?

**Comment by ShreyasZare** [comment]
This can be done in later releases.

**Comment by ShreyasZare** [comment]
Issue fixed with new release.
