### ISSUE TITLE
Feature Request - Add OpenDNS FamilyShield servers

### ISSUE THREAD

**Issue by Marshall321** [TechnitiumSoftware/DnsServer#139]
Would it be possible to add the OpenDNS FamilyShield DNS servers to the preconfigured list of resolvers? 208.67.222.123 and 208.67.220.123 offer OpenDNS funtionality without having to have an OpenDNS account and they are preset to block the Pornography, Tasteless, Proxy/Anonymizer, and Sexuality categories, which is quite useful for Guest type access with zero maintenance.

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. Will add it in next release.

**Comment by ShreyasZare** [comment]
Added to v5 release.
