### ISSUE TITLE
[request] linux version

### ISSUE THREAD

**Issue by cubakcabak** [TechnitiumSoftware/DnsServer#14]
dnscrypt has linux (and android) binary support, i hope this one will have it too.

with dns-over-tls and host blacklist, and easy management via web console, it's a perfect replacement for dnscrypt and the commercial adguard.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This DNS server is already cross-platform and can be used on any Linux or Mac using .NET Core runtime.

There is no installer available for now but, I will be working on an installer script for Ubuntu that will help in installing the DNS server as a daemon.

Right now, you can read [this blog post](https://blog.technitium.com/2017/11/running-dns-server-on-ubuntu-linux.html) and find out how to run DNS Server on Linux.
