### ISSUE TITLE
DHCP Relay fails

### ISSUE THREAD

**Issue by cs-network** [TechnitiumSoftware/DnsServer#141]
On a clean Ubuntu 18.04 Installation with your provided script for setup DHCP using relay agent fails in V4.1.
tcpdump show frames coming in, but no answer getting out.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Can you provide more details like errors in log file? tcpdump pcap file will help a lot. Also, put screenshots of the scope settings.

**Comment by ShreyasZare** [comment]
The issue was not reproduce able. I have tested this again with DHCP relay agent on Windows Server 2016 and it works well.
