### ISSUE TITLE
New version ??

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#142]
It's 3-6-2020 The update has not yet come, can you rush to it?

**Comment by ShreyasZare** [comment]
Thanks for the post. Its taking a bit time but should be available in a couple of weeks.

**Comment by thb007** [comment]
> Thanks for the post. Its taking a bit time but should be available in a couple of weeks.

ok

**Comment by muhanadali100** [comment]
it's 2-7-2020 ??

**Comment by ShreyasZare** [comment]
Its going to be released this weekend. All tests are working well and load testing too gave excellent results. Will update here to confirm availability.

**Comment by thb007** [comment]
> Its going to be released this weekend. All tests are working well and load testing too gave excellent results. Will update here to confirm availability.

good

**Comment by ShreyasZare** [comment]
New version is now available for download.
