### ISSUE TITLE
systemtray app missing in archlinux

### ISSUE THREAD

**Issue by 0xXA** [TechnitiumSoftware/DnsServer#144]
![Screenshot_20200611_190934](https://user-images.githubusercontent.com/45941452/84391857-28fb3b00-ac17-11ea-85f4-ffe837718d31.png)

**Comment by ShreyasZare** [comment]
System tray app is only available on Windows platform. There is no support to have a system tray icon in .NET Core for Linux.

**Comment by 0xXA** [comment]
look i setup dns server but im not able to see queries and cant block them also in windows i created a profile with 127.0.0.1 and ::1 as ipv4 and ipv6 but now on linux no queries are logged and cant block so how can i do it in linux ?

**Comment by ShreyasZare** [comment]
> look i setup dns server but im not able to see queries and cant block them also in windows i created a profile with 127.0.0.1 and ::1 as ipv4 and ipv6 but now on linux no queries are logged and cant block so how can i do it in linux ?

I am not sure what your setup is. Are you running DNS server on linux and want to use it over network on your Windows machine? Describe your setup and configuration fully.

**Comment by 0xXA** [comment]
![g1](https://user-images.githubusercontent.com/45941452/84475143-a53e5e80-aca9-11ea-8dcc-067bcbfbe01e.png)
![g2](https://user-images.githubusercontent.com/45941452/84475160-ac656c80-aca9-11ea-94cd-23ea406117ce.png)
![g3](https://user-images.githubusercontent.com/45941452/84475176-b2f3e400-aca9-11ea-9e8a-ca042398d6a6.png)

**Comment by ShreyasZare** [comment]
Your configuration in the first screenshot has issues. 
- Never change Local Addresses unless you understand the option and really need to do it. Restore the original values "0.0.0.0" and "::".

- Uncheck all the optional DNS Server protocols. These options are to be used if you want to host your own DNS service with these protocols enabled. You do not need to enable them to just use 3rd party DNS services that you configure as forwarders. Use the Forwarder Protocol option in there. Best is to use the Quick Select dropdown to configure it correctly.

- If you want to use the DNS server on the same computer then you need to configure it's network settings to use 127.0.0.1 and ::1 as the DNS Servers.

- If you want to use the DNS server over network on other devices, make sure you have a static IP address on your computer that is hosting the DNS Server and use that IP address as DNS server on other computers. Better way is to use the DHCP server on your home router to configure DNS on all computers or use the built in DHCP server in the DNS Server.

**Comment by 0xXA** [comment]
[2020-06-12.log](https://github.com/TechnitiumSoftware/DnsServer/files/4769662/2020-06-12.log)

**Comment by 0xXA** [comment]
i definetly want to host my custom DNS and everything is fine on windows where i block malware and game site but not working with my linux

**Comment by ShreyasZare** [comment]
From the log file it seems you are not using the Quick Select drop down for the forwarder configuration and trying out random forwarder protocol. Use the Quick Select option to correctly select forwarder and protocol option.

On Linux, you may be having **dnsmasq** or **systemd-resolved** that uses port 53 which the DNS server requires. You will need to disable them and then restart the DNS server daemon. Read [this blog post](https://blog.technitium.com/2017/11/running-dns-server-on-ubuntu-linux.html) to get more insights.

**Comment by 0xXA** [comment]
> From the log file it seems you are not using the Quick Select drop down for the forwarder configuration and trying out random forwarder protocol. Use the Quick Select option to correctly select forwarder and protocol option.
> 
> On Linux, you may be having **dnsmasq** or **systemd-resolved** that uses port 53 which the DNS server requires. You will need to disable them and then restart the DNS server daemon. Read [this blog post](https://blog.technitium.com/2017/11/running-dns-server-on-ubuntu-linux.html) to get more insights.

i disabled forwarders now and yesterday i disabled systemd-reslved may it reactivated on a restart ?

**Comment by ShreyasZare** [comment]
> i disabled forwarders now and yesterday i disabled systemd-reslved may it reactivated on a restart ?

Run **netstat -nlptu** and post the output here.

**Comment by 0xXA** [comment]
> 
> 
> > i disabled forwarders now and yesterday i disabled systemd-reslved may it reactivated on a restart ?
> 
> Run **netstat -nlptu** and post the output here.

hi, how can i block no data domains with DNS Server ? i know it can't but if u can add support for it it will be great also i'm a malware researcher so some malware connects to internet via no data domains that do not resolves to a hostname

**Comment by ShreyasZare** [comment]
> > Run **netstat -nlptu** and post the output here.
> 
> hi, how can i block no data domains with DNS Server ? i know it can't but if u can add support for it it will be great also i'm a malware researcher so some malware connects to internet via no data domains that do not resolves to a hostname, i know i can use firewall for this purpose but they bypass that too

I am not sure what "no data domains" are. Are you talking about domain names generated using algorithms by the malware so that the malware controller can register them later in event of primary domain take down?

**Comment by 0xXA** [comment]
> I am not sure what "no data domains" are. Are you talking about domain names generated using algorithms by the malware so that the malware controller can register them later in event of primary domain take down?
domains that do not resolves to a hostname i.e 187.99.xx.xx ( not resolves to a hostname or ip only)

**Comment by ShreyasZare** [comment]
There is no provision in the protocol to block domain names that have no/empty response. A no/empty response in itself acts as if the domain is not resolvable.

**Comment by 0xXA** [comment]
> 
> 
> There is no provision in the protocol to block domain names that have no/empty response. A no/empty response in itself acts as if the domain is not resolvable.

man, oh sorry i forgot that its server's ip it don't contain any domain name 
like gcloud, azure, etc but the ip is active in `Fast Resolver Tool`
