### ISSUE TITLE
IP fail over (Automatic change of IP addresses for A and MX records) Feature Request

### ISSUE THREAD

**Issue by akcpk** [TechnitiumSoftware/DnsServer#145]
DNS Failover keeps sites and web services online in the event of system or network issues. This is done by moving DNS traffic from one IP address to another IP address that is running at another location (secondary IP). 

1. Failover should use health checks (ping,http,https connectivity etc.) to monitor the status of the IP address(es) in DNS (A, Mx, txt etc.) records. 

2. Health checks should run every 1-4 minutes (set by user) to monitor that server is online or offline. Additionally it can alert users by emails that primary ip is down the server is switching to secondary IP and vice versa.

3. A failover event will occur if the monitoring system reports that first/primary IP address (e.g. against a record) as down. In that case, then system should update the record to point to your backup (secondary) IP address.

4.  The system should continue to monitor primary IP Address (in point 1), even after a failover event has occurred. When it comes back online, it should automatically “failback” traffic to primary IP.

**Comment by Globulopolis** [comment]
This would be a killer feature.

**Comment by ShreyasZare** [comment]
Thanks for the feature request.

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download that supports DNS Apps. A Default DNS App is now available to [download](https://download.technitium.com/dns/DefaultDnsApp.zip) which supports Split Horizon, Geo-location based responses, etc. This app will get updated in coming days to support health checks and respond with the healthy records.

If you are interested in making a more customized app, you can fork the Default DNS App on GitHub and add/update your own logic and deploy the app on your DNS server.

**Comment by ShreyasZare** [comment]
Failover DNS app is now available on the DNS App Store. The app supports email alerts as well as web hooks to notify on health status changes.
