### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#147]
I ran it for a whole day. I was surprised today morning that it was turned off until I made a reboot for the server and went back to work.

[2020-07-05.log](https://github.com/TechnitiumSoftware/DnsServer/files/4875041/2020-07-05.log)

![44](https://user-images.githubusercontent.com/31727156/86534945-73ee3280-bee5-11ea-82fd-ab912e473a71.png)

![332](https://user-images.githubusercontent.com/31727156/86534967-a1d37700-bee5-11ea-8c3b-8509b7e034dc.png)
![333](https://user-images.githubusercontent.com/31727156/86534968-a39d3a80-bee5-11ea-8d78-adf57959c205.png)
![665](https://user-images.githubusercontent.com/31727156/86534969-a435d100-bee5-11ea-872b-4a32c1156b7c.png)

**Comment by ShreyasZare** [comment]
Thanks for the detailed info. The logs are mostly network issues and does not give any particular info about the crash. 

Do let me know about the OS and the hardware config that is being used. I would also suggest to keep an eye on the stats like CPU and memory utilization and try to find out the stats when the service is crashing. 

Also do check the system logs which will include details of why the process crashed. 

I see that you are using 8.8.8.8 and 1.1.1.1 forwarders for the DNS server. I suggest that you try running the server without any forwarders as a recursive resolver and see if you get any better results.

**Comment by muhanadali100** [comment]
I used Ubuntu-Server 16.04.6
Hardware :
Core i5-3470 4Core-4threads
Ram 8GB 1600
SSD 128GB

I used ESXI 6.5
 log 5/7/2020
[syslog.2.gz](https://github.com/TechnitiumSoftware/DnsServer/files/4878967/syslog.2.gz)
log 4/7/2020
[syslog.3.gz](https://github.com/TechnitiumSoftware/DnsServer/files/4878974/syslog.3.gz)

**Comment by ShreyasZare** [comment]
Thanks for the logs. The logs is showing that the dns-service is starting and stopping. I could not find any entry which could indicate reason for the service to crash. The systemd service config however has a restart option set to 10 seconds and if the service process crashes, it should start automatically. 

How much RAM does the VM running on the ESXi has?

**Comment by muhanadali100** [comment]
ESXI 16GB
DNS SERVER 8GB

**Comment by ShreyasZare** [comment]
Thanks for the details. The DNS service should ideally restart automatically by systemd and if thats not happening then it could be that the process is not really crashing cleanly. When this scenario repeats, do check for clues to see if the process is indeed not running, check the CPU and memory stats and check if the process is still bound to the TCP and UDP ports, etc.

**Comment by muhanadali100** [comment]
[2020-07-07.log](https://github.com/TechnitiumSoftware/DnsServer/files/4884591/2020-07-07.log)

[syslog.gz](https://github.com/TechnitiumSoftware/DnsServer/files/4884592/syslog.gz)

https://youtu.be/Tf96s-GbZmY

I captured a video for the proplem

**Comment by ShreyasZare** [comment]
Thanks for the video and the logs. From the logs it seems that you are getting no response from the Google and Cloudflare forwarders for huge number of minutes like easily for more than 30 mins. This can be either some network issue at your end or that you are hitting the threshold for number of queries from single IP address and are being [rate-limited](https://developers.google.com/speed/public-dns/docs/security#rate_limit). This will cause Google or Cloudflare services to not respond to any queries from your IP address. Since you have a lot of users, it is bound to happen at peak hours. I would recommend that you remove the forwarders configured and let the server run its own recursive resolver and see if that helps.

Adding more forwarders wont help since the DNS server will send queries to *all* the forwarders and get the response from the first one that responds thus getting quick responses. So adding more forwarders will just increase the outbound traffic and wont do any kind of load balancing.

In such scenarios (network issues etc) the server will have a thousands of threads waiting for response from the forwarders and that will cause using up all the threads available in the thread pool. The web console uses the same thread pool and in such case wont respond to requests. This is a likely scenario that is occurring and the server is not really crashing which explains why there is nothing in the syslog.

I would also suggest that instead of reboot the server each time there is no response from the DNS web console, just check the stats on the server like checking for "netstat -nlptu" to see if the dotnet process is running and bound to the tcp and udp ports. Do check for CPU and memory utilization for the dotnet process. Keep an eye on the network bandwidth being used at peak hours and at normal hours. This will help in understanding the issue better.

Since, you have many users, do consider having 2 DNS servers running for redundancy and load balancing. This is useful with any software that you use since there can be issues with servers and software freezing or crashing. Having a couple of servers will help keeping things working well.

**Comment by muhanadali100** [comment]
if i remove the forwarders the network is cut , all the website doesn't work

**Comment by muhanadali100** [comment]
I apologized that I closed it by mistake

**Comment by muhanadali100** [comment]
in the ubuntu server I use nameserver 127.0.0.1 if i removed the forwarders the network is stopped how can i fix it ???

**Comment by ShreyasZare** [comment]
> in the ubuntu server I use nameserver 127.0.0.1 
If you mean for the resolv.conf then this is not used by the DNS server. The resolv.conf is just to let the system resolve DNS using the name servers.

> if i removed the forwarders the network is stopped how can i fix it ???
If you remove the forwarders from the DNS server settings then no domain is resolved? If that is the case then its network issue or probably your ISP blocking outbound DNS queries. You will need to test this to confirm. Use the DNS Client tab and try to query using "Recursive Query" and see if domain names are resolving.

**Comment by muhanadali100** [comment]
![Desktop Screenshot 2020 07 07 - 16 39 27 07](https://user-images.githubusercontent.com/31727156/86789894-8183f380-c070-11ea-88cc-d6e0f3fee158.png)


![Desktop Screenshot 2020 07 07 - 16 39 34 11](https://user-images.githubusercontent.com/31727156/86789907-85177a80-c070-11ea-987b-04d2b5164a5f.png)
![Desktop Screenshot 2020 07 07 - 16 39 41 35](https://user-images.githubusercontent.com/31727156/86789910-85b01100-c070-11ea-8d8d-b7284cba41cd.png)
![Desktop Screenshot 2020 07 07 - 16 38 23 22](https://user-images.githubusercontent.com/31727156/86789918-8779d480-c070-11ea-8e92-a65f0dac3695.png)

**Comment by ShreyasZare** [comment]
> ![Desktop Screenshot 2020 07 07 - 16 38 23 22](https://user-images.githubusercontent.com/31727156/86789918-8779d480-c070-11ea-8e92-a65f0dac3695.png)

Ahh! It seems your ISP is hijacking your DNS requests and that's why "f.gtld-servers.net" is responding with an "answer" to the www.facebook.com query. Probably, the domain names are being blocked by your ISP.

**Comment by muhanadali100** [comment]
I'm the isp , I have a puplic ip and I don't blocking anything , I made a dstnat address 15.15.15.4(DNS) to the 8.8.8.8 (Google)  i disable it now
![Desktop Screenshot 2020 07 07 - 17 14 58 19](https://user-images.githubusercontent.com/31727156/86794704-78495580-c075-11ea-9916-c11bea96dc39.png)
![Desktop Screenshot 2020 07 07 - 17 15 05 24](https://user-images.githubusercontent.com/31727156/86794715-7aabaf80-c075-11ea-9b69-beb36337cf43.png)

i check with netstat -nlptu

![Desktop Screenshot 2020 07 07 - 17 17 29 43](https://user-images.githubusercontent.com/31727156/86795948-c14dd980-c076-11ea-9cd5-b9b93faad906.png)




![Desktop Screenshot 2020 07 07 - 17 20 00 19](https://user-images.githubusercontent.com/31727156/86795969-c6ab2400-c076-11ea-9735-b4790f2fbcfa.png)


![Desktop Screenshot 2020 07 07 - 17 19 56 77](https://user-images.githubusercontent.com/31727156/86795959-c4e16080-c076-11ea-92da-6866f31e04ef.png)

**Comment by muhanadali100** [comment]
> Ahh! It seems your ISP is hijacking your DNS requests and that's why "f.gtld-servers.net" is responding with an "answer" to the [www.facebook.com](http://www.facebook.com) query. Probably, the domain names are being blocked by your ISP.

what i can do to fix the proplem , What is it supposed to give me when I use DNS Client ??

**Comment by ShreyasZare** [comment]
> I'm the isp , I have a puplic ip and I don't blocking anything , I made a dstnat address 15.15.15.4(DNS) to the 8.8.8.8 (Google) i disable it now

Its not good to use public IP addresses that you are not assigned for internal private usage.

**Comment by ShreyasZare** [comment]
> 
> 
> > Ahh! It seems your ISP is hijacking your DNS requests and that's why "f.gtld-servers.net" is responding with an "answer" to the [www.facebook.com](http://www.facebook.com) query. Probably, the domain names are being blocked by your ISP.
> 
> what i can do to fix the proplem , What is it supposed to give me when I use DNS Client ??

Check this [dnsclient.net link](https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/www.facebook.com/A/UDP) where you will see the response for a recursive query. You will see the the Facebook's name servers are responding with the answer whereas in your case, the Verisign name servers are responding with answer which means that someone on your network path is spoofing all IP addresses for "gtld-servers.net" and then responding with "answers" that could be filtered or modified.

**Comment by muhanadali100** [comment]
> 
> 
> > > Ahh! It seems your ISP is hijacking your DNS requests and that's why "f.gtld-servers.net" is responding with an "answer" to the [www.facebook.com](http://www.facebook.com) query. Probably, the domain names are being blocked by your ISP.
> > 
> > 
> > what i can do to fix the proplem , What is it supposed to give me when I use DNS Client ??
> 
> Check this [dnsclient.net link](https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/www.facebook.com/A/UDP) where you will see the response for a recursive query. You will see the the Facebook's name servers are responding with the answer whereas in your case, the Verisign name servers are responding with answer which means that someone on your network path is spoofing all IP addresses for "gtld-servers.net" and then responding with "answers" that could be filtered or modified.

can i make a drop for that ??? 

now my dns give me that
![Desktop Screenshot 2020 07 08 - 11 57 57 69](https://user-images.githubusercontent.com/31727156/86899145-489c5b00-c112-11ea-8e71-76b5efb5bc98.png)

**Comment by ShreyasZare** [comment]
> 
> 
> > > > Ahh! It seems your ISP is hijacking your DNS requests and that's why "f.gtld-servers.net" is responding with an "answer" to the [www.facebook.com](http://www.facebook.com) query. Probably, the domain names are being blocked by your ISP.
> > > 
> > > 
> > > what i can do to fix the proplem , What is it supposed to give me when I use DNS Client ??
> > 
> > 
> > Check this [dnsclient.net link](https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/www.facebook.com/A/UDP) where you will see the response for a recursive query. You will see the the Facebook's name servers are responding with the answer whereas in your case, the Verisign name servers are responding with answer which means that someone on your network path is spoofing all IP addresses for "gtld-servers.net" and then responding with "answers" that could be filtered or modified.
> 
> can i make a drop for that ???
> 
> now my dns give me that

I am not sure what you are doing. If that was something you had configured?

**Comment by muhanadali100** [comment]
> 
> 
> > > > > Ahh! It seems your ISP is hijacking your DNS requests and that's why "f.gtld-servers.net" is responding with an "answer" to the [www.facebook.com](http://www.facebook.com) query. Probably, the domain names are being blocked by your ISP.
> > > > 
> > > > 
> > > > what i can do to fix the proplem , What is it supposed to give me when I use DNS Client ??
> > > 
> > > 
> > > Check this [dnsclient.net link](https://dnsclient.net/#Recursive%20Query%20(recursive-resolver)/www.facebook.com/A/UDP) where you will see the response for a recursive query. You will see the the Facebook's name servers are responding with the answer whereas in your case, the Verisign name servers are responding with answer which means that someone on your network path is spoofing all IP addresses for "gtld-servers.net" and then responding with "answers" that could be filtered or modified.
> > 
> > 
> > can i make a drop for that ???
> > now my dns give me that
> 
> I am not sure what you are doing. Is that something you had configured?

Iam configured the ISP Server it's Mikrotik 1036 if anything i can do for best result of dns please tell me

**Comment by ShreyasZare** [comment]
Thanks for the inputs. I think I have some ideas for improving the DNS server to handle thread pool exhaustion properly. Will try to address this in upcoming updates.

**Comment by muhanadali100** [comment]
Can you tell me what the Hardware i need for 100 users or more please ,

**Comment by ShreyasZare** [comment]
Its not possible to give hardware requirements for any kind of application. It totally depends on the total number of requests the users generate. Any estimation requires trial and error initially to understand load for your use case.

However, I am adding Async IO into the DNS code which should improve the performance such that the server will handle more traffic with less threads.

**Comment by muhanadali100** [comment]
I install another system but it's same proplem it's crash
![Desktop Screenshot 2020 08 13 - 19 59 44 65](https://user-images.githubusercontent.com/31727156/90164047-93f3fa00-dd9f-11ea-904e-fe7e7b64bd62.png)

![Desktop Screenshot 2020 08 13 - 20 00 46 30](https://user-images.githubusercontent.com/31727156/90164161-b5ed7c80-dd9f-11ea-802b-598d11665375.png)

**Comment by ShreyasZare** [comment]
Thanks for the details. I am already working on a fix for this and will soon start testing.

**Comment by ShreyasZare** [comment]
New version is now available which implements async IO to prevent the server from stalling. Do update and see if the issue was fixed.
