### ISSUE TITLE
Set Technitium DNS Server as my DNS cache

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#152]
How to configure Technitium DNS Server as my DNS cache? Can the support for EDNS be added at the same time?

**Comment by ShreyasZare** [comment]
Thanks for the post. Can you describe the scenario where you want it to be used as a DNS cache?

EDNS support is planned and will try to get it added in coming releases.

**Comment by thb007** [comment]
> Thanks for the post. Can you describe the scenario where you want it to be used as a DNS cache?
> 
> EDNS support is planned and will try to get it added in coming releases.

Forward DNS requests through Forwarders, and then Forwarders of Technitium DNS Server fill in the corresponding running ports of Forwarders, so that all traffic goes through the encrypted channel. Technitium DNS Server is here to cache and block advertisements

**Comment by ShreyasZare** [comment]
Yes you can chain multiple DNS servers or proxies using forwarders.

**Comment by ShreyasZare** [comment]
You just need to point Technitium DNS Server to your dnsproxy using the forwarder settings. Use UDP protocol as it will be much more efficient.

**Comment by thb007** [comment]
> You just need to point Technitium DNS Server to your dnsproxy using the forwarder settings. Use UDP protocol as it will be much more efficient.

Technitium DNS Server My recursive resolution here is too slow so I can only use third-party DNS resolution

**Comment by thb007** [comment]
> You just need to point Technitium DNS Server to your dnsproxy using the forwarder settings. Use UDP protocol as it will be much more efficient.

![1](https://user-images.githubusercontent.com/17548936/87307526-5dcb1c80-c54c-11ea-90bf-9a6a3433ce40.png)
![2](https://user-images.githubusercontent.com/17548936/87307538-61f73a00-c54c-11ea-824c-95e956070fa9.png)

**Comment by thb007** [comment]
bug？

![a](https://user-images.githubusercontent.com/17548936/87308107-4f313500-c54d-11ea-82ae-05c7e0f02e98.png)
![s](https://user-images.githubusercontent.com/17548936/87308124-535d5280-c54d-11ea-8f73-d566de432742.png)
![d](https://user-images.githubusercontent.com/17548936/87308131-55bfac80-c54d-11ea-971a-fa79386aad58.png)

**Comment by thb007** [comment]
The DNS forwarder writes 127.0.0.1:5300, but by selecting "This Server (this-server)", why can't it resolve?

**Comment by ShreyasZare** [comment]
> The DNS forwarder writes 127.0.0.1:5300, but by selecting "This Server (this-server)", why can't it resolve?

This is a bug that I have [fixed already](https://github.com/TechnitiumSoftware/DnsServer/commit/8e37a337ed4b89bb8c835fa4a1ddfc76b7a995e7) and will be available in next update.

This new update added the feature to specify local end point with a different port, the "This Server" part in the DNS Client was not taking the port and was using port 53 by default. For now, you need to enter the local end point address i.e. "127.0.0.1:5354" in the DNS Client to query "This Server".

**Comment by thb007** [comment]
> > The DNS forwarder writes 127.0.0.1:5300, but by selecting "This Server (this-server)", why can't it resolve?
> 
> This is a bug that I have [fixed already](https://github.com/TechnitiumSoftware/DnsServer/commit/8e37a337ed4b89bb8c835fa4a1ddfc76b7a995e7) and will be available in next update.
> 
> This new update added the feature to specify local end point with a different port, the "This Server" part in the DNS Client was not taking the port and was using port 53 by default. For now, you need to enter the local end point address i.e. "127.0.0.1:5354" in the DNS Client to query "This Server".

thanks
