### ISSUE TITLE
How to deal with non-existent domain names

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#154]
After I published the DNS address, someone else maliciously swiped the DNS cache, and sometimes found that these domain names are non-existent domain names. How should I solve this situation?

**Comment by ShreyasZare** [comment]
Thanks for the post. Please describe it in a bit details.

**Comment by thb007** [comment]
> Thanks for the post. Please describe it in a bit details.

For example, this non-existent domain name has been requesting resolution, how can I ignore them

ns.nmhhptt.net.cn
nmdns.hh.nm.cn
ns.hesjptt.net.cn
ns-backup.qhxnptt.net.cn
ns.nmhhptt.net.cn
ns.qhxnptt.net.cn
nmdns.hh.nm.cn
ns.hesjptt.net.cn
ns-backup.qhxnptt.net.cn
2cd732259df07d03d0b8095fd.mdbook.cn
ns1.gz.china169.cn
m2.xbdj.cn

**Comment by thb007** [comment]
![4Q`TWL8JW()03}F8K){2VCH](https://user-images.githubusercontent.com/17548936/87434614-460f9900-c61d-11ea-9d48-0a88b732212d.png)
There is no corresponding IP, how can I ignore them

**Comment by ShreyasZare** [comment]
I tried a couple of domain names and found that the name servers that are supposed to host them are not responding to queries. The DNS Server will keep an failure record in cache for a while and once it expires then it will again try to resolve the domain.

There is nothing that can be done about it other than blocking them manually.

**Comment by thb007** [comment]
> I tried a couple of domain names and found that the name servers that are supposed to host them are not responding to queries. The DNS Server will keep an failure record in cache for a while and once it expires then it will again try to resolve the domain.
> 
> There is nothing that can be done about it other than blocking them manually.

So, we can add a menu. No query is made for the domain name in this menu, and it can also prevent others from maliciously destroying the DNS cache

**Comment by ShreyasZare** [comment]
You can already block such domains using Blocked zones. Another thing is that, such queries do not affect DNS cache in any way.

**Comment by thb007** [comment]
> You can already block such domains using Blocked zones. Another thing is that, such queries do not affect DNS cache in any way.

ok
