### ISSUE TITLE
Static IP Lease Failure

### ISSUE THREAD

**Issue by TashingaE** [TechnitiumSoftware/DnsServer#155]
I manage my home Network dns from only a specific ip e.g. 192.168.1.100  and only allowed the firewall to allow port 5380  for dns web app management.....now after this update i have the correct configurations to only lease ip 192.168.1.100  to my device but the device is getting a dynamic ip everytime. please check  
My Device is Ubuntu 18.04

**Comment by ShreyasZare** [comment]
Thanks for the feedback. A fix will be available by this weekend.

**Comment by ShreyasZare** [comment]
Version 5.0.2 is now available which fixes the DHCP issue.

**Comment by TashingaE** [comment]
Thanks very much
