### ISSUE TITLE
Some little Problems?

### ISSUE THREAD

**Issue by big-sanchez** [TechnitiumSoftware/DnsServer#156]
Hello, 
i upgraded the version from 4 to 5.0.1.

1:
The performance of the Web frontend is great and the use of resources too.
I use the DNS-Server to amange my network at home.

2:
I usa a scope from 192.168.1.1 to 192.168.1.254.
In the Scope there are some adresses that fixed by the mac adresses and need the same ip adress everytime. 
This is needed why in my network are some devices that must have the same ip adress.
Now in version 5.0.1 the fixed ip adresses from the scope are not delivery to the clients. All clients become dynamicly adresses from the dynamic block 200-250 of the scope. 
Can you check this? 

3: 
I use some Blocklistst to block ad by the dns server. It is correct that they not listed in blocked zones? In version 4 they are listed in blocked zones.
My server talkt that it block 1.5 million domains but i can not show the domainnames ore can verify it. 

If you have an idear to fix this and if you need more infos let me know.

My system: Windows server 2016 Datacenter, 16gb Memory

kind regards

**Comment by ShreyasZare** [comment]
Thanks for the feedback.

> The performance of the Web frontend is great and the use of resources too.
> I use the DNS-Server to amange my network at home.

Great to know that!

> I usa a scope from 192.168.1.1 to 192.168.1.254.
> In the Scope there are some adresses that fixed by the mac adresses and need the same ip adress everytime.
> This is needed why in my network are some devices that must have the same ip adress.
> Now in version 5.0.1 the fixed ip adresses from the scope are not delivery to the clients. All clients become dynamicly adresses from the dynamic block 200-250 of the scope.
> Can you check this?

Yes, there is a bug that got added while fixing another issue. An update for this will be available mostly by tomorrow. Do check for update by tomorrow evening or max by Sunday.

> I use some Blocklistst to block ad by the dns server. It is correct that they not listed in blocked zones? In version 4 they are listed in blocked zones.
> My server talkt that it block 1.5 million domains but i can not show the domainnames ore can verify it.

Your observation is correct. Earlier, the blocked zone was being used to manage domains that you directly blocked and all the domains from block lists. This was creating issue of high memory usage and thus we now got blocked zone and an internal block list zone. The internal block list zone is not a browse able data structure so its not visible in the web panel. But, the block list zone will use extremely less memory compared to the previous versions such that 1.5 mn domain names would now take just 300-400 MB memory compared to 3+ GB memory.

**Comment by big-sanchez** [comment]
> The performance of the Web frontend is great and the use of resources too.
I use the DNS-Server to amange my network at home.

> Great to know that!

By the way, simultaneously i run the Web Frontend behind an nginx revers proxy with TLS 1.3 encryption. So i can manage my Network and make it accassable over the Internet. 

>  I usa a scope from 192.168.1.1 to 192.168.1.254.
    In the Scope there are some adresses that fixed by the mac adresses and need the same ip adress everytime.
    This is needed why in my network are some devices that must have the same ip adress.
    Now in version 5.0.1 the fixed ip adresses from the scope are not delivery to the clients. All clients become dynamicly adresses from the dynamic block 200-250 of the scope.
    Can you check this?

> Yes, there is a bug that got added while fixing another issue. An update for this will be available mostly by tomorrow. Do check for update by tomorrow evening or max by Sunday.

That's good news. You make great work. 

> I use some Blocklistst to block ad by the dns server. It is correct that they not listed in blocked zones? In version 4 they are listed in blocked zones.
My server talkt that it block 1.5 million domains but i can not show the domainnames ore can verify it.

> Your observation is correct. Earlier, the blocked zone was being used to manage domains that you directly blocked and all the domains from block lists. This was creating issue of high memory usage and thus we now got blocked zone and an internal block list zone. The internal block list zone is not a browse able data structure so its not visible in the web panel. But, the block list zone will use extremely less memory compared to the previous versions such that 1.5 mn domain names would now take just 300-400 MB memory compared to 3+ GB memory.

Good to Know. I had installed 16GB of memory to handle the dns on version 4. In this version the system used more than 9 GB of memory. Now the System use 4,3 GB of Memory. Thats very great. 

Kind regards.

**Comment by ShreyasZare** [comment]
Version 5.0.2 is now available which fixes the DHCP issue.
