### ISSUE TITLE
127.0.0.1:53: response: dial udp 127.0.0.1:53: socket: too many open files

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#158]
127.0.0.1:53: response: dial udp 127.0.0.1:53: socket: too many open files

**Comment by ShreyasZare** [comment]
There is a limit of max number of file handles that can be opened which is by default is too small and you will see this error. You need to increase this limit manually for any Linux server that you have. See this [link](https://easyengine.io/tutorials/linux/increase-open-files-limit/) to know how to increase the limit.

**Comment by thb007** [comment]
> There is a limit of max number of file handles that can be opened which is by default is too small and you will see this error. You need to increase this limit manually for any Linux server that you have. See this [link](https://easyengine.io/tutorials/linux/increase-open-files-limit/) to know how to increase the limit.

thanks
