### ISSUE TITLE
Add a privacy policy please

### ISSUE THREAD

**Issue by PEPERSO** [TechnitiumSoftware/DnsServer#159]
Hello,

At first, thanks for Technitium, it's amazingly simple and efficient !
But could you please add a privacy policy on your website and github ? Since a DNS server is critical to privacy, a Privacy policy would clarify some implicit things...

Thanks a lot :)

**Comment by ShreyasZare** [comment]
Thanks for the compliments! The DNS server is entirely self hosted so there is no data that is being transferred. There is just a check for update option that pings which would disclose the IP address of the DNS server. And Google Analytics running on the website. 

Will try to add a privacy policy describing these couple of things soon.

**Comment by ShreyasZare** [comment]
[Privacy policy](https://technitium.com/dns/privacypolicy.html) is now available on the website.
