### ISSUE TITLE
[Feature request] Improve all queries view, add it in the dashboard

### ISSUE THREAD

**Issue by PEPERSO** [TechnitiumSoftware/DnsServer#160]
Hello again :) 

I am using Technitium to check that my computer is not making unwanted connections. To do so, I often look in logs, after enabled all queries logging. But could you please add it to the dashboard, when all queries are logged ? I mean, not just the top hit and top blocked domains, but all of them, if all queries are logged ? This would make it easier to read than the logs

Thanks a lot for Technitium, it's (almost ;)) perfect !

**Comment by ShreyasZare** [comment]
Thanks for the compliments! Will plan something for this.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds Top 1000 list in the dashboard. Let me know if that is sufficient. Reopen issue if needed.

**Comment by PEPERSO** [comment]
Nice integration, thank you ! I think it will be perfect :)
