### ISSUE TITLE
Run as Service with no login on MacOS

### ISSUE THREAD

**Issue by rikyotei** [TechnitiumSoftware/DnsServer#162]
How I can run this DNS Server on MacOS as service, and it works even i don't need to login.

explain:
Just like a service installed on windows server, the service startup automatically after the hardware boot up, and doesn't require user login.

**Comment by ShreyasZare** [comment]
Thanks for the post. The issue is that I don't have a macOS for developing and testing a service for it. And I have not found anyone who has macOS and is willing to do this for the project.

**Comment by rikyotei** [comment]
thank you for your reply, I'm going to find another way, maybe clone your code and deploy to docker?

**Comment by ShreyasZare** [comment]
> 
> 
> thank you for your reply, I'm going to find another way, maybe clone your code and deploy to docker?

There is one unofficial docker available on [GitHub](https://github.com/hm400/docker) that you can try out.
