### ISSUE TITLE
Any idea for my proplem

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#164]
My DNS is always Crash , if i need the dns works just with facebook and youtube , and another domain work without dns server ??
I have in Mikrotik Server , any ideia to make this real ??

Facebook >> DNS Server >> Main ISP (With DNS)
Netflix >> Main ISP (Without DNS)

**Comment by ShreyasZare** [comment]
You can have such a setup by configuring another DNS server software with conditional forwarders set.

**Comment by ShreyasZare** [comment]
New version is now available. Do try that and let me know if the issue still persists.
