### ISSUE TITLE
v5.1 only Resolves local zones over IPv6

### ISSUE THREAD

**Issue by ryakel** [TechnitiumSoftware/DnsServer#165]
On Linux (CentOS 7 and Ubuntu 18.04), the current 5.2 version only appears to resolve local zones over IPv6, despite allowing recursion on all zones. On the Ubuntu host with IPv6 enabled, I get the following:
```
nslookup domain.int
;; Got recursion not available from 127.0.0.1, trying next server
Server:		::1
Address:	::1#53

Name:	domain.int
Address: 192.168.15.3
;; Got recursion not available from 127.0.0.1, trying next server
```

If I remove the IPv6 listener from the UI and restart the dns service, resolution for internal zones fail.

For the CentOS 7 host, local zone resolution fails entirely with IPv6 disabled in the network interface configuration file.

I had no issues utilizing the exact same config on these hosts using 5.0.2.

In the interim, is it possible for you to provide me with a link to the 5.0.2 Portable tarball to get my DNS servers working again?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I tried this on Ubuntu 20.04 and could not reproduce this issue. 

Please post output of `sudo netstat -nlptu` and `cat /etc/resolv.conf` here so that I can get some details. Also, let me know the "DNS Server Local End Points" that you have in the DNS server settings.

Here is the download link for the previous version: [https://download.technitium.com/dns/DnsServerPortable_v5.0.2.tar.gz](https://download.technitium.com/dns/DnsServerPortable_v5.0.2.tar.gz)

**Comment by ryakel** [comment]
Thanks! Here are the outputs you've requested. 

```
# sudo netstat -nlptu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1226/nginx: master
tcp        0      0 0.0.0.0:5380            0.0.0.0:*               LISTEN      930/dotnet
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1226/nginx: master
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      930/dotnet
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1197/sshd
tcp6       0      0 :::53                   :::*                    LISTEN      930/dotnet
tcp6       0      0 :::22                   :::*                    LISTEN      1197/sshd
udp        0      0 0.0.0.0:53              0.0.0.0:*                           930/dotnet
udp6       0      0 :::53                   :::*                                930/dotnet
```
```
# cat /etc/hosts
127.0.0.1 localhost
127.0.1.1 ns1

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by ShreyasZare** [comment]
Thanks for the details. Do send output for `cat /etc/resolv.conf` too.

**Comment by Chewie9999** [comment]
I seem to be having this same problem on Technitium DNS v6, even though I have "Allow Recursion" enabled, resolving non-local domains  only seems to work on IPv4.
For example:

- On nslookup under CentOS, i get `** server can't find www.google.com: NXDOMAIN`.
- nslookup under OpenSuSE Tumbleweed 20210307: `** server can't find www.google.com: REFUSED`.
- yum on CentOS 7.9: `;; Got recursion not available from <TECHNITIUM IPv6 ADDRESS>, trying next server.`.
- dig on CentOS 7.9, i get `;; WARNING: recursion requested but not available`.

When using the IPv4 address for the same server, it works fine.
Resolving local zones via the Technitium IPv6 address works fine.
(Today is the first time I have really used IPv6 with Technitium, so cannot comment on previous versions)

**Comment by ShreyasZare** [comment]
Thanks for the post. Since you have a public IPv6 address, you need to uncheck the "Allow Recursion Only For Private Networks" option in the settings to allow recursion from public networks. This option is by default enabled to avoid having recursion enabled accidentally on the Internet.

**Comment by Chewie9999** [comment]
Sorry Shreyas, Yes, that exactly fixed my problem.
