### ISSUE TITLE
Request to add edns support

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#166]
Request to add edns support

**Comment by thb007** [comment]
There is also the addition of domain name designation DNS resolution functions, such as specifying the domain name "google.com domain name uses dns.google for resolution", "youtuebe.com domain name uses 1.1.1.1 for resolution", of course, it is better to import the domain name list.

The format can refer to:
[/google.com/]dns.google
[/youtube.com/]1.1.1.1
[/domain.example/]1.1.1.1
[/google.com/youtube.com/baidu.com/domain.example/]9.9.9.9

**Comment by ShreyasZare** [comment]
> 
> 
> There is also the addition of domain name designation DNS resolution functions, such as specifying the domain name "google.com domain name uses dns.google for resolution", "youtuebe.com domain name uses 1.1.1.1 for resolution", of course, it is better to import the domain name list.
> 
> The format can refer to:
> [/google.com/]dns.google
> [/youtube.com/]1.1.1.1
> [/domain.example/]1.1.1.1
> [/google.com/youtube.com/baidu.com/domain.example/]9.9.9.9

Are you referring to something like conditional forwarders? There is already conditional forwarder zone where you can create forwarder zone for "google.com" and then forward all requests for it to 8.8.8.8.

**Comment by thb007** [comment]
> > There is also the addition of domain name designation DNS resolution functions, such as specifying the domain name "google.com domain name uses dns.google for resolution", "youtuebe.com domain name uses 1.1.1.1 for resolution", of course, it is better to import the domain name list.
> > The format can refer to:
> > [/google.com/]dns.google
> > [/youtube.com/]1.1.1.1
> > [/domain.example/]1.1.1.1
> > [/google.com/youtube.com/baidu.com/domain.example/]9.9.9.9
> 
> Are you referring to something like conditional forwarders? There is already conditional forwarder zone where you can create forwarder zone for "google.com" and then forward all requests for it to 8.8.8.8.

![GTWH7 XT{1)R0~~0DSU80YM](https://user-images.githubusercontent.com/17548936/91724027-3e0cb800-ebcf-11ea-8e11-f323b430db93.png)
It doesn’t seem to support importing list files, it’s too much to fill in one by one

**Comment by ShreyasZare** [comment]
> It doesn’t seem to support importing list files, it’s too much to fill in one by one

Yes, its ok to use if you have a few 10s of domain names. Wont be practical if you have too many of them to add. You can do a bit of scripting using curl with the DNS server API calls to do that though.

**Comment by thb007** [comment]
> > It doesn’t seem to support importing list files, it’s too much to fill in one by one
> 
> Yes, its ok to use if you have a few 10s of domain names. Wont be practical if you have too many of them to add. You can do a bit of scripting using curl with the DNS server API calls to do that though.

I need to add about thousands of domain names, because our country has carried out DNS pollution on these domain names. Can you help me achieve it? I don't know.

**Comment by ShreyasZare** [comment]
> I need to add about thousands of domain names, because our country has carried out DNS pollution on these domain names. Can you help me achieve it? I don't know.

Will try to create a script and let you know in a few days.

**Comment by thb007** [comment]
> > I need to add about thousands of domain names, because our country has carried out DNS pollution on these domain names. Can you help me achieve it? I don't know.
> 
> Will try to create a script and let you know in a few days.


thank you very much

**Comment by ShreyasZare** [comment]
Just added [API documentation](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) to help with writing script to automate tasks.

**Comment by thb007** [comment]
> Just added [API documentation](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) to help with writing script to automate tasks.

Thank you, is there any plan to increase edns support?

**Comment by ShreyasZare** [comment]
> 
> 
> > Just added [API documentation](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) to help with writing script to automate tasks.
> 
> Thank you, is there any plan to increase edns support?

EDNS is planned and will get implemented soon.

**Comment by thb007** [comment]
> > > Just added [API documentation](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) to help with writing script to automate tasks.
> > 
> > 
> > Thank you, is there any plan to increase edns support?
> 
> EDNS is planned and will get implemented soon.

Very good, my private dns are currently edns, dnssec have been done, next will use your project to forward DNS, I don’t know how much QPS your project has.

**Comment by ShreyasZare** [comment]
> Very good, my private dns are currently edns, dnssec have been done, next will use your project to forward DNS, I don’t know how much QPS your project has.

I have load tested the DNS server on i7 8700 CPU and could get around 100,000 QPS.

**Comment by thb007** [comment]
> > Very good, my private dns are currently edns, dnssec have been done, next will use your project to forward DNS, I don’t know how much QPS your project has.
> 
> I have load tested the DNS server on i7 8700 CPU and could get around 100,000 QPS.

Beautiful

**Comment by thb007** [comment]
@ShreyasZare Hello developer! What is the current schedule of EDNS and DNSSEC? How long will it take to complete?

**Comment by ShreyasZare** [comment]
There is no specific timeline for both of them since it totally depends on how much time I can manage for the development.

Still, EDNS wont take much time to implement but, DNSSEC will take longer to implement.

**Comment by thb007** [comment]
> There is no specific timeline for both of them since it totally depends on how much time I can manage for the development.
> 
> Still, EDNS wont take much time to implement but, DNSSEC will take longer to implement.

Brothers worked hard, but I'm not good programming

**Comment by thb007** [comment]
> There is no specific timeline for both of them since it totally depends on how much time I can manage for the development.
> 
> Still, EDNS wont take much time to implement but, DNSSEC will take longer to implement.

If dnssec takes too long, you can prioritize edns.

**Comment by tango38317** [comment]
Hi @ShreyasZare ,
any update regarding EDNS implementation?
br
Chris

**Comment by ShreyasZare** [comment]
> Hi @ShreyasZare , any update regarding EDNS implementation? br Chris

EDNS is implemented in `develop` branch and work for DNSSEC is in progress. Next update will have both EDNS and DNSSEC validation support.

**Comment by tango38317** [comment]
Hi,
maybe also a release date?
br

**Comment by ShreyasZare** [comment]
> Hi, maybe also a release date? br

Most probably in next month.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which adds support for EDNS. Do check and let me know your feedback.
