### ISSUE TITLE
listen on specified IP

### ISSUE THREAD

**Issue by rikyotei** [TechnitiumSoftware/DnsServer#17]
Hi, Is there any way that i can set the server listen on specified IPs?

**Comment by ShreyasZare** [comment]
Thanks for the query. Right now there is no config option to do so. You can use a firewall config to allow only specific IP access for now.

**Comment by ShreyasZare** [comment]
Advance options like these are planned later once core features are done. So this issue can be kept open.

**Comment by ShreyasZare** [comment]
This feature is now available with release of DNS Server v2.2.
