### ISSUE TITLE
Node class missing?

### ISSUE THREAD

**Issue by paulfryer** [TechnitiumSoftware/DnsServer#170]
I can't compile the DnsServerCore project because there is a reference to a "Node" class that is missing.

**Comment by paulfryer** [comment]
I found it, it was in the TechnitiumLibrary.ByteTree assembly.

**Comment by ShreyasZare** [comment]
You figured it out correctly. You need to clone TechnitiumLibarary repo in the same folder you have the DnsServer repo cloned. Just compile the TechnitiumLibrary solution once in Release mode and then all the references used in the DnsServer project will resolve and the project would compile.
