### ISSUE TITLE
any feature to redirect youtube to another domain

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#173]
any feature to redirect youtube.com to another domain that's we can cache like
youtube.com >>>> youtube.my.com

**Comment by ShreyasZare** [comment]
That is not technically possible due to websites using HTTPS.

**Comment by muhanadali100** [comment]
> 
> 
> That is not technically possible due to websites using HTTPS.

the thunderCache 7.3 using this feature But it paid
it's redirect youtube.com to youtube.https.co

**Comment by ShreyasZare** [comment]
> 
> 
> > That is not technically possible due to websites using HTTPS.
> 
> the thunderCache 7.3 using this feature But it paid
> it's redirect youtube.com to youtube.https.co

This is looks like a peering solution which a lot of CDN networks provide to ISPs. Google, Facebook etc too have their own peering solutions available. This software seems to install these solutions though I am not entirely sure how it would work.

Any solution that claims to work without installing root certificate on user's computer should be taken as suspicious. And any solution that wants you to install a root certificate must be taken as a threat.

**Comment by muhanadali100** [comment]
> 
> 
> > > That is not technically possible due to websites using HTTPS.
> > 
> > 
> > the thunderCache 7.3 using this feature But it paid
> > it's redirect youtube.com to youtube.https.co
> 
> This is looks like a peering solution which a lot of CDN networks provide to ISPs. Google, Facebook etc too have their own peering solutions available. This software seems to install these solutions though I am not entirely sure how it would work.
> 
> Any solution that claims to work without installing root certificate on user's computer should be taken as suspicious. And any solution that wants you to install a root certificate must be taken as a threat.

it's working with comdo certificate so it's found in user's computer without install but how to do this i don't know

**Comment by ShreyasZare** [comment]
From the video on their website, it looks that the HTTPS redirection works only when you have their chrome extension installed. That "youtube.https.co" is their own domain in which they are proxying youtube.com content.

**Comment by muhanadali100** [comment]
> 
> 
> From the video on their website, it looks that the HTTPS redirection works only when you have their chrome extension installed. That "youtube.https.co" is their own domain in which they are proxying youtube.com content.

https://www.bmsoftware.org/ 

this cache is good but the price of the license it's high 

You are good at programming. Why not design a similar system like him at lower prices?

**Comment by ShreyasZare** [comment]
> https://www.bmsoftware.org/
> 
> this cache is good but the price of the license it's high
> 
> You are good at programming. Why not design a similar system like him at lower prices?

Such a solution is only useful for ISPs and doesn't make sense for end users. And, ISPs already have better options like to setup actual peering with [Google](https://peering.google.com/#/) or other [CDN providers](https://www.akamai.com/us/en/products/network-operator/akamai-network-partnerships.jsp) wherein you don't have to compromise on security or privacy of the customers.
