### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by js001** [TechnitiumSoftware/DnsServer#174]
delete

**Comment by ShreyasZare** [comment]
Yes, you can create reverse zone by just entering the network address in CIDR format while creating the zone.

**Comment by js001** [comment]
how to set up reverse dns zone, ptr record?

**Comment by ShreyasZare** [comment]
Do you have static IP addresses assigned from your ISP?

For setting up PTR record for public IP, you need to contact your ISP who provided you with the static IP addresses. Your ISP needs to delegate the reverse zone to your DNS servers and then only you can host the reverse zone on your DNS server.

For your local network, you can setup reverse zone on your own. Lets say your local network address is "192.168.0.0/24" then just create a primary zone with that network address. Then add PTR record for each IP address manually e.g. for 192.168.0.1, create a PTR with "1" and the name and the domain name of your choice.

**Comment by js001** [comment]
is dynamic ip can use?

**Comment by ShreyasZare** [comment]
> 
> 
> is dynamic ip can use?

If you dont own the IP address then creating a zone for it will only resolve from your local network. It wont resolve from the internet.
