### ISSUE TITLE
Using the provided forwarders, DoT doesn't work and DoH only works with Cloudflare

### ISSUE THREAD

**Issue by ICTAddict** [TechnitiumSoftware/DnsServer#175]
I get these errors when I try to use DNS over HTTPS or DNS over TLS with DNS forwarders (Cloudflare, Google, Quad9)
I tried Adguard and it works with both.

DNS over TLS (Cloudflare, Google, Quad9)
Error! A call to SSPI failed, see inner exception. The function requested is not supported
    Adguard: works

    "NameServer": "dns.adguard.com:853 (176.103.130.130:853)",
    "Protocol": "Tls"

DNS over HTTPS (Cloudflare, AdGuard) working

    Cloudflare:
    "NameServer": "https://cloudflare-dns.com/dns-query (104.16.248.249:443)",
    "Protocol": "Https",

    Adguard:
    "NameServer": "https://dns.adguard.com/dns-query (176.103.130.130:443)",
    "Protocol": "Https",

(Quad 9)
Error! An error occurred while sending the request. The underlying connection was closed: An unexpected error occurred on a send.
(Google)
Error! An error occurred while sending the request. The request was aborted: Could not create SSL/TLS secure channel.

**Comment by ShreyasZare** [comment]
Which OS are you running the DNS server on?

**Comment by ICTAddict** [comment]
Windows 7 64-bit

**Comment by ShreyasZare** [comment]
This is because the DNS-over-TLS services are using higher version of TLS protocol while Windows 7 it is supporting older version. 

Do upgrade to latest version of Windows since Windows 7 is not supported anymore.

**Comment by muhanadali100** [comment]
+1 
the forwarders doesn't work in last version, i using ubuntu 18.04

**Comment by Globulopolis** [comment]
> 
> 
> Windows 7 64-bit
> Technitium DNS Server Version 5.2

Very strange. I'm using DOT with
cloudflare-dns.com (1.1.1.1:853)
cloudflare-dns.com (1.0.0.1:853)
dns10.quad9.net (9.9.9.10:853)
on windows 7 64bit and latest Technitium DNS resolve hosts without errors.

But Google DOT thrown an error with SSPI exception.

Try to enable TLS 1.2 on your server, reboot and try resolve hosts via CF or Q9 DOT.

**Comment by ShreyasZare** [comment]
@ICTAddict Do try to upgrade TLS 1.2 support on Window 7 as @Globulopolis said using fix given in [here](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi) by Microsoft.

**Comment by ShreyasZare** [comment]
> 
> 
> +1
> the forwarders doesn't work in last version, i using ubuntu 18.04

I just tested on Ubuntu 18.04 LTS with all updates and both DoT and DoH are working well for Cloudflare, Google and Quad9.

**Comment by ICTAddict** [comment]
I followed Microsoft's guide. Google's DNS servers still show the same errors as before, but Cloudflare and Quad9 are now working fine with DoT and DoH.
Thanks!
