### ISSUE TITLE
DHCP Server has no import/export functionality

### ISSUE THREAD

**Issue by gtmadev** [TechnitiumSoftware/DnsServer#178]
After just learning that all my scopes are not going to work (and entering in about 40 different mac addresses, ip addresses, hosts, I see that I cannot export these records or import them into a main scope.

I looked at the scope files, but they are binary. So also these are not useful for import/export. Ugh....

This seems like something that is really needed for this thing to be useful. It's going to take forever now for me to re-type in all those reservations.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will try to add some bulk import/update options to help in such scenarios.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds backup/restore feature.
