### ISSUE TITLE
[Feature request] Add support for DNAME record

### ISSUE THREAD

**Issue by fakhrulhilal** [TechnitiumSoftware/DnsServer#179]
It would be nice if there's support for [DNAME](https://en.wikipedia.org/wiki/CNAME_record#DNAME_record). It's like ANAME but works for the entire tree. Suppose we have registered this zone:
```
company-website.com
www.company-website.com IN A 1.2.3.4
mail.company-website.com IN A 2.3.4
@ MX 10 mail.company-website.com
```
Then we can create domain alias (let's say cw.local) which's an alias for actual domain. The benefit is having alias domain but maintaining single zone only.

**Comment by ShreyasZare** [comment]
Thanks for the feature request.

**Comment by jaydouble** [comment]
Hi,

I need this, any progress in this feature request?

**Comment by ShreyasZare** [comment]
> 
> 
> Hi,
> 
> I need this, any progress in this feature request?

Will try to get it added in next update.

**Comment by ShreyasZare** [comment]
New update v6.4 is now available which adds DNAME support.
