### ISSUE TITLE
[Bug ?] Domain randomly blocked

### ISSUE THREAD

**Issue by PEPERSO** [TechnitiumSoftware/DnsServer#181]
Hello !

I've used technitium dns server for a while and it was perfect for me, except for this : 

- the domain [mail.lilo.org](mail.lilo.org) is often blocked (IP adress returned is 0.0.0.0)
- the domain [mail.lilo.org](mail.lilo.org) is in my allowed zones
- the domain [mail.lilo.org](mail.lilo.org) isn't in any of my blocklists
- the only workaround I have found is to delete the cached zone (with IP 0.0.0.0) and reload the page several times, sometimes delete the allowed zone and then re-allow it...

Any way to handle this ?
Thanks for your project and your time anyway :)

**Comment by ShreyasZare** [comment]
Hi, thanks for the feedback.

The thing that you had to delete the cached zone for the domain to fix it, means that the forwarder (upstream DNS server) that you are using is probably returning this record with 0.0.0.0 IP address.

Try this on test. When you see that the domain resolving to 0,0,0,0, just use the DNS Client tool and try querying the forwarder that you have configured and check the response. Also, try DNS Client with "Recursive Query" as server and see what the authoritative name server for the domain returns.

Let me know what you see in those tests.

**Comment by PEPERSO** [comment]
Thanks for your quick answer !
I had two dns resolvers, the first returned (with DNS Client tool) 0.0.0.0 and the second one an ip adress. So I chose to only keep the second one (libre-dns) with recursion enabled.
I logged out and back in, and no problem anymore, thanks !
