### ISSUE TITLE
[Feature request] In logs page, only scroll on the file, not the whole page

### ISSUE THREAD

**Issue by PEPERSO** [TechnitiumSoftware/DnsServer#182]
Currently, when scrolling down on the log page, when you've found what you wanted at the end you have to go back at the top of the page, it's not really user friendly (IMO).
Could it be possible to anly put the scroll bar inside the file preview, so that scrolling down in the logs does not impose you to go back to top (since the whole page isn't scrolled, only logs), I don't know if I make myself clear ?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Ya, the log viewer is really not easy to use. Will try to add scrolling to make it a bit better. There are a few more UI options requires in there which I will add as I get some time.

**Comment by ShreyasZare** [comment]
I tried fixing this but it will require a lot of UI redesign to make this work so dropping this. Next update is planned to have db logging support which should make the query logs searchable so will fix this issue of long log file display.

**Comment by PEPERSO** [comment]
Alright, no worries, it's perfect if the logs are searchable
