### ISSUE TITLE
Please add support for additional DHCP options

### ISSUE THREAD

**Issue by lfarrand** [TechnitiumSoftware/DnsServer#183]
First of all I'd like to extend my thanks for all of your hard work building such a feature rich DNS / DHCP server. You've done a great job and it really is a fantastic piece of software.

I would like to configure the DHCP server to broadcast some additional options as part of the DHCP offer message. These options are required for network booting a Raspberry Pi for example.

Name|Option Code|Example value
------------ | ------------- | -------------
Vendor encapsulated|43|Raspberry Pi Boot
Vendor class id|60|PXEClient
TFTP server name|66|192.168.100.2
Boot file name|67|bootcode.bin

It would be nice to have a drop down listing all of the available options as defined in https://tools.ietf.org/html/rfc2132. Failing that, then two text boxes allowing the user to input the option code and value would be sufficient.

Do you allow pull requests in this project? I'm a developer and have been working with .Net for over 15 years, so I'd be happy to contribute to your project.

Thanks,

Lee

**Comment by ShreyasZare** [comment]
Thanks for the compliments and request. Will try to make these available in coming update.

My initial plan was to add DHCP options as and when there is a requirement since a lot of options are not commonly used and adding all of them will take a lot of time to implement.

For PR, there is no policy for now. If the PR is helpful then I would definitely accept it. However, contributing code without any collaboration is quite difficult to align as per the future goals.

**Comment by lfarrand** [comment]
I've forked your repo and added the DHCP options that I discussed in my first post. It all appears to be working very well indeed, and my Raspberry Pi 4B is booting successfully via TFTP.

I've attached the files that I modified just in case they are of any use to you.

[Technitium DHCP options.zip](https://github.com/TechnitiumSoftware/DnsServer/files/5438764/Technitium.DHCP.options.zip)

**Comment by ShreyasZare** [comment]
Thanks for the code. I had already pushed the changes for them on the weekend and already tested to work with PXE booting.

![image](https://user-images.githubusercontent.com/10008172/97175319-56f1ae00-17b9-11eb-993e-6f05ffc4dc96.png)

Will release an update in a couple of weeks.

**Comment by lfarrand** [comment]
Very nice! Thanks for the quick turnaround. I couldn't see it in your screenshot, but have you also implemented 'Vendor encapsulated' (option 43) and 'Vendor class id' (option 60)?

**Comment by ShreyasZare** [comment]
> Very nice! Thanks for the quick turnaround. I couldn't see it in your screenshot, but have you also implemented 'Vendor encapsulated' (option 43) and 'Vendor class id' (option 60)?

Both the options are optional. Vendor class ID option (60) is sent by the client to the server and server is supposed to respond with vendor-specific info option (43) if the server identifies the vendor class id and has some vendor specific settings to return. 

PXE boot will work without these options unless there is a special requirement in raspberry pi for these options to be present to boot.

**Comment by lfarrand** [comment]
Options 43 & 60 are required for network booting the Raspberry Pi. It's not a PXE boot at all which is confusing, but it appears that the Raspberry Pi hijacks some of the PXE options to boot over the network. There's more info here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net.md

Here is the DHCP exchange between a Raspberry Pi 4B and dnsmasq that I captured using Wireshark:

Frame 438600: 364 bytes on wire (2912 bits), 364 bytes captured (2912 bits) on interface \Device\NPF_{9DFCEF29-48FE-4453-A855-F3778CA558ED}, id 0
Ethernet II, Src: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
Internet Protocol Version 4, Src: 0.0.0.0, Dst: 255.255.255.255
User Datagram Protocol, Src Port: 68, Dst Port: 67
Dynamic Host Configuration Protocol (Discover)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0xd383a6ac
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Discover)
        Length: 1
        DHCP: Discover (1)
    Option: (55) Parameter Request List
        Length: 14
        Parameter Request List Item: (1) Subnet Mask
        Parameter Request List Item: (3) Router
        Parameter Request List Item: (43) Vendor-Specific Information
        Parameter Request List Item: (60) Vendor class identifier
        Parameter Request List Item: (66) TFTP Server Name
        Parameter Request List Item: (67) Bootfile name
        Parameter Request List Item: (128) DOCSIS full security server IP [TODO]
        Parameter Request List Item: (129) PXE - undefined (vendor specific)
        Parameter Request List Item: (130) PXE - undefined (vendor specific)
        Parameter Request List Item: (131) PXE - undefined (vendor specific)
        Parameter Request List Item: (132) PXE - undefined (vendor specific)
        Parameter Request List Item: (133) PXE - undefined (vendor specific)
        Parameter Request List Item: (134) PXE - undefined (vendor specific)
        Parameter Request List Item: (135) PXE - undefined (vendor specific)
    Option: (60) Vendor class identifier
        Length: 32
        Vendor class identifier: PXEClient:Arch:00000:UNDI:002001
    Option: (93) Client System Architecture
        Length: 2
        Client System Architecture: IA x86 PC (0)
    Option: (94) Client Network Device Interface
        Length: 3
        Major Version: 2
        Minor Version: 1
    Option: (97) UUID/GUID-based Client Identifier
        Length: 17
        Client Identifier (UUID): 34695052-3114-00d0-32c2-1ffeb1cddbe2
    Option: (255) End
        Option End: 255




Frame 438601: 392 bytes on wire (3136 bits), 392 bytes captured (3136 bits) on interface \Device\NPF_{9DFCEF29-48FE-4453-A855-F3778CA558ED}, id 0
Ethernet II, Src: 72:b2:f8:5c:f0:ab (72:b2:f8:5c:f0:ab), Dst: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe)
Internet Protocol Version 4, Src: 192.168.100.2, Dst: 192.168.100.107
User Datagram Protocol, Src Port: 67, Dst Port: 68
Dynamic Host Configuration Protocol (Offer)
    Message type: Boot Reply (2)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0xd383a6ac
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
    Client IP address: 0.0.0.0
    Your (client) IP address: 192.168.100.107
    Next server IP address: 192.168.100.2
    Relay agent IP address: 0.0.0.0
    Client MAC address: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Offer)
        Length: 1
        DHCP: Offer (2)
    Option: (54) DHCP Server Identifier (192.168.100.2)
        Length: 4
        DHCP Server Identifier: 192.168.100.2
    Option: (51) IP Address Lease Time
        Length: 4
        IP Address Lease Time: (86400s) 1 day
    Option: (58) Renewal Time Value
        Length: 4
        Renewal Time Value: (43200s) 12 hours
    Option: (59) Rebinding Time Value
        Length: 4
        Rebinding Time Value: (75600s) 21 hours
    Option: (1) Subnet Mask (255.255.255.0)
        Length: 4
        Subnet Mask: 255.255.255.0
    Option: (28) Broadcast Address (192.168.100.255)
        Length: 4
        Broadcast Address: 192.168.100.255
    Option: (3) Router
        Length: 4
        Router: 192.168.100.1
    Option: (60) Vendor class identifier
        Length: 9
        Vendor class identifier: PXEClient
    Option: (97) UUID/GUID-based Client Identifier
        Length: 17
        Client Identifier (UUID): 34695052-3114-00d0-32c2-1ffeb1cddbe2
    Option: (43) Vendor-Specific Information (PXEClient)
        Length: 32
        Option 43 Suboption: (6) PXE discovery control
            Length: 1
            discovery control: 0x03, Disable Broadcast, Disable Multicast
                .... ...1 = Disable Broadcast: Set
                .... ..1. = Disable Multicast: Set
                .... .0.. = Serverlist only: Not set
                .... 0... = Bootstrap override: Not set
        Option 43 Suboption: (10) PXE menu prompt
            Length: 4
            menu prompt: 00505845
                Timeout: 0
                Prompt: PXE
        Option 43 Suboption: (9) PXE boot menu
            Length: 20
            boot menu: 00001152617370626572727920506920426f6f74
                Type: Local boot (0)
                Length: 17
                Description: Raspberry Pi Boot
        PXE Client End: 255
    Option: (255) End
        Option End: 255




Frame 438602: 351 bytes on wire (2808 bits), 351 bytes captured (2808 bits) on interface \Device\NPF_{9DFCEF29-48FE-4453-A855-F3778CA558ED}, id 0
Ethernet II, Src: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
Internet Protocol Version 4, Src: 0.0.0.0, Dst: 255.255.255.255
User Datagram Protocol, Src Port: 68, Dst Port: 67
Dynamic Host Configuration Protocol (Request)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0xd383a6ac
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 192.168.100.2
    Relay agent IP address: 0.0.0.0
    Client MAC address: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Request)
        Length: 1
        DHCP: Request (3)
    Option: (50) Requested IP Address (192.168.100.107)
        Length: 4
        Requested IP Address: 192.168.100.107
    Option: (54) DHCP Server Identifier (192.168.100.2)
        Length: 4
        DHCP Server Identifier: 192.168.100.2
    Option: (60) Vendor class identifier
        Length: 32
        Vendor class identifier: PXEClient:Arch:00000:UNDI:002001
    Option: (97) UUID/GUID-based Client Identifier
        Length: 17
        Client Identifier (UUID): 34695052-3114-00d0-32c2-1ffeb1cddbe2
    Option: (255) End
        Option End: 255




Frame 438607: 342 bytes on wire (2736 bits), 342 bytes captured (2736 bits) on interface \Device\NPF_{9DFCEF29-48FE-4453-A855-F3778CA558ED}, id 0
Ethernet II, Src: 72:b2:f8:5c:f0:ab (72:b2:f8:5c:f0:ab), Dst: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe)
Internet Protocol Version 4, Src: 192.168.100.2, Dst: 192.168.100.107
User Datagram Protocol, Src Port: 67, Dst Port: 68
Dynamic Host Configuration Protocol (ACK)
    Message type: Boot Reply (2)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0xd383a6ac
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
    Client IP address: 0.0.0.0
    Your (client) IP address: 192.168.100.107
    Next server IP address: 192.168.100.2
    Relay agent IP address: 0.0.0.0
    Client MAC address: Raspberr_c2:1f:fe (dc:a6:32:c2:1f:fe)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (ACK)
        Length: 1
        DHCP: ACK (5)
    Option: (54) DHCP Server Identifier (192.168.100.2)
        Length: 4
        DHCP Server Identifier: 192.168.100.2
    Option: (51) IP Address Lease Time
        Length: 4
        IP Address Lease Time: (86400s) 1 day
    Option: (58) Renewal Time Value
        Length: 4
        Renewal Time Value: (43200s) 12 hours
    Option: (59) Rebinding Time Value
        Length: 4
        Rebinding Time Value: (75600s) 21 hours
    Option: (1) Subnet Mask (255.255.255.0)
        Length: 4
        Subnet Mask: 255.255.255.0
    Option: (28) Broadcast Address (192.168.100.255)
        Length: 4
        Broadcast Address: 192.168.100.255
    Option: (3) Router
        Length: 4
        Router: 192.168.100.1
    Option: (6) Domain Name Server
        Length: 12
        Domain Name Server: 192.168.12.2
        Domain Name Server: 192.168.12.3
        Domain Name Server: 192.168.12.4
    Option: (255) End
        Option End: 255

**Comment by ShreyasZare** [comment]
Thanks for the details. Will try to get it implemented.

**Comment by ShreyasZare** [comment]
@lfarrand I have updated the code. It would be best if you can this update first with your Pi setup before its released officially. Attaching the code that should work with Linux. Just overwrite an existing installation with the zip file contents and restart the dns server.

I have added the Pi PXE config in the HTML itself as example that you can try out to see if its working.

[DnsServer.zip](https://github.com/TechnitiumSoftware/DnsServer/files/5504504/DnsServer.zip)

Let me know if it worked or if any changes are required.

**Comment by lfarrand** [comment]
> 
> 
> @lfarrand I have updated the code. It would be best if you can this update first with your Pi setup before its released officially. Attaching the code that should work with Linux. Just overwrite an existing installation with the zip file contents and restart the dns server.
> 
> I have added the Pi PXE config in the HTML itself as example that you can try out to see if its working.
> 
> [DnsServer.zip](https://github.com/TechnitiumSoftware/DnsServer/files/5504504/DnsServer.zip)
> 
> Let me know if it worked or if any changes are required.

Excellent! Thanks for turning this round so quickly.

I've tested this version and I can confirm that it is working very well and I am able to network boot my Raspberry Pi 4.

The values I used were:

DHCP Option|Value
------------ | -------------
Vendor Class Identifier|substring(vendor-class-identifier,0,9)=="PXEClient"
Vendor Specific Information|06:01:03:0A:04:00:50:58:45:09:14:00:00:11:52:61:73:70:62:65:72:72:79:20:50:69:20:42:6F:6F:74

**Comment by ShreyasZare** [comment]
Thanks for confirming. The next release should be available by the next weekend.

**Comment by ShreyasZare** [comment]
Version 5.5 released which fixes this issue.
