### ISSUE TITLE
Feature request: Add option to force re-caching blocklists

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#188]
In 5.4 the only way I can find to force re-caching blocklists is to modify the current blocklists (settings, block list URLs), save changes, revert the change to the block list URLs, then save again. This is a significant time sink for something that is necessary when troubleshooting a blocklist. This has been the only functional process since 5.x was released (per #150 ).

Please add a button in the Settings/Block List URLs block to trigger re-caching the URLs.

If you're modifying that block, it would be great if the interface could indicate when blocklists were last cached, too, and when they will be automatically triggered to re-cache in the future. Adding the interval timeout from #73 would be great for this issue, too.

**Comment by ShreyasZare** [comment]
Thanks for the post. Will try to add this with the pending option to allow configuring the re-sync interval for block list URL which is fixed 24hrs currently.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds Update Now button in settings to force update block lists.
