### ISSUE TITLE
Difficulty to setup forwarding to internal domain

### ISSUE THREAD

**Issue by EHRETic** [TechnitiumSoftware/DnsServer#189]
Hi there,

I don't want to bother the author because it is probably due to a misinterpretation or a lack of knowledge, but I don't know where to ask for it.

I've now discovered this product a couple of days ago and I found it to be an impressive addition to my home lab.
**What I had:** 2 domain controllers as primary DNS for the infra, forwarding the external requests to my FW which has Unbound, then  outside. Let's call my internal domain xxxxx.local
**What I have now:** still 2 DCs as primary, but forwarding DNS request to 2 Technitium servers (for redundancy/patching), then straight outside.
**What I would like:** use Technitium DNS as primaries, forwarding internal request to my internal domain (recursive requests too)

What I found working is the use of two separate "Conditional Forwarder Zone" for xxxxx.local and for 192.168.xxx.0/24 zone, forwarding to the DC IP address (I even put both DCs IPs in those zone with FWD records

But is it the **RIGHT** way to do? It doesn't match anything written in the doc at chapter 5 (https://technitium.com/dns/help.html)

_1) Create 'internal.example.com' zone.
2) Edit the SOA record and change the Master Name Server value to the domain name of your internal DNS server.
3)Edit the NS record and change the domain name to the domain name of your internal DNS server.
4)If the domain name of your internal DNS server is not publicly resolveable then create another zone for that domain name and configure a Type A record to point to the IP address of your internal DNS Server._

I've tried to create a primary zone xxxxx.local, edit the SOA master server name to dc1, edited the NS record to dc1 and added an A record as stated in 4) as my domain is only local :

![image](https://user-images.githubusercontent.com/28634810/98709560-d4edb180-2382-11eb-9ab4-171367fa8f93.png)

But this didn't work for internal names.
I don't know if I'm overthinking or I just don't know how to do it right but I'd like to discuss it with you guys 😄

Important to know, my CentOS server still has the DCs IPs as primary DNS on the nic.

Thanks in advance for your help! 😉

PS: of course, this is not the real life values...

**Comment by EHRETic** [comment]
PS2 : what an amazing product we got there! 😃

**Comment by ShreyasZare** [comment]
Thanks for the post and the compliments!

The Help Topics page that you referred is obsolete, there is a small note on the page which is not clear though. There was no conditional forwarder option in version older that 5.0 so the chapter 5 on that help was about making it work with a hack.

Now that we have conditional forwarder option, its straight forward to use it and also supports overriding records that the DNS server should answer instead of forwarding them. You can just create normal records in the conditional forwarder zone and they work like its a primary zone but forwards for other records.

The help topics needs to be re-written for the current version for which I am unable to find time due to too many tasks at hand.

**Comment by EHRETic** [comment]
> Now that we have conditional forwarder option, its straight forward to use it and also supports overriding records that the DNS server should answer instead of forwarding them. You can just create normal records in the conditional forwarder zone and they work like its a primary zone but forwards for other records.
> 
So that was right, right ? 😁

![image](https://user-images.githubusercontent.com/28634810/98802969-61948000-2414-11eb-9e0b-eea6d3ca70a8.png)

![image](https://user-images.githubusercontent.com/28634810/98803073-84269900-2414-11eb-837f-f30fe47cbece.png)

PS: you're welcome, it is really a great product, and if I have to pick something aside the great interface, it is the installation script that WORKS!!! Thank you for that! 😉

**Comment by ShreyasZare** [comment]
> So that was right, right ? 😁

Yup, that's the correct way. :)

> PS: you're welcome, it is really a great product, and if I have to pick something aside the great interface, it is the installation script that WORKS!!! Thank you for that! 😉

Thanks for the feedback. One of the aims of this project is to make it as friction-less as possible to install and configure so that people with little background in DNS or networking should be able to use it and learn concepts with it.
