### ISSUE TITLE
Feature request: Display service port numbers beside line items in web console

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#190]
First time restarting my server since installing 5.4. It ate the IP again, which I had resolved last time by changing the service to delayed start. The install changed it back to automatic, which launched it before IIS and caused a few minute delay to getting everything back up again.

Troubleshooting would have been much easier (and for firewall configuration and other uses) to know at a glance which ports the various services run on. These ports should be indicated on the web console. 

Example:
![tdns-ports](https://user-images.githubusercontent.com/6037167/98952254-17f97300-24b0-11eb-8ca6-c4f413c0fbf1.png)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I will add the port numbers being used so that it will be much clear.

**Comment by ShreyasZare** [comment]
Version 5.5 released which fixes this issue.
