### ISSUE TITLE
[Feature request] Log browsing experience enhancement

### ISSUE THREAD

**Issue by EHRETic** [TechnitiumSoftware/DnsServer#191]
Hi there,

Here a are some thoughts about log browsing ideas that I came up with:
- Ability to click on a client's name and get all the logs concerning this particular client
- Coloring of logs: use the same colors that the main chart, so you can easily debug and find problematic entries.
- Filtering/search in logs

Not critical, but really nice to have... 😉 #

**Comment by Globulopolis** [comment]
It's hard to implement(imho) and required a lot of time. See https://github.com/TechnitiumSoftware/DnsServer/issues/103

**Comment by ShreyasZare** [comment]
Thanks for the post. Such a feature will require adding some kind of database to allow querying. Right now its just a simple text file. Will think on having such an option later since there are some core features to implement first like EDNS and DNSSEC.

**Comment by EHRETic** [comment]
> It's hard to implement(imho) and required a lot of time. See #103

@Globulopolis I didn't say it would be easy and for sure this can wait... And I'm already super happy this tool exists! 😊
(But of course, we can always suggest...)

**Comment by EHRETic** [comment]
> Thanks for the post. Such a feature will require adding some kind of database to allow querying. Right now its just a simple text file. Will think on having such an option later since there are some core features to implement first like EDNS and DNSSEC.

Coloring based on the log info would not be "easily" possible?

**Comment by ShreyasZare** [comment]
> 
> Coloring based on the log info would not be "easily" possible?

Implementing such a thing will need parsing of text data. Its not if it could be done easily or not, its about maintainability. Like in later release if there is something added to the logs then this coloring code needs to be updated too to make it work.

**Comment by Globulopolis** [comment]
> > 
> > Coloring based on the log info would not be "easily" possible?
> 
> Implementing such a thing will need parsing of text data. Its not if it could be done easily or not, its about maintainability. Like in later release if there is something added to the logs then this coloring code needs to be updated too to make it work.

How about coloring with js? Something like highlight.js with custom definitions for coloring.

**Comment by ShreyasZare** [comment]
> 
> How about coloring with js? Something like highlight.js with custom definitions for coloring.

Not sure how would that would work out in js since displaying the log file itself freezes the browser so there is a limit of 2mb to display the log file.

Another concern is if this feature be actually beneficial? Highlighting error entries in red color would sure improve visibility but if you keep the server running for a couple of days and once the cache is built for common queries there are almost all no-error log entries.

**Comment by Globulopolis** [comment]
> > 
> > How about coloring with js? Something like highlight.js with custom definitions for coloring.
> 
> Not sure how would that would work out in js since displaying the log file itself freezes the browser so there is a limit of 2mb to display the log file.
> 
> Another concern is if this feature be actually beneficial? Highlighting error entries in red color would sure improve visibility but if you keep the server running for a couple of days and once the cache is built for common queries there are almost all no-error log entries. 

Yes, you are right.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with a new Query Logs (Sqlite) DNS app that supports logging. Do update and let me know if any changes are required. Closing this issue for now.
