### ISSUE TITLE
[Feature request] Multiple users

### ISSUE THREAD

**Issue by Tooxic** [TechnitiumSoftware/DnsServer#192]
I would like to be able to add multiple users. And be able to give users permission to specific zones

**Comment by ShreyasZare** [comment]
Thanks for the request. This feature is already in to-do list and should be available in a couple of months.

**Comment by Leen15** [comment]
Hi, I would like to do the same thing.
Any ETA on this?

Thanks!

**Comment by ShreyasZare** [comment]
> 
> 
> Hi, I would like to do the same thing.
> Any ETA on this?
> 
> Thanks!

Should be available in a couple of releases but not in the next release that is coming in march.

**Comment by Tooxic** [comment]
> > Hi, I would like to do the same thing.
> > Any ETA on this?
> > Thanks!
> 
> Should be available in a couple of releases but not in the next release that is coming in march.

Is this being worked on?

**Comment by ShreyasZare** [comment]
> 
> 
> > > Hi, I would like to do the same thing.
> > > Any ETA on this?
> > > Thanks!
> > 
> > 
> > Should be available in a couple of releases but not in the next release that is coming in march.
> 
> Is this being worked on?

It has been pushed a bit back for core features that many people have requested like EDNS & DNSSEC.

**Comment by Pfuenzle** [comment]
Hi, sorry to bump this again, but are there any news? From what Ive seen DNSSEC is implemented, and User Management would be really nice to have :)

**Comment by ShreyasZare** [comment]
> Hi, sorry to bump this again, but are there any news? From what Ive seen DNSSEC is implemented, and User Management would be really nice to have :)

The next minor update is planned to fix some issues and adding a caching option. After this minor release, user management implementation will be done. After user management feature is released, clustering feature is planned next.

**Comment by ShreyasZare** [comment]
New version 9.0 is now available with multi-user support with zone lever permissions. Do update and let me know if you have any feedback.
