### ISSUE TITLE
add option to auto-start service

### ISSUE THREAD

**Issue by mrjones2014** [TechnitiumSoftware/DnsServer#193]
Why is there not an option to just automatically start the service? if I ever restart, I have to manually start the service from the system tray.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please check Windows Services console and ensure that the "Technitium DNS Service" has the startup type set to "Automatic" as shown in the image below:

![image](https://user-images.githubusercontent.com/10008172/99224980-4b6c3280-280d-11eb-9fbe-11fc14a6143a.png)

The service will start when machine reboots and if its still not starting then do check the log files once and see if there are any errors being logged.

**Comment by mrjones2014** [comment]
@ShreyasZare it is already set to Automatic. Where can I check the log files?

**Comment by mrjones2014** [comment]
@ShreyasZare here are the most recent log files surrounding the times when I restarted my server (the whole machine, not the DNS server)

[2020-11-16.log](https://github.com/TechnitiumSoftware/DnsServer/files/5548785/2020-11-16.log)
[2020-11-15.log](https://github.com/TechnitiumSoftware/DnsServer/files/5548786/2020-11-15.log)

**Comment by Globulopolis** [comment]
@mrjones2014 see the system and app logs for errors under Event Viewer(`Start > Control Panel > System and Security > Administrative Tools`).
And try to setup service recovery on failure. Set all three to restart after 1 min.

**Comment by ShreyasZare** [comment]
@mrjones2014: The logs don't contain the events when the DNS server starts. Try to get the logs for the period when the server reboots and the DNS service fails to start.

And as @Globulopolis said, do check for Windows Event Viewer (see image below) and see for Error entries for the DNS service at the time when the server rebooted. 

![image](https://user-images.githubusercontent.com/10008172/99354554-aa44b100-28cc-11eb-82a5-1fa47a2c9a28.png)

Post any errors that you see from the Event Viewer or from the DNS server logs.
