### ISSUE TITLE
[Feature request] Import/Export option for created Zones.

### ISSUE THREAD

**Issue by domgth** [TechnitiumSoftware/DnsServer#194]
Would like to import zones from a list dynamically, or export to backup. This would be a game changer. Thanks!

**Comment by ShreyasZare** [comment]
Thanks for the request. Will try to add these options soon.

**Comment by ots-georgewilkins** [comment]
Yes, this would be a very useful feature.

I have reason to migrate my installation to another machine (while updating to 5.5) and can't see any way to avoid manually re-entering 50+ zone entries through the web UI.

**Comment by ShreyasZare** [comment]
> 
> 
> Yes, this would be a very useful feature.
> 
> I have reason to migrate my installation to another machine (while updating to 5.5) and can't see any way to avoid manually re-entering 50+ zone entries through the web UI.

You can migrate easily by just copying the `config` folder to your new machine. You can find the folder in `/etc/dns/config` which you can zip on source machine and unzip on the new machine overwriting any default files that the fresh install created.

**Comment by ots-georgewilkins** [comment]
> You can migrate easily by just copying the `config` folder to your new machine.

Fantastic, thank you for pointing this out - that should save me some time.

**Comment by ShreyasZare** [comment]
New update supports import and export for all config and settings. The import/restore option allows importing only selected items like zone files.

**Comment by Taomyn** [comment]
> New update supports import and export for all config and settings. The import/restore option allows importing only selected items like zone files.

Where is this? I just updated to 5.6 and cannot find any import/export options anywhere in the web console, and nowhere is this documented,

**Comment by Taomyn** [comment]
> > New update supports import and export for all config and settings. The import/restore option allows importing only selected items like zone files.
> 
> Where is this? I just updated to 5.6 and cannot find any import/export options anywhere in the web console, and nowhere is this documented,

I just found it, but unfortunately you appear to use a non-standard format for the .zone files making them useless for importation into another DNS server https://en.wikipedia.org/wiki/Zone_file

**Comment by ShreyasZare** [comment]
> 
> 
> > > New update supports import and export for all config and settings. The import/restore option allows importing only selected items like zone files.
> > 
> > 
> > Where is this? I just updated to 5.6 and cannot find any import/export options anywhere in the web console, and nowhere is this documented,
> 
> I just found it, but unfortunately you appear to use a non-standard format for the .zone files making them useless for importation into another DNS server https://en.wikipedia.org/wiki/Zone_file

The export/import feature is to allow backup/restore option in DNS server. The zone files that the DNS server uses are in binary format. There is no option currently to export the zone file in the standard text format.
