### ISSUE TITLE
Question: what do we need to do to make this production ready?

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#20]
When released in 2017, the release notes stated:

> It must be noted that this DNS server is not suitable to be used for production or any critical application. The software is released as alpha version denoting that its not yet stable and may have bugs.

So I would like to start a discussion on what we can do to make the DNS server production ready.

I presume we need to consider things such as DNS Flood protection, but is there anything else we need to consider, such as security?

**Comment by ShreyasZare** [comment]
Currently the effort is to add core features and make the DNS Server stable under load. Correctness of responses and working of the core DNS protocol features is a priority.

There are a lot of things needed to make it ready for production usage like prevent brute force attacks on the API, IP banning (like you mentioned) etc. These enhancements are planned when core features are stable.

As of now, its suitable for usage in individual computers and on small networks.

**Comment by shawnkhall** [comment]
add ability to edit the blocklist.txt file somehow

**Comment by ShreyasAdPushup** [comment]
@shawnkhall : Thanks for the suggestion. However, there is already Blocked Zone option where you can manually add zones to block from the UI. The blocklist.txt file's intended purpose is to use the built in web server to allow automation that can be done using simple scripts on the same server.

**Comment by ShreyasZare** [comment]
@shawnkhall: Thanks for the suggestion. However, there is already Blocked Zone option where you can manually add zones to block from the UI. The blocklist.txt file's intended purpose is to use the built in web server to allow automation that can be done using simple scripts on the same server.

**Comment by shawnkhall** [comment]
I understand that, but if I want to add 300 domains to a custom blocklist my options are currently to host a text file for my block list on a webserver somewhere or manually add all 300 domains 1 by 1. That's not fun. An import option would be okay, but it would be better to have a free-form text block to edit a local blocklist equivalent to the HOSTS file.

**Comment by shawnkhall** [comment]
It would also be nice to have an option to create a whitelist along the same lines as the blacklist (also with freeform text editing) so that we can easily override items within the various blacklists we subscribe to so that if one of our blacklists prevents access to TeamViewer, for example, we can still get there without too much trouble.

**Comment by shawnkhall** [comment]
add ability to disable all logging

**Comment by ShreyasZare** [comment]
@shawnkhall: I could add a bulk insert options for Block and Allowed zones quickly. I will plan for blocklist.txt and allowlist.txt feature.

Disabling all logging would not be desirable for now since you would not know what went wrong. The software is still in beta so it will be difficult for anyone to report bugs if they can disable it.

**Comment by shawnkhall** [comment]
@ShreyasZare - I understand that the ability to disable logging might not be desirable during beta, however, if the goals include privacy then before this is production ready, it needs to have the ability to turn off all the logs.

**Comment by ShreyasZare** [comment]
Closing this issue. The DNS Server is now quite stable for use in small/medium networks with multiple 10s of clients. However, its not tested in a large network setup yet.
