### ISSUE TITLE
[Feature request] Command Line Options

### ISSUE THREAD

**Issue by egauk** [TechnitiumSoftware/DnsServer#200]
It would be nice to have command line configuration options. Among other benefits this would be helpful when scripting a build of Technitium DNS Server.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. The DNS server is supposed to run 24x7 so it provides an HTTP based API that you can use to configure it. You can read the [API docs here](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md).

The only command line option is to specify the config folder path which is optional.

To build a specific configuration, you can just run the portable version to configure the DNS server and then zip the config folder to ship it where you wish to run the exact same configuration.
