### ISSUE TITLE
[Feature request] Web console timeout option

### ISSUE THREAD

**Issue by egauk** [TechnitiumSoftware/DnsServer#201]
I am not sure what the web console timeout value is (15-minutes?) but it would be nice to have an option to set the timeout value.

**Comment by ShreyasZare** [comment]
Thanks for the post. There is a timeout value of 30 mins for session expiry. But, if you keep the web console open with the Dashboard tab showing then it keeps refreshing data every minute and thus the session expiry gets pushed ahead every minute.
