### ISSUE TITLE
Can log logs be deleted automatically

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#206]
Can the later version increase the time of saving log? Otherwise, there are more and more log files. If you add this function, you can automatically delete expired logs.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I am planning to add more options for logging so will try to add this one in upcoming release.

**Comment by thb007** [comment]
> Thanks for the feedback. I am planning to add more options for logging so will try to add this one in upcoming release.

ok

**Comment by ShreyasZare** [comment]
DNS server version 5.6 fixes this issue.
