### ISSUE TITLE
DNS-over-QUIC

### ISSUE THREAD

**Issue by nRafinia** [TechnitiumSoftware/DnsServer#208]
Please add DNS-over-QUIC support

**Comment by ShreyasZare** [comment]
Thanks for the feature request. DoQ will take a while to implement since we have to wait for dotnet to add support for QUIC or HTTP/3. You can track the dotnet issue [here](https://github.com/dotnet/aspnetcore/issues/15271).

**Comment by iamGavinJ** [comment]
@ShreyasZare Microsoft's open-source implementation of QUIC, [msquic](https://github.com/microsoft/msquic), can be [called from C# using P/Invoke](https://github.com/microsoft/msquic/blob/main/docs/API.md).  Understandably that approach may be more effort than desirable, but thought I'd highlight the possibility.

**Comment by ShreyasZare** [comment]
> 
> 
> @ShreyasZare Microsoft's open-source implementation of QUIC, [msquic](https://github.com/microsoft/msquic), can be [called from C# using P/Invoke](https://github.com/microsoft/msquic/blob/main/docs/API.md). Understandably that approach may be more effort than desirable, but thought I'd highlight the possibility.

The ecosystem with QUIC is still evolving and its implementation is still in draft stage in IETF. Its also not widely deployed to be used yet. So, I am just waiting till there is stable cross-platform support available and there are DoQ services available to be used.

Its going to be stable next year with .NET 6 release. While I am still migrating a lot of code to .NET 5.

**Comment by hairyfred** [comment]
adguard home just added dns over quic support
hopefully means its at a mature enough stage to implement into technitium

**Comment by ShreyasZare** [comment]
> adguard home just added dns over quic support hopefully means its at a mature enough stage to implement into technitium

QUIC is not yet available in .NET (HTTP/3 is there but QUIC api is not) so will have to wait for it.

**Comment by ShreyasZare** [comment]
> @ShreyasZare Now that you can update.NET 7, you have quic (http3)

Yes .NET 7 has added QUIC support. DNS-over-QUIC will get added soon but not in the upcoming update which already has a lot of features ready for release. So, you can expect it in the next update after that. 

Support for both DNS-over-QUIC to be used with forwarders, and to host it as a service on the DNS server will be available.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which now supports DNS-over-QUIC. Do check and let me know your feedback.

**Comment by ShreyasZare** [comment]
> > Technitium DNS Server v11 is now available which now supports DNS-over-QUIC. Do check and let me know your feedback.
> 
> ![图片](https://user-images.githubusercontent.com/28734349/221399426-ad52c3fa-b998-43ae-b209-aabe637cbde0.png) Why??
> 
> https://learn.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software

Check out [this blog post](https://blog.technitium.com/2023/02/configuring-dns-over-quic-and-https3.html) on this topic which explains in details on how to get QUIC running on Linux.

**Comment by ShreyasZare** [comment]
> > Check out [this blog post](https://blog.technitium.com/2023/02/configuring-dns-over-quic-and-https3.html) on this topic which explains in details on how to get QUIC running on Linux.
> 
> It's not in there. My system is debian

Were you able to install `libmsquic` from Microsoft repo? What openssl version you have?
