### ISSUE TITLE
Filter mobile traffic ?

### ISSUE THREAD

**Issue by 0xXA** [TechnitiumSoftware/DnsServer#209]
Can it filter mobile traffic on specific ports ?

**Comment by ShreyasZare** [comment]
Thanks for the post. Please explain in detail by what you mean to filter mobile traffic on specific ports. Do note that this project is a DNS server and can only be used for domain related filtering. For general TCP/IP filtering you will need to use iptables.

**Comment by 0xXA** [comment]
> Thanks for the post. Please explain in detail by what you mean to filter mobile traffic on specific ports. Do note that this project is a DNS server and can only be used for domain related filtering. For general TCP/IP filtering you will need to use iptables.

Yeah, I mean like if I connect my device to usb can dns server handle traffic on mobile devices ?

**Comment by ShreyasZare** [comment]
> Yeah, I mean like if I connect my device to usb can dns server handle traffic on mobile devices ?

If the DNS server is reachable via your mobile device then it should work. However, with windows 10 wifi hotspot, if you have the DNS server running on the same computer then the devices connected to hotspot cant access the DNS server due to how the hotspot is designed to work.

**Comment by 0xXA** [comment]
> > Yeah, I mean like if I connect my device to usb can dns server handle traffic on mobile devices ?
> 
> If the DNS server is reachable via your mobile device then it should work. However, with windows 10 wifi hotspot, if you have the DNS server running on the same computer then the devices connected to hotspot cant access the DNS server due to how the hotspot is designed to work.
What do u mean by reachable ?

**Comment by ShreyasZare** [comment]
> What do u mean by reachable ?

Reachable means there must be some IP connectivity between the mobile and the machine that is running the DNS server. You should be able to ping to test the connectivity.

**Comment by 0xXA** [comment]
> > What do u mean by reachable ?
> 
> Reachable means there must be some IP connectivity between the mobile and the machine that is running the DNS server. You should be able to ping to test the connectivity.

Is there a good alternative for android like urs dns server ?
I mean which can block domains with regex like *.myapp.com

**Comment by ShreyasZare** [comment]
> Is there a good alternative for android like urs dns server ?
> I mean which can block domains with regex like *.myapp.com

I dont know any specific app for android but, you wont get any proper server app for mobile devices. Running app in background on mobile is simply not possible since the OS kills any app as required. Thus its not feasible to make server apps for mobile devices that can reliably keep running. 

What you can achieve is to get a cheap $5/mo linux hosting and setup your DNS server there and configure you mobile to use that server with DNS-over-TLS that is supported on android.

**Comment by Globulopolis** [comment]
> > Is there a good alternative for android like urs dns server ?
> > I mean which can block domains with regex like *.myapp.com
> 
> I dont know any specific app for android but, you wont get any proper server app for mobile devices. Running app in background on mobile is simply not possible since the OS kills any app as required. Thus its not feasible to make server apps for mobile devices that can reliably keep running. 
> 
> What you can achieve is to get a cheap $5/mo linux hosting and setup your DNS server there and configure you mobile to use that server with DNS-over-TLS that is supported on android.

No. Topic starter just need to install adguard. I'm using this app on my sgs9+ w/o root. And I even cannot remember when i see adv last time. Additionally you can set you own dns ip or select predefined. And lifetime license for 3 devices cost much cheaper than VPS, and not require special knowledge.

PS! I'm not sponsored by adguard team.

**Comment by 0xXA** [comment]
> > Is there a good alternative for android like urs dns server ?
> > I mean which can block domains with regex like *.myapp.com
> 
> I dont know any specific app for android but, you wont get any proper server app for mobile devices. Running app in background on mobile is simply not possible since the OS kills any app as required. Thus its not feasible to make server apps for mobile devices that can reliably keep running.
> 
> What you can achieve is to get a cheap $5/mo linux hosting and setup your DNS server there and configure you mobile to use that server with DNS-over-TLS that is supported on android.

Can technitium dns server act as a http proxy ?
Filtering traffic ?

**Comment by ShreyasZare** [comment]
> Can technitium dns server act as a http proxy ?
> Filtering traffic ?

No. There is no proxy server built into the DNS server.
