### ISSUE TITLE
Provide a better dashboard to protect against DNS tunneling

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#21]
Provide a better dashboard to protect against DNS tunneling, something along the line of:

![image](https://user-images.githubusercontent.com/7858744/49691260-505edc80-fb36-11e8-8f3a-5da6ef301b5a.png)

Based on the work already done I don't think it would be too much effort to achieve this level of detail in the reports on the dashboard.

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. The dashboard is recently added feature and definitely needs a lot of upgrades to make it more useful.

**Comment by cubakcabak** [comment]
@ShreyasZare 

maybe you can integrate and use this for convenience instead creating from scratch.

it is one of the most useful and beautiful dashboard implementation if i may say, and it's opensource too.

https://adminlte.io/

btw, i have nothing to do with that project, just a regular user.

**Comment by ShreyasZare** [comment]
@cubakcabak : Thanks for the suggestion. Using AdminLTE will make the DNS Server look just like pi-hole DNS proxy which is a competitor! Making from scratch is not inconvenient, it done intentionally!

**Comment by rikyotei** [comment]
I think some of Vue.Js oprensource admin templates are more better than AdminLTE. lol...

**Comment by Matthew-Bonner** [comment]
The dashboard as it stands is really easy to get from what is there to what is proposed in the attached screen grab. Not sure it is worth a major refactor.
