### ISSUE TITLE
Support edns_client_subnet?

### ISSUE THREAD

**Issue by hk59775634** [TechnitiumSoftware/DnsServer#211]
I choose an upstream server that belongs to DOH JSON.

Can it be sent to upstream edns_client_subnet?

**Comment by ShreyasZare** [comment]
If the DoH server supports JSON format then you can use it. But its best to use the wire format. The DNS server does not support EDNS client subnet. The upstream DoH server that you configure as forwarder is supposed to have EDNS client subnet and will use your IP address as input for this EDNS extension.

**Comment by hk59775634** [comment]
Can I set subnet as the client's IP address? And submit the forwarding request to the upstream?

**Comment by ShreyasZare** [comment]
> 
> 
> Can I set subnet as the client's IP address? And submit the forwarding request to the upstream?

There is no support for that right now. EDNS support is planned but will take a while to implement it.

**Comment by hk59775634** [comment]
well. Thank you very much for your development work. I will continue to look forward to new features coming online. Thanks again.
