### ISSUE TITLE
Feature Request: Introduce option to add notes or comments on records

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#215]
Maybe add some more tracking properties for records?

It'd be quite neat to have a few extra properties such as a comment or note field, and perhaps creation / last-update timestamps.

Mike.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will try to get it added.

**Comment by ShreyasZare** [comment]
New version 6.3 is now available that adds the comments feature for each record in zones.
