### ISSUE TITLE
Auto-prefetching does not work on reboot

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#216]
> > @ShreyasZare is this still true with the prediction of which domain names to resolve before they're needed?
> > I assume that logic is based on the cache/some metrics.
> 
> The cache auto prefetching feature relies on the stats data that is also displayed on the dashboard. This data is on disk and will be used when the server reboots. The auto prefetch however uses only last hour data.

Just confirmed that auto prefetching wont work after the server reboots. The full query stats are not stored on disk but, only the crunched numbers are stored so it doesn't work.

_Originally posted by @ShreyasZare in https://github.com/TechnitiumSoftware/DnsServer/issues/41#issuecomment-753956397_

**Comment by ShreyasZare** [comment]
New update v6.0 is now available for download which now stores the query stats to allow auto prefetch to refresh cache when server restarts.
