### ISSUE TITLE
DHCP Scope Issue

### ISSUE THREAD

**Issue by Hemsby** [TechnitiumSoftware/DnsServer#224]
Since updating to 5.6 any new scopes created all show 0.0.0.0 as the interface.
Also, to test I installed 5.6 on a different device and created its first scope and this also shows the interface as 0.0.0.0

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The scope should use 0.0.0.0 interface only when the server's ip address is not in the scope's network.

Can you provide more details like the network that the scope is using and the ip addresses with network masks on your server?

**Comment by Hemsby** [comment]
You can mark this as closed or delete it.  User Error!  Needed to restart the Service for it to take affect.  Thanks for the response though.

**Comment by ShreyasZare** [comment]
Good to know it worked.
