### ISSUE TITLE
After reboot, DHCP scope is listening on interface "0.0.0.0" and is not responding to client requests

### ISSUE THREAD

**Issue by Chewie9999** [TechnitiumSoftware/DnsServer#227]
Technitium 5.6 is running on a "CentOS Linux release 7.9.2009 (Core)" VM, and I needed to reboot it today, which is the first time after a while of running the DHCP server part of the software, and I noticed clients were not getting DHCP addresses.
DHCP requests were being received by the Technitium VM (as checked with tcpdump). but nothing was being returned, even though 67/udp seemed to be listening on all interfaces:
``udp    UNCONN     0      0       *:bootps                *:*                     users:(("dotnet",pid=391,fd=61))``

In the web gui, the interfaces column for the scope showed as ``0.0.0.0``.
Once I disabled the scope and re-enabled it again, the interfaces column showed "192.168.2.216", which is what I would expect, and ss showed the following:
``udp    UNCONN     0      0      192.168.2.216:bootps                *:*                     users:(("dotnet",pid=391,fd=61))``.

Could this be a timing problem?
I tried adding a 30 second delay to the systemd service using ``ExecStartPre=/bin/sleep nn``, where ``nn`` was 10 at first and 30 at my last reboot, but this did not make any difference.

Note: I only have 1 scope and 1 NIC, but the NIC has 2 IP addresses (second IP is another address in the same subnet as the first).

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I have noticed this issue too a few times. 

It seems to happen when the DHCP server starts and the network interfaces are still not ready. So, the DHCP server waits for a while if there are no interfaces at all but if there is at lease one interface with static IP address available then it wont wait and start the scopes. If there is no interface with address in the scope's network range then it assumes that the scope is remote and will bind to "0.0.0.0" to allow DHCP relay agents to connect.

I will try to see if something can be done to fix this.

**Comment by ShreyasZare** [comment]
Can you provide more details like the scope range and subnet. Plus the NIC's both IP addresses and mask. This will help me to try to reproduce this issue to try to fix it.

**Comment by Chewie9999** [comment]
Thank you for the quick reply.
Ok, so it is a timing issue. I will try changing the wait time to 60 seconds in case that helps, but I won't be able to reboot the server for a few days for testing.
Server NIC details:
```
    inet 192.168.2.216/24 brd 192.168.2.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet 192.168.2.250/24 brd 192.168.2.255 scope global secondary noprefixroute eth0:1
       valid_lft forever preferred_lft forever
```
Scope Screenshot:
![Firefox_Screenshot_2021-02-05T14-46-20 435Z](https://user-images.githubusercontent.com/6060283/107048627-14c90700-67c1-11eb-94e1-c9851984ecd6.png)
Let me know if you need any more details.

**Comment by ShreyasZare** [comment]
I tried on my setup and could not reproduce it with 2 static IP addresses. But, I have seen issues related to this that used to come earlier and have added code to wait for the interface to mitigate. This is typical race condition which is hard to replicate but comes up in certain scenarios.

Earlier it was too common when server reboots and the network is not available then the DHCP would not start scope since there is no static IP on the NIC to bind. After the mitigation a couple of releases back I haven't seen this issue coming up.

Will try to add a bit more tweaks to the wait for interface code but that is going to make any scope that should listen on "0.0.0.0" to wait for 30 sec max when the server boots. Scopes that bind on the connected interfaces would start as soon as they see the IP address in scope range though.

**Comment by lfarrand** [comment]
I've also noticed this issue. It frequently happens just after rebooting and more rarely when restarting the service. A few of the network interfaces will bind to 0.0.0.0 and I have to stop and start the scopes to get them working. Once they've been bound then there's normally no problem unless I reboot or restart the DNS service.

I'm running Technitium 5.6 in a Linux LXC container (Ubuntu 20.10).

My interfaces are somewhat complex due to multiple VLANs. Here's the output from ip addr:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether aa:cc:1d:c6:f0:b9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.112.24/20 brd 192.168.127.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd11:5b05:3321:1:a8cc:1dff:fec6:f0b9/64 scope global dynamic mngtmpaddr 
       valid_lft 7143sec preferred_lft 7143sec
    inet6 fd00::1:a8cc:1dff:fec6:f0b9/64 scope global dynamic mngtmpaddr 
       valid_lft 7071sec preferred_lft 7071sec
    inet6 fe80::a8cc:1dff:fec6:f0b9/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 96:d3:35:55:18:18 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.10.3/24 brd 192.168.10.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::94d3:35ff:fe55:1818/64 scope link 
       valid_lft forever preferred_lft forever
4: eth2@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 2e:a0:32:3b:ac:7f brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.11.3/24 brd 192.168.11.255 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::2ca0:32ff:fe3b:ac7f/64 scope link 
       valid_lft forever preferred_lft forever
5: eth3@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a6:25:0f:bd:5b:eb brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.12.3/24 brd 192.168.12.255 scope global eth3
       valid_lft forever preferred_lft forever
    inet6 fe80::a425:fff:febd:5beb/64 scope link 
       valid_lft forever preferred_lft forever
6: eth4@if19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 46:c3:30:fc:09:5c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.20.3/24 brd 192.168.20.255 scope global eth4
       valid_lft forever preferred_lft forever
    inet6 fe80::44c3:30ff:fefc:95c/64 scope link 
       valid_lft forever preferred_lft forever
7: eth5@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 4a:8b:3c:05:8f:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.30.3/24 brd 192.168.30.255 scope global eth5
       valid_lft forever preferred_lft forever
    inet6 fe80::488b:3cff:fe05:8fe1/64 scope link 
       valid_lft forever preferred_lft forever
8: eth6@if25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:6e:7d:ec:ee:d0 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.40.3/24 brd 192.168.40.255 scope global eth6
       valid_lft forever preferred_lft forever
    inet6 fe80::fc6e:7dff:feec:eed0/64 scope link 
       valid_lft forever preferred_lft forever
9: eth7@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 86:45:84:78:cc:18 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.50.3/24 brd 192.168.50.255 scope global eth7
       valid_lft forever preferred_lft forever
    inet6 fe80::8445:84ff:fe78:cc18/64 scope link 
       valid_lft forever preferred_lft forever
10: eth8@if31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 3a:dc:2d:47:a8:50 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.60.3/24 brd 192.168.60.255 scope global eth8
       valid_lft forever preferred_lft forever
    inet6 fe80::38dc:2dff:fe47:a850/64 scope link 
       valid_lft forever preferred_lft forever
11: eth9@if34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 86:e1:c3:59:11:c2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.100.3/24 brd 192.168.100.255 scope global eth9
       valid_lft forever preferred_lft forever
    inet6 fe80::84e1:c3ff:fe59:11c2/64 scope link 
       valid_lft forever preferred_lft forever
```

Here are the scopes:

<img width="1155" alt="Screenshot 2021-02-25 at 21 42 35" src="https://user-images.githubusercontent.com/1841445/109223489-8b4e9880-77b2-11eb-8b6f-4a2799f503e2.png">

**Comment by ShreyasZare** [comment]
@lfarrand Thanks for the details. Lets see if the changes that I made works out well in the upcoming update in March.

**Comment by ShreyasZare** [comment]
New update v6 is now available. Please check the issue in this update and reopen the issue if its not fixed.
