### ISSUE TITLE
[feature] Setting to allow transfers to other clients

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#229]
Would it be possible to allow AXFR to other clients, than those in the NS records of a zone?

Could be useful for testing, or other special setups where one wouldn't want the other nameservers to actually be listed in the NS records.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will get this option added with an option to allow AXFR only to listed IP addresses.

**Comment by ShreyasZare** [comment]
New version 6.3 is now available that adds Zone Options to allow configuring zone transfer and notify options.
