### ISSUE TITLE
WSL 2 conflict

### ISSUE THREAD

**Issue by rachidbch** [TechnitiumSoftware/DnsServer#230]
I have WSL2 on Windows 10 20H2 Build 19042.746.
I have Technitium DNS server installed on the same machine.

Whenever I launch a Ubuntu WSL2 distribution with Technitium DNS server running, I get the error process exited with code 4294967295.

If I kill Technitium DNS and launch Ubuntu WSL2 everything works smoothly.
I created an Issue on WSL Github repo.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Do post the link to the issue that you created in WSL repo. I am not sure exactly but it could be that Ubuntu in WSL requires port 53 which is already taken by the DNS server.

**Comment by rachidbch** [comment]
Sorry for the delay.
Here's the [comment](https://github.com/microsoft/WSL/issues/5092#issuecomment-777503461) I added on an existing issue on WSL2 repo

**Comment by ShreyasZare** [comment]
closing the issue since its not related to the DNS server.

**Comment by icepole-jon** [comment]
Change the DNS Server Local End Points from `0.0.0.0:53`  to  `127.0.0.1:53`
That worked for me

**Comment by navhaxs** [comment]
Just adding to the comments here, for the benefit of future google searches. I was close to considering a Windows reinstall - but luckily I remembered that I had recently installed this DNS server software!!

This was the error message I was seeing when starting WSL:
`Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0xffffffff`

**Comment by CDN18** [comment]
In WSL2 2.0.0, if the `mirrored` network mode is enabled, even if the DNS Server Local Endpoints are set to `127.0.0.1:53`, WSL will not be able to start properly.

**Comment by ShreyasZare** [comment]
> In WSL2 2.0.0, if the `mirrored` network mode is enabled, even if the DNS Server Local Endpoints are set to `127.0.0.1:53`, WSL will not be able to start properly.
> 
> `Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x8007054f`

Try using another IP address available on the system for the DNS local end point and see if that works.
