### ISSUE TITLE
Feature Request: Sync multiple DNS servers on change.

### ISSUE THREAD

**Issue by ChrisTracy** [TechnitiumSoftware/DnsServer#231]
Great work on this project. It is working perfectly in my home lab!

It would be nice to have a way to sync two of these servers when one is changed. I am currently running two of them (primary and secondary) and updating both when I make changes to a zone/record.

**Comment by ShreyasZare** [comment]
Thanks for the compliments.

There is clustering feature in pipeline which should be available in a couple of releases. This clustering will sync all the settings and zones to multiple other servers in the cluster.

You can in current version create secondary zones on the other DNS server to sync records for the zone automatically when you make any changes on the primary zone. 

To do this, create a NS record with the domain name of the secondary DNS server in to your primary zone. If the secondary DNS server domain name is not publicly resolvable then add its IP address as glue address. Once done, create a secondary zone on the other DNS server with the IP address of the primary server if the domain is not publicly resolvable. Once done, the secondary zone will auto sync with primary within a few seconds of any change.

Let me know if you need any help with setting this up.

**Comment by ChrisTracy** [comment]
Awesome! I would be willing to give it a go when you have it in the develop branch.

I went ahead and tried your suggestion and that works perfectly. Thank you!
