### ISSUE TITLE
TXT Record multiple values

### ISSUE THREAD

**Issue by dahunni** [TechnitiumSoftware/DnsServer#232]
I am trying to creeate a TXT Record with multiple values for DNS-SD Airprint which should look like
`Test\032Printer\032\040Do\032Not\032\Use\041._ipp._tcp IN TXT "txtvers=1"
"qtotal=1" "rp=printers/dummy" "note=Domain test.aprnt.net is resolving properly."
"ty=HP Color LaserJet 9500 MFP" "adminurl=http://www.printopiapro.com" "priority=0"
"product=(HP color LaserJet 9500 MFP)" "printer-state=3" "printer-type=0xC0B0DE"
"Transparent=T" "Binary=T" "Fax=F" "Color=T" "Duplex=T" "Staple=F" "Copies=T"
"Collate=T" "Punch=F" "Bind=F" "Sort=F" "Scan=F" "pdl=application/octetstream,application/pdf,application/postscript,image/jpeg,image/png,image/urf"
"URF=W8,SRGB24,CP255,RS600,DM1"`

but the quotes get escaped if I try to lookup the record. Also the whole escaped string is enclosed in doublequotes which would mean I am only able to enter one key-value pair per record which makes dns-sd for Airprint impossible.
Am I doing something wrong or is this an actual limitation or issue?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. It looks like each of the text in double quotes is an independent TXT record so you will need to add a TXT record for each of the strings independently without the enclosing double quotes. So, "txtvers=1" becomes one TXT record, "qtotal=1" becomes another TXT record, etc.

If its a single long TXT data then its working as expected. The output shown in DNS Client is in JSON format so you will see escape sequences in the output. But if you test it with something like nslookup then there wont be any escape sequences.
