### ISSUE TITLE
Menu hidden by task bar orientation

### ISSUE THREAD

**Issue by AuracleTech** [TechnitiumSoftware/DnsServer#233]
Horizontal task bar
![image](https://user-images.githubusercontent.com/40531871/109390868-17aba900-78e2-11eb-94b2-5b2df41cdb05.png)

Vertical task bar
![image](https://user-images.githubusercontent.com/40531871/109390927-7cff9a00-78e2-11eb-94dd-fdd1c41856f3.png)

The menu is out of my monitor

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will take a look at it to see if something can be done.

**Comment by ShreyasZare** [comment]
Unfortunately, there was no way found to fix this issue. Will keep this issue open as I try to find some fix.

**Comment by ShreyasZare** [comment]
Closing this issue as it seems there is no fix for this.
