### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by AuracleTech** [TechnitiumSoftware/DnsServer#234]
https://docs.github.com/en/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository#enabling-or-disabling-discussions-for-your-repository

Can you enable discussion or open up a discord server so we can help eachother and ask questions

**Comment by ShreyasZare** [comment]
Thanks for the request. I have enabled discussions. I was already thinking on this lines and a few days ago had create [/r/technitium](https://www.reddit.com/r/technitium/) community on reddit which too you can join.
