### ISSUE TITLE
Don't lock on `this`

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#24]
I've created a PR to remove the lock on `this` for the LogManager.

https://github.com/TechnitiumSoftware/DnsServer/pull/23

**Comment by ShreyasZare** [comment]
Thanks for the PR. It would be great if you can create the same PR for "develop" branch instead of "master".

**Comment by Matthew-Bonner** [comment]
Will do so today, thanks.

**Comment by Matthew-Bonner** [comment]
Done...
https://github.com/TechnitiumSoftware/DnsServer/pull/28

Thanks.

**Comment by ShreyasZare** [comment]
merged to `develop`.
