### ISSUE TITLE
[Feature Request] Ability to auto-update allow lists

### ISSUE THREAD

**Issue by chrismeller** [TechnitiumSoftware/DnsServer#241]
Essentially, just duplicate the functionality available for block lists.

**Comment by ShreyasZare** [comment]
Thanks for the request. Can you describe your use case in details? Will using the API work out for your use case to add domains to allowed list?

**Comment by chrismeller** [comment]
The use case is simple: in addition to block lists, there are also published allow lists ([like this](https://github.com/anudeepND/whitelist)) that do change from time to time (though nowhere as frequently as block lists do). Rather than doing that manually every few months, I'd like to be able to have the server update the list itself.

I believe the API provides what I need to implement this myself, I just thought it might be worth adding as a core feature at some point as well.

**Comment by ShreyasZare** [comment]
Thanks for the details. This can be added to the existing block list URL option with `!` at start to indicate that its an allowed list URL. This will get processed with the other block lists and the domains in the allowed list wont get added to the blocked list zone. I guess such an option should be easy to use. Let me know if that works.

**Comment by chrismeller** [comment]
That sounds like a great solution to me.

**Comment by ShreyasZare** [comment]
Version 6.1 release now includes this feature. Do test it out and let me know if there are any issues.
