### ISSUE TITLE
[BUG] Web app session cookie missing - Page refresh requires re-auth

### ISSUE THREAD

**Issue by iamGavinJ** [TechnitiumSoftware/DnsServer#244]
This appears related to #218.  There is no session cookie set on successful login, therefore a refresh of the page requires re-auth.

```
---
Version: 6.0
Host: Linux (5.8.0-16-generic)
Runtime: mcr.microsoft.com/dotnet/runtime:5.0-alpine
---
```

**Comment by ShreyasZare** [comment]
Thanks for the post. This is a designed feature and not a bug. The web panel is a single page web application that uses the HTTP API to configure the server. The HTTP API has been designed to only use tokens in the query string. 

The single page app, i.e. the web panel does not require you to refresh the entire page. When you click on most of the tabs on the page, the content is refreshed. If the content does not refresh then you will find a refresh link on the page like on the Cache tab. 

So, you don't really need to refresh the page, just click on the tabs to refresh the view or click on the refresh links.

**Comment by iamGavinJ** [comment]
Thanks for the feedback...
