### ISSUE TITLE
[REQUEST] Documentation of backlog and roadmap

### ISSUE THREAD

**Issue by iamGavinJ** [TechnitiumSoftware/DnsServer#245]
Hi Team,
Am loving your stack and I'm in the process of migrating over from pi-hole for a number of reasons, most notably the Dns Apps framework.

I've reviewed most of the open issues on GH, and you've mentioned a couple of times that the request raised is already on your backlog or roadmap.

I was wondering/hoping you might be willing to share and document what's on your plan?

Many thanks.

**Comment by ShreyasZare** [comment]
Thanks for the compliments. That's a good suggestion. I will add thing from my to-do list into the readme.md repo page so that it becomes available to everyone to see the upcoming features that are planned.

**Comment by ShreyasZare** [comment]
I have added Planned Features section in the [read me](https://github.com/TechnitiumSoftware/DnsServer/blob/master/README.md) which lists major features that are planned.
