### ISSUE TITLE
[Question] Dynamically Updating DNS through DHCP Server

### ISSUE THREAD

**Issue by KevinFumbles** [TechnitiumSoftware/DnsServer#249]
Hi I was wondering if there is a way to update DNS records on Technitium from a separate DHCP server. I’m using PfSense as mine and it supports RFC 2136 dynamic DNS updates, but it requires a TSIG key which I’m not sure is something Technitium already generates.
[Here’s a link to PfSense’s documentation describing it](https://docs.netgate.com/pfsense/en/latest/services/dyndns/rfc2136.html) 

If this is something that isn’t already implemented, can we count this as a feature request then?
Thanks!

**Comment by ShreyasZare** [comment]
Thanks for the request. Dynamic DNS support is planned and it will take some time to get it implemented. 

Right now, this can be achieved only by using the HTTP API with your application or a custom script.

**Comment by ShreyasZare** [comment]
I have added planned features section in the [read me](https://github.com/TechnitiumSoftware/DnsServer/blob/master/README.md) now with a list of major features that are planned.

**Comment by ctrlbrk42** [comment]
+1

**Comment by ShreyasZare** [comment]
Version 9.1 is now available that supports Dynamic Updates [RFC 2136]. Do update and let me know your feedback.

**Comment by Protocol73** [comment]
### Wanted to note:

Working with DDNS updates & ACME SSL in PFsense 2.6.0 via:  
- Services > Dynamic DNS > RFC2136 Clients
- PFsense > ACME > Certificates > DNS-NSupdate / RFC 2136
