### ISSUE TITLE
Version 6.1 blocked all request by default

### ISSUE THREAD

**Issue by josh0036** [TechnitiumSoftware/DnsServer#250]
Hi.
In version 6.1 All request are blocked/Refused by default.
 ![Screenshot from 2021-04-11 19-18-39](https://user-images.githubusercontent.com/37348786/114302337-374a0a00-9afb-11eb-9d5e-21b5fac8c139.png)

Is there a way to "allow" all requests by default in 6.1?

--------------------------------------------------------------------------------------------
_blocking all requests / Refused by default._.
I like this Feature in my other servers but can you please add  "allow" all requests by default.

**Comment by ShreyasZare** [comment]
Thanks for the post. There is no default setting to block all domains. It seems you have added wildcard blocking entry in the Blocked zone which is causing this issue. Do check your Blocked zone and remove any entry you see in there.

**Comment by rezist** [comment]
Hmm, seems like I need to check it too :)  I've imported a few K of records to blocked section on fresh install. I'll report back soon.

**Comment by rezist** [comment]
Maximum size for .config file is 250 KB - this I blame .Net for :)
I've tried to add 12K records and looks like blocked.config is broken

**Comment by ShreyasZare** [comment]
> 
> 
> Maximum size for .config file is 250 KB - this I blame .Net for :)
> I've tried to add 12K records and looks like blocked.config is broken

Thanks for the info. There is no such limit with .NET, it could be some bug in code. Do you see any errors in the log file? Do share any errors that you see.

Also, if possible do share the list of domains that you are using to block as a text file. I will try it on my test setup to reproduce the issue.

**Comment by Globulopolis** [comment]
After update to 6.1 all requests blocked.
I see refused for any request.
```
{
  "Metadata": {
    "NameServer": "server:53 (127.0.0.1:53)",
    "Protocol": "Udp",
    "DatagramSize": "28 bytes",
    "RoundTripTime": "4,19 ms"
  },
  "Identifier": 44989,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "Refused",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 0,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "google.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [],
  "Additional": []
}
```

![image](https://user-images.githubusercontent.com/740757/114307069-ad904180-9ae6-11eb-8b88-0abdaf000239.png)

**Comment by rezist** [comment]
Sorry, my mistake (about the size)!  I've successfully imported all the urls and then... I managed to go full circle by clearing Block List Url's inside Settings Tab. If Quick Add is empty and Block List URL's does not contain any records, all requests are blocked.

**Comment by Globulopolis** [comment]
> If Quick Add is empty and Block List URL's does not contain any records, all requests are blocked.

Quick Add is empty, but Block List URL's not and same problem.

**Comment by ShreyasZare** [comment]
Thanks guys for the feedback. I found the bug in a condition check that was added for optimization. This bug occurs when you have blocked domains using the Blocked zone but there is no Block List URL added.

Will fix this bug immediately and there should be an update available around an hour's time. Will post here when the update is available.

Until then you can mitigate this bug by adding at least one block list URL.

**Comment by ShreyasZare** [comment]
Version 6.2 is now available that fixes this critical bug. Please update and let me know if the issue was fixed.

**Comment by Globulopolis** [comment]
> 
> 
> Version 6.2 is now available that fixes this critical bug. Please update and let me know if the issue was fixed.

Looks like the issue is fixed.

**Comment by Globulopolis** [comment]
NXdomain on stats dashboard, what is it?

**Comment by ShreyasZare** [comment]
Name Error is an old term which confuses many people. So, it was renamed to
NX DOMAIN term which is better at conveying that the domain does not exist.

Also, now you have option to configure how the DNS server responds to
blocked domain names. You can use the existing method where server returns
0.0.0.0 address or the new option which makes the server return NX DOMAIN
response.
