### ISSUE TITLE
[Feature Request] Add Blockpage / Change sinkhole IP-Address

### ISSUE THREAD

**Issue by reneshp** [TechnitiumSoftware/DnsServer#252]
Hi,

would it be possible to change the sinkhole ip-address from 0.0.0.0 to a specific ip in future? 

I think it would be great to make an own block page like cisco umbrella / opendns - just to let the networkusers know the network isnt broken, but a certain page is actually blocked.

Thank you.

**Comment by ShreyasZare** [comment]
Thanks for the request. This was requested a few times earlier too. The main concern here is that since all websites use HTTPS, you will then see certificate error in browser for all the blocked websites. Which means that you have to click to ignore the cert errors to see the page. This will also show up warnings on the iframe on websites where the ads got blocked.

In enterprise setup with AD integration, you can get it done since all devices already trust the AD root cert. For home or small office cases, this will end up training people to ignore cert errors.

And for websites which has HTTP Strict Transport Security (HSTS) deployed, there wont be a way to ignore the cert errors.

**Comment by Globulopolis** [comment]
> The main concern here is that since all websites use HTTPS, you will then see certificate error in browser for all the blocked websites. Which means that you have to click to ignore the cert errors to see the page. This will also show up warnings on the iframe on websites where the ads got blocked.
> 
> In enterprise setup with AD integration, you can get it done since all devices already trust the AD root cert. For home or small office cases, this will end up training people to ignore cert errors.
> 
> And for websites which has HTTP Strict Transport Security (HSTS) deployed, there wont be a way to ignore the cert errors.

How about implement mikrotik dns behaviour? At least nxdomain or forward-to replies? On first, we will get a non-existent error on second we can forward request to another dns server.

**Comment by reneshp** [comment]
I use Technitium on my home network, and of course, both Iframes or other content is loaded with htpps. I agree with you.
But I think, that is still a default behavior just to type along a domain name in the browser, which will have the browser to get a http site. 
forwarding, as Globulopolis suggest would also be a possible solution for this.

**Comment by ShreyasZare** [comment]
> 
> 
> I use Technitium on my home network, and of course, both Iframes or other content is loaded with htpps. I agree with you.
> But I think, that is still a default behavior just to type along a domain name in the browser, which will have the browser to get a http site.
> forwarding, as Globulopolis suggest would also be a possible solution for this.

The default HTTP protocol is going to change with the next release of Chrome. So, with it, the browser would try HTTPS when you enter a domain name in address bar. It would fallback to HTTP if HTTPS fails though.

I will test a few things regarding feature this for a while and then get back here with the implementation.

**Comment by ShreyasZare** [comment]
> 
> How about implement mikrotik dns behaviour? At least nxdomain or forward-to replies? On first, we will get a non-existent error on second we can forward request to another dns server.

Will try a few things and get back.

**Comment by ShreyasZare** [comment]
New version 6.3 now adds option to set custom addresses for blocked domain names. There is no block page support yet since need to figure out how to run it along side of the DoH web server.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with new Block Page DNS App which can display a block page. To use this app, its required to configure custom blocking address for blocking settings with the IP address of your server.
