### ISSUE TITLE
[bug] Dashboard graphs not loading in 6.2

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#253]
Just updated to 6.2, and the graphs on the dashboard do not load in Firefox. I've force-reloaded (Ctrl+F5), so it shouldn't be stale resources.

The firefox web console shows the following stacktrace.

```
Uncaught TypeError: responseJSON.response.stats.totalNameError is undefined
    success http://dns.home/js/main.js:1221
    success http://dns.home/js/common.js:111
    jQuery 6
    HTTPRequest http://dns.home/js/common.js:92
    refreshDashboard http://dns.home/js/main.js:1213
    showPageMain http://dns.home/js/main.js:76
    success http://dns.home/js/main.js:507
    success http://dns.home/js/common.js:111
    jQuery 6
    HTTPRequest http://dns.home/js/common.js:92
    login http://dns.home/js/main.js:502
    onclick http://dns.home/:1
main.js:1221:14
    success http://dns.home/js/main.js:1221
    success http://dns.home/js/common.js:111
    jQuery 6
    HTTPRequest http://dns.home/js/common.js:92
    refreshDashboard http://dns.home/js/main.js:1213
    showPageMain http://dns.home/js/main.js:76
    success http://dns.home/js/main.js:507
    success http://dns.home/js/common.js:111
    jQuery 6
    HTTPRequest http://dns.home/js/common.js:92
    login http://dns.home/js/main.js:502
    onclick http://dns.home/:1
    LP_InputClickToSubmit moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:71
    LP_doSubmit moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:71
    submit moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:71
    receiveBG moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:71
    e moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:71
    apply self-hosted:2705
    apply moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:49
    onLoad moz-extension://50910776-9060-4e73-9b44-a1679d24ebe3/onloadwff.js:71
    apply self-hosted:2705
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2432
```

Screenshot:

![image](https://user-images.githubusercontent.com/1027111/114459271-96357f00-9be0-11eb-82f3-c8f6ca1bed7f.png)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is definitely a cache related issue. Do try it with private/incognito mode or with another web browser.

**Comment by LordMike** [comment]
I opened up an inprivate firefox, and got this:

![image](https://user-images.githubusercontent.com/1027111/114556293-d9d3cb80-9c68-11eb-92db-635875209e3f.png)

Same undefined variable/name.

* Chrome shows the same (I don't use it regularly)
* Edge shows the same (I don't use it regularly)

**Comment by LordMike** [comment]
Maybe I screwed up the update?

**Comment by ShreyasZare** [comment]
> 
> 
> Maybe I screwed up the update?

Do try to update again so that the files get overwritten just in case something failed previously.

You can confirm if the files were not updated by comparing the main.js file from your disk and from the [GitHub repo](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/www/js/main.js). The `totalNameError` text should not exists in the file from the update.

**Comment by LordMike** [comment]
That was it. Bad update.

Sorry 'bout that.
