### ISSUE TITLE
Query fails for large responses

### ISSUE THREAD

**Issue by DRSDavidSoft** [TechnitiumSoftware/DnsServer#254]
Hi,

Firstly, I would like to thank you for developing this DNS Server, I have been using it as a public-facing endpoint in production for a while now.

Today I have upgraded to the latest `6.2` release of Technitium DNS Server, due to an intermittent issue in the older version (`4.x` that I've been using in production) that would sometimes fail to resolve queries, and thus requiring me to manually restart the service.

However, after upgrading to the latest version I'm facing a different issue now.

I'm not sure why, but Technitium DNS Server is failing to resolve queries that contain large responses.  Here's an output for working queries (it is listening on `127.0.0.4`):

```bash
$ dig eth0.me @127.0.0.4

; <<>> DiG 9.11.9 <<>> eth0.me @127.0.0.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24485
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;eth0.me.                       IN      A

;; ANSWER SECTION:
eth0.me.                91      IN      A       5.132.162.27
```

As you can see, Technitium DNS Server is forwarding the response and thus resolving the query for an example domain, `eth0.me` quite fine.

However, let's resolve something like `www.youtube.com`:
```bash
$ dig www.youtube.com @127.0.0.4

; <<>> DiG 9.11.9 <<>> www.youtube.com @127.0.0.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 52782
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; Query time: 12 msec
;; SERVER: 127.0.0.4#53(127.0.0.4)
;; WHEN: Fri Apr 16 19:24:30 +0430 2021
;; MSG SIZE  rcvd: 33
```

As you can see, it's not responding to the query.  I see this in the logs for my query when it fails:

```
[2021-04-16 04:48:45 UTC] [192.168.30.1:34508] [UDP] QNAME: www.youtube.com; QTYPE: AAAA; QCLASS: IN; RCODE: NoError; ANSWER: [......]
[2021-04-16 04:48:45 UTC] DNS Server recursive resolution failed for QNAME: www.youtube.com; QTYPE: A; QCLASS: IN;
TechnitiumLibrary.Net.Dns.DnsClientException: DnsClient failed to resolve the request: no response from name servers. ---> System.Net.Sockets.SocketException: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at TechnitiumLibrary.Net.Dns.ClientConnection.UdpClientConnection.Query(DnsDatagram request)
   at TechnitiumLibrary.Net.Dns.DnsClient.Resolve(DnsDatagram request)
   --- End of inner exception stack trace ---
   at TechnitiumLibrary.Net.Dns.DnsClient.Resolve(DnsDatagram request)
   at DnsServerCore.Dns.DnsServer.<>c__DisplayClass71_0.<RecursiveResolve>b__0(Object state)
```

I have not tested this on another machine, but I'm quite perplexed as to why I'm getting this exception:  
**DnsClient failed to resolve the request: no response from name servers. ---> System.Net.Sockets.SocketException: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself**

I'm not sure if there is something wrong with my machine, or something else.  I'm hoping that you could help me find the culprit, and fix it, since this issue was not present in the older version.

I have made sure that the parent DNS resolver (which is Unbound/DNSCrypt-Proxy) working fine.  Here's the result of my parent resolver:

```
$ dig www.youtube.com @127.0.0.3

; <<>> DiG 9.11.9 <<>> www.youtube.com @127.0.0.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26594
;; flags: qr rd ra; QUERY: 1, ANSWER: 17, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        21323   IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 23     IN      A       142.250.179.78
youtube-ui.l.google.com. 23     IN      A       216.58.198.206
youtube-ui.l.google.com. 23     IN      A       216.58.209.238
youtube-ui.l.google.com. 23     IN      A       142.250.179.110
youtube-ui.l.google.com. 23     IN      A       216.58.201.238
youtube-ui.l.google.com. 23     IN      A       216.58.206.238
youtube-ui.l.google.com. 23     IN      A       172.217.18.206
youtube-ui.l.google.com. 23     IN      A       216.58.214.78
youtube-ui.l.google.com. 23     IN      A       142.250.74.238
youtube-ui.l.google.com. 23     IN      A       142.250.75.238
youtube-ui.l.google.com. 23     IN      A       216.58.214.174
youtube-ui.l.google.com. 23     IN      A       216.58.213.142
youtube-ui.l.google.com. 23     IN      A       216.58.213.174
youtube-ui.l.google.com. 23     IN      A       216.58.204.142
youtube-ui.l.google.com. 23     IN      A       172.217.19.238
youtube-ui.l.google.com. 23     IN      A       172.217.22.142

;; Query time: 5 msec
;; SERVER: 127.0.0.3#53(127.0.0.3)
;; WHEN: Fri Apr 16 19:29:27 +0430 2021
;; MSG SIZE  rcvd: 720
```

I would appreciate it if your could please investigate this issue and possibly find out why this is happening.

Thank you again for your time,
With best regards.

**Comment by ShreyasZare** [comment]
Hi,

Thanks for the feedback and details. I got a fair idea about the issue and
will try to get it fixed this weekend. A new update is also due this
weekend so the fix should get included in it.

For now I would suggest that you use DNS-over-TCP in your forwarder
configuration so that the issue won't occur.

Regards,
Shreyas Zare
Technitium

**Comment by DRSDavidSoft** [comment]
Thank you for the quick response!

I have enabled DNS-over-TCP as a workaround for now (the upstream configuration already provided TCP), and it's working correctly for now.

I'm looking forward to the UDP fix, so I can switch back to DNS-over-UDP.  I appreciate it!

Best regards

**Comment by ShreyasZare** [comment]
I was able to replicate the issue by sending large response. In your dig output, the Unbound server is responding with 720 bytes which is causing the issue.

Since, Technitium DNS Server is yet to support EDNS, the receive buffer is set to 512 bytes and any response greater that that would throw error. However, Unbound should have truncated the response to 512 bytes with truncation flag set in the response headers as per the standard but it looks like its assuming the client to support EDNS and sending a large response.

Now, the fix that is implemented with just detect when the response size is greater than 512 bytes and then switch to TCP protocol and query again just like how it would happen when response contains truncation flag set.

A new update v6.2.1 is now available with the fix. Do update your server and let me know it the issue is resolved.
