### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#256]
https://go.technitium.com:443/

**Comment by ShreyasZare** [comment]
This is working as expected. Its an implementation for having permanent URL so it will just redirect to other URLs based on an Id just like an URL shortening service. Just try Id=1 link [here](https://go.technitium.com/?id=1).

**Comment by thb007** [comment]
> This is working as expected. Its an implementation for having permanent URL so it will just redirect to other URLs based on an Id just like an URL shortening service. Just try Id=1 link [here](https://go.technitium.com/?id=1).

thk !
