### ISSUE TITLE
Logs are not updated after disabling, deleting, and enabling them again

### ISSUE THREAD

**Issue by aliron19** [TechnitiumSoftware/DnsServer#259]
Hi, 

I'm using Technitium DNS Server (TDS) v6.2.2 on Windows 10 Pro 64 bits. Under logging settings, I've got `Log All Queries` and `Use Local Time` options enabled.

If I do the following:

1. Disable logging.
2. Delete all logs.
3. Enable logging again.

Then the logs only show one line that says `Logging started.`, and nothing else, until I restart the TDS Service. Once I've restarted the TDS service, the logs start working again.

If I only disable and re-enable logging (without deleting the logs), then TDS restart updating the logs perfectly fine.

I've tried to reinstall TDS without success.

How can I help to debug this issue?

Thanks.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I found the issue and fixed it. Will get it updated in today or tomorrow.

**Comment by aliron19** [comment]
Great news you found it! 

Thank you very much for your quick response.

**Comment by ShreyasZare** [comment]
Version 6.2.3 is released that fixes this issue.
