### ISSUE TITLE
How to avoid caching loss?

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#260]
The program update will lose all DNS cache, and the restart system will be lost. Is there any way to save these cache to the hard disk? For example, use Redis?

**Comment by ShreyasZare** [comment]
Thanks for asking. 

For a small setup, its not really worth doing it since the data in cache expires within few hours and rebuilding cache on startup is not that expensive. So, storing cache on disk while server shutdowns is also not a good option as it will take a lot of time to stop/start the server. 

Also, the DNS server uses last hour stats with auto prefetch to refresh the cache when the server restarts so that the popular queries are cached within few seconds on start. So you can fine tune the auto prefetch values in settings as per your requirements.

For production setup, you can mitigate any such issues by having 2 or more DNS servers that would allow you to remove one for maintenance and then add it back without any impact on resolutions.

I have in mind an idea related to this to use DNS App model to allow using NoSQL key-value database as a backing store for cache that can be shared among multiple DNS server instances. This could be useful for running a large DNS operation where the cache size is too big for each server to have an independent cache that use a lot of RAM.

Do let me know your scenario to help me understand the issue better.

**Comment by thb007** [comment]
> Thanks for asking.
> 
> For a small setup, its not really worth doing it since the data in cache expires within few hours and rebuilding cache on startup is not that expensive. So, storing cache on disk while server shutdowns is also not a good option as it will take a lot of time to stop/start the server.
> 
> Also, the DNS server uses last hour stats with auto prefetch to refresh the cache when the server restarts so that the popular queries are cached within few seconds on start. So you can fine tune the auto prefetch values in settings as per your requirements.
> 
> For production setup, you can mitigate any such issues by having 2 or more DNS servers that would allow you to remove one for maintenance and then add it back without any impact on resolutions.
> 
> I have in mind an idea related to this to use DNS App model to allow using NoSQL key-value database as a backing store for cache that can be shared among multiple DNS server instances. This could be useful for running a large DNS operation where the cache size is too big for each server to have an independent cache that use a lot of RAM.
> 
> Do let me know your scenario to help me understand the issue better.

I currently use redis for persistent caching.

**Comment by thb007** [comment]
> Thanks for asking.
> 
> For a small setup, its not really worth doing it since the data in cache expires within few hours and rebuilding cache on startup is not that expensive. So, storing cache on disk while server shutdowns is also not a good option as it will take a lot of time to stop/start the server.
> 
> Also, the DNS server uses last hour stats with auto prefetch to refresh the cache when the server restarts so that the popular queries are cached within few seconds on start. So you can fine tune the auto prefetch values in settings as per your requirements.
> 
> For production setup, you can mitigate any such issues by having 2 or more DNS servers that would allow you to remove one for maintenance and then add it back without any impact on resolutions.
> 
> I have in mind an idea related to this to use DNS App model to allow using NoSQL key-value database as a backing store for cache that can be shared among multiple DNS server instances. This could be useful for running a large DNS operation where the cache size is too big for each server to have an independent cache that use a lot of RAM.
> 
> Do let me know your scenario to help me understand the issue better.

Can two DnsServer programs be installed on one server?

**Comment by thb007** [comment]
If I have 2 servers, how do I configure them to connect to each other and balance the load?

**Comment by ShreyasZare** [comment]
> 
> I currently use redis for persistent caching.

Can you describe more on this?

**Comment by ShreyasZare** [comment]
> 
> If I have 2 servers, how do I configure them to connect to each other and balance the load?

Just configure your DHCP to give 2 DNS server addresses. The clients will handle the failover automatically.

**Comment by ShreyasZare** [comment]
> 
> Can two DnsServer programs be installed on one server?

Yes, you can do that. You will need to bind both the DNS servers to different IP address. 

To do that, you will need 2 IP addresses on your network adapter on the server. Install one DNS server and set its local endpoint in settings to the first address and change the web console port to a different one. Then install another DNS server instance and use the other IP address as the local end point.

Installing another DNS server instance will depend on the OS. For Linux:
- Just copy the /etc/dns directory to /etc/dns2. 
- Edit the /etc/dns2/systemd.service to change the paths to /etc/dns2 
- Copy the systemd.service to /etc/systemd/system/dns2.service. 
- Run `systemctl enable dns2` and `systemctl start dns2` to start the second instance.

Note that you should change the web console port on the first instance to something other than 5380 so that the second instance can start on that default port.

**Comment by thb007** [comment]
> > I currently use redis for persistent caching.
> 
> Can you describe more on this?

Unbound supports redis. My unbound upstream is DnsServer. All dns cache data will be cached by redis to the hard disk. When DnsServer restarts/updates or restarts the system, unbound will automatically load the redis dump.rdb file. The disadvantage is that DnsServer currently does not support edns and DNSSEC.

**Comment by thb007** [comment]
> > If I have 2 servers, how do I configure them to connect to each other and balance the load?
> 
> Just configure your DHCP to give 2 DNS server addresses. The clients will handle the failover automatically.

Can you give an example of configuring DHCP?

**Comment by ShreyasZare** [comment]
> 
> 
> > > I currently use redis for persistent caching.
> > 
> > 
> > Can you describe more on this?
> 
> Unbound supports redis. My unbound upstream is DnsServer. All dns cache data will be cached by redis to the hard disk. When DnsServer restarts/updates or restarts the system, unbound will automatically load the redis dump.rdb file. The disadvantage is that DnsServer currently does not support edns and DNSSEC.

Thanks for the details. Those features will role out as I keep working. 

I had thought about using NoSql backed cache last month when implementing the DNS App framework. Will try to design and implement it in coming months.

**Comment by ShreyasZare** [comment]
> 
> 
> > > If I have 2 servers, how do I configure them to connect to each other and balance the load?
> > 
> > 
> > Just configure your DHCP to give 2 DNS server addresses. The clients will handle the failover automatically.
> 
> Can you give an example of configuring DHCP?

The option depends on the DHCP server that you are using. Any DHCP server will allow you to specify more than one DNS server. With the DHCP server that is included with DNS server, you can give multiple IP addresses for DNS server one below other.

**Comment by thb007** [comment]
> > > > If I have 2 servers, how do I configure them to connect to each other and balance the load?
> > > 
> > > 
> > > Just configure your DHCP to give 2 DNS server addresses. The clients will handle the failover automatically.
> > 
> > 
> > Can you give an example of configuring DHCP?
> 
> The option depends on the DHCP server that you are using. Any DHCP server will allow you to specify more than one DNS server. With the DHCP server that is included with DNS server, you can give multiple IP addresses for DNS server one below other.

I am installed on the VPS and only one IP, I still don't understand how to fill in this menu.
![N2MKSF2B7IQ)J__8KNX%4WH](https://user-images.githubusercontent.com/17548936/117135061-05198880-add9-11eb-96eb-a65f649e1699.png)

**Comment by ShreyasZare** [comment]
Scroll down a bit and find this option:
![image](https://user-images.githubusercontent.com/10008172/117135617-d5608580-adc4-11eb-83e2-531649c3d20a.png)

**Comment by ShreyasZare** [comment]
> I am installed on the VPS and only one IP, I still don't understand how to fill in this menu.

If you have the DNS server on the VPS, you cannot use DHCP from there to assign addresses to your clients on local network. You need to install the DHCP on your local network separately for it to work.

**Comment by thb007** [comment]
> > I am installed on the VPS and only one IP, I still don't understand how to fill in this menu.
> 
> If you have the DNS server on the VPS, you cannot use DHCP from there to assign addresses to your clients on local network. You need to install the DHCP on your local network separately for it to work.


I thought I could be a cloud server load balancing on it

**Comment by ShreyasZare** [comment]
> 
> I thought I could be a cloud server load balancing on it

Its even simple. You will need 2 DNS servers which you can host anywhere either on cloud or locally. So now you have 2 IP addresses that you can use to assign to your clients.

Now, run a DHCP server locally which assigns IP address all your clients on the network and use the 2 DNS server addresses for the DNS option in the DHCP scope.

**Comment by echodreamz** [comment]
Our current DNS solution stores cache between restarts / updates. It shuts down and starts up within seconds, even when there is 100k cached records. It simply uses a file on disk to store the cache contents, no redis or any external systems needed.

It keeps us from having to requery against paid DNS services where we billed per-query or billed based on total queries. If we have 50k records from X service in cache, restart the server, cache is lost, we resume, get hit with say 10k requests against said service, that is now 10k additional queries. This is helpful with our mail servers that are doing RDNS checks against paid blacklist providers.

**Comment by ShreyasZare** [comment]
> Our current DNS solution stores cache between restarts / updates. It shuts down and starts up within seconds, even when there is 100k cached records. It simply uses a file on disk to store the cache contents, no redis or any external systems needed.
> 
> It keeps us from having to requery against paid DNS services where we billed per-query or billed based on total queries. If we have 50k records from X service in cache, restart the server, cache is lost, we resume, get hit with say 10k requests against said service, that is now 10k additional queries. This is helpful with our mail servers that are doing RDNS checks against paid blacklist providers.

Thanks for sharing this. Such a feature will be useful for scenarios like you mention. Will plan to add a feature.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which can now save DNS cache to disk and reload it on startup. Do check and let me know your feedback.

**Comment by liang-hiwin** [comment]
> Technitium DNS Server v11 is now available which can now save DNS cache to disk and reload it on startup. Do check and let me know your feedback.

thank you. I will update it later, but it will be better if it supports Redis high availability!
