### ISSUE TITLE
<Feature_Req> Add response policy functionality (different answer for different DNS clients). 

### ISSUE THREAD

**Issue by Yuri-01** [TechnitiumSoftware/DnsServer#261]
Hi, Shreyas, and thank you for your work.

My suggestion - is add ability to define different answers (and maybe different modes for blocked domains (IP addr.0.0.0.0, NXDOMAIN, pre-configured IP addr., etc.) for different group of DNS clients (like RPZ in BIND and similar functionality in other forwarding  DNS servers ("dnsmasq", "unbound", "AdGuard Home", "DNS Safity", ...).

Appendix:
DNS clients can be grouped by IP addr, IP addr.range, IP addr.network, MAC-addr., DHCP vendor class, etc.).

**Comment by ShreyasZare** [comment]
Thanks for the compliments and the feature request. I think this could be implemented with DNS Apps framework. Will post update after evaluating it.

**Comment by Yuri-01** [comment]
Shreyas, thank you.

**Comment by ShreyasZare** [comment]
Lets keep this issue open to allow tracking the feature.

**Comment by Yuri-01** [comment]
Ok. Sorry.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with new Advanced Blocking DNS App that supports blocking based on multiple groups of IP addresses or subnets.
