### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#262]
Previously, when I used version 3 or 4 I thought the system was crashing, but I used the adguard home version and I did not encounter this problem. Now, did the last version remain the same proplem or did it become much better and not crash ??
Let it be, with knowledge, that stopping it does not work in my interest, as it causes me to lose a lot

**Comment by ShreyasZare** [comment]
Thanks for the post. If you are using older version then its highly recommended that you upgrade to the latest version. There are huge amounts for bug fixes and improvements. Latest version is highly stable compared to v3 & v4.
