### ISSUE TITLE
any feature to change the puplic ip in whatsmyip by dns or anything

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#264]
![Desktop Screenshot 2021 05 09 - 22 03 56 19](https://user-images.githubusercontent.com/31727156/117583909-7a0afc00-b112-11eb-99ad-dcfca8208fb6.png)

**Comment by ShreyasZare** [comment]
You need to use a VPN or Tor to change your IP address. Its not possible to this using DNS.
