### ISSUE TITLE
Secondary Zone, AXFR transfers

### ISSUE THREAD

**Issue by itssimple** [TechnitiumSoftware/DnsServer#266]
I'm trying to setup a secondary DNS in case our primary provider has issues, so that our internal servers can still serve lookups.

But I cannot get it to fill the entire zone, so I'm guessing I'm doing something wrong.

## Steps I take
1. Add Zone, select Secondary
2. Enter the zone name (root domain)
3. Enter the AXFR-domain (IP-address)
4. Zone gets created, but I only get a SOA entry pointing to the AXFR-domain.

## Expected results
Zone should be filled up from primary servers

It could also be that I'm understanding this whole thing wrong.. :)

**Comment by ShreyasZare** [comment]
Thanks for the post. Your secondary zone setup is all ok. If you check the logs you should find that the primary server is probably responding with RCODE=Refused. This is since zone transfer is allowed only for servers that have an NS record in the zone.

In that case, you will need to add an NS record in your primary zone with the domain name that points to your secondary server. If the domain name used in the NS record does not have an A record in the zone and if the domain is not publicly resolvable then enter the IP address of your secondary server as the Glue Address in the NS record.

In the next update that is coming this weekend, there will be explicit option for each zone where you can configure how the zone transfer should be allowed and how the Notify option should be handled. These zone options will make it a bit easier to configure secondary zones.

**Comment by itssimple** [comment]
Log output:

```plain
[2021-06-03 08:53:01 UTC] [172.22.0.122:43127] [admin] Authoritative secondary zone was created: <domain>
[2021-06-03 08:53:01 UTC] Saved zone file for domain: <domain>
[2021-06-03 08:53:06 UTC] DNS Server has started zone refresh for secondary zone: <domain>
[2021-06-03 08:53:07 UTC] DNS Server successfully refreshed '<domain>' secondary zone from: axfr.dnsimple.com:53 (50.31.225.92:53)
[2021-06-03 08:53:07 UTC] Saved zone file for domain: <domain>
```

So, it looks like it's successful at least, but I still only get the SOA-record.
And the server should be allowed/whitelisted at DNSimple as well (I've tried with our AD-server as well).

Looking forward to the next update!

**Comment by ShreyasZare** [comment]
Thanks for the details. Since you have already configured your primary zone to allow zone transfer, try using the DNS Client (built-in tool in the DNS web console) to do zone transfer using AXFR type. Let me know what you see in the output in the DNS Client.

**Comment by itssimple** [comment]
```json
{
  "Metadata": {
    "NameServer": "unknown.servercentral.net:53 (50.31.225.92:53)", // This is axfr.dnsimple.com
    "Protocol": "Tcp",
    "DatagramSize": "90 bytes",
    "RoundTripTime": "971.69 ms"
  },
  "Identifier": 9738,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": false,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 1,
  "NSCOUNT": 0,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "<domain>",
      "Type": "AXFR",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "<domain>",
      "Type": "SOA",
      "Class": "IN",
      "TTL": "3600 (1 hour)",
      "RDLENGTH": "47 bytes",
      "RDATA": {
        "PrimaryNameServer": "axfr.dnsimple.com",
        "ResponsiblePerson": "admin.dnsimple.com",
        "Serial": 1491230021,
        "Refresh": 86400,
        "Retry": 7200,
        "Expire": 604800,
        "Minimum": 300
      }
    }
  ],
  "Authority": [],
  "Additional": []
}
```

I tried configuring a bind9 server the same, and then I got all the records.

**Comment by ShreyasZare** [comment]
Thats a strange response for AXFR.

> I tried configuring a bind9 server the same, and then I got all the records.

I did not get this. Were you able to resolve it? or it worked with bind9?

**Comment by itssimple** [comment]
Yeah it worked with the bind9 server, and also with the Windows Server DNS service as well.

**Comment by ShreyasZare** [comment]
It seems that the primary server is not responding correctly. Do try to use any other tool to perform a zone transfer just to confirm if that's the case.

**Comment by itssimple** [comment]
Will do, thanks!
