### ISSUE TITLE
Failover app .how to setup  or  how to use ?　

### ISSUE THREAD

**Issue by w796933** [TechnitiumSoftware/DnsServer#267]
sir . Failover app .how to setup  or  how to use ?   is have example ?

**Comment by ShreyasZare** [comment]
Thanks for asking. There are 2 parts to configure failover for a domain in your primary zone:

1. Edit the Failover App's config from the Config option in the GUI. Here there are 4 health check examples defined. For ping/tcp type checks you can reuse them. For HTTP type health check you need to edit the existing www.example.com health check or create another block in the healthChecks array. You can also configure email alert name in the health check and then edit the email alert block below to point to your email server.

2. Once you have the app config done, you can now use it for your domain. Just edit the primary zone and add a new APP type record. While adding the APP record, select Failover app and select Failover.Address (if you want to return IP addresses) or Failover.CNAME (if you want to return CNAME) as the class path. You will get a json template in the Record Data box below where you can edit and fill up the IP address / domain name for your servers. Use the name of the health check in there to bind the APP record to the health check and add the record to complete the config.

Once you have done the config as above, the DNS server will start monitoring health for the server specified in the APP record when the APP record is first hit. 

If you set `allowTxtStatus` to `true` in the APP record data json, then you can just query the APP record domain name with type TXT and get a health check report in the DNS response in form of TXT records.

Do give it a try and let me know if you were able to make it work. If not then let me know your scenario here and I will try to give you a proper config to use.

**Comment by w796933** [comment]
install failover app   no see   app record  .  
systemctl restart dns.service  can use it .

**Comment by w796933** [comment]
if  i   enabled   failover app .  how to  use  master  and slave  dns ?

**Comment by ShreyasZare** [comment]
> 
> 
> if i enabled failover app . how to use master and slave dns ?

If you add an APP record in your primary zone then they get synced automatically to your secondary zone. You have to make sure that the secondary DNS server also has the Failover app installed.

Please let me know what is your scenario so that I can guide you better.

**Comment by w796933** [comment]
okay .  so thanks . 
how to  setup  primary zone and   secondary  zone ?

**Comment by ShreyasZare** [comment]
> 
> 
> okay . so thanks .
> how to setup primary zone and secondary zone ?

I don't think Failover app is what you are looking for. I can help only when I can understand what you are trying to do.

**Comment by w796933** [comment]
I need to set up an authoritative dns to improve resolution for my domain name, which can detect downtime, failover, one master dns  server  and one slave dns server .   master  zone  auto syn to  slave

**Comment by ShreyasZare** [comment]
> 
> 
> I need to set up an authoritative dns to improve resolution for my domain name, which can detect downtime, failover, one master dns server and one slave dns server . master zone auto syn to slave

Alright. For setting up live servers, you will need 2 servers with static IP addresses one for your primary and for secondary. The domain name registrar that you are using must support child name servers.

Lets say your domain name is example.com then lets assume that ns1.example.com is your primary name server and ns2.example.com is your secondary name server. You login to your domain registrar's web panel and in the options find child name servers and enter your primary name server domain name (ns1.example.com) and the IP address of your primary server. Add another entry for your secondary name server (ns2.example.com) and the IP address of your secondary server. Once done, find the option to change name server for your domain and remove the existing name servers and add ns1.example.com and ns2.example.com in there.

The above change will take some time to take effect and this will start pointing your domain name to your primary and secondary name servers on the given IP addresses.

Now, on the primary name server, login to the DNS web console, go to Zones, click Add Zone, and add your domain name example.com as primary zone. Once created, remove any default NS record and add two NS records for ns1.example.com and ns2.example.com. Create all your other records here. You can now create the APP record, select Failover app and the class path, edit the json to point to your web server as primary and the back web server as the secondary. Set `healthCheck` to `tcp80` and set `allowTxtStatus` to `true` to allow checking health status by querying for TXT record.

Now, on secondary name server, login to the DNS web console, go to Zones, click Add Zone, and add your domain name example.com as secondary zone. Once the secondary zone is created, it will automatically sync and load all records. Just make sure that you have the Failover app installed on the secondary name server too to allow the APP record to work.

When your domain name is first queried, the DNS server will start checking for health of the primary web server and when your primary web server fails to respond, the address/domain of the secondary web server is returned. If you configure email alerts in the Failover app config then you will get email for any failure detection.

I hope this helps with your setup.

**Comment by w796933** [comment]
Thank you for your patient answer. COVID-19, take care  ，nice every  day . Healthy body .love

**Comment by ShreyasZare** [comment]
> 
> 
> Thank you for your patient answer. COVID-19, take care ，nice every day . Healthy body .love

You're welcome. Take care.

**Comment by w796933** [comment]
Add the  master zone  , automatically add to the slave area, no need to log in to the slave node  web console  .

**Comment by ShreyasZare** [comment]
> 
> 
> Add the master zone , automatically add to the slave area, no need to log in to the slave node web console .

This will be done with the clustering feature that is planned.

**Comment by w796933** [comment]
okay . nice . so good .

**Comment by w796933** [comment]
Failover    url  , is check   url  200 code ?  is not 200 code ,will  Failover ?

**Comment by ShreyasZare** [comment]
> Failover url , is check url 200 code ? is not 200 code ,will Failover ?

Yes. If the http code returned is in 200-299 range then its considered a positive response. Any code other than that will be considered as a failure.
