### ISSUE TITLE
[0.0.0.0:68] System.IO.EndOfStreamException: Attempted to read past the end of the stream

### ISSUE THREAD

**Issue by lfarrand** [TechnitiumSoftware/DnsServer#268]
Hi,

I've been seeing a lot of these errors in the logs recently:

```
[2021-06-08 19:51:57 UTC] [0.0.0.0:68] System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at TechnitiumLibrary.IO.StreamExtension.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.IO\StreamExtension.cs:line 37
   at TechnitiumLibrary.Net.Dns.DnsDatagram.DeserializeDomainName(Stream s, Int32 maxDepth) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary.Net\Dns\DnsDatagram.cs:line 518
   at DnsServerCore.Dhcp.Options.ClientFullyQualifiedDomainNameOption.ParseOptionValue(Stream s) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\Options\ClientFullyQualifiedDomainNameOption.cs:line 94
   at DnsServerCore.Dhcp.DhcpOption.ParseOptionValue() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpOption.cs:line 251
   at DnsServerCore.Dhcp.DhcpMessage..ctor(Stream s) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpMessage.cs:line 269
   at DnsServerCore.Dhcp.DhcpServer.ReadUdpRequestAsync(Socket udpListener) in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dhcp\DhcpServer.cs:line 191
```

Any idea what could be causing it?

Another issue I've got is that my HP Color LaserJet Pro M453DW printer cannot acquire an IP address dynamically. If I set a static IP then all is well and it works fine. It might be related to the error above. This thread describes a similar issue that someone was having with their HP printer not acquiring an IP address via DHCP: **https://www.linuxquestions.org/questions/linux-networking-3/network-printer-cannot-acquire-a-lease-through-dhcp-4175545626/**

**Comment by ShreyasZare** [comment]
Thanks for the feedback. It seems that the DHCP request is not getting parsed for some reason. 

If possible run `tcpdump -i any -w dump.pcap` and then connect your printer to the network. Once the error comes, press stop the tcpdump by ctrl-c and just send the `dump.pcap` file over here or by email. This will help in understanding the issue and fixing it quickly.

**Comment by lfarrand** [comment]
Thanks for the info about tcpdump. I ran it on the machine running Technitium and then set the printer to DHCP. The log again contained an error about reading past the end of stream, so I'm pretty certain that the error relates to the printer DHCP request.

I've attached the dump file.
[dump.zip](https://github.com/TechnitiumSoftware/DnsServer/files/6621944/dump.zip)

**Comment by lfarrand** [comment]
I was running it on the machine running the DNS server. I'll try it again, and this time I'll renew the DHCP lease on my desktop as well as the printer to see if it captures any DHCP packets. I'll open it in Wireshark to check first before sending it over.

**Comment by lfarrand** [comment]
It turns out that I was running it on my other Technitium instance by mistake. I have two DNS servers running - one virtualized and another running on a dedicated host. Only one of them has the DHCP server enabled.

I've run tcpdump again on the right host, and I see there are DHCP messages contained in it using Wireshark. The HP discover request is the 3rd item in the list after you filter for 'dhcp'. The message contains this identifier: Client MAC address: HP_c9:9a:99 (30:24:a9:c9:9a:99)

[dump.zip](https://github.com/TechnitiumSoftware/DnsServer/files/6630015/dump.zip)

**Comment by ShreyasZare** [comment]
Thanks for the dump. It looks like a bug in HP DHCP client. They are setting flag to use canonical wire format (binary encoding) and then missing a 1 byte null character at the end of the name of the printer which is causing the DHCP parser to hit end of data when its expecting 1 byte there. 

I could be that other DHCP server already have this fix since it may be a common issue.

Will try to update the code to make it work around this issue. Fix should be available in next update.

![image](https://user-images.githubusercontent.com/10008172/121529959-8c7e9b00-ca1a-11eb-8a94-34cff4133197.png)

**Comment by lfarrand** [comment]
Hah, trust HP to make a mistake like this and then not correct it for (presumably) a long time! It's annoying to have to work around a problem like this. The best solution would be to fix the root cause, but I know there are too many hurdles to jump over trying to get a large organization like HP to make a change in a reasonable timeframe.

Thanks for looking into it and hopefully we will have a workaround for it in the next release.

**Comment by ShreyasZare** [comment]
Keeping this issue open so that I wont forget to notify here when the fix is available with next update.

**Comment by ShreyasZare** [comment]
New update v6.4 is now available which fixes this issue.
