### ISSUE TITLE
Feature Request: Human Readable configuration files

### ISSUE THREAD

**Issue by AshleyJackson** [TechnitiumSoftware/DnsServer#269]
Hi @ShreyasZare 

Has there been any thought into implementing Human Readable Configuration files?

e.g. As a Json file for the config files (dns.config, log.config, etc..)

Please let me know if you have any thoughts around this.

Thanks.

**Comment by ShreyasZare** [comment]
Thanks for asking. All config formats used are binary as its easier to read/write the config in code since most of the components that have been built do their own binary serialization.

For any update it is recommended to use the HTTP API as the server state is updated immediately and the server does not need to be restarted for any reason.

**Comment by dawbs** [comment]
I'd absolutely love this too, but if it's a definite no, could I maybe ask you to consider some kind of basic CLI wrapper for the API? for casual admin when I've botched hostnames or something it's a pain to have to script something up for one-offs - even just the basics of hostname, listen address/ports to get a system going again

**Comment by ShreyasZare** [comment]
> I'd absolutely love this too, but if it's a definite no, could I maybe ask you to consider some kind of basic CLI wrapper for the API? for casual admin when I've botched hostnames or something it's a pain to have to script something up for one-offs - even just the basics of hostname, listen address/ports to get a system going again

Thanks for the feedback. I will think on some option to help with the web service address/port issue. May be some cli option for the dns server itself can help.

For using the API, you can just use curl on the cli or even a web browser if you can access the web service. The API is actually easier to use than it seems at first.
