### ISSUE TITLE
Record Data Template

### ISSUE THREAD

**Issue by w796933** [TechnitiumSoftware/DnsServer#273]
{
  "primary": [
    "1.1.1.1",
    "::1"
  ],
  "secondary": [
    "2.2.2.2",
    "::2"
  ],
  "healthCheck": "tcp80",
  "allowTxtStatus": false
}

 "::1"    "::2"    What do you mean?

**Comment by ShreyasZare** [comment]
Thanks for asking. These are IPv6 address examples. You can use both IPv4
and IPv6 addresses together as required.

**Comment by w796933** [comment]
how to use  "allowTxtStatus": true ?　　dig -a test   app.example.com ?

**Comment by ShreyasZare** [comment]
When you have this option set to true, you can query the record with type
set to TXT and will receive TXT records that tell you the health status for
the configured IP addresses.

This is one quick way to check the health status for the APP record.

Shreyas Zare
Technitium

**Comment by w796933** [comment]
i set "allowTxtStatus": true  . but    dig  -t txt  @server IP    failvover.xx.com  .  No response response txt record

**Comment by ShreyasZare** [comment]
> 
> 
> i set "allowTxtStatus": true . but dig -t txt @server IP failvover.xx.com . No response response txt record

I would recommend that you try this query using the DNS Client tab available in the DNS web console. This built-in tool will help you with debugging issues better. 

If this doesn't work then do send screenshots of your zone with the APP record so that I can understand your config better.

**Comment by w796933** [comment]
![image](https://user-images.githubusercontent.com/4869179/124477410-935cbb80-ddd6-11eb-9ebc-6084f209cf8b.png)

dig -t txt @dnsip   xiang.openresty.xyz No response response txt record


![image](https://user-images.githubusercontent.com/4869179/124477572-bd15e280-ddd6-11eb-9f63-7921dde0b939.png)
![image](https://user-images.githubusercontent.com/4869179/124477608-c8690e00-ddd6-11eb-8e50-a8546c91ebbd.png)

**Comment by ShreyasZare** [comment]
Please find the response inline:

> 
> ![image](https://user-images.githubusercontent.com/4869179/124477410-935cbb80-ddd6-11eb-9ebc-6084f209cf8b.png)

The secondary IP address format is invalid since comma is used as separator. This will cause error while doing the health check.

> ![image](https://user-images.githubusercontent.com/4869179/124477572-bd15e280-ddd6-11eb-9f63-7921dde0b939.png)

Set the Type to TXT and see what response you get.

**Comment by w796933** [comment]
If both the main and standby 80 are closed, no record will be responded to.

**Comment by ShreyasZare** [comment]
> 
> 
> If both the main and standby 80 are closed, no record will be responded to.

Yes, that's why its required to add more IP addresses as "secondary". When none of the IP addresses are healthy then the DNS response will be empty for A type request.

**Comment by w796933** [comment]
when i  add  domain .  how to auto add  ns  record ?
example  :      i  add  test.com    will  be  auto  add  ns1.xx.com  ns2.xx.com .

**Comment by ShreyasZare** [comment]
> 
> when i add domain . how to auto add ns record ?
> example : i add test.com will be auto add ns1.xx.com ns2.xx.com .

If you set the NS domain name as the DNS Server Domain in settings then the NS record and SOA record that gets created will have that domain.

There is a planned feature to have a clustering option when you run multiple DNS servers. So, this feature will auto add all NS records per server in the cluster.

For now, if you have multiple name servers, you have to add the NS records manually.
