### ISSUE TITLE
Customize the line, modify the IP network address library IP  ?

### ISSUE THREAD

**Issue by w796933** [TechnitiumSoftware/DnsServer#276]
{
  "public": [
    "1.1.1.1", 
    "2.2.2.2"
  ],
  "private": [
    "192.168.1.1", 
    "::1"
  ]
}

Customize the line, modify the IP network address library IP  ?

**Comment by ShreyasZare** [comment]
Thanks for the post. Do you mean to have option to define a custom network? If its so then this is already planned feature. Will try to get it added soon by the weekend.

**Comment by w796933** [comment]
Yes, that's it. That's great.

**Comment by ShreyasZare** [comment]
I have pushed an update for the DNS App. Do update and let me know if that works for you.
