### ISSUE TITLE
Split Horizon this app have bug . 

### ISSUE THREAD

**Issue by w796933** [TechnitiumSoftware/DnsServer#278]
Error! Could not load file or assembly 'DnsApplicationCommon, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

sir  Split Horizon this app have bug .  .

**Comment by ShreyasZare** [comment]
Thanks for reporting the error. Please try again and see if its working now.

**Comment by w796933** [comment]
now .is okay . so thanks .
