### ISSUE TITLE
How can we set a QPM (query per minute) per IP limit?

### ISSUE THREAD

**Issue by norandom** [TechnitiumSoftware/DnsServer#281]
Hi,

I just updated and saw the changelog. How do I set a QPM limit per IP?
Don't see it in the Settings.

Best,
Marius

**Comment by ShreyasZare** [comment]
Thanks for asking. The QPM limit option is in the Settings tab itself. 

Settings UI is a bit cluttered now due to too many options so it is difficult to find thing. I have planned to update the UI to make it easier in the next update.

**Comment by norandom** [comment]
You are right. I was blind. Thank you!
