### ISSUE TITLE
Still able to do DNS lookups even though Recursion is disabled

### ISSUE THREAD

**Issue by AshleyJackson** [TechnitiumSoftware/DnsServer#282]
I've recently built two servers as authorative servers and on both I have disabled recursion.

![image](https://user-images.githubusercontent.com/12793989/128318682-2aa4cb2b-3af8-4b05-913f-298ed9c7bac2.png)

Even with this disabled, I am still able to do lookups to google.com, facebook.com, etc..

Is there an additional setting that needs to be enabled? Or is something just broken?

Thanks.

**Comment by ShreyasZare** [comment]
Thanks for the post. Do you have any kind of conditional forwarder or stub zone configured? Such zones will bypass the recursion setting. 

Another thing, just check the logs once and confirm if the DNS server is able to bind on UDP and TCP port 53. A lot of times its usually a case that there is another DNS stub resolver running on the port which is actually responding to these queries.

I would also recommend that you test this out with the DNS Client tab this will give you most accurate results than using any other command line tool.

**Comment by AshleyJackson** [comment]
Sorted.

Thanks mate.
