### ISSUE TITLE
"No such name" response for www.uber.com

### ISSUE THREAD

**Issue by cassiorenan** [TechnitiumSoftware/DnsServer#284]
Hello team,

I've ran into an issue with the current version (6.3 - although I'm not sure if it's specific to this version) - It doesn't seem to be able to resolve the domain `uber.com` properly. I have not seen this behavior on any other domain, and clearing the cache doesn't seem to help.

My server has mostly default settings. More importantly, I don't have any forwarders set up, so I'm using the default builtin ones, as far as I know.

When looking at a packet capture in wireshark, I'm seeing a "No such name" reply code (3). Here's a [pcap file showing what the query looks like](https://drive.google.com/file/d/1PQanpf24lq8ptfoa1TXiEKNPgvha7JEM/view?usp=sharing).

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I checked with the domain "www.uber.com" and their own authoritative servers are responding with NXDOMAIN response code which is why the DNS server is also responding with same error. So looks like some misconfiguration with their own DNS servers.

I tested with all 4 of their name servers: edns126.ultradns.com, edns126.ultradns.net, edns126.ultradns.biz, and edns126.ultradns.org

This is the response that all these name servers are responding with:
```
{
  "Metadata": {
    "NameServer": "edns126.ultradns.com:53 (204.74.66.126:53)",
    "Protocol": "Udp",
    "DatagramSize": "213 bytes",
    "RoundTripTime": "14.2 ms"
  },
  "Identifier": 40797,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": false,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NxDomain",
  "QDCOUNT": 1,
  "ANCOUNT": 3,
  "NSCOUNT": 1,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "www.uber.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "www.uber.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "300 (5 mins)",
      "RDLENGTH": "16 bytes",
      "RDATA": {
        "Domain": "frontends-all.uber.com"
      }
    },
    {
      "Name": "frontends-all.uber.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "300 (5 mins)",
      "RDLENGTH": "18 bytes",
      "RDATA": {
        "Domain": "frontends-cloud.uber.com"
      }
    },
    {
      "Name": "frontends-cloud.uber.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "300 (5 mins)",
      "RDLENGTH": "13 bytes",
      "RDATA": {
        "Domain": "cn-ecg.cfe.uber.com"
      }
    }
  ],
  "Authority": [
    {
      "Name": "uber.com",
      "Type": "SOA",
      "Class": "IN",
      "TTL": "900 (15 mins)",
      "RDLENGTH": "58 bytes",
      "RDATA": {
        "PrimaryNameServer": "edns126.ultradns.com",
        "ResponsiblePerson": "serviceproviders.uber.com",
        "Serial": 2019057840,
        "Refresh": 3600,
        "Retry": 180,
        "Expire": 604800,
        "Minimum": 900
      }
    }
  ],
  "Additional": []
}
```

However, querying "uber.com" works well and the servers give correct answer.

I am not sure how the domain is getting resolved by other public DNS servers. But querying for the last CNAME in that first response again gives the answer as shown below: 

```
{
  "Metadata": {
    "NameServer": "edns126.ultradns.com:53 (204.74.66.126:53)",
    "Protocol": "Udp",
    "DatagramSize": "186 bytes",
    "RoundTripTime": "23.09 ms"
  },
  "Identifier": 47570,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": false,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 1,
  "NSCOUNT": 4,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "cn-ecg.cfe.uber.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "cn-ecg.cfe.uber.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "300 (5 mins)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "34.98.127.226"
      }
    }
  ],
  "Authority": [
    {
      "Name": "cfe.uber.com",
      "Type": "NS",
      "Class": "IN",
      "TTL": "86400 (1 day)",
      "RDLENGTH": "22 bytes",
      "RDATA": {
        "NameServer": "edns126.ultradns.org"
      }
    },
    {
      "Name": "cfe.uber.com",
      "Type": "NS",
      "Class": "IN",
      "TTL": "86400 (1 day)",
      "RDLENGTH": "19 bytes",
      "RDATA": {
        "NameServer": "edns126.ultradns.com"
      }
    },
    {
      "Name": "cfe.uber.com",
      "Type": "NS",
      "Class": "IN",
      "TTL": "86400 (1 day)",
      "RDLENGTH": "22 bytes",
      "RDATA": {
        "NameServer": "edns126.ultradns.net"
      }
    },
    {
      "Name": "cfe.uber.com",
      "Type": "NS",
      "Class": "IN",
      "TTL": "86400 (1 day)",
      "RDLENGTH": "22 bytes",
      "RDATA": {
        "NameServer": "edns126.ultradns.biz"
      }
    }
  ],
  "Additional": []
}
```

So, for now you can fix this by creating a conditional forwarder zone for "uber.com" and point it towards any public resolver.

**Comment by cassiorenan** [comment]
Got it! I thought it was some kind of bug, as I could resolve it anywhere but in my local DNS.

Thank you very much for the help, sir!

**Comment by ShreyasZare** [comment]
It seems most of the DNS servers out there are trying again for that last CNAME and are thus able to respond to the query correctly.

I have updated the code to make a retry so that the domain resolves as expected. This will be available in the next update which is scheduled for release on next weekend.

**Comment by ShreyasZare** [comment]
New update v6.4 is now available which fixes this issue.

**Comment by edfries-wy** [comment]
I'm seeing NXDomain for ubereats.com and uber.com in v8.02, but only when the web page attempts to load.  Nslookup resolves correctly using Technitium but the webpage fails to load with NXDOMAIN.  

Both domains resolve correctly using either the pfsense resolver or google's DNS resolvers.   

I've worked around it with conditional forwarder zones so this is just a heads up and in case it helps someone else.

Thank you.

**Comment by ShreyasZare** [comment]
> I'm seeing NXDomain for ubereats.com and uber.com in v8.02, but only when the web page attempts to load. Nslookup resolves correctly using Technitium but the webpage fails to load with NXDOMAIN.
> 
> Both domains resolve correctly & web page loads using either the pfsense resolver or google's DNS resolvers.
> 
> I've worked around it with conditional forwarder zones so this is just a heads up and in case it helps someone else.
> 
> Thank you.

Thanks for the feedback. I tested on the v8.0.2 and its working as expected. Both the domain names with and without "www" are working. Do test the domain names from the DNS Client tab on the DNS web console to confirm. You can also check Cache to see the records for the domains. Let me know if you find anything.
