### ISSUE TITLE
Bug: Refreshing the page forces user back to Login Screen

### ISSUE THREAD

**Issue by AshleyJackson** [TechnitiumSoftware/DnsServer#285]
There is a bug where when you refresh the page, it will always force you back to the login screen, even if you are already logged in.

Can this please be fixed?

Thanks

**Comment by ShreyasZare** [comment]
Thanks for the post. This is not a bug but a feature! The web panel does not use cookies and instead uses a session token which is lost once web page navigates away.

The web app is designed as a single page app where you do not need to refresh the web page. In most tabs on the page, when you click on the tab, the data is refreshed. In places like Cache tab, you will find a "refresh" link to refresh the data. The dashboard also refreshes automatically every 60 sec for last hour view or when you click on the Dashboard tab once again. So you don't have to refresh the entire web page.
