### ISSUE TITLE
Feature request: Dashboard info for connection types

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#287]
It would be useful to see what percentage of my connections are UDP/TCP and DNS/TLS/DOH/HTTPS/JSON.  A breakdown in the statistics would be ideal.

**Comment by ShreyasZare** [comment]
Thanks for the post. Are you looking for inbound connections or the outbound connections?

**Comment by shawnkhall** [comment]
Inbound - just a reflection of what's in the detailed log.

**Comment by ShreyasZare** [comment]
Thanks will try to add that.

**Comment by drksbr** [comment]
UP

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that adds transport protocol type chart on dashboard. Do update and let me know your feedback.
