### ISSUE TITLE
Logs for secondary root zone has empty name

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#289]
```
[2021-08-10 09:26:11 UTC] DNS Server successfully checked for update to '' secondary zone from: a.root-servers.net:53 (192.203.230.10:53)
[2021-08-10 09:26:12 UTC] Saved zone file for domain: 
```

After following [your guide on setting up the root zone to speed up recursive lookups](https://blog.technitium.com/2021/07/running-root-server-locally-on-your-dns.html), I saw these in the logs. The name is empty, presumably because you truncate the last "." on the FQDN, leading to a blank name.

It looks odd, so maybe it shouldn't be truncated in the logs? :)

**Comment by ShreyasZare** [comment]
Thanks for the post. FQDN is used only in the UI part of most DNS software while in the protocol itself it is a blank string for root zone which is why the logs is showing a blank string. Will get the logging part updated to show it explicitly to avoid any confusion.

**Comment by ShreyasZare** [comment]
New update v6.4 is now available which fixes this issue.
