### ISSUE TITLE
Dashboard after upgrade to 6.4

### ISSUE THREAD

**Issue by Hemsby** [TechnitiumSoftware/DnsServer#293]
![Dashboard](https://user-images.githubusercontent.com/36005402/129526484-b2f8dc80-4a2b-47ff-8049-63e5524102e4.jpg)

The dashboard has always shown correct number of clients but after upgrade its now showing incorrect on both my DNS Servers.
Usuall users on each is 20, but since upgrade its showing over 300 which is impossible as these are internally available only.

**Comment by ShreyasZare** [comment]
Thanks for the post. I too have observed this today. Will get this fixed by the weekend.

**Comment by ShreyasZare** [comment]
Update v6.4.1 is released which fixes this issue.
