### ISSUE TITLE
Is it possible to skip login for the web service?

### ISSUE THREAD

**Issue by Shuenhoy** [TechnitiumSoftware/DnsServer#294]
I have set up a [Authelia](https://github.com/authelia/authelia) service as an SSO auth middleware with my reverse proxy. Is it possible to skip login for the technitium DNS server web service, so that two login screens could be avoided? Thanks.

**Comment by ShreyasZare** [comment]
Thanks for the post. There is no option to do that since the DNS api depends on it. You may set the password to default "admin" which will make the web app perform auto login and prompt for password change which you can just ignore.

**Comment by Shuenhoy** [comment]
Thanks for your reply @ShreyasZare. I then decided to hack on the `www/js/main.js` file and remove the prompt for password change. Now I make it what I want :)

**Comment by ShreyasZare** [comment]
> 
> 
> Thanks for your reply @ShreyasZare. I then decided to hack on the `www/js/main.js` file and remove the prompt for password change. Now I make it what I want :)

Ya that's one good option to do!
