### ISSUE TITLE
Feature Request: Parse adblock-compatible lists

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#295]
For now I'm creating two files for some block and allow lists, and I'd like to remove duplication wherever possible.

I know it's not possible to implement the vast majority of features within the [adblock-syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax) since most are not possible via DNS, but it would be great if the block list and allow list parser obeyed the following behaviors when parsing an adblock-compatible list:

Where line like "example.com*" BLOCK "example.com"
Where line like "example.com^$all" BLOCK "example.com"
Where line like "example.com^/path" IGNORE record
Where line like "example.com^$anythingelse" IGNORE record
Where line like "||example.com^$all" BLOCK "example.com"
Where line like "||example.com^$document" BLOCK "example.com"
Where line like "||example.com^" BLOCK "example.com"
Where line like "||example.com^/path" IGNORE record
Where line like "||example.com^$anythingelse" IGNORE record
Where line like "@@||example.com" ALLOW "example.com"
Where line like "@@||example.com:nnn" ALLOW "example.com"
Where line like "@@||example.com^" ALLOW "example.com"
Where line like "@@||example.com:nnn^" ALLOW "example.com"
Where line like "@@||example.com^$document" ALLOW "example.com"
Where line like "@@||example.com:nnn^$document" ALLOW "example.com"
Where line like "@@||example.com^/path" ALLOW "example.com"

**Comment by ShreyasZare** [comment]
Thanks for the post. I will study this when work for regex feature will be planned.

**Comment by ShreyasZare** [comment]
@shawnkhall can you provide a URL for such a block list file or a sample file?

**Comment by shawnkhall** [comment]
Any of the lists [from here](https://github.com/uBlockOrigin/uAssets/tree/master/filters) are good examples of "real world" filter lists. Most entries are either documentation or include more than simply the domain name, so are invalid for this purpose.

The [syntax](https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md)* [can be](https://adblockplus.org/filter-cheatsheet)* [obtuse](https://help.eyeo.com/en/adblockplus/how-to-write-filters)*, but again it's only important to parse for those records that meet very limited criteria: full-domain blocking. If it's not a full-domain block then adding it to the blocklist in TDNS is going to cause problems.

Really, the simplest matching RegEx rules could be as simple as:

Add capture to blocklist:
   `^(?:\|\|)?([\w\.]+\.\w+)(?:\:\d+)?(?:\*|\^|\^\$all|\^\$doc(?:ument))?$`
Note the hard stop `$` on the end. If there's more text then it's not a domain-only match.

Add capture to allowlist:
   `^@@(?:\|\|)?([\w\.]+\.\w+)(?:$|\W)`
Since the allowlist needs to be more tolerant, there's no hard stop and any domain on a line starting with `@@` should match.

These should both only capture the domain name, so it should be pretty clean. These do not play well with certain AdBlock Syntax features, notably the ["badfilter" exclusion](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter).

**Comment by ShreyasZare** [comment]
Thanks for all these pointers. I have implemented a regex blocking feature already, just need to be able to parse a proper block list file and test it.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with a new Advanced Blocking DNS App that supports loading adblock format lists. Do update and let me know if any changes are needed. Closing this issue for now.

**Comment by shawnkhall** [comment]
> Hello! I have an issue. When using this list https://abp.oisd.nl/ in adblock list. It doesn't block a lot of queries most of them get through so it looks like advanced blocking app is still letting through a lot of rules. Can you please take a look?

I suspect you're doing it wrong. This feature relies on proper configuration of the adblockListUrls record in the Advanced Blocking App. Here's a sample configuration that works for this blocklist:

```
{
  "enableBlocking": true,
  "blockListUrlUpdateIntervalHours": 24,
  "networkGroupMap": {
    "0.0.0.0/0": "everyone"
  },
  "groups": [
    {
      "name": "everyone",
      "enableBlocking": true,
      "allowTxtBlockingReport": true,
      "blockAsNxDomain": false,
      "blockingAddresses": [
        "0.0.0.0",
        "::"
      ],
      "allowed": [],
      "blocked": [],
      "allowListUrls": [],
      "blockListUrls": [],
      "allowedRegex": [],
      "blockedRegex": [],
      "regexAllowListUrls": [],
      "regexBlockListUrls": [],
      "adblockListUrls": [ 
        "https://abp.oisd.nl/"
      ]
}
```

You can see whether it's been parsed correctly by reviewing the log file for something like this:
```
[2022-07-02 15:46:50 Local] DNS App [Advanced Blocking]: Advanced Blocking app is reading adblock list from: https://abp.oisd.nl/
[2022-07-02 15:46:51 Local] DNS App [Advanced Blocking]: Advanced Blocking app read adblock list file (389126 domains) from: https://abp.oisd.nl/
```

If you're using this record correctly already then please post your Advanced Blocking configuration and the domains you're testing with.

**Comment by ShreyasZare** [comment]
> Hello! I have an issue. When using this list https://abp.oisd.nl/ in adblock list. It doesn't block a lot of queries most of them get through so it looks like advanced blocking app is still letting through a lot of rules. Can you please take a look?

As @shawnkhall mentioned, do share your config. 

I would also recommend that you test domain names that should be blocked using the DNS Client tab on the DNS web console. Query with type set to TXT to know which block list is blocking that domain name. This will give you better info on it.
