### ISSUE TITLE
isp's network. I need to add a lot. How to set it up?

### ISSUE THREAD

**Issue by w796933** [TechnitiumSoftware/DnsServer#297]
App Name: Split Horizon
Class Path: SplitHorizon.SimpleAddress
Record Data:
{
  "public": [
    "1.1.1.1", 
    "2.2.2.2"
  ],
  "private": [
    "192.168.1.1", 
    "::1"
  ],
  "10.0.0.0/8": [
    "10.1.1.1"
  ]
}

10.0.0.0/8   isp's network. I need to add a lot. How to set it up?

**Comment by ShreyasZare** [comment]
Thanks for asking. The JSON in there is just a template to give a basic idea about the config. You can edit the "10.0.0.0/8" network address or add multiple networks similarly in that JSON as per the number of networks you have.

Lets say you need to add "192.168.10.0/24" network then just add another json property:
```
"192.168.10.0/24": [
    "192.168.10.5"
]
```

**Comment by w796933** [comment]
if isp have  many  network . how to setup .  
Many network addresses. 
example  ipset .

**Comment by ShreyasZare** [comment]
Please let me know what is the exact scenario that you want to achieve so that I can understand it better.
