### ISSUE TITLE
DNS client import issue

### ISSUE THREAD

**Issue by avber** [TechnitiumSoftware/DnsServer#3]
I'm trying to import domain.com.

A domain.com zone is created with 2 records: SOA and A.

Then I'm trying to import www.domain.com (a CNAME record)

domain.com zone is not updated.

Expected result: domain.com zone should contain 3 records.

**Comment by ShreyasZare** [comment]
Hi,

Thanks for the feedback. This is how it was intended to work. The DNS Client Import option will create new zone for the domain in query to import. If zone exists then new records overwrite existing records.

So, in your case, when you import www.domain.com, then a new zone for the same is created without changing domain.com zone.

This can be improved for sure. I will try to add an option to the import feature to specify destination zone which will make it more usable. This may get added in next release.

Regards,
Shreyas Zare

**Comment by ShreyasZare** [comment]
I did multiple tests with import and its working correctly. You need to first import the parent domain and then import the sub domain. Sub domain entries get added to the parent domain correctly.
