### ISSUE TITLE
zone/scope definition/data split

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#304]
It might be wise to split out the zone/scope definitions from the zone/scope data instead of having both the definition and data reside within the same file. Having them both in the same file makes it impossible to copy the definitions between servers without also copying the data. Thoughts?

**Comment by ShreyasZare** [comment]
Thanks for asking. If you are looking at copying these files to another installation for creating a cluster setup then you don't have to invest a lot of time to build it since there is a plan to add clustering support for the DNS server.

**Comment by ShreyasZare** [comment]
Closing this issue since its not feasible to implement.
