### ISSUE TITLE
Fast

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#305]
I used namebench to benchmark your DNS server. 

Congratulations! Yours is the fastest. Well done.

Disclaimer: According to namebench. In my specific setup. YMMV. See attachment for results.

[namebench.pdf](https://github.com/TechnitiumSoftware/DnsServer/files/7102651/namebench.pdf)

**Comment by ShreyasZare** [comment]
Thanks! That looks nice. One thing could be that your windows DNS server has DNSSEC validation enabled so its probably taking too long to respond.
