### ISSUE TITLE
Feature Request - Promote seconday zone to primary

### ISSUE THREAD

**Issue by blaxer** [TechnitiumSoftware/DnsServer#306]
It is a trick I use more times than I would care to admit but when changing to a new DNS server I will do a zone transfer to the new server as a secondary zone then promote it to primary then decom the original servers. I'm sure I could do this by editing the config files in Technitium but would be nice to have the option in the GUI.

**Comment by ShreyasZare** [comment]
Thanks for the request. There is even better option to do that with
Technitium DNS server.

Just use the built-in DNS client tab, enter the primary name server as the
server, enter the domain name, select type as AXFR, and hit import. The
primary zone will be created with all records.

Shreyas Zare
Technitium

**Comment by blaxer** [comment]
Wow that was easy and worked perfectly thank you! Quick question though, what format are the zone files in?

**Comment by ShreyasZare** [comment]
The zone files are in binary format. All records are serialized in wire format in the file.

**Comment by ShreyasZare** [comment]
Closing this issue since there is a workaround available.
