### ISSUE TITLE
[Bug] Invisible/empty host

### ISSUE THREAD

**Issue by thepra** [TechnitiumSoftware/DnsServer#311]
Like in the screenshot, there's this unknown hostname that made 24 calls without knowing what it is:
![immagine](https://user-images.githubusercontent.com/7032509/133560837-256505a4-ee10-4ee0-ad27-30641365f958.png)

What could be that prevents the catch of the hostname?

**Comment by ShreyasZare** [comment]
Thanks for the post. The empty domain listed as top most queried domain name with 24 hits is the root domain. That is, some client is querying with QNAME as the `<root>` which is an empty string internally and thus it is coming as a blank entry on the GUI.

Just to avoid confusion, I will update the UI to make it look like `.`

**Comment by ShreyasZare** [comment]
New version 7.0 is now available that fixes this issue.
