### ISSUE TITLE
Can the DNS APP Change the puplic ip

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#312]
Can the DNS APP change the public ip ? and how ?

![123](https://user-images.githubusercontent.com/31727156/133923211-9c645c77-a786-4d5b-8a9e-3341c1606b5a.png)

**Comment by ShreyasZare** [comment]
Thanks for asking. Any kind of DNS server or a public DNS service cannot change your public IP address. You will need to use a VPN provider or Tor Browser to make that happen.
