### ISSUE TITLE
Docker Container Settings Environment Variables

### ISSUE THREAD

**Issue by Cossey** [TechnitiumSoftware/DnsServer#313]
I would like to have Environment Variables for configuring all the settings in the Docker Container. Specifically, when I am provisioning it would be nice to have all the Setting configurations that can be overridden or set via the Environment Variables as well as reading Variables from Files as well (for Docker/Kubernetes secrets).

In my case I normally provision TDNS behind HAProxy on their own Docker Network segments. HAProxy handles certificates and proxying of DNS over HTTP and DNS over TLS, as well as many other services available on the server hosting the docker containers in the cloud. I use compose to deploy all the services required at once and as these are on the open web would like to set some config variables so I don't have to worry about having to quickly log into the web interface, change the password and then configure the server with the settings to get it up and running. This makes it easy to bring up and take down these services without much interaction.

The ones I would like first, if possible are 
* The admin password
* The DNS server domain
* Enable DNS over HTTP
* Forwarders and Forwarder Protocol

It could look something like this:
```
DNS_ADMIN_PASSWORD_FILE="/secrets/dnsadminpass"
DNS_SERVER_DOMAIN="dns.example.org"
DNS_OPTIONAL_DNSOVERHTTP="true"
DNS_FORWARDERS="https://dns.google/dns-query (8.8.8.8),https://dns.google/dns-query (8.8.4.4)"
DNS_FORWARDER_PROTO="https"
```

I use Portainer and using docker-compose makes it easy to shift services to one separated host to another.

**Comment by ShreyasZare** [comment]
Thanks for the request. Such an implementation would read these env vars on first start, that is, when there is no config file present. Once the DNS server runs for the first time, it will use these env vars and create a new config file. On subsequent starts, the env vars wont have any effect and all settings will load from the config file. Does that look ok?

**Comment by Cossey** [comment]
Sounds like a good way to implement and this seems to be what the other containers do. *Typically* its handled in the EntryPoint via a script that builds the config.

Looking at the config file, it seems like its not exactly plaintext, but I'll dive into the source code and see what I can come up with - if you don't mind assigning this to me for the meantime?

**Comment by ShreyasZare** [comment]
> 
> 
> Sounds like a good way to implement and this seems to be what the other containers do. _Typically_ its handled in the EntryPoint via a script that builds the config.
> 
> Looking at the config file, it seems like its not exactly plaintext, but I'll dive into the source code and see what I can come up with - if you don't mind assigning this to me for the meantime?

Ya, the config is binary formatted. I am already working on adding a couple of options in the config so will get this implemented with that.

**Comment by Cossey** [comment]
Excellent, thank you.

**Comment by ShreyasZare** [comment]
Just implemented the above env vars:
- `DNS_SERVER_DOMAIN`
- `DNS_SERVER_ADMIN_PASSWORD_FILE`
- `DNS_SERVER_FORWARDERS`
- `DNS_SERVER_FORWARDER_PROTOCOL`

Not implemented `DNS_OPTIONAL_DNSOVERHTTP` since this option is not required for forwarder configuration and will require additional options to configure the TLS certificate to run the DoH service.

Do let me know if any more variables are required.

**Comment by Cossey** [comment]
Awesome, that's all I need.

Can you please reconsider the DNS over HTTP environment variable? It doesn't need TLS certificates, just some care when enabling. I would like to docker-compose this out with HA Proxy (reverse proxy) but need the DNS over HTTP enabled on deploy too.

**Comment by ShreyasZare** [comment]
> 
> 
> Awesome, that's all I need.
> 
> Can you please reconsider the DNS over HTTP environment variable? It doesn't need TLS certificates, just some care when enabling. I would like to docker-compose this out with HA Proxy (reverse proxy) but need the DNS over HTTP enabled on deploy too.

Ohh, I misread that option as HTTPS. Added that as a boolean option named `DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP`.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with support for the environment variables.

**Comment by gaby** [comment]
@ShreyasZare Can all these new variables be documented somewhere? I can't find them on the website/this repo. Thanks!

**Comment by ShreyasZare** [comment]
> 
> 
> @ShreyasZare Can all these new variables be documented somewhere? I can't find them on the website/this repo. Thanks!

Yes, will get them documented and post a link here.

**Comment by gaby** [comment]
> > @ShreyasZare Can all these new variables be documented somewhere? I can't find them on the website/this repo. Thanks!
> 
> Yes, will get them documented and post a link here.

Thanks, make sure to add a proper table of variables in the README of this repo. That's the best way to go about this.

See example here:  https://github.com/bitnami/bitnami-docker-wordpress#user-and-site-configuration
