### ISSUE TITLE
Feature request: View state of health check for app failover

### ISSUE THREAD

**Issue by tango38317** [TechnitiumSoftware/DnsServer#314]
HI,
maybe is it possible to view the state of the healthchecks from app "failover" in webinterface.

br
Chris

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The DNS apps are generic so there is no UI available on the DNS web panel. There are plans to have some sort of UI that the DNS app itself provides but it will take a while to design and implement it.

For now, the Failover app supports reporting the health state via DNS itself. You can just set `allowTxtStatus` property to `true` for your APP record and then query for the domain with TXT type to get a status report. If its a public domain then you can query from anywhere using nslookup and see the health state.

Another option is to configure email alerts which will send an email alert for any critical event. And if you have any kind of in-house reporting panel that needs the data then its possible to integrate the Failover app to your code using webhooks too. And in any case, all the events are logged to the DNS server logs which are available on the web panel.

**Comment by tango38317** [comment]
Hello @ShreyasZare ,

one further question to DNS Apps:
How long can the list be, or how many can be made in eg split horizon app?
many thanks
Chris

**Comment by ShreyasZare** [comment]
> one further question to DNS Apps: How long can the list be, or how many can be made in eg split horizon app?

There is no specific limit on the number of entries. I have not tested the limits but a few hundred entries should not matter. You can add as many entries in the json config as you want and see the response times by querying multiple times via DNS Client tab to see if there are any delays.
