### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LakeTravisBum** [TechnitiumSoftware/DnsServer#315]
It would be nice to have the queries logged in to a separate log file from the main log file.

**Comment by LakeTravisBum** [comment]
Sorry, found the option, but it would be nice if it could be logged in a separate file.

**Comment by ShreyasZare** [comment]
In the next release, there is a new DNS app that logs queries in sqlite database. There is also an interface to query these logs and filter them by one or more parameters (see screenshot below). So, I guess this should cover your requirements.

![image](https://user-images.githubusercontent.com/10008172/135572349-4e8a8024-06d1-40ab-b923-e2bbf05fffff.png)

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with query logs support that should cover your requirements. Do update and let me know.

**Comment by LakeTravisBum** [comment]
Thank you.  The query log is nice,
