### ISSUE TITLE
7.0 Download

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#316]
===============================
Technitium DNS Server Installer
===============================

Updating .NET 5 Runtime...
.NET 5 Runtime was updated successfully!

Downloading Technitium DNS Server...

Failed to download Technitium DNS Server from: https://download.technitium.com/dns/DnsServerPortable.tar.gz

the proplem because the SSL Certificate 

root@DNS:~# curl -sSL https://download.technitium.com/dns/install.sh | sudo bash
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

please fix the install.sh 

if u use the -k or --insecure the install don't working same 

because the curl inside install.sh 

don't have -k or --insecure to download the file 

sorry for the poor language

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The certificate on that domain is fine and the installer script is working well on all the installations I have done so far on multiple platforms. 

This issue is likely due to Let's Encrypt Root certificate that expired on 30th Sept 2021. If you have not updated your OS running the DNS server then do the update which should add a new root certificate that will make it work correctly.

Let me know here if you were able to fix this.

**Comment by Globulopolis** [comment]
@muhanadali100 see an answer https://superuser.com/a/1679138

**Comment by muhanadali100** [comment]
> 
> 
> Thanks for the feedback. The certificate on that domain is fine and the installer script is working well on all the installations I have done so far on multiple platforms.
> 
> This issue is likely due to Let's Encrypt Root certificate that expired on 30th Sept 2021. If you have not updated your OS running the DNS server then do the update which should add a new root certificate that will make it work correctly.
> 
> Let me know here if you were able to fix this.

i use ubuntu 16.04

i install the system with --insecure and it's installed successfully

**Comment by ShreyasZare** [comment]
> i use ubuntu 16.04
> 
> i install the system with --insecure and it's installed successfully

Thanks for letting us know.
