### ISSUE TITLE
Issue with Google Domains

### ISSUE THREAD

**Issue by Cossey** [TechnitiumSoftware/DnsServer#317]
I seem to be having sporadic issues with google domains quite regularly for the past half a year. I have two dns servers on the network `1.dns` and `2.dns` that receive network queries via the standard port 53. 

Firstly, the DNS Servers were forwarding onto google via TLS and then later DoH and then recently I upgraded the process further to both forward resolve to another TDNSS via DoH in the cloud that then forwards queries onto google via DoH (as you suggested via your blog). Under all three conditions Google domains won't always resolve, even though the forwarder has always been Google DNS.

The problem is that sometimes google domains return `NXDOMAIN`. At first I though this might have been due to one of the blocklists but the standard logging didn't include if a query was returning `NXDOMAIN` because of a block. However with the new SQL Lite logging in version 7, it seems like this is not the cause of the problem as the response type is `Authoritative`.

Typically, when I come across the google domain load error on my devices, I just spam clicks on the reload button in Chrome until eventually it loads up. This occurs on all network devices using my local DNS Servers.

Now that it has just occurred, I noticed that `1.dns` has cached the record correctly, but `2.dns` has it as a `NXDOMAIN` even though both DNS Servers forward to the same DoH TDNSS in the cloud. Although I have included the logs below, they don't seem to be helpful. I would assume both DNS Servers should cache the record correctly.

I do notice that things start working as they should when I Flush the Cache on both DNS Servers for a while (maybe a day or three) and then it starts sporadically having problems again. **Is there anything further I can do to try and diagnose what is going on with Google domains?**

Thanks in advance.

*Both servers run on Raspberry Pi 3b's in a Docker Container, and are configured as DNS Servers using DHCP on a Cisco Switch.*

## 1.dns
Log File
```
[2021-10-03 11:03:13 Local] [192.168.1.1:58929] [UDP] QNAME: mail.google.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [googlemail.l.google.com., 142.251.32.69]
```

SQL Lite
```
2021-10-04 00:03:13 | 192.168.1.1 | Udp | Recursive | NoError | mail.google.com | A | IN | googlemail.l.google.com., 142.251.32.69
```

DNS Client
```
{
  "Metadata": {
    "NameServer": "1.dns:53 (127.0.0.1:53)",
    "Protocol": "Udp",
    "DatagramSize": "76 bytes",
    "RoundTripTime": "4.01 ms"
  },
  "Identifier": 4492,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 2,
  "NSCOUNT": 0,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "mail.google.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "mail.google.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "7913 (2 hours 11 mins 53 sec)",
      "RDLENGTH": "15 bytes",
      "RDATA": {
        "Domain": "googlemail.l.google.com"
      }
    },
    {
      "Name": "googlemail.l.google.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "148 (2 mins 28 sec)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "142.251.32.69"
      }
    }
  ],
  "Authority": [],
  "Additional": []
}
```

## 2.dns
Log File
```
[2021-10-03 12:51:08 Local] [192.168.1.1:62618] [UDP] QNAME: mail.google.com; QTYPE: A; QCLASS: IN; RCODE: NxDomain; ANSWER: []
```

SQL Lite
```
2021-10-04 01:51:08 | 192.168.1.1 | Udp | Authoritative | NxDomain | mail.google.com | A | IN
```

DNS Client
```
{
  "Metadata": {
    "NameServer": "2.dns:53 (127.0.0.1:53)",
    "Protocol": "Udp",
    "DatagramSize": "84 bytes",
    "RoundTripTime": "3.24 ms"
  },
  "Identifier": 52590,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NxDomain",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 1,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "mail.google.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [
    {
      "Name": "google.com",
      "Type": "SOA",
      "Class": "IN",
      "TTL": "14400 (4 hours)",
      "RDLENGTH": "39 bytes",
      "RDATA": {
        "PrimaryNameServer": "2.dns",
        "ResponsiblePerson": "hostadmin.google.com",
        "Serial": 4,
        "Refresh": 14400,
        "Retry": 3600,
        "Expire": 604800,
        "Minimum": 900
      }
    }
  ],
  "Additional": []
}
```

**Comment by ShreyasZare** [comment]
Thanks for the DNS Client output. It seems that your 2.dns server is blocking "google.com" and you have the NX domain blocking option enabled. You can confirm this by querying on the DNS Client tab for "google.com" and type TXT which will let you know the source of the blocking.

This explains why it works sometime and then does not work. You probably have 1.dns set as primary DNS server and 2.dns as your secondary in your DHCP config. The clients thus will always try the primary first and in case when primary does not respond quick enough that they query the secondary dns which responds with a NX domain. Now, if you keep refreshing the page then eventually the web browser will make another request which gets answered by the primary dns and it works.

**Comment by Cossey** [comment]
I would have thought that the SQL Lite log would have had `Blocked` instead of `Authoritative` in the respective column? Yes I do have 1.dns as primary and 2.dns as secondary. I also came to the conclusion that this would be why it works sometimes. I suspected it may have been a block list, but both servers are configured *almost* identically, including with the same block lists.

I still feel like there could be something else going on. Is there some extra debugging I could add somewhere in the code or a particular exception I should be looking out for? Thanks heaps!

Below is my `mail.google.com` `TXT` output. I don't see any record of why it could be blocked. It is worth noting that `google.com` resolves fine to an IP address.
```
{
  "Metadata": {
    "NameServer": "2.dns:53 (127.0.0.1:53)",
    "Protocol": "Udp",
    "DatagramSize": "84 bytes",
    "RoundTripTime": "2.96 ms"
  },
  "Identifier": 56045,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NxDomain",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 1,
  "ARCOUNT": 0,
  "Question": [
    {
      "Name": "mail.google.com",
      "Type": "TXT",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [
    {
      "Name": "google.com",
      "Type": "SOA",
      "Class": "IN",
      "TTL": "14400 (4 hours)",
      "RDLENGTH": "39 bytes",
      "RDATA": {
        "PrimaryNameServer": "2.dns",
        "ResponsiblePerson": "hostadmin.google.com",
        "Serial": 4,
        "Refresh": 14400,
        "Retry": 3600,
        "Expire": 604800,
        "Minimum": 900
      }
    }
  ],
  "Additional": []
}
```

**Comment by ShreyasZare** [comment]
> 
> I would have thought that the SQL Lite log would have had `Blocked` instead of `Authoritative` in the respective column? 

I missed that. For any blocked request it will be `Blocked`.

> Below is my `mail.google.com` `TXT` output. I don't see any record of why it could be blocked. It is worth noting that `google.com` resolves fine to an IP address.
> 
> ```
> {
>   "Metadata": {
>     "NameServer": "2.dns:53 (127.0.0.1:53)",
>     "Protocol": "Udp",
>     "DatagramSize": "84 bytes",
>     "RoundTripTime": "2.96 ms"
>   },
>   "Identifier": 56045,
>   "IsResponse": true,
>   "OPCODE": "StandardQuery",
>   "AuthoritativeAnswer": true,
>   "Truncation": false,
>   "RecursionDesired": true,
>   "RecursionAvailable": true,
>   "Z": 0,
>   "AuthenticData": false,
>   "CheckingDisabled": false,
>   "RCODE": "NxDomain",
>   "QDCOUNT": 1,
>   "ANCOUNT": 0,
>   "NSCOUNT": 1,
>   "ARCOUNT": 0,
>   "Question": [
>     {
>       "Name": "mail.google.com",
>       "Type": "TXT",
>       "Class": "IN"
>     }
>   ],
>   "Answer": [],
>   "Authority": [
>     {
>       "Name": "google.com",
>       "Type": "SOA",
>       "Class": "IN",
>       "TTL": "14400 (4 hours)",
>       "RDLENGTH": "39 bytes",
>       "RDATA": {
>         "PrimaryNameServer": "2.dns",
>         "ResponsiblePerson": "hostadmin.google.com",
>         "Serial": 4,
>         "Refresh": 14400,
>         "Retry": 3600,
>         "Expire": 604800,
>         "Minimum": 900
>       }
>     }
>   ],
>   "Additional": []
> }
> ```

Observing the SOA record, the values it uses were set by default in previous version for primary zones. So, it seems that this response is being generated from a zone. 

Do you have any zone configured probably for conditional forwarding?

**Comment by Cossey** [comment]
I think that might be it! Don't recall adding this here but I probably did without realising:

![image](https://user-images.githubusercontent.com/6280250/135812964-8cc69898-3c2a-48ef-aba0-4876b204fd7d.png)

Wouldn't have been for conditional forwarding since that's a bit beyond what I understand for DNS at present. I'll remove this and see how things go. Thanks again!

**Comment by ShreyasZare** [comment]
> 
> 
> I think that might be it! Don't recall adding this here but I probably did without realising:
> 
> ![image](https://user-images.githubusercontent.com/6280250/135812964-8cc69898-3c2a-48ef-aba0-4876b204fd7d.png)
> 
> Wouldn't have been for conditional forwarding since that's a bit beyond what I understand for DNS at present. I'll remove this and see how things go. Thanks again!

Great! Its a primary zone so probably got added by accident, probably for some testing.
