### ISSUE TITLE
DNS App Split Horizon not expected answer

### ISSUE THREAD

**Issue by tango38317** [TechnitiumSoftware/DnsServer#318]
Hello @ShreyasZare,

i´m not sure, but maybe i made some missconfiguration.
i have created a DNS Entry as App > DNS Split Horizon.
Following Entry:

{
  "private": [
    "10.201.19.62"
  ],
  "10.64.0.0/9": [
    "10.73.19.43"
  ]
}
if i make a nslookup from a client with ip adress 10.32.34.24 or 10.32.237.186
i get as answer instead of expected "10.201.19.62" the answer: "10.73.19.43".

maybe you have an idea?

br
Chris

**Comment by tango38317** [comment]
Further Test:
from client with ip adress: 10.201.19.149 i get the correct answer 10.201.19.62
br
Chris

**Comment by tango38317** [comment]
OK, i see, i have made a subnet calculation error :-)
many thanks
Chris

**Comment by ShreyasZare** [comment]
> 
> 
> OK, i see, i have made a subnet calculation error :-) many thanks Chris

Ya that happens with everyone sometimes :)

Another thing just to let you know is that `private` and `public` entries are used after all the network addresses are matched first.
