### ISSUE TITLE
Feature Request: Add a DHCP server

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#32]
I know the focus at the moment is to improve stability, but something I'd like to suggest is that a DHCP server is added to your group of projects under the TechnitiumSoftware umbrella.

Then at some point create another project that incorporates the DNS server and DHCP server together, so that people can choose to use one or the other, or both.

The benefit of this is that if a router does not allow the changing of DNS settings, the DHCP server can be used to achieve the same result.

**Comment by TechnikEmpire** [comment]
Seems a little heavy-handed just to modify DNS. You can use host's files, adapter properties and more to enforce your DNS. You can also drop in a packet diverter to enforce your DNS as well.

**Comment by ShreyasZare** [comment]
DHCP server is now available with v4.0 release! DHCP supports multiple scopes to allow working with multiple networks on the server plus also works with DHCP relay agents on remote networks.

DHCP Features Implemented:
- Multiple scopes support.
- Offer delay.
- Automatic forward and reverse zone management for DHCP domain option with control over TTL.
- WINS option.
- NTP option.
- Classless static route option.
- IP address range exclusions.
- Reserved leases based on MAC address.

![image](https://user-images.githubusercontent.com/10008172/60381797-f3962580-9a77-11e9-9ffe-fb574f680d73.png)
