### ISSUE TITLE
DNS over TLS forwarder: add fails

### ISSUE THREAD

**Issue by squromiv** [TechnitiumSoftware/DnsServer#329]
I am newbie to DNSServer. I try to add DNS forwarder from [this instruction](https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/), but it fails.
[Screen](http://s01.geekpic.net/di-FW4PR5.png)

**Comment by ShreyasZare** [comment]
Yes do what @Hemsby said. 

I will update this code to auto complete the address wrt the protocol it in the next release to make it easier.
