### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by asterriya** [TechnitiumSoftware/DnsServer#331]
Can you add DoQ support into forwarder section, please? Better if you will also create option to make own DoQ on self VPS

Also add this HTTPS DNS to the forwarder section https://blitz.ahadns.com/ (172.66.43.149). Original url is here https://blitz-setup.ahadns.com/

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which now supports DNS-over-QUIC. Do check and let me know your feedback.
