### ISSUE TITLE
How to disable ipv6 resolve?

### ISSUE THREAD

**Issue by LittleGrocery** [TechnitiumSoftware/DnsServer#337]
I already set DNS Server Local End Points as 0.0.0.0:53. However, the dashboard still shows the program still resolve ipv6 DNS request. How can I disable it?

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS Server does not resolve IPv6 addresses by itself, the client applications query for AAAA type to resolve IPv6 addresses. Thus there is no such option to do so.

**Comment by LittleGrocery** [comment]
> Thanks for the post. The DNS Server does not resolve IPv6 addresses by itself, the client applications query for AAAA type to resolve IPv6 addresses. Thus there is no such option to do so.

Can DnsServer just ignore the ipv6 request?

**Comment by ShreyasZare** [comment]
> 
> 
> > Thanks for the post. The DNS Server does not resolve IPv6 addresses by itself, the client applications query for AAAA type to resolve IPv6 addresses. Thus there is no such option to do so.
> 
> Can DnsServer just ignore the ipv6 request?

That would cause the client apps to keep on repeating the requests so the DNS server will be hit with even more requests that has to be ignored.

There is a way to do that using the Drop Requests app from the DNS App store where you can specify just the type `AAAA` and the requests will be dropped. Totally not recommended though since as stated above will increase the traffic the DNS server has to manage.

**Comment by LittleGrocery** [comment]
> > > Thanks for the post. The DNS Server does not resolve IPv6 addresses by itself, the client applications query for AAAA type to resolve IPv6 addresses. Thus there is no such option to do so.
> > 
> > 
> > Can DnsServer just ignore the ipv6 request?
> 
> That would cause the client apps to keep on repeating the requests so the DNS server will be hit with even more requests that has to be ignored.
> 
> There is a way to do that using the Drop Requests app from the DNS App store where you can specify just the type `AAAA` and the requests will be dropped. Totally not recommended though since as stated above will increase the traffic the DNS server has to manage.

I understand. Thank you very much.
