### ISSUE TITLE
Possible copy-paste bug.

### ISSUE THREAD

**Issue by Singijeon** [TechnitiumSoftware/DnsServer#342]
https://github.com/TechnitiumSoftware/DnsServer/blob/d61f31162f0969721180d03b4a41f3fab71e0e18/Apps/AdvancedBlockingApp/App.cs#L920-L921
Should be
```csharp
var loadBlockList = (group.Value & LOAD_BLOCK_LIST_ZONE) != 0;
```
https://github.com/TechnitiumSoftware/DnsServer/blob/d61f31162f0969721180d03b4a41f3fab71e0e18/Apps/AdvancedBlockingApp/App.cs#L922-L923
Should be
```csharp
var loadRegexBlockList = (group.Value & LOAD_REGEX_BLOCK_LIST_ZONE) != 0; 
```

**Comment by ShreyasZare** [comment]
Thanks for the finding this bug. Will get that fixed.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which fixes this issue. Do check and let me know your feedback.
