### ISSUE TITLE
Disable UDP

### ISSUE THREAD

**Issue by Wunderharke** [TechnitiumSoftware/DnsServer#347]
I thought i saw an option in the past to disable DNS over UDP, now i can't find it anymore. Has this been patched out?

**Comment by ShreyasZare** [comment]
Thanks for the post. There was no such option since DNS-over-UDP is like the default standard. If you configure a forwarder with specific protocol then only that will be used for outbound request. However, the DNS server will always accept inbound UDP requests on port 53.

**Comment by Wunderharke** [comment]
Okay thank you! Since UDP is vulnerable to reflection attacks and I use DoH for most services I would still like to see such a feature.

**Comment by Wunderharke** [comment]
Yes I think I will just drop the UDP packets :) Thanks!
