### ISSUE TITLE
Temporary disable blocking button doesn't stop Advanced Blocking App from blocking domains

### ISSUE THREAD

**Issue by zpxp** [TechnitiumSoftware/DnsServer#349]
Create a blocking regex in blocking app then go to settings and temp disable blocking. Regex block app will still block.

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS Server and the DNS Apps are independent by design so any settings on the DNS Server wont affect the DNS Apps. DNS Apps use its own json config to function.
