### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jschenke488** [TechnitiumSoftware/DnsServer#351]
![image](https://user-images.githubusercontent.com/44783760/145332511-7c702647-f101-4fb5-a9e4-3935a037a17b.png)
Your logo contains a swastika. This should be changed.

**Comment by ShreyasZare** [comment]
Thanks for the post. The logo is made of 4 "T" characters, the initial character of "Technitium", arranged on a blue background. What you are trying to find is actually the background. It may resemble a bit like a swastik but its not how an actual swastik looks like (I am a Hindu by birth and there are a couple of swastik on my front door). It does not resemble anything like the Nazi symbol which is a swastik rotated to 45 degrees.

**Comment by BonnieSoftware** [comment]
Nothing wrong with the logo, if you think it resembles a swastika you need to reign in your imagination.

**Comment by ShreyasZare** [comment]
> Nothing wrong with the logo, if you think it resembles a swastika you need to reign in your imagination.

Ya, its kind of like finding faces in inanimate objects or seeing shapes in the clouds.

**Comment by TheBarret** [comment]
> Nothing wrong with the logo, if you think it resembles a swastika you need to reign in your imagination.

Exactly what he said, don't make problems out of thin air, leave ur "offended feelings" at the door.

**Comment by ShreyasZare** [comment]
Closing this issue. If anyone still sees a swastik then just think it of as a Hindu religious symbol.
