### ISSUE TITLE
DHCP and NFS

### ISSUE THREAD

**Issue by Richie765** [TechnitiumSoftware/DnsServer#354]
I have an issue when my NFS Clients obtain an IP from the DHCP Server. On my NFS Server I have rights configured in `/etc/exports` using hostnames. For this to work, the hostname must resolve to an IP address when the NFS Server starts up. If the IP cannot be obtained, the NFS Client won't get access when it becomes available later.

My NFS Clients are configured using static DHCP Leases. The problem is, when the NFS Client shuts down, it's DNS record is removed as well. So if the NFS Server restarts, it cannot find the IP Address and the NFS Client won't get access when it becomes available again.

I've tried setting a DNS record directly, but it doesn't help. The entry is still removed when the NFS Client shuts down.

I came up with some work-arounds. 
One is to avoid DHCP and use a fixed IP address and add the DNS Address directly.
Another is to add a bogus DNS entry, e.g. `hostname-nfs.tld` which then should be used in `/etc/exports` on the NFS Server. Another way is to use fixed IP in `/etc/exports`.

None are optimal. In a previous DNS/DHCP setup I used, the manually entered DNS entries would not be overwritten/removed by the DHCP server. So I could just add the DNS records manually along with the DHCP static reservations and they would stay there.

Perhaps something similar could be implemented? Perhaps an option that DNS records will not be removed for static DHCP reservations could be implemented?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The DHCP server removes DNS entries when a lease expires or the client releases the lease. Do check the logs to know the reason why the DNS entries are being removed.

The DNS entries that are being automatically managed by the DHCP server use hostname provided by the client and if you have explicitly provided a hostname in reserved lease then that overrides any hostname that the client provides. I would suggest you to use a different name to create a manual entry in the DNS zone. The manual entry that you make with a different name will stay even when the lease expires or is released.

Do let me know if that works for you.

**Comment by Richie765** [comment]
Thanks for the suggestions. My host apparently releases the DHCP lease when it shuts down. 

I tried to override the hostname in the reserved leases but that does not work. It will still register the DNS record with the client provided hostname. I will try it again in the next few days and report back, because that could indeed be a solution for this.

**Comment by Richie765** [comment]
I just had a look at it again. I've set a hostname in the DHCP "Reserved Leases" but it is not used for the DNS record. I'm sure the "MAC Address" is correct because if I change the "IP Address" it is used. But the hostname is not used.

Here is the logfile
```
[2022-01-03 20:30:48 UTC] [0.0.0.0:68] DHCP Server offered IP address [10.0.0.12] to soundbox [XX-XX-XX-5A-F7-90].
[2022-01-03 20:30:48 UTC] [0.0.0.0:68] DHCP Server leased IP address [10.0.0.12] to soundbox [XX-XX-XX-5A-F7-90].
[2022-01-03 20:30:48 UTC] DHCP Server updated DNS A record 'soundbox.lan' with IP address [10.0.0.12].
[2022-01-03 20:30:48 UTC] DHCP Server updated DNS PTR record '12.0.0.10.in-addr.arpa' with domain name 'soundbox.lan'.
[2022-01-03 20:30:53 UTC] DHCP Server successfully saved scope file: /etc/dns/config/scopes/Default.scope
[2022-01-03 20:30:58 UTC] Saved zone file for domain: 0.0.10.in-addr.arpa
[2022-01-03 20:30:58 UTC] Saved zone file for domain: lan
```

I've set the hostname to "soundbox_dhcp". Any idea why it isn't used?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I did try this for a couple of devices but I am not able to reproduce this issue. I have tested with Ubuntu 20.04 and a couple of mobile phones. It works as expected for both overriding hostname and changing reserved IP address.

It can be some issue with the config. If you don't mind then do share config screenshots on email (support@technitium.com).

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which fixes this issue. Do check and let me know your feedback.
