### ISSUE TITLE
SmartDNS Query

### ISSUE THREAD

**Issue by jnnngs** [TechnitiumSoftware/DnsServer#355]
Hi,

Great repro!! Quick question - Can this be used as a smartDNS like https://unlocator.com/? i.e. certain DNS queries directed to Geo proxies to spoof the end website

TIA!

*I tried to find the answer but could see anything

**Comment by ShreyasZare** [comment]
Thanks for the post. You can forward specific domain names to one or more DNS servers using Conditional Forwarder Zones. So, you can get the domain name for a specific website resolved from a different DNS server in a different location. You will need to find the DNS servers in those locations though to make it work or host your own DNS server on a cheap VPS hosting in that location.

Another option is to use a HTTP/SOCKS5 proxy service and configure the DNS server to use that proxy. This will make it looks like your DNS requests are coming from the location of the proxy server. This will affect all DNS queries though unlike Conditional Forwarder Zone where you create a zone per domain name you wish to forward. 

You can also run TOR and use it as SOCKS5 proxy for your DNS server which will result in all your DNS queries to go over TOR and appear to come from different locations every few minutes. You wont have control over the location though with this setup.

**Comment by jnnngs** [comment]
Thanks buddy.

I guess the ideal solution would be HTTP/SOCKS5 proxy with conditional zones. Be a great feature to have as it will open up geo streaming restrictions. Feature request?

Thanks again.

**Comment by ShreyasZare** [comment]
Thanks for the suggestion. Combining proxy with Conditional Forwarders looks like a good option to explore. Will look into it and try to get it added if it's feasible.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which adds support for HTTP/SOCKS5 proxy in conditional forwarder zones. Do check and let me know your feedback.
