### ISSUE TITLE
Feature Request: Lock a specific DNS record

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#358]
Hi,

Please add the ability (tick box on a record?) to lock a specific DNS record from being modified. If you manually create a DNS record, and then another host with the same name gets a DHCP address, then the original manually created record is overwritten with the DHCP assignment. This should not be the case. Thanks for looking into it.

Regards,

Michael

**Comment by ShreyasZare** [comment]
Thanks for the request. Please describe your scenario for which you are making this request. Since, in many cases, you can fix this with updating your config, or renaming your device's name.

**Comment by micush** [comment]
Hi. 

Indeed, you can update your config and rename the offending device. However, the damage is already done at that point. The point is to prevent it from happening in the first place. The 5000 people in the company that rely on the server whose DNS record was overwritten by a "bad" DHCP host can no longer work until the offending host is renamed, the bad DHCP record is removed, the bad DNS record is fixed, and all the DNS secondaries and cache servers down stream all receive the corrected data or flush their cache. 

It would be much more effective to put a simple check box on a DNS record that allows it to not be overwritten in such a manner to begin with, preventing the scenario from ever happening in the first place. It happened to at my company. It will happen to others.  

Thanks for looking into it.

Regards,

Michael

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I will try to find a solution for this.

**Comment by LordMike** [comment]
@micush I think you have a larger problem in your network then, if you have 5.000 devices (employees) who use the same DNS zone as your servers seem to be.

You will always have problems here, like if users were to name their computers `password-reset`, they would get `password-reset.corp.local`..

For you, I would recommend placing the DHCP scope within a sub-zone, like `*.pcs.corp.local`. Then you will never have conflicts, and the `corp.local` zone will be tightly controlled.

**Comment by micush** [comment]
Hi,

Thanks for your opinion. However, it does not solve the problem I
experienced.

We also have Infoblox devices in our network. They allow us to lock
individual DNS records so that modifications cannot be made to them without
first unlocking the record. That type of option implemented in
Technitium would also solve this issue.

Regards,

Michael

**Comment by ShreyasZare** [comment]
Just an update: This issue is fixed by adding checks to prevent dynamic leases to override existing records. For reserved leases, it will work as expected and will override any record if it exists. Next update is expected to be available this weekend.

**Comment by micush** [comment]
Hi,

That should work. Much appreciated.

Regards,

Michael

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which fixes this issue. Do check and let me know your feedback.
