### ISSUE TITLE
Cannot modify existing DHCP scope through API?

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#359]
Hi,

Is it not possible to edit an existing DHCP scope through an API call? It can only be modified at initial scope creation? Maybe I'm using the wrong API call?

"
curl $host'/api/setDhcpScope?token='$token'&name='$scope'&offerDelayTime='$delay

{"status":"error","errorMessage":"Parameter 'startingAddress' missing.","stackTrace":"   at DnsServerCore.WebServiceDhcpApi.SetDhcpScopeAsync(HttpListenerRequest request) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\WebServiceDhcpApi.cs:line 384\n   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\DnsWebService.cs:line 607"}{"status":"error","errorMessage":"Parameter 'startingAddress' missing.","stackTrace":"   at DnsServerCore.WebServiceDhcpApi.SetDhcpScopeAsync(HttpListenerRequest request) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\WebServiceDhcpApi.cs:line 384\n   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\DnsWebService.cs:line 607"}{"status":"error","errorMessage":"Parameter 'startingAddress' missing.","stackTrace":"   at DnsServerCore.WebServiceDhcpApi.SetDhcpScopeAsync(HttpListenerRequest request) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\WebServiceDhcpApi.cs:line 384\n   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\DnsWebService.cs:line 607"}{"status":"error","errorMessage":"Parameter 'startingAddress' missing.","stackTrace":"   at DnsServerCore.WebServiceDhcpApi.SetDhcpScopeAsync(HttpListenerRequest request) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\WebServiceDhcpApi.cs:line 384\n   at DnsServerCore.DnsWebService.ProcessRequestAsync(HttpListenerRequest request, HttpListenerResponse response) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\DnsWebService.cs:line 607"}
"

**Comment by ShreyasZare** [comment]
Thanks for asking. The DHCP API has only get & set type of calls. The `setDhcpScope` is used to create as well as update a scope and the 3 parameters `startingAddress`, `endingAddress`, & `subnetMask` are required to be passed along with the `token` & `name` parameters. Rest all the parameters are optional.

I will update the API call to make these 3 parameter optional to make it easier to use.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which fixes this issue. Do check and let me know your feedback.
