### ISSUE TITLE
Web console page width for a long txt domain records case

### ISSUE THREAD

**Issue by meteonet** [TechnitiumSoftware/DnsServer#360]
In the case of a very long domain record, such as a TXT record for a DKIM public key, the page width is much larger than my 30" screen :)
It's not a big problem, but...
![20220215170012 l](https://user-images.githubusercontent.com/72390815/154292732-49d5779a-3d8e-4e5f-8009-bcfddf9b4362.jpg)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get that fixed in next update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v8 is now released which fixes this issue. Do check and let me know your feedback.

**Comment by meteonet** [comment]
It look's fine. Thank you for a awesome job!
