### ISSUE TITLE
Technitium Service breaks Windows Subsystem for Linux 2 (WSL2)

### ISSUE THREAD

**Issue by Titan21** [TechnitiumSoftware/DnsServer#363]
Hi Team,

Unfortunately it looks like installing Technitium DNS Server interferes with WSL2.
When trying to register a new Distribution (e.g. Ubuntu) this fails with 
`WslRegisterDistribution failed with error: 0xffffffff`
as long as there is a local service using port 53
[Stackoverflow](https://stackoverflow.com/questions/64191759/wslregisterdistribution-failed-with-error-0xffffffff)

I don't think it's Technitium's fault, but I wanted to leave this comment here for anyone having the same issue in the future.
My solution was to disable the Technitium Service. After that I was able to install Ubuntu on WSL2.

**Comment by ShreyasZare** [comment]
Thanks for the post. This was already posted here https://github.com/TechnitiumSoftware/DnsServer/issues/230

The fix seems to be to configure DNS server to listen on a specific IP instead of ANY `0.0.0.0`. So using the IP on your LAN interface or just using 127.0.0.1 should help with that.

**Comment by Titan21** [comment]
Oh, Sorry - didn't find that issue.
Awesome, good to know there's a workaround!

Solution:

> Change the DNS Server Local End Points from 0.0.0.0:53 to 127.0.0.1:53
> That worked for me
