### ISSUE TITLE
Change default admin user name

### ISSUE THREAD

**Issue by jnehlmeier** [TechnitiumSoftware/DnsServer#364]
Hi,

is it possible to change the default `admin` user name to something else? I usually prefer changing default user names to something else for that extra bit of security.

**Comment by x-tk** [comment]
this would be a nice to have.

**Comment by ShreyasZare** [comment]
There is no option right now but there is a planned feature to have user management with role based access so that should cover this feature request.

**Comment by ShreyasZare** [comment]
New version 9.0 is now available that allows renaming admin user.
