### ISSUE TITLE
DNSSEC validation

### ISSUE THREAD

**Issue by libDarkstreet** [TechnitiumSoftware/DnsServer#367]
Is there a way to set up dnssec validation?

I'm thinking of putting a bind9 proxy with dnssec validation in front of it. I think that could work. 

I would like to hear any advice on how to solve this. I like this project so if possible without having to replace it completely.🪛

**Comment by ShreyasZare** [comment]
Thanks for asking. Next update that will be released coming weekend will support DNSSEC validation as well as hosting DNSSEC signed zones.

**Comment by libDarkstreet** [comment]
Thanks for the quick reply! I guess I'll wait for the update before I do anything! 😄
