### ISSUE TITLE
GUI Refresh Logout

### ISSUE THREAD

**Issue by x-tk** [TechnitiumSoftware/DnsServer#368]
Is it the normal experience that a page refresh forces new credentials?  If so, can we get a refresh button added or something?  If I want to refresh the dashboard without re-entering credentials, I have to click a different timeframe and click back which is fairly annoying.  It would also be cool if there was an autorefresh interval that could be set while on the main page.  I know that "GUI" enhancements are lower on the list but some small things go a long way.  Thanks!

**Comment by ShreyasZare** [comment]
Thanks for the post. The Dashboard "Last Hour" view auto refreshes every 60 seconds and thus keeps your session active. 

The web console is designed to refresh data when you click on the tabs to navigate. So, when you click on the Dashboard tab, the data will be refreshed immediately. 

There are a few tabs that do not refresh data when clicked on it to allow preserving the view state. In such tabs, you will find a refresh option to reload the data.

**Comment by x-tk** [comment]
I guess that is helpful, would be nice if it was more apparent I suppose but as long as I know that's the case, that's cool.

What about the page refresh forcing new credentials?  That is regardless of how recent the login.  Is that the expected behavior?  So much easier to hit F5 or refresh button than click back and forth.

**Comment by ShreyasZare** [comment]
> What about the page refresh forcing new credentials? That is regardless of how recent the login. Is that the expected behavior? So much easier to hit F5 or refresh button than click back and forth.

Yes, the web app does not store the login token so refreshing page will need relogin.
