### ISSUE TITLE
Tray App after upgrade to 8

### ISSUE THREAD

**Issue by Hemsby** [TechnitiumSoftware/DnsServer#370]
After upgrading the Tray App appears to not start or work.  I have upgraded 2 servers and both same issue.  The other 2 on v7 are ok.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Let me know the details of the OS that you are running. I have tested it on Win10 and Windows Server 2022.

**Comment by ShreyasZare** [comment]
> All server 2022 

Check once if you have .NET 6.0.3 Windows Desktop installed correctly using "dotnet --info" command. If not then download and install it separately from [here](https://dotnet.microsoft.com/en-us/download).

**Comment by Hemsby** [comment]
Ahhh…

I have version 6.  Updating worked.  Thanks.  Please close the issue.


Kind Regards,

Roy Hagland

mail: ***@***.******@***.***>
Mob UK: +44 7806888933
Mob PT: +351 925476984
Mob ES: +34 698970254

Please note that electronic mail may be monitored. This e-mail is confidential. If you received it by mistake, please let me know and then delete it from your system; you should not copy, disclose, or distribute its contents to anyone nor act in reliance on this e-mail, as this is prohibited and may be unlawful.

**Comment by ShreyasZare** [comment]
Thanks for letting me know that it worked.
