### ISSUE TITLE
Refused

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#373]
The installed version is Version 8.0
![GLE(Y$2(VBPBCF`A0Z4XCJH](https://user-images.githubusercontent.com/17548936/160432337-d6186a52-53ee-47f1-94f7-e9af6973a246.png)

"ExtraText": "localidns:5357 (127.0.0.1) returned RCODE=Refused for www.google.com.hk. A IN"

**Comment by ShreyasZare** [comment]
> I chose Deny Recursion

Since you have enabled Deny Recursion option the DNS server will return REFUSED response for a zone not hosted locally. You need to change that option to a suitable one.

**Comment by thb007** [comment]
> > I chose Deny Recursion
> 
> Since you have enabled Deny Recursion option the DNS server will return REFUSED response for a zone not hosted locally. You need to change that option to a suitable one.

ok.

**Comment by thb007** [comment]
There seems to be a problem by testing edns. I parsed by attaching the subnet client ip and found that their results are the same.
![2 C{2BI20IU6P_}%H`} 4TH](https://user-images.githubusercontent.com/17548936/160612649-5a7ba973-8575-4aaf-ac48-bb4a5ef3c38b.png)


```
dig www.baidu.com @127.0.0.1 -p 5357 +subnet=1.1.1.1
dig www.baidu.com @127.0.0.1 -p 5357 +subnet=8.8.8.8
```

**Comment by ShreyasZare** [comment]
> There seems to be a problem by testing edns. I parsed by attaching the subnet client ip and found that their results are the same.
> 
> ```
> dig www.baidu.com @127.0.0.1 -p 5357 +subnet=1.1.1.1
> dig www.baidu.com @127.0.0.1 -p 5357 +subnet=8.8.8.8
> ```

The new update has EDNS support but does not implement the Client Subnet option.

Other issue is that the Client Subnet option is not useful if you are running the DNS server locally. This option is intended to be used by recursive resolvers that are hosted on public Internet and uses the IP address of the requests it receives to forward to the authoritative name servers using Client Subnet option. If the authoritative server has different records for different region then it will respond likewise using that provided IP address. The locally running DNS server is going to receive requests from private IP addresses on your LAN so its not going to help with using EDNS Client Subnet.

**Comment by thb007** [comment]
> > There seems to be a problem by testing edns. I parsed by attaching the subnet client ip and found that their results are the same.
> > ```
> > dig www.baidu.com @127.0.0.1 -p 5357 +subnet=1.1.1.1
> > dig www.baidu.com @127.0.0.1 -p 5357 +subnet=8.8.8.8
> > ```
> 
> The new update has EDNS support but does not implement the Client Subnet option.
> 
> Other issue is that the Client Subnet option is not useful if you are running the DNS server locally. This option is intended to be used by recursive resolvers that are hosted on public Internet and uses the IP address of the requests it receives to forward to the authoritative name servers using Client Subnet option. If the authoritative server has different records for different region then it will respond likewise using that provided IP address. The locally running DNS server is going to receive requests from private IP addresses on your LAN so its not going to help with using EDNS Client Subnet.

I'm running on ECs. Check allow recurrence only for private networks (default)

**Comment by ShreyasZare** [comment]
> I am running on cloud server. And check Allow Recursion Only For Private Networks (default)

If you allow recursion only for private networks then you wont be able to use the DNS server as a resolver over Internet. You will have to set it to allow recursion for everyone or if you know your specific network address and are sure that it does not change then you can allow only specific networks.

**Comment by thb007** [comment]
> > I am running on cloud server. And check Allow Recursion Only For Private Networks (default)
> 
> If you allow recursion only for private networks then you wont be able to use the DNS server as a resolver over Internet. You will have to set it to allow recursion for everyone or if you know your specific network address and are sure that it does not change then you can allow only specific networks.

I try to switch other menus, I still have a question Is the edns subnet IP added actively?

**Comment by ShreyasZare** [comment]
> I try to switch other menus, I still have a question Is the edns subnet IP added actively?

No the Client Subnet option is not implemented. So, your DNS server's public IP address will be used by the upstream to decide the response that should be returned.

**Comment by thb007** [comment]
> > I try to switch other menus, I still have a question Is the edns subnet IP added actively?
> 
> No the Client Subnet option is not implemented. So, your DNS server's public IP address will be used by the upstream to decide the response that should be returned.

ok, when is the plan to fully support the edns subnet ip function?

**Comment by ShreyasZare** [comment]
> 
> ok, when is the plan to fully support the edns subnet ip function?

There is currently no plan to implement this since it causes privacy issues.

**Comment by thb007** [comment]
> > ok, when is the plan to fully support the edns subnet ip function?
> 
> There is currently no plan to implement this since it causes privacy issues.

It can be turned on and off with a switch, and everything is set by the customer.

**Comment by thb007** [comment]
> > ok, when is the plan to fully support the edns subnet ip function?
> 
> There is currently no plan to implement this since it causes privacy issues.

Use my dns service to accept privacy issues (generally companies will not disclose it online), otherwise please do not use

**Comment by ShreyasZare** [comment]
> Use my dns service to accept privacy issues (generally companies will not disclose it online), otherwise please do not use

Actual privacy issue is that client's subnet is available to all authoritative name servers so its not a good option to have. The only reason this option is used is for finding closest IP address for a CDN network. If you do not have such an use case then this option is of no use.
