### ISSUE TITLE
setting use local time in logging has no affect (Docker image 8.0)

### ISSUE THREAD

**Issue by michael-pellegrini** [TechnitiumSoftware/DnsServer#374]
Hello,

Tried setting logs to use local time on both AMD64 and ARM docker image 8.0 without success.
settings -> logging -> use local time
Logs show UTC time when the box is checked.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I tried it here and could not reproduce the issue. I am seeing local time. If possible, send some more details like a screenshot or copy of logs so that I can analyze it.

**Comment by michael-pellegrini** [comment]
OS: Ubuntu 20.04  
Docker Community Edition: 20.10.14
Docker image: technitium/dns-server:8.0 (also tired 8.0.1)

Output from date command.
![image](https://user-images.githubusercontent.com/47049792/160722590-5830400c-2b13-4ef0-a4ec-3593a8726dee.png)
Docker run command
![image](https://user-images.githubusercontent.com/47049792/160722730-b7bb9691-eadb-4640-83fd-1ef65aac6956.png)
Output from date command inside container
![image](https://user-images.githubusercontent.com/47049792/160722921-a3deac6f-fa0d-4ec0-b07b-ba0df12599a3.png)
Check use local time under under settings -> logging. Added zone, log shows UTC time. Time off by 4 hours.
![image](https://user-images.githubusercontent.com/47049792/160723704-e7ce0d85-58ee-443f-bc23-db168fb6ca02.png)

**Comment by ShreyasZare** [comment]
Thanks for the details. The timezone on your host machine is of no use since docker container uses UTC by default. This is why the local time that you see in the logs is just the UTC time. 

So, you will need to configure the container with a preferred timezone to make it work.

**Comment by michael-pellegrini** [comment]
Hello,
Would it be possible to add USE_LOCAL_TIME (boolean) environmental variable. I would like to set this at runtime. 
Was able to link time zone in dockerfile and set with ENV at runtime. [https://github.com/michael-pellegrini/technitium_docker/blob/master/Dockerfile](https://github.com/michael-pellegrini/technitium_docker/blob/master/Dockerfile)

**Comment by ShreyasZare** [comment]
Sure, will add that variable in the next update.

**Comment by michael-pellegrini** [comment]
Nice!

**Comment by ShreyasZare** [comment]
Version 8.1 is now available that adds the environment variable. See the [docs](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DockerEnvironmentVariables.md) for details.
