### ISSUE TITLE
Hosts with FQDN hostnames seem to cause duplicate leases

### ISSUE THREAD

**Issue by Zorlin** [TechnitiumSoftware/DnsServer#386]
Hi there,

I've noticed duplicate leases appearing in my new setup.

It appears to be caused by machines with FQDN hostnames (ie: plexy.windowpa.in as hostname instead of plexy)

I'll see if I can reproduce it better and report back with my findings.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is probably the same issue as this comment describes: https://github.com/TechnitiumSoftware/DnsServer/issues/385#issuecomment-1109579956.

**Comment by Zorlin** [comment]
I'll try to make a test case of some kind, then test it on $nextUpdate then :)

**Comment by ShreyasZare** [comment]
Version 8.1 is now available that fixes this issue.
