### ISSUE TITLE
`TXT` records aren't returned in answers

### ISSUE THREAD

**Issue by ZzZombo** [TechnitiumSoftware/DnsServer#388]
I've added a custom `TXT` record to a new primary zone. The zone's correctly reported for all questions but the `TXT` record. All `nslookup`, `dnscrypt-proxy --resolve` and the Technitium DNS Server's built-in client indicate nothing is returned for this kind of question.
 Here is my zone setup:
![image](https://user-images.githubusercontent.com/10889612/165702356-7a4f8334-8193-413e-a3d6-06749d6eb30d.png)

<details>
<summary>And the returned response</summary>

``` json
{
  "Metadata": {
    "NameServer": "192.168.0.2",
    "Protocol": "Tcp",
    "DatagramSize": "94 bytes",
    "RoundTripTime": "142,1 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "DnsClientExtendedErrors": [],
  "Identifier": 14467,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 1,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "test.dev",
      "Type": "TXT",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [
    {
      "Name": "test.dev",
      "Type": "SOA",
      "Class": "IN",
      "TTL": "900 (15 mins)",
      "RDLENGTH": "45 bytes",
      "RDATA": {
        "PrimaryNameServer": "192.168.0.2",
        "ResponsiblePerson": "hostadmin.test.dev",
        "Serial": 6,
        "Refresh": 900,
        "Retry": 300,
        "Expire": 604800,
        "Minimum": 900
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Indeterminate"
    }
  ]
}
```
</details>

I've tried multiple times to recreate both zones and records to no avail. Any help there?

**Comment by ShreyasZare** [comment]
Thanks for the post. The TXT record you added is for "test.test.dev". Edit the record and put in "@" in the name field.

**Comment by ZzZombo** [comment]
If I have an instruction to create a record named `X.Y.test.dev`, is the correct name for it then just `X.Y`? Or there is some other kind of setup needed?

**Comment by ShreyasZare** [comment]
> If I have an instruction to create a record named `X.Y.test.dev`, is the correct name for it then just `X.Y`? Or there is some other kind of setup needed?

Yes, the name will be "x.y". The GUI shows the last part of the domain to avoid this confusion:

![image](https://user-images.githubusercontent.com/10008172/165722172-a62d6745-a3de-4c9e-8541-43f21f77bdd7.png)
