### ISSUE TITLE
lame namservers

### ISSUE THREAD

**Issue by amirmnoohi** [TechnitiumSoftware/DnsServer#392]
Hi,

I use this DNS server as a forwarder. but the problem is that intonds show nameserver as **lame** since it responds with non-authoritative DNS server while it should be authoritative

what should I do to solve that?

**Comment by ShreyasZare** [comment]
Are you hosting your domain names live on the DNS server? If yes, have you configured them as a conditional forwarder zone? 

The response from the DNS server will have the authoritative answer (AA) flag true only when the domain has a zone of primary or secondary type.

**Comment by amirmnoohi** [comment]
See, we have multiple Cpanel servers. Each of these servers has its DNS server. Now I want to use one unique DNS alongside them, which is possible through a conditional forwarder zone. 

For example, I have two websites—one on server 1 with domain x1.com and another on server 2 with domain x2.com. Traditionally, I should assign, for example, ns1.d.com ns2.d.com for server one and ns3.d.com, ns4.d.com to server two and then set these DNS to that domains. But now, I want to have a single unique DNS, for example, only ns1 and ns2 and then using a conditional forwarder zone; I choose which server is responsible for this domain. 

I have done this scenario but the problem is that intodns shows an error which I mentioned above...

is there any way to solve this error? or is there any other alternative solutions/scenario?

**Comment by ShreyasZare** [comment]
Conditional forwarder zone is not intended to be used to host domain names authoritatively. They are to be used when you are using the DNS server as a recursive resolver/forwarder.

You must use secondary zones to host domain names on another server. Secondary zones will serve authoritative responses and will continue to work even when your primary zone goes down for some reason. Conditional forwarder zone will stop working once your primary zone is down and the cached records expire.

You have 2 servers say ns1 and ns2 so you should create all your primary zones on ns1 and then on ns2 create secondary zones for each of them.

**Comment by amirmnoohi** [comment]
Thanks for your help. using Secondary zones solved my problem. 

BTW, it seems there is a problem with using Power DNS zone transfer. it seems it can not parse packets correctly. However, I used BIND.
