### ISSUE TITLE
Bug: Error! VendorSpecificInformation option data must be a colon (:) separated hex string.

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#393]
Version: `8.0.2`

I use the DHCP scopes settings to share a vendor specific option (my unifi controller IP address). But recently, the settings page for the DHCP options is invalid by default. When I load the page, the `Vendor Specific Information` field is as shown below, with no colons etc., but when saving the page - it's invalid until colons are added.

![image](https://user-images.githubusercontent.com/1027111/166939400-1b839c7b-3827-462e-b5ae-f85cde694a30.png)

![image](https://user-images.githubusercontent.com/1027111/166939715-8a0ee409-9c95-4661-b288-c3447884162c.png)

Adding the three colons to my value fixes the validation thing, but on the next page load it will be back to no colons and invalid again. :)

**Comment by ShreyasZare** [comment]
Version 8.1 is now available that fixes this issue.

**Comment by besynnerlig** [comment]
> ![image](https://user-images.githubusercontent.com/1027111/166939715-8a0ee409-9c95-4661-b288-c3447884162c.png)

Shouldn't that be 01:04:C0:A8:01:12 for your specific IP?

**Comment by LordMike** [comment]
6 bytes would make for an odd IP - as I understand this (and I'm pretty sure it works in practice), it's a binary IPv4 - 4 bytes.
