### ISSUE TITLE
Anonymous relays

### ISSUE THREAD

**Issue by dethknite** [TechnitiumSoftware/DnsServer#397]
Does this support anonymous relays such as:
https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md
https://download.dnscrypt.info/resolvers-list/v3/relays.md

**Comment by ShreyasZare** [comment]
Thanks for the post. There is no support for DNSCrypt protocol and no plans yet to implement it.
