### ISSUE TITLE
DNS checker

### ISSUE THREAD

**Issue by asterriya** [TechnitiumSoftware/DnsServer#399]
It's not issue but suggestion. Can you add DNS measurement tool which will choose fastest DNS as frequent resolver? Like AdGuard Home does.

Also, will be good if you can add DNS mass checker for validity, too.

**Comment by ShreyasZare** [comment]
I would recommend that you try the [DNS Benchmark](https://www.grc.com/dns/benchmark.htm) tool which is quite nice. 

The DNS Server by itself can choose the fastest response of a given set of forwarders. So, you just have to add the forwarders that you want to use and the DNS server will query them all concurrently and use the first response it receives.

I didn't get "DNS mass checker" can you explain what it is?

**Comment by asterriya** [comment]
> I didn't get "DNS mass checker" can you explain what it is?
Something like this https://github.com/farrokhi/dnsdiag#dnseval=

**Comment by ShreyasZare** [comment]
> > I didn't get "DNS mass checker" can you explain what it is?
>
> Something like this https://github.com/farrokhi/dnsdiag#dnseval=

That is an interesting tool set but, this is out of scope for the DNS server project. There are a lot of core DNS and other features that are still pending so not possible to spend time on adding such a set of features.

**Comment by asterriya** [comment]
Can you add support of DNScrypt and DNS over QUIC into forwarders section? And please add option to turn on/off ECS manually.

**Comment by ShreyasZare** [comment]
> Can you add support of DNScrypt and DNS over QUIC into forwarders section? And please add option to turn on/off ECS manually.

Thanks for asking. DNSCrypt is not planned since other encrypted protocols are as capable and are Internet standards. Most DNS service providers support DoT or DoH but if you wish to use a DNS service provider that supports only DNSCrypt protocol then you can install any of the available DNSCrypt proxies on the same server and configure them as the forwarder in Technitium DNS server.

DNS-over-QUIC is planned feature and you can track issue #208 for it.

ECS is not planned to be implemented since it has privacy issues. This feature is also useful only for large DNS providers so that it can return the closest CDN network's IP address to the client. For a self hosted DNS server, this is not an useful option unless you have the DNS server hosted on a VPS which is in a different country that your actual location.

**Comment by asterriya** [comment]
But you told that ECS already integrated into DNS server, that's why I ask to add option for controlling ECS manually because of privacy issue. Nextdns somehow anonymized it. Add ControlD into default list too, please. And OpenDNS has DoH upstream, but into your default list it's unavailable.

**Comment by asterriya** [comment]
> you have the DNS server hosted on a VPS which is in a different country that your actual location.

Yeah that's my situation.

**Comment by ShreyasZare** [comment]
> But you told that ECS already integrated into DNS server, that's why I ask to add option for controlling ECS manually because of privacy issue. Nextdns somehow anonymized it. Add ControlD into default list too, please. And OpenDNS has DoH upstream, but into your default list it's unavailable.

ECS is not implemented but EDNS(0) which is required for ECS is which may have confused you.

The forwarders quick select list has not been updated for long. Will add OpenDNS DoH option too in there. You can just copy paste the OpenDNS DoH URL for now till its available in the list.

**Comment by asterriya** [comment]
> > But you told that ECS already integrated into DNS server, that's why I ask to add option for controlling ECS manually because of privacy issue. Nextdns somehow anonymized it. Add ControlD into default list too, please. And OpenDNS has DoH upstream, but into your default list it's unavailable.
> 
> ECS is not implemented but EDNS(0) which is required for ECS is which may have confused you.
> 
> The forwarders quick select list has not been updated for long. Will add OpenDNS DoH option too in there. You can just copy paste the OpenDNS DoH URL for now till its available in the list.

Got it. I know that can add manually. Just saying about updating list and don't forget about ControlD.

**Comment by ShreyasZare** [comment]
> 
> Got it. I know that can add manually. Just saying about updating list and don't forget about ControlD.

Never heard of Control D. The quick select list is for popular options to avoid it being too large but, there is already a feature request to make this list editable so that you can add/remove entries as per your needs.
