### ISSUE TITLE
Support custom port number and custom protocol for forwarders

### ISSUE THREAD

**Issue by ebrahim** [TechnitiumSoftware/DnsServer#4]
It is useful in some scenarios to set a custom port number for forwarder servers.

For example let the user set forwarders to use UDP port number 5353 like this: 1.2.3.4@5353 (or 1.2.3.4:5353 which one you like better)

Another useful feature is to support TCP, DNS-over-TLS, etc. for forwarders.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will try to add both the suggestions. Even better, I will try to support DNS over Tor hidden service for use with [Cloudflare hidden DNS service](https://blog.cloudflare.com/welcome-hidden-resolver/).

**Comment by ShreyasZare** [comment]
DNS Server v1.3 is released with support for the requested features! Check out [this blog post](https://blog.technitium.com/2018/06/configuring-dns-server-for-privacy.html) for configuration details.
