### ISSUE TITLE
Failover app problem with ping healthCheck

### ISSUE THREAD

**Issue by surfparadise** [TechnitiumSoftware/DnsServer#400]
Can't configure a reliable healthCheck based on ping. Simply doesn't works correctly. Please check it.

Configure this record, ping always respond with the ip of serverDown:

{
  "primary": [
    "1.1.1.1"
  ],
  "secondary": [
    "192.168.1.1"
  ],
  "serverDown": [
    "8.8.8.8"
  ],
  "healthCheck": "ping"
}

Thanks

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Add `"allowTxtStatus": true` in the APP record data and then use the DNS Client tool to query the domain with TXT type to get a response with report. This report will tell you the status of the health check and any errors that may have occurred. 

Also check the logs for the health check status changes. If you see any specific error logs then do post them here.

**Comment by surfparadise** [comment]
Hi,

tcp healthCheck as well have problems.  Seems to work well, but after a while that the primary and the secondary hosts are down, and correctly the dns record point to "serverDown" address (8.8.8.8), it's start to point again (random?) to one of the 2 hosts.
When I bring on-line again my primary or my secondary address, it's start to work correctly again.
The problem is that when my primary and secondary hosts are off-line, the dns server doesn't keep the servDown address "available" until one of the 2 address come back on-line, but after several minutes start to point to one of the two unreachables hosts .

{
  "primary": [
    "192.168.1.73",
  ],
  "secondary": [
    "192.168.1.72",
  ],
  "serverDown": [
    "8.8.8.8"
  ],
  "healthCheck": "tcp6600",
  "allowTxtStatus": true,
}

******************************************************

{
  "Metadata": {
    "NameServer": "dns1.sntc (127.0.0.1)",
    "Protocol": "Tcp",
    "DatagramSize": "335 bytes",
    "RoundTripTime": "0.6 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "DnsClientExtendedErrors": [],
  "Identifier": 47664,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": true,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 2,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "hatest3.sntc",
      "Type": "TXT",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "hatest3.sntc",
      "Type": "TXT",
      "Class": "IN",
      "TTL": "30 (30 sec)",
      "RDLENGTH": "134 bytes",
      "RDATA": {
        "Text": "app=failover; addressType=Primary; address=192.168.1.73; healthCheck=tcp6600; healthStatus=Failed; failureReason=Host is unreachable;"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "hatest3.sntc",
      "Type": "TXT",
      "Class": "IN",
      "TTL": "30 (30 sec)",
      "RDLENGTH": "136 bytes",
      "RDATA": {
        "Text": "app=failover; addressType=Secondary; address=192.168.1.72; healthCheck=tcp6600; healthStatus=Failed; failureReason=Host is unreachable;"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Indeterminate"
    }
  ]
}

**Comment by ShreyasZare** [comment]
The health check for the given IP addresses work only when they are being queried at least once an hour. If there is no query for the APP record for more than an hour then the health check stops. So, when you query again after that time, the APP will return the primary address first with 30 sec TTL and immediately start health check for it. If the primary is down then for the second query, it will return the secondary address with 30 sec TTL and start health check for it too. If secondary too is down then the 3rd query will return the server down address.

This could be the reason for your case. Try to keep a low TTL value for the APP record so that the record expires in client's cache quick enough that you receive a new query for it within 1 hour.

**Comment by surfparadise** [comment]
Thank you for the answer, but I think could be better enable the 'serverDown' address to respond until one of the 2 hosts come back to live. I think it could be more logic.

thanks!

**Comment by ShreyasZare** [comment]
Its more like the app does not know the health status anymore so it start from scratch again. Responding with server down address at such case will make it more of an issue since downtime is relatively rare case.
