### ISSUE TITLE
Persist web UI session for a given time period

### ISSUE THREAD

**Issue by ZzZombo** [TechnitiumSoftware/DnsServer#408]
Right now the session ends on each page refresh, and also intermittently at random. I'd like to make it last a predefined amount of time instead, like 6 months.

**Comment by ShreyasZare** [comment]
Thanks for the post. The web console login session times out after 30 mins of inactivity. If you want the session to persist, just keep the Dashboard > Last Hour view running which keeps updating the stats every minute.

**Comment by ZzZombo** [comment]
Sorry, this is not a solution, just a workaround. I do not use the hourly report BTW, I set a custom period.

**Comment by ShreyasZare** [comment]
The next major update will feature multi user role based access support. This feature will allow configuring the session timeout so that will cover your request. Meanwhile the workaround will help by keeping one tab open with the last hour chart.

**Comment by ShreyasZare** [comment]
New version 9.0 is now available with option to set session timeout value with option to disable timeout.
