### ISSUE TITLE
Empty cache after service restart

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#41]
After restart the service I see an empty cache. Is this normal behavior? Maybe better to keep cache?

**Comment by ShreyasZare** [comment]
Yes, this is intended behavior. The cache is in application memory and is not written to disk. There is not much benefit to storing it on disk since most of the entries will be expired anyways with their TTL reaching 0.

**Comment by LordMike** [comment]
@ShreyasZare is this still true with the prediction of which domain names to resolve before they're needed?

I assume that logic is based on the cache/some metrics.

**Comment by ShreyasZare** [comment]
> 
> 
> @ShreyasZare is this still true with the prediction of which domain names to resolve before they're needed?
> 
> I assume that logic is based on the cache/some metrics.

The cache auto prefetching feature relies on the stats data that is also displayed on the dashboard. This data is on disk and will be used when the server reboots. The auto prefetch however uses only last hour data.

**Comment by ShreyasZare** [comment]
> 
> 
> > @ShreyasZare is this still true with the prediction of which domain names to resolve before they're needed?
> > I assume that logic is based on the cache/some metrics.
> 
> The cache auto prefetching feature relies on the stats data that is also displayed on the dashboard. This data is on disk and will be used when the server reboots. The auto prefetch however uses only last hour data.

Just confirmed that auto prefetching wont work after the server reboots. The full query stats are not stored on disk but, only the crunched numbers are stored so it doesn't work.
