### ISSUE TITLE
It seems EDNS is not working

### ISSUE THREAD

**Issue by xsy2004** [TechnitiumSoftware/DnsServer#413]
Whether you set all dns resolution requests to be forwarded to upstream Google dns, or cancel the forwarding and request directly to root dns server, edns does not take effect.

The result simply returns the nearest ip address to my server, not the nearest ip address to the requesting user.

I'm sorry to bother you guys, I don't know if it's my settings that are wrong, or if it's a problem with the program.

Note:
Test using DOH to request dns server
EDNS UDP Payload Size is 1232
Version 8.1.3

**Comment by ShreyasZare** [comment]
Thanks for the post. Technitium DNS server supports EDNS but does not implement Extended Client Subnet option.There is no plan yet to add the feature but can be implemented sometime later.

**Comment by xsy2004** [comment]
> Thanks for the post. Technitium DNS server supports EDNS but does not implement Extended Client Subnet option.There is no plan yet to add the feature but can be implemented sometime later.

Thank you for your reply, I hope this feature will appear soon!

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds support for EDNS Client Subnet. Do update and let me know your feedback.
