### ISSUE TITLE
API Add Reserved Lease

### ISSUE THREAD

**Issue by xrxca** [TechnitiumSoftware/DnsServer#416]
It would be nice if you could add a single new reserved lease from the API without having to send the entire existing list using the setDhcpScope option.

Also a minor error in the documentation, the example URL for setDhcpScope contains 
`&reservedLeases=00-00-00-00-00-00;192.168.1.10;comments&`
Which based on the docs and testing is wrong on two counts, first incorrect number of parameters (missing hostname), and second using `;` instead of `|`, the section should be:
`&reservedLeases=hostname|00-00-00-00-00-00|192.168.1.10|comments&`

Other portions of the example also do not match the docs using `;` instead of `|` (staticRoutes and exclusions),

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will look into adding additional API calls to manage reserved leases. Will get the docs fixed soon.

**Comment by ShreyasZare** [comment]
The API docs have been fixed. API call to manage reserved lease will come in a later release.

**Comment by ShreyasZare** [comment]
API for adding and removing reserved lease is now available. Check the API docs for them. Let me know if its good.
