### ISSUE TITLE
DNS APP in Conditional Forward Zone

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/DnsServer#419]
I wanted to add the What Is My DNS app functionality to my CF Zone, but APP is not an available type it appears.

Is there a design reason/limitation or can this be added?

**Comment by ShreyasZare** [comment]
Thanks for asking. APP types are only available with primary (and secondary) zones. Conditional forwarder zones are not authoritative and thus lack SOA record which is sometimes required when processing APP records.

If you need APP record then create a primary zone for that specific domain name and use it with it.

**Comment by djarbz** [comment]
That is what I ended up doing.
