### ISSUE TITLE
Please make this app work with windows 32bit

### ISSUE THREAD

**Issue by rustforfuture** [TechnitiumSoftware/DnsServer#420]
Hello
i installed .net runtime 6.0.6 and also other requirements that was written in download page (that redirected to Microsoft website) then installed dns server but it shows error.

I also tested running executable file of portable version after uninstalling setup and restating pc but it shows same error.
Error:
The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program and then contest the software publisher.

Please make it to work if may please.

Thank you very much.

**Comment by ShreyasZare** [comment]
Thanks for the post. Which exact windows version are you trying to install the DNS server on?

**Comment by ShreyasZare** [comment]
Thanks for the details. The setup not working could be due to some missing updates to Windows 7. If possible do install all the updates and try again.

A better way could be to install Ubuntu on the laptop if you are familiar with Linux since using very old and unsupported OS like Win7 is a security risk.

**Comment by ShreyasZare** [comment]
> Can I ise this portable version with that start.bat and maybe in a way, automate its run when system boots?

Yes you can use the portable version too. Its exactly same except that the setup version creates a windows service which starts automatically when windows boots.

> If i can may you please say where i can do this?

You can try using the Windows Task Scheduler where you create a task to run the start.bat on startup.

> Also about software updates, can i backup my configurations then press ctrl+c then close cmd windows and then just remove the folder of the dns server and then extract and copy the new version and run start.bat without doing anything else?

If you backup settings from the DNS web console with all options selected then the zip file you get is essentially the config folder that the DNS server uses. So, you can take that backup or just copy the config folder and use it again anywhere on the same computer or even a different computer.

> Thank you very much for this great software, it is really a life saver.

You're welcome.
