### ISSUE TITLE
[Feature Request] Allow sslip.io like hostname resolution

### ISSUE THREAD

**Issue by jnehlmeier** [TechnitiumSoftware/DnsServer#421]
Would be nice to have an option to define a wildcard subdomain that resolves hostnames with embedded IP to that IP, just like sslip.io does. Or is it already possible and I haven't found it?

See: https://sslip.io

**Comment by ShreyasZare** [comment]
Thanks for the post. Its not possible to do that currently but, this can be achieved by creating a new DNS App. Will try to add an app for this.

**Comment by bmacao** [comment]
Hi, i've made an app for that, check it out , https://github.com/bmacao/technitium_IpWildcard , it maybe fit your needs.

**Comment by ShreyasZare** [comment]
New app called "Wild IP" is now available when you update DNS server to v9.0.
