### ISSUE TITLE
Error! SQLite Error 11: 'database disk image is malformed'.

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#427]
Error! SQLite Error 11: 'database disk image is malformed'.

this show me when i use sqllite to show the connection tracking between two date like
2022-07-02 11:00:02 and 2022-07-03 11:00:02

**Comment by ShreyasZare** [comment]
Thanks for the post. The error means the sqlite db file is corrupt so you will need to create a new file and delete old one. You can edit the app's config and change the file name in there to create a new file.

**Comment by muhanadali100** [comment]
> Thanks for the post. The error means the sqlite db file is corrupt so you will need to create a new file and delete old one. You can edit the app's config and change the file name in there to create a new file.

i will test this thanx
