### ISSUE TITLE
Can we have dns over quic ?

### ISSUE THREAD

**Issue by Techguyprivate** [TechnitiumSoftware/DnsServer#43]
I know that right now , it is not implemented , but there are some servers supporting dns over quic . One is google. Also I want to have my own server so that I can test that. So can we have dns over quic support ? I read that it is fast, with low latency . It is basically dns over udp, but secure, encrypted. So for a pure theoratical purposes or testing purposes .Thank you in advance.

**Comment by ShreyasZare** [comment]
Its too early. Only Google has gQUIC deployed widely as they control both the web server and web browser. The IETF QUIC version is still under development and I don't think it will be ready quickly. 

It implements the transport mechanism like TCP and has multiplexed streams like HTTP/2, combined with TLS like encryption built into the protocol itself. 

It will take time to have a portable library available for it in .NET Standard. Until then its not feasible to add the feature to the DNS Server.

Meanwhile there are some QUIC reverse proxies that you can try to use with the DNS Server.
