### ISSUE TITLE
[Feature Request] Environment variable for blocklist

### ISSUE THREAD

**Issue by MVlaar-GH** [TechnitiumSoftware/DnsServer#433]
According to [the documentation](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DockerEnvironmentVariables.md), you can enable blocking. To roll out completely automated it would be nice if there's also a variable for setting which blocklist we actually want to use.

**Comment by ShreyasZare** [comment]
Environment variable for block list is now available with v9.0 release.
