### ISSUE TITLE
Request to add support for edns subnet client ip

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#436]
At present, the global DNS that supports edns subnet client ip is Google and 9.9.9.11, so if you use this project as a dns server, the effect is more beautiful

**Comment by ShreyasZare** [comment]
Thanks for the post. This is the same with this [earlier issue](https://github.com/TechnitiumSoftware/DnsServer/issues/413). Its not planned yet but can be implemented later.

**Comment by thb007** [comment]
> Thanks for the post. This is the same with this [earlier issue](https://github.com/TechnitiumSoftware/DnsServer/issues/413). Its not planned yet but can be implemented later.

ok,thanks

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds support for EDNS Client Subnet. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
> Version 10 is now released that adds support for EDNS Client Subnet. Do update and let me know your feedback.

ok I will update the test to see, thank you for your efforts
