### ISSUE TITLE
Conditional Forwarder Zone

### ISSUE THREAD

**Issue by thb007** [TechnitiumSoftware/DnsServer#439]
How to Import a Large Number of Conditionally Forwarded Domain Names

**Comment by ShreyasZare** [comment]
Thanks for asking. There is no built in option to do that. You will need to write a script that uses the HTTP API to create those zones.

**Comment by thb007** [comment]
> Thanks for asking. There is no built in option to do that. You will need to write a script that uses the HTTP API to create those zones.

I don't know how to write, can you teach me how to write?

**Comment by ShreyasZare** [comment]
> > Thanks for asking. There is no built in option to do that. You will need to write a script that uses the HTTP API to create those zones.
> 
> I don't know how to write, can you teach me how to write?

Well, that is not possible for me. I would suggest that you take a look at learning bash or python, and use this as a project to learn it. You will find a lot of learning material for both of them.

**Comment by thb007** [comment]
Do you plan to add the function of importing forwarding domain name lists?

**Comment by ShreyasZare** [comment]
> Do you plan to add the function of importing forwarding domain name lists?

This is a very specific requirement and there are multiple ways someone would want to configure the forwarder zones so having a general feature for it is not feasible. 

Writing a script is the recommended way for such configurations. You can try bash script with curl to make HTTP API calls and then use the jq command to parse the json response from curl to read required values. It wont take long to learn and try it out.
