### ISSUE TITLE
DoT not working on Android

### ISSUE THREAD

**Issue by libDarkstreet** [TechnitiumSoftware/DnsServer#440]
DNS over TLS does not want to work with TLS proxy on android.

I have 2 servers, one does not block anything and the other one does.

I route traffic between the two servers with haproxy based on SNI.

The uncensored DNS server (knot resolver) works fine, but the filtered one (Technitium DNS server) does not work.

When I type the domain name of the filtered dns server into the private dns section on the phone, it does not want to connect. It throws the error "Private DNS server cannot be accessed".

I tried the same solution with PI-hole and it worked perfectly. (But the pi-hole is not very stable...)

The DNS servers are running on TCP port 53, HAproxy adds TLS.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I haven't tried with haproxy but had tried nginx and it works well so it mostly could be some config issue. Please check the DNS server's logs and see if you find any errors that would give a hint about the issue.

You can also try running packet capture tool like Wireshark or tcpdump on the same server running the DNS and inspect the requests that the DNS server receives. This should also tell whats going wrong.

**Comment by libDarkstreet** [comment]
The interesting thing is that DoT works perfectly on all devices and apps except the android built-in Private DNS setting.

I'll try to look into the traffic but it won't be easy since it runs on linux in docker.

I use this config:

```
frontend dns-proxy
  bind :853 ssl crt /usr/local/certs/haproxy/bundle.pem
  mode tcp
  log global
  option dontlog-normal
  tcp-request inspect-delay 1s
  tcp-request content accept if { req_ssl_hello_type 1 }
  
  use_backend bk_dot if { ssl_fc_sni -i uncensored.com }
  use_backend bk_filter if { ssl_fc_sni -i adblock.com }

backend bk_dot
  balance roundrobin
  mode tcp
  log global
  server balancer dnsdist:53 check

backend bk_filter
  balance roundrobin
  mode tcp
  log global
  server filter dns-adblock:53 check
  ```

**Comment by libDarkstreet** [comment]
So I checked the traffic with TCP dump and I found the problem.

When the phone wants to get connected to the DoT it makes many requests to domains like:

`793af2-dnsotls-ds.metric.gstatic.com`
`15e2af2c-dnsotls-ds.metric.gstatic.com`

But these domain names are blocked, so the phone cannot check if the DNS server can resolve domain names.

Thanks for your help!

**Comment by libDarkstreet** [comment]
There is no option not to block subdomains of domains in the list.

For example, in my list I have this domain: `domain.com`
there is no setting to not block `*.domain.com`

This caused the problem. Because I couldn't find the blocked subdomains in my list, only the main domains, but if I want to resolve any subdomain from a blocked domain it will be blocked too.

![Screenshot from 2022-07-26 14-10-12](https://user-images.githubusercontent.com/55440418/181002660-8c1fe60a-1195-4731-9f52-03fc5e094efd.png)

Only the domain name `0x1f4b0.com` is in the list.

**Comment by ShreyasZare** [comment]
Thanks for the details. You can add the `*.domain.com` in the allowed list to allow only the subdomain names while the domain itself is blocked by the blocked list. Try and let me know if that works.

**Comment by libDarkstreet** [comment]
Thanks, unfortunately it is still blocked.

The whitelist contains the domain `*.metric.gstatic.com`, the list has been updated in the admin interface.

![Screenshot from 2022-07-26 15-20-42](https://user-images.githubusercontent.com/55440418/181016039-635548db-e66c-4234-b1a4-8f64b44672f7.png)

**Comment by ShreyasZare** [comment]
If you have this in the allowed list fetched by a URL that is configured with `!` then its not going to work since the allowed list just prevents the domains in blocked list from loading. You need to add the domain in the Allowed list from the Allowed tab in the admin panel.

**Comment by libDarkstreet** [comment]
Okay, it works now, thanks!
