### ISSUE TITLE
[Feature Request] Interface to monitor, blocklist or whitelist domain from Top Domains or Top Blocked Domains table

### ISSUE THREAD

**Issue by itsKV** [TechnitiumSoftware/DnsServer#45]
On dashboard, we can see Top Domains or Top Blocked Domains which are served by server. 
There should be option of blocking particular domain from _Top Domain_ list or of whitelisting particular domain from _Top Blocked Domains_ list.

Also, the list is truncated to only limited number (seems only 10). We can give iframe scrollbar interface for it so that, we can see complete served list. 

Also, we can show which exact query was served (like A, AAAA, MX, PTR or other) with detail. 
Currently, dashboard only shows a pie chart.

**Comment by ShreyasZare** [comment]
Thanks for the feedback.

Do you mean to have an option to hide certain domain names from the Top 10 lists?

There is already a plan to show expanded list for all the tables on dashboard into a modal.

All details on the dashboard are crunched stats. For exact details on queries, you can enable query logging from settings and then see the logs which will list detailed query and response data.

**Comment by itsKV** [comment]
no, I meant to say, an option to block/unblock particular domain name directly from _Top Domains_ List

**Comment by Matthew-Bonner** [comment]
@ShreyasZare I think itsKV has a point, and I'd be happy to pick this up if it helps?

It makes sense to keep the stats as they are when blocking/unblocking a domain, as the stats are a true reflection of the top domains and top blocked domains, if you move a domain between being allowed to being blocked, it should then in theory have a number for the domain in both lists, which might look a bit strange, and may even lead to a bug being reported.

So what should happen in this instance? Is it ok to see the domain appear in both lists, should the domain be removed from the list it was in before the user action was taken, or something else? My preference is that it should appear in both lists, but if we go down this route it might be an idea to give some indication to the user as to why this is, and if you agree with this do you have any suggestions on how you would like this to work?

**Comment by ShreyasZare** [comment]
@Matthew-Bonner: this suggestion by @itsKV will be implemented with a few more features to view an expanded list on the dashboard.

Regarding updating the stats, the stats are read only since its maintaining historic data. Any update to it will skew all historic charts and will give simply show wrong stats like showing that more queries were blocked than the actual value in the case if allowed domain is moved to blocked zone.

With current implementation, the blocked domain will be seen in both lists but as time passes, it will not show up in the top list but would still be visible for historic data.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with new Query Logs (Sqlite) DNS App that can be used to log and query using the GUI available on the DNS web panel to monitor queries with filters.

**Comment by itsKV** [comment]
Awesome Shreyas. 
Thanks.

**Comment by ShreyasZare** [comment]
Version 9.1 is now available that now has options on dashboard to allow/block domain names in the list. Do update and let me know your feedback.
