### ISSUE TITLE
acl view

### ISSUE THREAD

**Issue by w796933** [TechnitiumSoftware/DnsServer#451]
sir  it support  example bind  acl view ?

**Comment by ShreyasZare** [comment]
Thanks for the post. There is ACL support for different things like recursion, zone transfer, etc. Which specific thing you are looking to configure?

**Comment by w796933** [comment]
Authoritative DNS. different isps. Resolving different IP addresses

**Comment by ShreyasZare** [comment]
> Authoritative DNS. different isps. Resolving different IP addresses

If you mean to say that you want to resolve different IP addresses for different ISP users then you can use the Split Horizon app. Use the APP record with Split Horizon where you can specify which network gets which IP as an answer.

**Comment by w796933** [comment]
{
  "public": [
    "1.1.1.1", 
    "2.2.2.2"
  ],
  "private": [
    "192.168.1.1", 
    "::1"
  ],
  "10.0.0.0/8": [
    "10.1.1.1"
  ]
}

if  one isp have  many network . how to seup ?
  "1.1.1.0/8 2.2.2.0/8 3.3.3.0/8": [
    "10.1.1.1"
  ]

is right ?

**Comment by ShreyasZare** [comment]
You cannot combine multiple network addresses. Each one will need a separate entry like:

```
"1.1.1.0/8": [
"10.1.1.1"
],
"2.2.2.0/8": [
"10.1.1.1"
],
"3.3.3.0/8": [
"10.1.1.1"
]
```

To avoid repeating the IP addresses for each of these entries, you can use the CNAME option of the APP record which will allow you to use a domain name in place of the IP and you can manage those A record entries independently.

**Comment by w796933** [comment]
each isp have  many ip  networks . how to  setup  a collection ？

**Comment by ShreyasZare** [comment]
Currently there is no other option to configure it. I will try to figure out if something can be done to make it scale for such scenarios.

**Comment by ShreyasZare** [comment]
So, I gave a thought on this and can add a config to the app to allow specifying a collection of networks which then can be used in the APP record's config. Will try to update this app as soon as then changes are done and tested.

**Comment by ShreyasZare** [comment]
> each isp have many ip networks . how to setup a collection ？

I have updated the app to v3.1 which will now allow to configure a collection of networks. Check the app's config by clicking on the Config button for that app in the Apps section. You will find a `custom-networks` example item in there. Add your ISP networks similar to that example. So you will have ISP1 entry with a list of networks and then ISP2 entry with its own list of networks. Once the config is saved, you can use that network name in your APP record's config.

Let me know if you have any queries with the config.

**Comment by w796933** [comment]
now i try .  so good .  thanks much .

**Comment by ShreyasZare** [comment]
> app store is error . DNS App Store ×Error! The SSL connection could not be established, see inner exception.

It seems some local issue. Try again and see if it works again. If not then you can download the [app's zip file](https://download.technitium.com/dns/apps/SplitHorizonApp.zip) and manually install it using the "Install" button or update the already installed app using the "Update" button for it.

**Comment by w796933** [comment]
okay .  app store is error is fix . 
how to change  SplitHorizonApp   Record Data Template?
I test the app and everything works fine, it's great

**Comment by ShreyasZare** [comment]
> okay . app store is error is fix . how to change SplitHorizonApp Record Data Template? I test the app and everything works fine, it's great

You will have to define your ISP networks in the app's config in the App section. Then use the network name that you configured as the name in the APP record data template. So when a request is received that hits the APP record, the app will find the name in the APP's record data from the networks collection in the config and check for match.

**Comment by w796933** [comment]
i know . and  test  pass . 
Record Data Template
{
  "public": [
    "1.1.1.1", 
    "2.2.2.2"
  ],
  "private": [
    "192.168.1.1", 
    "::1"
  ],
  "custom-networks": [
    "172.16.1.1", 
  ],
  "10.0.0.0/8": [
    "10.1.1.1"
  ]
}

this default  SplitHorizonApp Record Data Template? .  how to change ?

**Comment by ShreyasZare** [comment]
You have to add APP record in your primary zone where you will see the json template that you can edit before adding that APP record.

**Comment by w796933** [comment]
Isp network collection, is there a limit on the number of records?   now add  3 isp . each  isp  3000 networks .  
but it not working . 

Unable to resolve correct IP address.
.

**Comment by ShreyasZare** [comment]
Please share your config for both the APP record and the app's config. You can email them if you wish to ***@***.***

**Comment by w796933** [comment]
now is work .  is json  format error . sorry .

**Comment by ShreyasZare** [comment]
Good to know that its working well.
