### ISSUE TITLE
Support TLSA records

### ISSUE THREAD

**Issue by renne** [TechnitiumSoftware/DnsServer#453]
TLSA records enforce TLS encryption and verify TLS certificates in [DNS-based Authentication of Named Entities](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities).

Currently this is mainly used for TLS connections between mail-servers and is a requirement to get the german national data privacy seal for mail-servers.

Please add TLSA-RRs in Technitium DNS server.

**Comment by ShreyasZare** [comment]
Thanks for the request. TLSA is already planned to be implemented and available in an update after the current major update which will be released in a couple of weeks.

**Comment by zcyph** [comment]
Hello,
Is this feature still coming? I just realized I cannot switch some of my domains over without this

**Comment by ShreyasZare** [comment]
> Hello, Is this feature still coming? I just realized I cannot switch some of my domains over without this

Yes, its already tested and coming in the next update mostly by this month end.

![image](https://user-images.githubusercontent.com/10008172/201579811-d54bfef6-4922-45cd-bf05-8e65194c6279.png)

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds DANE TLSA record support. Do update and let me know your feedback.

**Comment by garylavayou** [comment]
The TLSA type cannot be seen from the drop-down list of "Type", as shown in the screenshot below:

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/d148d7ef-7dbb-4d91-842f-9d1c423ee432" />

If I open the drop-down and enter "T", then "TLSA" will show in the select box. Is this dialogue window too small to show all the options of the drop-down list?

> **P.S.** I am using the version 14.3.

**Comment by ShreyasZare** [comment]
@garylavayou You need to DNSSEC sign your zone to enable TLSA record support.
