### ISSUE TITLE
Advanced Blocking App cannot parse blocklist

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#457]
Hi!
I'm trying to configure `Advanced Blocking` for LAN. Here is config
```
{
  "enableBlocking": true,
  "blockListUrlUpdateIntervalHours": 24,
  "networkGroupMap": {
    "10.10.10.0/24": "LAN",
    "0.0.0.0/0": "everyone"
  },
  "groups": [
    {
      "name": "everyone",
      "enableBlocking": false,
      "allowTxtBlockingReport": true,
      "blockAsNxDomain": false,
      "blockingAddresses": [
        "0.0.0.0",
        "::"
      ],
      "allowed": [],
      "blocked": [
        "example.com"
      ],
      "allowListUrls": [],
      "blockListUrls": [],
      "allowedRegex": [],
      "blockedRegex": [
        "^ads\\."
      ],
      "regexAllowListUrls": [],
      "regexBlockListUrls": [],
      "adblockListUrls": []
    },
    {
      "name": "LAN",
      "enableBlocking": true,
      "allowTxtBlockingReport": true,
      "blockAsNxDomain": false,
      "blockingAddresses": [
        "0.0.0.0",
        "::"
      ],
      "allowed": [],
      "blocked": [],
      "allowListUrls": [],
      "blockListUrls": [
        "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt"
      ],
      "allowedRegex": [],
      "blockedRegex": [],
      "regexAllowListUrls": [],
      "regexBlockListUrls": [],
      "adblockListUrls": []
    }
  ]
}
```

Block list loaded but only 41 domains parsed. This is not a valid blocklist format or I'm doing something wrong?

**Comment by ShreyasZare** [comment]
Thanks for the post. You need to use this type of block lists with the `adblockListUrls` option which is able to parse the format.

**Comment by Globulopolis** [comment]
Ok. Added this list into `adblockListUrls`. Now 141 domains parsed. But when I request e.g. `ibs.lgappstv.com` from `DNS Client` tab I got the wrong response. I think it should return 0.0.0.0 as it configured in `Settings - Blocking` options?
Response
```
{
  "Metadata": {
    "NameServer": "server (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "468 bytes",
    "RoundTripTime": "232.25 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NoError",
    "Version": 0,
    "Flags": "None",
    "Options": [
      {
        "Code": "PADDING",
        "Length": "364 bytes",
        "Data": {
          "Data": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        }
      }
    ]
  },
  "DnsClientExtendedErrors": [],
  "Identifier": 59899,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": true,
  "RCODE": "NoError",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 1,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "ibs.lgappstv.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [
    {
      "Name": "lgappstv.com",
      "Type": "SOA",
      "Class": "IN",
      "TTL": "10 (10 sec)",
      "RDLENGTH": "43 bytes",
      "RDATA": {
        "PrimaryNameServer": "prmns.lg.co.kr",
        "ResponsiblePerson": "root@prmns.lg.co.kr",
        "Serial": 2022083101,
        "Refresh": 86400,
        "Retry": 3600,
        "Expire": 604800,
        "Minimum": 10
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "368 bytes",
      "RDATA": {
        "Options": [
          {
            "Code": "PADDING",
            "Length": "364 bytes",
            "Data": {
              "Data": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
            }
          }
        ]
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

**Comment by ShreyasZare** [comment]
> Ok. Added this list into `adblockListUrls`. Now 141 domains parsed. But when I request e.g. `ibs.lgappstv.com` from `DNS Client` tab I got the wrong response. I think it should return 0.0.0.0 as it configured in `Settings - Blocking` options? Response

The Advanced Blocking app and the Blocking Settings are totally independent of each other. You should either use the built in blocking system or use only the Advanced Blocking app to avoid confusion.

The config you posted has the block list set for `LAN` group which is mapped to `10.10.10.0/24` network. So, the blocking will work only when you test from that network. If you use the DNS Client tab then its going to use `127.0.0.1` as its IP address which will not match with the network map for LAN group in the app's config.

**Comment by Globulopolis** [comment]
> DNS Client tab then its going to use `127.0.0.1` as its IP

This is the main thing.

So the `blockingAddresses` this is response addresses for blocked domains?

**Comment by ShreyasZare** [comment]
> > DNS Client tab then its going to use `127.0.0.1` as its IP
> 
> This is the main thing.
> 
> So the `blockingAddresses` this is response addresses for blocked domains?

No. The `blockingAddresses` is going to be the one configured for the `LAN` group. Check the `LAN` group's json config for the blocking addresses array. Each group has its own independent config options.

Like I said earlier, you have to test if the domain is blocked from some client on `10.10.10.0/24` network using nslookup command or similar.

**Comment by Globulopolis** [comment]
> Like I said earlier, you have to test if the domain is blocked from some client on `10.10.10.0/24` network using nslookup command or similar.

Yes, it's work.

Maybe some documentations available for app options? It's really hard to understand and tune raw options.

**Comment by ShreyasZare** [comment]
> > Like I said earlier, you have to test if the domain is blocked from some client on `10.10.10.0/24` network using nslookup command or similar.
> 
> Yes, it's work.
> 
> Maybe some documentations available for app options? It's really hard to understand and tune raw options.

Unfortunately there is no documentation available. There is a plan to add UI option for apps so that you wont have to edit the raw json config directly. So, that feature should help making it easier to configure the app.
