### ISSUE TITLE
Homeassistant addon

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#458]
Trying to create this as an addon in homeassistant, (from Docker Hub)

I can run it but not keep peristant data

unable to run run.sh

COPY run.sh /
RUN chmod a+x /run.sh
CMD [ "/run.sh" ]

**Comment by ShreyasZare** [comment]
I am not familiar with Homeassistant so wont be able to provide an exact solution. You will have to manage to add a volume to the docker container to keep the data persistent in there not sure of the steps though.

**Comment by ChristoffBo** [comment]
Hi could you create an image that would allow me to set  configuration directory via an environmental variable.

Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
Just pass the directory as a command line argument when running the DNS server and it will use that directory for the config.

**Comment by ChristoffBo** [comment]
Thank you if I knew how I would I'm a bit of a noob. Will see if I can figure it out. Thank you

Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
Its quite straight forward. Since you are running a shell script, you must be running the dotnet command. So just add the path to it as shown below:

`dotnet DnsServerApp.dll "/path/to/config/dir"`

**Comment by ChristoffBo** [comment]
Currently my sh.run looks like this:

#! /usr/bin/with-content bashio
mkdir -p /data/technitium
ln -s /data/technitium /etc/dns/config
/usr/bin/dotnet /etc/dns/DnsServerApp.dll

But my container or add won't start

Christoff Bothma
Sent From Mobile
________________________________

**Comment by ChristoffBo** [comment]
This is the answer I got from one of the homeassistant addon developers


The issue is the docker file you are using wants to store configuration in: /etc/dns/config/ and wants you to create a volume to do so (you can see in https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml) . But you cant with homeassistant. Getting this to work is hit and miss,. You could try to create a symbolic link. Thus your run.sh<http://run.sh/> should try to:
mkdir -p /data/technitium (you did this)
ln -s /data/technitium /etc/dns/config/ (or vice versa, I forget)
/usr/bin/dotnet /etc/dns/DnsServerApp.dll (I think you need this, but maybe not)

This is a common issue. Again, the link method might not work and is a pain as you need to rebuild the addon every time to test it. You could also email the author of technitium and ask him/her to allow setting the configuration directory via an environmental variable. Then you could set it to whatever you want. that would be much easier. Good luck


Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
Just try the one given below:
```
#! /usr/bin/with-content bashio
mkdir -p /data/technitium
/usr/bin/dotnet /etc/dns/DnsServerApp.dll /data/technitium
```
This will make the DNS server use the given path and not touch the default `/etc/dns/config` directory.

**Comment by ChristoffBo** [comment]
Hi, no still does not start

Tried it like this aswell


#! /usr/bin/with-content bashio

CONFIG_PATH=/data/
mkdir -p /data/technitium
/usr/bin/dotnet /etc/dns/DnsServerApp.dll /data/technitium


Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
I am not sure about this since have never used Home assistant. Probably someone from the [/r/homeassistant](https://www.reddit.com/r/homeassistant/) community will be able to help with the setup. The fix should be generic to running any docker image that requires persistence so someone who has any docker container running with a volume will be able to help here.

**Comment by ChristoffBo** [comment]
Finally got it working using manual install and a base debian docker. Thanks for your assistance. Only issue is that my script will download and install the latest portable everytime it restarts but that's fine I guess makes it easier to update to the latest version. Also I have persistent storage. Thanks again

**Comment by ChristoffBo** [comment]
Yea, I also thought that but if there is no internet connection it's seems to still install it.. Not sure how or why because it still runs?

If you get bored at some point you can have a look on my github Repo and make any changes or advise if you want. Github/Christoffbo/Hassio but at least it's running now. It's basically the backbone dns at my house. I have 2 adguard servers that connect to it via port 5335. Over kill or unnecessary but I love your server that much it's awesome.

Also adguard has integrations for homeassistant so you can stop and start blocking. And my wife uses that function alot.

**Comment by ShreyasZare** [comment]
Thanks for the details. Closing this issue. Reopen if needed.

**Comment by frostworx** [comment]
technitium landed on [ycombinator](https://news.ycombinator.com/item?id=39024148).
Possibly some other people are looking for home assistant compatibility as well and find this issue,
so leaving the direct url to @ChristoffBo project here:

https://github.com/ChristoffBo/homeassistant

Haven't tested anything yet, but thank you both for your work :)
