### ISSUE TITLE
Dashboard: Use Local Time

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/DnsServer#460]
This is just a feature request to have the dashboard show local time rather than UTC.
I have verified that my docker container is showing the local time zone on the shell.

**Comment by ShreyasZare** [comment]
The dashboard currently uses data in the server's local timezone. Can you confirm that when you set logs to use Local Time in Settings, do you see the correct local time for logs?

**Comment by ShreyasZare** [comment]
New update v9.1 is now available that will always show client's local timezone for the main chart instead of server timezone. To test and let me know your feedback.

**Comment by djarbz** [comment]
Works great! Thanks!
