### ISSUE TITLE
[Error] TSIG Key not found for new Secondary Zone

### ISSUE THREAD

**Issue by stefan-ffr** [TechnitiumSoftware/DnsServer#463]
Hi everyone
Since the Version 9.0 I'm, getting errors when I try to create a secondary zone, even with these zones who hasn't TSIG Keys.
Has anyone a clue whats happening here?
Greetings Stefan

**Comment by ShreyasZare** [comment]
Thanks for the post. Yes, this is a bug in the web panel that got introduced in the last update. A fix for this is coming soon.

The TSIG drop down in the Add Zone dialog is not getting initialized causing this error. There is a immediate workaround for this which is to just click on the Settings tab once which reloads the settings and initializes the TSIG drop down, then proceed to add the zone.

**Comment by ShreyasZare** [comment]
This issue is fixed with v9.1 release. Do update and let me know your feedback.
