### ISSUE TITLE
Dns rewrite

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#466]
Hi, can technitium do dns rewrites? I have use self hosted bitwarden and it points to My duckdns so when I'm on my internal network I need to rewrite my duckdns url to my local bitwarden?

**Comment by ShreyasZare** [comment]
Yes, you can do that using Conditional Forwarder zones. Just create a forwarder zone for the domain name and select "This Server" as the forwarder so that all requests for the zone get forwarded to the local DNS server just like normal except for any records that you add to that zone. So, if you add an A record, it will be returned in the response while any other request will get forwarded internally and will resolve as usual.

**Comment by ChristoffBo** [comment]
Thank you will do so. Awesome software, replaced my adguard servers with your much better just a bit of a learning curve.

Christoff Bothma
Sent From Mobile
________________________________

**Comment by ChristoffBo** [comment]
Hi, Last question, is it possible to have the server keep something in cache permanently as in always prefetch even if there is no hit per hour? Say like github.com to always have it cached and prefetching?

**Comment by ShreyasZare** [comment]
There is no option available to do that. Is there any specific scenario for which you are looking for this option?

**Comment by ChristoffBo** [comment]
Hi, was thinking that since the cache isent persistent across reboots you could add a few site or addresses you want permanently cached. So everytime you restart the server will cache those sites and your ready to rock, please see attached. I added the forwarder zone but it does not seem to work. I probably did something wrong.

Christoff Bothma
Sent From Mobile
________________________________

**Comment by ShreyasZare** [comment]
Its actually recommended to not reboot DNS server that is running as a recursive resolver for this reason. Saving cache on DNS server shutdown is also not much feasible since the process can get killed midway while the OS reboots.

The attached screenshot in email didn't get posted on github. Do post on github from web or email them to support@technitium.com.

**Comment by echodreamz** [comment]
Saving cache really should be implemented. Reboots have to happen... the server cannot just run forever, new builds of the software, .net updates, OS updates etc. have to be performed.

You also run into the issue of paid queries, such as RBL lookups for mail servers, where we pay for up to x thousands of queries, rebooting the server loses those cached records which means they must be queried again when they really shouldnt have been.

SimpleDNS writes its cache, Bind can be configured to write its cache, Knot Resolver, from what I can tell, can also write its cache.

It is a very useful feature to have such data saved.

**Comment by ShreyasZare** [comment]
> Saving cache really should be implemented. Reboots have to happen... the server cannot just run forever, new builds of the software, .net updates, OS updates etc. have to be performed.
> 
> You also run into the issue of paid queries, such as RBL lookups for mail servers, where we pay for up to x thousands of queries, rebooting the server loses those cached records which means they must be queried again when they really shouldnt have been.
> 
> SimpleDNS writes its cache, Bind can be configured to write its cache, Knot Resolver, from what I can tell, can also write its cache.
> 
> It is a very useful feature to have such data saved.

Thanks for the feedback. Will evaluate this and try to get it implemented.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which now supports saving DNS cache to disk and also adds Advanced Forwarding app that supports Adguard config that you may find interesting. Do check and let me know your feedback.

**Comment by ChristoffBo** [comment]
Hi,

So in advanced forwarding I just add the below and it will forward my
clients through my proxy?

{
  "enableForwarding": true,
  "proxyServers": [
    {
      "name": "local-proxy",
      "type": "socks5",
      "proxyAddress": "10.0.0.100",
      "proxyPort": 9050,
      "proxyUsername": null,
      "proxyPassword": null
    }
  ],

**Comment by ShreyasZare** [comment]
> Hi, So in advanced forwarding I just add the below and it will forward my clients through my proxy? 
> ```{ "enableForwarding": true, "proxyServers": [ { "name": "local-proxy", "type": "socks5", "proxyAddress": "10.0.0.100", "proxyPort": 9050, "proxyUsername": null, "proxyPassword": null } ],```

The proxy option in the app when configured will make the DNS server use that proxy to query the forwarder to resolve the domain name. 

The clients wont get their HTTP request out through it unless you configure your client web browser independently to use that proxy server.
