### ISSUE TITLE
DNS failing to resolve "new websites" and some others

### ISSUE THREAD

**Issue by Deiity** [TechnitiumSoftware/DnsServer#468]
Hi,

Before posting this, i'd like to say thank you for this awesome software.

I have noticed only one issue happening from time to time: Sometimes when im using recursive DNS, broswer fails to resolve NS and i need to hit refresh 10-15 times in firefox/chrome in order to resolve it. Going trough logs i haven't noticed anything weird...

I'm getting messages like this:

NS Server failed to resolve the request with QNAME: google.com; QTYPE: DS; QCLASS: IN;
TechnitiumLibrary.Net.Dns.DnsClientException: DnsClient recursive resolution exceeded the maximum stack count for domain: google.com

And after i hit refresh a couple of times, broswer resolves it ,caches and then its working until its cache expires.

Similar thing for a famous website kupujemprodajem.com

[2022-10-10 11:27:31 UTC] [178.220.222.134:61285] [UDP] QNAME: www.kupujemprodajem.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [www.kupujemprodajem.ha.rs., 185.29.102.50]
[2022-10-10 11:27:31 UTC] [178.220.222.134:49585] [UDP] QNAME: www.kupujemprodajem.ha.rs; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [185.29.102.50]
[2022-10-10 11:27:31 UTC] [178.220.222.134:59150] [UDP] QNAME: www.kupujemprodajem.ha.rs; QTYPE: AAAA; QCLASS: IN; RCODE: NoError; ANSWER: []

Any idea how i can troubleshoot this one? Happening on iOS / Windows and Linux device so its not device specific...

Thank you

**Comment by Deiity** [comment]
Hi,

Nah, that's not the case.

nslookup google.com 1.2.3.4
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  1.2.3.4

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out

Any idea how i can troubleshoot futhermore? I tried enabling query logging but still there isn't anything weird there. Tried with 2 separate ISP's and the issue is same.

Thank you

**Comment by ShreyasZare** [comment]
The nslookup command test can only confirm hijack if there is a response. If there is no response then it does not prove that there is no hijack.

The issue you mention is not reproducible as the domain names are resolving here as expected. You can test using the [dnsclient.net](https://dnsclient.net) website which uses the exact same code to do recursive resolution.

I would still recommend that you use a DoT/DoH encrypted DNS forwarder which will mitigate the issues you see.

**Comment by Deiity** [comment]
Just to confirm, best approach would be to enable forwarder DNS server to use DoT encryption? 


![image](https://user-images.githubusercontent.com/11446302/195621107-7959b928-8a92-4149-92e1-acb7939b520f.png)

**Comment by ShreyasZare** [comment]
Yes, since recursive resolution is not working on your network, just use any of the available public DNS providers like Cloudflare, Google, Quad9, etc. with DoT or DoH.

**Comment by NenadQC** [comment]
Still the same, issue is persistent. Could it be that recursion has some issues? Im hosting DNS server on VPS with stable network & latency so thats out of question... any idea?

**Comment by Deiity** [comment]
Still the same, issue is persistent. Could it be that recursion has some issues? Im hosting DNS server on VPS with stable network & latency so thats out of question... any idea?

For example,

[2022-10-13 16:06:24 UTC] [ip:15413] [UDP] QNAME: www.mapcrunch.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
[2022-10-13 16:06:24 UTC] [ip:15413] [UDP] QNAME: www.mapcrunch.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
[2022-10-13 16:06:25 UTC] [ip:15413] [UDP] QNAME: www.mapcrunch.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []

After couple of refreshes in broswer, works properly..

Same for 

[2022-10-13 16:09:25 UTC] [ip:22857] [UDP] QNAME: openpuppies.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
[2022-10-13 16:09:25 UTC] [ip:22857] [UDP] QNAME: openpuppies.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []
[2022-10-13 16:09:26 UTC] [ip:22857] [UDP] QNAME: openpuppies.com; QTYPE: A; QCLASS: IN; RCODE: ServerFailure; ANSWER: []

**Comment by ShreyasZare** [comment]
This is quite normal operational issue with running recursive resolver be it Technitium DNS server or any other DNS server software.

When you query for a domain that is not in cache, the recursive resolver has to make multiple requests to resolve it. The name servers for that domain name may be geographically far that adds to delays. Something the name server do not respond quick enough or there are packet drop issues causing timeout. This means the recursive resolver has to retry multiple times.

The DNS server has to respond to the requests meanwhile its trying to resolve it in the background so it returns a ServerFailure response.

If you keep the DNS server running and don't restart it often then after a couple of days, most of the common domain names and their name servers would have been cached so this issue would become rare.
