### ISSUE TITLE
[quest] A DHCP reserved lease is bypassed in favor of a new dynamic address

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#475]
I have a (new) device on my network which I assigned a static IP to using the DHCP panel. It made a dynamic reservation from which I then copied the MAC address and created a static reservation. I then ran `dhclient -r; dhclient` on the device which renewed the DHCP IP and received my new static address.. All is well.

Something weird has now happened twice. First, it happened when I installed the software I want, which triggered a reboot - when it started up, it got a new IP which was unexpected. I managed to find the new IP and connect to it, run the `dhclient` again and got back to my reserved IP.. Then again during the night, it didn't reboot, but it did get an entirely new IP. 

It seems that when a DHCP cycle runs, this device gets new addresses despite my reservation. In the DHCP leases I now have this screenshot below. The `.0.103` is entirely new and has never been assigned to this before, yesterday it got `.0.120` - so it's not even because the device insists on `.0.103`.. 

What can I get to help this?
Again, if I run `dhclient -r; dhclient`, it gets the reserved address. :|

![image](https://user-images.githubusercontent.com/1027111/196654781-cd35c12a-3e97-4851-9fa1-8d0029b03263.png)

Update: I had to reboot the device, so I started a tcpdump on the DNS server. On this reboot, it got the expected address, so it showed nothing.. But I'm leaving this tcpdump running, hopefully if it ditches me again sometime today I can get back to it..

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will try to reproduce this issue and let you know.

**Comment by ShreyasZare** [comment]
I just ran a ubuntu server VM and tried it and got it to reproduce the issue.

When `dhclient -r; dhclient` is used, the DHCP request is missing the Client Identifier (Option 61) upon which the DHCP server will use the MAC address as the unique identifier for the client. So, now the DHCP server matches the client with the reserved lease using the MAC address and will give it the reserved IP address lease.

When the OS (systemd) tries to get an IP allocation by itself, it sends an Client Identifier (Option 61) in the DHCP request which is then used to uniquely identify that client. So, now as per the DHCP server, this is a completely different client. It will try to find the reserved lease for its MAC address but that lease is already in use by "another" client. So, the DHCP server hands over a dynamic lease to the "current" client request.

The solution to this issue is basically to not use the `dhclient -r; dhclient` command. Disabling the network interface and enabling it back will trigger DHCP request and that should work as expected.

**Comment by LordMike** [comment]
Oooh.. Was just about to add another to the list. A debian install that now has two dynamic leases (I renamed it between reboots). I assume this too has had the Client Identifier option set in one or both cases which must then have been different.

![image](https://user-images.githubusercontent.com/1027111/196799457-a15202a3-90df-427a-97f3-738147b3cd9b.png)

In my case, the desired IP is the reserved one, since it's receiving a dynamic one on interface up - and the reserved on `dhcli..`, that's purely a coincidence - as I myself ensured that the reservation was in use by my manual action.. I should just have rebooted and everything would've been fine.

Is a warning logged when a client comes in asking for a reserved address, that is in use by another client?

**Comment by LordMike** [comment]
Would it make sense to show this identifier in the leases tab?
It would make sense since the thing "identifying" the client is no longer the MAC, but the provided identifier..

Could reservations be made on the identifier instead of the MAC?

**Comment by ShreyasZare** [comment]
> Is a warning logged when a client comes in asking for a reserved address, that is in use by another client?

There is no warning logged in for this.

> Would it make sense to show this identifier in the leases tab? It would make sense since the thing "identifying" the client is no longer the MAC, but the provided identifier..

The client identifier is usually random bytes that can be of varying lengths. The API returns the actual client identifier in the response but showing it in the UI will take up a lot of space.

> Could reservations be made on the identifier instead of the MAC?

Its possible to have a way to do that but no user will be able to figure out the client identifier for a given device unless they use something wireshark and read the packet. I am not sure where the client identifier is stored by systemd and any such config will vary for each platform. Plus entering a large hex string will make it difficult to configure it. 

Compared to that, using a MAC address is much easier as its known for most devices like a switch or a router will have its MAC address printed on a label below the device. And on any platform, finding out MAC address is much easier too.

**Comment by LordMike** [comment]
I think a warning might be useful, maybe the first time it occurs for a reservation. It can be tricky to troubleshoot why a reservation doesn't work (like in my case).

I'm thinking something like this for display:
![image](https://user-images.githubusercontent.com/1027111/196939089-14a9e001-32bf-4925-a00f-fae1e4892fa2.png)

Smaller text, grayed out so it doesn't strike a lot, and only visible if the client identifier is actually provided. This is of course a requirement before any reservation can be made with the client identifier, as of course no user can find the identifier without this display. :)

**Comment by ShreyasZare** [comment]
> I think a warning might be useful, maybe the first time it occurs for a reservation. It can be tricky to troubleshoot why a reservation doesn't work (like in my case).

Will try to add some logging for this.

> I'm thinking something like this for display: ![image](https://user-images.githubusercontent.com/1027111/196939089-14a9e001-32bf-4925-a00f-fae1e4892fa2.png)
> 
>   * Smaller text
> 
>   * Grayed out so it doesn't strike a lot
> 
>   * Only visible if the client identifier is actually provided
> 
>   * If the text is long, use [text-overflow: ellipsis](https://www.w3schools.com/csSref/css3_pr_text-overflow.asp) to ensure it stays short

The client identifier when specified by the device is quite large string. When its not specified, a mock up client id that uses MAC address is used which looks short. So when its present, it will get only partly displayed most of the time.

> This is of course a requirement before any reservation can be made with the client identifier, as of course no user can find the identifier without this display. :)

I am not getting how having option to configure reserved lease with client id help fix this issue. Even if you could have it, you will still have this issue where systemd uses client id option and the dhclient command doesn't so its always two different clients. When using MAC address for reserved leases, both cases match the reserved lease and whatever request that comes first, with or without client id option, it gets the reserved lease assigned.

**Comment by LordMike** [comment]
Hmm … that makes sense .. so reservations are never on client identifier?

I wonder what the purpose of the identifier even is then.

Mike.
________________________________

**Comment by LordMike** [comment]
I found an HP guide to a dhcp server where you can add reservations based on the client identifier. So they at least use it that way. :)

Anyhoo. A warning would help identifying when reservations don't work for some reason. Something like "would have used reservation A, but could not due to ..."

Mike.
________________________________

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds warning logs messages as discussed. Do update and let me know your feedback.
