### ISSUE TITLE
[feature] Ability to specify FQDN's in DHCP NTP server setting

### ISSUE THREAD

**Issue by LordMike** [TechnitiumSoftware/DnsServer#477]
I was looking over the DHCP options and found that it might make sense to configure an NTP server - but then found that I _have_ to specify IP's (because that's what the DHCP protocol needs).

Would it make sense to provide FQDN's as well, and then when a DHCP request is made, the DNS client is used to resolve the addresses first?

This allows me to put in `dk.pool.ntp.org` (which rotates often) or even a local hostname, and then DHCP clients will always get some IP's (limited to some set, I guess ..)

**Comment by ShreyasZare** [comment]
Thanks for the post. The NTP server (option 42) only allows for IP address. There is no way to specify domain name for NTP with DHCP as I haven't seen any such option that supports it.

The usual way this NTP option is used is to setup a NTP server on your local network that is configured with the domain name of the upstream NTP server, an use this local server's IP address in your DHCP config.

**Comment by LordMike** [comment]
That’s why I imagined you could resolve the FQDN using the dns client in the server. The cache would ensure you don't need to do the actual query too often.

The only drawback here is that the lifetime of the ntp address goes from whatever ttl is set on the dns response to whatever lifetime is set on the dhcp response. So if someone has fast changing ntp servers, they would become stale.

Mike.
________________________________

**Comment by ShreyasZare** [comment]
> The only drawback here is that the lifetime of the ntp address goes from whatever ttl is set on the dns response to whatever lifetime is set on the dhcp response. So if someone has fast changing ntp servers, they would become stale.

Ya, thats the main concern when the NTP server address changes and the DHCP lease is in multiple days. So the client will fail to sync time until the DHCP lease is refreshed.

**Comment by LordMike** [comment]
In my opinion - the benefit of being able to change the ip of an ntp server by changing the dns record and then having dhcp client auto update outweighs any risk that an ntp server changes often.

So I’m still in favor :)

A warning on the setting could do though.

Mike.
________________________________

**Comment by ShreyasZare** [comment]
> In my opinion - the benefit of being able to change the ip of an ntp server by changing the dns record and then having dhcp client auto update outweighs any risk that an ntp server changes often.

The problem is that DHCP clients cannot be notified about any updates by the DHCP server. There is no such provision in the protocol to push changes. This means if the lease is of 7 days then most DHCP clients would refresh lease only after 3.5 days.

**Comment by LordMike** [comment]
Yes - and that’s fine, in my opinion. Because they do refresh eventually. The warning I imagine will be in place will describe this scenario - but for the most part it will be irrelevant as most ntp servers will never change their ip.

If they do. It’s probably ok that it takes a few days for all clients to catch up.

In my use case, I’d like to set all my clients to use servers from the public ntp pool. These come as domains that automatically update to include some servers in the pool. I could of course just resolve it and use the ip addresses I get - which will probably work fine for years - because again, it’s highly unlikely that these servers change ips (or stop being part of the pool).

This feature request is to cover that last bit - to ensure that if they do switch, I won’t have to do anything.

Mike.
________________________________

**Comment by ShreyasZare** [comment]
That makes sense. With a warning text it should be generally more useful to have this option. Will get that added.

**Comment by LordMike** [comment]
You could also consider having a default or suggesting a value like “pool.ntp.org”.

Mike.
________________________________

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds option in DHCP scopes to add domain names for NTP server option. Do update and let me know your feedback.
