### ISSUE TITLE
docker 中如何设置 network dns providers

### ISSUE THREAD

**Issue by fzxs8** [TechnitiumSoftware/DnsServer#478]
在window 中可以通过这个设置
![image](https://user-images.githubusercontent.com/1922294/197982043-6fc8e5ba-d4e7-48f3-ad73-3126c28d8f66.png)

在docker中 如何设置呢..

**Comment by ShreyasZare** [comment]
> 非常感谢您的回答,按照您的指导,解决了我的问题 [DnsServer](https://github.com/TechnitiumSoftware/DnsServer) 是一个非常优秀的软件. 功能也很强大., 非常感谢维护了这样优秀的软件.

You're welcome. Thanks for the compliments.
