### ISSUE TITLE
Ability to turn off DNS updates when a DHCP lease is confirmed

### ISSUE THREAD

**Issue by besynnerlig** [TechnitiumSoftware/DnsServer#480]
On my wish list is the ability to control whether or not the DHCP server will attempt to do a DNS update when a lease is confirmed.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please describe it in a bit details.

**Comment by besynnerlig** [comment]
If a reserved DHCP lease for a host has been defined, any existing DNS host entry (including its comments) in the zone file gets overwritten when the lease is initiated. When the DHCP lease eventually expires the DNS host entry in the zone file gets deleted.

This feature request will add a way to prevent DHCP from modifying the DNS zone file.

The ISC dhcpd has a configuration for this.
```
# dhcpd.conf
#
# Configuration file for ISC dhcpd

# The ddns-updates-style parameter controls whether or not the server will
# attempt to do a DNS update when a lease is confirmed. We default to the
# behavior of the version 2 packages ('none', since DHCP v2 didn't
# have support for DDNS.)
ddns-update-style none;
```

**Comment by ShreyasZare** [comment]
Thanks for the details. So you wish to be able to define the Domain option in DHCP scope such that each client gets a domain name assigned but do not want the DHCP server to make DNS updates?

**Comment by besynnerlig** [comment]
Yes, it's still important to be able to set the domain-name option regardless if I like to update the zone file or not. :smile:

**Comment by ShreyasZare** [comment]
Ok so will plan this option for the update that is planned to cover multiple DHCP related tasks.

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds option in DHCP scopes to disable DNS update. Do update and let me know your feedback.
