### ISSUE TITLE
[bug] problem to windows's query

### ISSUE THREAD

**Issue by seyedmohammaddehqani** [TechnitiumSoftware/DnsServer#482]
For a mount ago, I see common problem when Windows 10 Users are querying to technitium dns server.
When a user's query generating from a software that installed on his OS (like chrom, firefox, etc), not resolving by technitium dns server but at this time if you generate a query from nslookup, technitum dns server resolve that.
My colleague make solution for this problem, fist of all clear cache with "ipconfig /flushdns" and after that register IP of dns server.

I do not see this problem in older version.
This problem has been started from 8.4.1 and everything was good until 8.1.3.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please share more details about your setup. The DNS server is installed on which OS? Are clients configured via DHCP? Are clients configured to use only the locally running DNS server or you have added any other DNS server too? Post here the outputs of `ipconfig` and `nslookup` commands too.
