### ISSUE TITLE
[feature request] Wildcard Zone

### ISSUE THREAD

**Issue by seyedmohammaddehqani** [TechnitiumSoftware/DnsServer#483]
I have suggestion!
In technitum dns server I can make zone like company.com and chose specific forwarder and method for it but I can not make wildcard zode like *.company.com or biger example *.com.
Could you please add this feature?

**Comment by ShreyasZare** [comment]
Thanks for the request. Such a feature is not possible to be implemented as its non standard and will not work for many reasons. If you wish to use wildcard then you have to use it with the individual DNS records.
