### ISSUE TITLE
HTTP server doesn't listen for ipv6 connections on Linux

### ISSUE THREAD

**Issue by besynnerlig** [TechnitiumSoftware/DnsServer#485]
Even though configured properly to listen for both IPv4 and IPv6 connections, the internal HTTP server used by DnsServer doesn't listen for IPv6 connections on Linux.

**Comment by ShreyasZare** [comment]
Thanks for reporting this issue. This is an issue with the HTTPListener that the DNS server uses which is already planned to be replaced as per issue #366.

**Comment by ShreyasZare** [comment]
> [A C# Http Server](https://github.com/duplicati/httpserver)

That is unmaintained project. Its already planned to use Kestrel web server as a replacement since it supports HTTP/2 and HTTP/3.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which now uses Kestrel web server and thus fixes this issue. Do check and let me know your feedback.
