### ISSUE TITLE
Forwarder zones are having records put into them by DHCP server

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#487]
Hi,

As the title says, I have a few forwarder DNS zones defined on my TDNS servers that also have DHCP scopes defined that contain said forwarder zones under the domain name field in the DHCP scope. When the DHCP server gives out an address, it adds a record into these forwarder zones. This should not be allowed as they're strictly forwarder zones. So now I have zones that contain both FWD records and A records. Please do the needful. Thanks.

Regards,
micush

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Earlier DHCP scope would add records only to primary zones but there were multiple requests to allow forwarder zone to also host these records so this support was added recently.

In the next update, there is a new option in DHCP scope being added that can be used to disable DNS updates (#480). This option should be able to work for your scenario.

**Comment by micush** [comment]
That will work. Thanks much.

**Comment by ShreyasZare** [comment]
Version 10 is now released that adds option in DHCP scopes to disable DNS update. Do update and let me know your feedback.
