### ISSUE TITLE
Can dnssec be flexible?

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#490]
Can dnssec be flexible?Mandatory dnssec is not required.Some dns servers do not have dnssec and some websites do not support dnssec. If you forcibly enable dnssec, the websites may be inaccessible.

**Comment by ShreyasZare** [comment]
DNSSEC validation does not affect when a domain name is not signed. If you get DNSSEC errors then its always your ISP or someone on the network tampering the DNS responses which get detected by the DNSSEC implementation. 

So, when a website does not resolve and you see DNSSEC error in logs then its just that your DNS traffic is being intercepted.

You can disable DNSSEC from settings though and it will stop validating all domain names. If you wish to stop validation only for specific domain name then using Conditional Forwarder zone, you can disable DNSSEC for that specific domain name.

**Comment by ShreyasZare** [comment]
> So there is no way to do flexible dnssec, there are too many domain names.
> 
> There is no way but to close the mandatory dnssec, because this problem puzzled me for a long time, other programs can do flexible dnssec

Can you explain what flexible DNSSEC means?

**Comment by ShreyasZare** [comment]
> Ah, this is because the cdn of the domain name in China does not support dnssec, but if I set it to mandatory dnssec, the cdn in China will not be used normally. That's why I propose the development of flexible dnssec, which is similar to dnsmasq proxy-dnssec.

DNSSEC validation is backward compatible. Which means, domain names that are unsigned do not have to do anything to make it work with DNSSEC validation. DNSSEC validation only works for domain names that are signed i.e. the domain names who have DS record added in their parent zone.

In your case, if DNSSEC validation is causing errors then it simply means that the DNS server is unable to fetch DS records to know if the domain is signed or not. So, even when a domain name is not signed, failure to get a valid response that says there is no DS record for the domain will cause DNSSEC validation errors.

So, in will just have to disable DNSSEC validation in settings to make it work. Other option is to use encrypted DNS protocols with a DNS provider that does not perform any filtering. Or, buy a VPS/server in another region, host a DNS server with DNS-over-HTTPS and then use it as your personal DNS provider for your local DNS server.
