### ISSUE TITLE
hotmail.com MX record resolution issue.

### ISSUE THREAD

**Issue by echodreamz** [TechnitiumSoftware/DnsServer#491]
Having issues with resolving hotmail.com MX record (mainly resolving the MX record hostname). Any idea what the issue can be?

Attached dig output showing the differences. Very strange behavior, both share the same host, same IP address etc.

[log.txt](https://github.com/TechnitiumSoftware/DnsServer/files/10016178/log.txt)

**Comment by ShreyasZare** [comment]
Thanks for the feedback and logs. I tried it on multiple setups and could not reproduce the issue. You can also test it with the hosted [dnsclient.net](https://dnsclient.net/#Recursive%20Query%20%7Brecursive-resolver%7D/hotmail-com.olc.protection.outlook.com/A/UDP/true) website.

From the logs the dig response includes extended DNS errors that the DNS server sent in response:

>  ; EDE: 22 (No Reachable Authority): (No response from name servers for hotmail-com.olc.protection.outlook.com. A IN)

This extended DNS error tells the reason that the DNS server did not receive a response from any of the name servers, i.e. there was timeout for all the name servers it queried. This can be a temporary issue which should get resolved when the DNS server retries after the negative cache expires in 60 sec.

**Comment by echodreamz** [comment]
What is strange, it works for SimpleDNS no problems, I simply stop the SDNS service and startup Technetium. Same IP address, nothing is different except the software. Works for SimpleDNS, stop service, start Technitium, issue query, query fails. Within a matter of a few seconds.

**Comment by ShreyasZare** [comment]
Check the DNS server logs from the web panel and see if there are any errors logged for that domain name.

If feasible, try to do packet capture, using Wireshark on Windows or tcpdump command on Linux, on the DNS server and query for the domain name. This should give crystal clear reason for whats going on at the network level. If you need help with analyzing the output then save the capture file and share it here or on email (support@technitium.com).
