### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by fzxs8** [TechnitiumSoftware/DnsServer#492]
我应该如何配置
我本地无法解析`download.docker.com`
![image](https://user-images.githubusercontent.com/1922294/202065631-710630b5-3c3d-4624-abb9-fd431768ce2e.png)
![image](https://user-images.githubusercontent.com/1922294/202077002-b0adea35-81f0-4f71-acc4-d556f3313dcf.png)

我在这里做了转发
![image](https://user-images.githubusercontent.com/1922294/202065789-ed95536a-3873-4d11-8df0-112f3882ed7d.png)

但是我使用google的dns 是可以访问的
![image](https://user-images.githubusercontent.com/1922294/202065906-11800031-2b55-465a-bff7-9aae27080ffe.png)
![image](https://user-images.githubusercontent.com/1922294/202077289-7cf144ca-a7aa-448f-8e02-eb66bc50d6c7.png)

我本地dns是可用的
```
[ljyr@17216260 ~]$ ping 219.149.6.99
PING 219.149.6.99 (219.149.6.99) 56(84) bytes of data.
64 bytes from 219.149.6.99: icmp_seq=1 ttl=60 time=2.29 ms
64 bytes from 219.149.6.99: icmp_seq=2 ttl=60 time=2.04 ms
64 bytes from 219.149.6.99: icmp_seq=3 ttl=60 time=1.85 ms



```

但是 这个就不通
```
[ljyr@17216260 ~]$ ping download.docker.com 
ping: download.docker.com: 未知的名称或服务

```
换一个就可以ping通
```
[ljyr@17216260 ~]$ ping www.docker.com
PING emzm5pam37e4.wpeproxy.com (141.193.213.20) 56(84) bytes of data.
64 bytes from 141.193.213.20 (141.193.213.20): icmp_seq=1 ttl=54 time=168 ms
64 bytes from 141.193.213.20 (141.193.213.20): icmp_seq=2 ttl=54 time=171 ms
64 bytes from 141.193.213.20 (141.193.213.20): icmp_seq=3 ttl=54 time=171 ms

```

请问,我应该怎么配置

**Comment by ShreyasZare** [comment]
谢谢你的帖子。 问题是您的本地 DNS 服务器启用了 DNSSEC 并检测到干扰。

在其中一个响应中，有一个扩展 DNS 错误，它说：
`219.149.6.99 未返回 cloudfront.net 的 DS`

这意味着您的上游服务器（转发器）没有正确响应 DNSSEC 验证所需的请求。 您的 ISP 可能会劫持请求并导致此问题。 您应该尝试使用加密的 DNS 协议来缓解此问题。

如果没有任何效果，那么您可能必须从“设置”中禁用 DNSSEC 验证，以便您可以解析域名。 但是，不能保证您收到的响应没有被劫持。

**Comment by fzxs8** [comment]
@ShreyasZare 

明白了.非常感谢解决我的疑问, 

也特别感谢能用中文回复,您的中文太榜了, 请原谅我的英文能力一般,不足以描述清楚问题..

**Comment by ShreyasZare** [comment]
> @ShreyasZare
> 
> 明白了.非常感谢解决我的疑问,
> 
> 也特别感谢能用中文回复,您的中文太榜了, 请原谅我的英文能力一般,不足以描述清楚问题..

很高兴知道您的问题已解决。

顺便说一句，我不懂中文。 我只是用谷歌翻译来写回复。 :)
