### ISSUE TITLE
Adopt CNAME flattening for Apex records.

### ISSUE THREAD

**Issue by Leopere** [TechnitiumSoftware/DnsServer#493]
I would like to be able to use RFC compliant CNAME DNS records at the root of a domain if possible.  https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/ CloudFlare added this in 2014 and I'm hoping that Technitium either already has it and I already missed it or we could have it soon because I have a number of clients that require this.

To further explain my use case, I've got a number of reverse proxies in my scalable cloud stack that point back to client websites.  This architecture allows for us to take any number of nodes offline manually without customer disruption or having to set up some fanciness with Failover/Floating IP's which only works in some scenarios. 

However, currently if we want to take a service offline we have to orchestrate taking a DNS record out of the round robin manually on multiple different authoritative DNS providers.  If Technitium can be used to allow for a CNAME to be RFC compliant at the Apex of a domain I am no longer required going forward to do this all manually and I'll switch my clients NameServers over to a cluster of Technitium nodes.

**Comment by Leopere** [comment]
Perhaps #179 is this issues duplicate but I'll wait for @ShreyasZare to weigh in with a confirmation it does look like an ANAME is basically what I wanted.

**Comment by ShreyasZare** [comment]
ANAME is the record that you are looking for. It will take the same domain name that you would want to use with CNAME and it will resolve it internally to return A/AAAA records for queries. ANAME works at the domain's apex and also with subdomain names.
