### ISSUE TITLE
Setting query log saving to disk hangsup the server and vps too

### ISSUE THREAD

**Issue by t-e-s-tweb** [TechnitiumSoftware/DnsServer#494]
I tried setting up query logs to disk and it hanged up my server and everything. Trying to start from scratch now. 

The logs saving location is set to just logs in the settings. Do we need to set it up like/logs or /home/logs etc?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. What is the throughput (request/min) on your DNS server? Do you see any errors in the DNS logs?

**Comment by ShreyasZare** [comment]
The issue you are reporting is something specific to your installation and is not generally reproducible. You need to check issues like if disk was full or other similar diagnostics. 

The logs by default are stored in the `/etc/dns/config/logs` folder unless you specify a full path in settings.
