### ISSUE TITLE
v10.0 eating too much memory on Windows

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#499]
Hi!
10.0 eating too much memory on Windows 7. Both versions with .Net 7.0.

old 9.1 version.

![Clipboard01](https://user-images.githubusercontent.com/740757/204099718-00e56201-04be-4321-a971-77b9516a8985.jpg)

New 10.0

![Clipboard02](https://user-images.githubusercontent.com/740757/204099750-c622c3db-5928-4924-97b1-3e3c659a1a9d.jpg)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Memory usage can be high at the beginning if there are blocklists configured. The .NET runtime will eventually free up the memory after a while.

Are you using any block lists or any specific app that loads a lot of config?

**Comment by Globulopolis** [comment]
> Are you using any block lists or any specific app that loads a lot of config?

Only Advanced blocking app is in use with one blocklist.

**Comment by Globulopolis** [comment]
> Thanks for the feedback. Memory usage can be high at the beginning if there are blocklists configured. The .NET runtime will eventually free up the memory after a while.

How long this could be? I'm wait for 6 hours and no changes. Memory consumption is still ~500mb.

**Comment by ShreyasZare** [comment]
> > Are you using any block lists or any specific app that loads a lot of config?
> 
> Only Advanced blocking app is in use with one blocklist.

Can you share the block list url so that I can try to replicate the issue?

**Comment by Globulopolis** [comment]
Config from advanced blocking app
```
{
  "enableBlocking": true,
  "blockListUrlUpdateIntervalHours": 24,
  "networkGroupMap": {
    "10.10.10.0/24": "LAN",
    "0.0.0.0/0": "everyone"
  },
  "groups": [
    {
      "name": "everyone",
      "enableBlocking": false,
      "allowTxtBlockingReport": true,
      "blockAsNxDomain": false,
      "blockingAddresses": [
        "0.0.0.0",
        "::"
      ],
      "allowed": [],
      "blocked": [
        "example.com"
      ],
      "allowListUrls": [],
      "blockListUrls": [],
      "allowedRegex": [],
      "blockedRegex": [
        "^ads\\."
      ],
      "regexAllowListUrls": [],
      "regexBlockListUrls": [],
      "adblockListUrls": []
    },
    {
      "name": "LAN",
      "enableBlocking": true,
      "allowTxtBlockingReport": true,
      "blockAsNxDomain": true,
      "blockingAddresses": [
        "0.0.0.0",
        "::"
      ],
      "allowed": [],
      "blocked": [],
      "allowListUrls": [],
      "blockListUrls": [],
      "allowedRegex": [],
      "blockedRegex": [],
      "regexAllowListUrls": [],
      "regexBlockListUrls": [],
      "adblockListUrls": ["https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt"]
    }
  ]
}
```

**Comment by ShreyasZare** [comment]
Just tested this with the app and its not taking any unusual amount of memory. I have v10 running on Windows 10, couple of Ubuntu servers, and a couple of raspberry pi devices. Memory usage is consistent on all installations compared with the previous version. I also am using block lists with 1mn+ domains blocked and its using around 300mb on all installations as expected.

Do you have anything that is not default in the DNS config?

**Comment by Globulopolis** [comment]
> Do you have anything that is not default in the DNS config?

No. Tested fresh install on different Windows 7 machine with the same results- ~500mb instead of ~40mb as on previous version.
PS! I just installed dns server and run service. The server was not configured.

**Comment by ShreyasZare** [comment]
I just checked on Window 7 and it seems that the app you are using is showing the Commit Size. Below is the screenshot from my setup:

![image](https://user-images.githubusercontent.com/10008172/204265277-bad72339-b264-440b-8521-8b3a6ac88591.png)

The actual memory used is ~45MB. The commit size for both the server and the system tray app is almost same that is consistent with your screenshot. It seems that its what the new .NET 7 runtime is doing on Windows 7. I don't see it doing the same on my Windows 10 setup.

Its not the actual amount of RAM being used by the DNS server so you don't have to worry about it.

**Comment by ShreyasZare** [comment]
This seems to be related to this [dotnet runtime issue](https://github.com/dotnet/runtime/issues/79469). Looks like they wont be fixing it since Windows 7 is out of support.

**Comment by Globulopolis** [comment]
> This seems to be related to this [dotnet runtime issue](https://github.com/dotnet/runtime/issues/79469). Looks like they wont be fixing it since Windows 7 is out of support.

Quite in the style of Microsoft :)

So the 9.х is the last stable version for Windows 7 OS? Or is there some option not to use new dotnet 7(and use 6.x) for 10.х DNS on Win 7 OS? In other words - dotnet 7 is required for 10.х DNS to working properly?

**Comment by ShreyasZare** [comment]
It seems setting a [couple of environment variables](https://github.com/dotnet/runtime/issues/79469#issuecomment-1345189478) fixes the issue. Do try it out and see if that works for your setup.

**Comment by Globulopolis** [comment]
> It seems setting a [couple of environment variables](https://github.com/dotnet/runtime/issues/79469#issuecomment-1345189478) fixes the issue. Do try it out and see if that works for your setup.

Unfortunately, these options did not help. Server still eating 500+Mb RAM and even grow. Is almost 800Mb sometimes.
I say RAM because windows tools(such as processexplorer or even powershell) did not reporting available memory correctly.

**Comment by ymalich** [comment]
> > It seems setting a [couple of environment variables](https://github.com/dotnet/runtime/issues/79469#issuecomment-1345189478) fixes the issue. Do try it out and see if that works for your setup.
> 
> Unfortunately, these options did not help. Server still eating 500+Mb RAM and even grow. Is almost 800Mb sometimes. I say RAM because windows tools(such as processexplorer or even powershell) did not reporting available memory correctly.

Interesting.
as I mentioned here 
https://github.com/dotnet/runtime/issues/79469#issuecomment-1371202114 
setting system environment variables 
set DOTNET_GCName=clrgc.dll
set DOTNET_EnableWriteXorExecute=0
in Windows 7 helped me on all system I tested.
