### ISSUE TITLE
Blocked domain resolves to 0.0.0.0 rather than Custom IP

### ISSUE THREAD

**Issue by marekbeckmann** [TechnitiumSoftware/DnsServer#500]
Hello,

I am currently testing out Technitium DNS and stumbled on the following problem: 
When I set the blocking type to Custom Address, domains in the blocked domain lists, I added are still being resolved to `0.0.0.0`, even after flushing the cache and rebooting the server.

All the lists I use are in a domain format, like that:  (All lists below)
```
www.googleadservicees.com
```
However, a simple dig returns the following output: 

```bash
dig -4 -c IN -t A googleadservices.com @10.10.10.10

; <<>> DiG 9.16.33-Debian <<>> -4 -c IN -t A googleadservices.com @10.10.10.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8482
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;googleadservices.com.          IN      A

;; ANSWER SECTION:
googleadservices.com.   60      IN      A       0.0.0.0

;; Query time: 0 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Sat Nov 26 21:15:26 CET 2022
;; MSG SIZE  rcvd: 65
```

I get the same output, when I query the domain using the DNS-Client feature. 
Is this due to the formatting of the blocking lists? 

**System Info:**

OS: Debian 11.5
Kernel: 5.10.0-19-amd64
Technitium DNS Version: Version 10.0
Blocking Lists: 
```
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/fake.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh-vpn-proxy-bypass.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.apple.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.winoffice.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/hoster.txt
```

**Comment by ShreyasZare** [comment]
Thanks for the post. I tested this on my local setup and its working as expected.

Are you using the blocking feature from the Settings > Blocking section or using the Advanced Blocking app? Both of these blocking features are independent of each other and thus if you are using the app then the custom blocking address needs to be configured in the app's config itself.

You can also query for TXT record type to get blocking report if you have disabled that option. The response will contain TXT record that will tell which app and which blocking list caused the domain to be blocked.

**Comment by marekbeckmann** [comment]
Yes, I had the app installed, adapting the config there fixed it, thanks a lot!

**Comment by ShreyasZare** [comment]
You're welcome. Good to know its working.
