### ISSUE TITLE
cache does not work 

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#501]
Updated the latest version of the dns program v10.0 and enabled ecs, but from the web panel, the cache does not work properly.

**Comment by liang-hiwin** [comment]
You can see from the screenshot that the number of caches is only 2

![C(KT1)9FF)5HAJSJY_1`$7](https://user-images.githubusercontent.com/17548936/204121476-5037000e-a356-4194-a080-4d6aa8b181cc.png)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Can you explain your setup since I am unable to reproduce the issue? Also, let me know what number you see for "Cached Entries" on the dashboard.

You can also check the record in the cache. For example, check for "www.google.com" in the Cache, you should find A record for it. The record should have a `eDnsClientSubnet` with a subnet value corresponding to your client. Check the `lastUsedOn` date time which should update when the client requests for the same record which means the records is being served from cache.

**Comment by liang-hiwin** [comment]
> Thanks for the feedback. Can you explain your setup since I am unable to reproduce the issue? Also, let me know what number you see for "Cached Entries" on the dashboard.
> 
> You can also check the record in the cache. For example, check for "www.google.com" in the Cache, you should find A record for it. The record should have a `eDnsClientSubnet` with a subnet value corresponding to your client. Check the `lastUsedOn` date time which should update when the client requests for the same record which means the records is being served from cache.

here

```
[
  {
    "name": "www.google.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "142.251.220.36"
    },
    "dnssecStatus": "Disabled",
    "lastUsedOn": "2022-11-27T13:50:22.2551978Z"
  },
  {
    "name": "www.google.com",
    "type": "AAAA",
    "ttl": "184 (3 mins 4 sec)",
    "rData": {
      "ipAddress": "2404:6800:4005:80e::2004"
    },
    "dnssecStatus": "Disabled",
    "lastUsedOn": "2022-11-27T13:49:51.9980119Z"
  }
]
```

**Comment by liang-hiwin** [comment]
> Thanks for the feedback. Can you explain your setup since I am unable to reproduce the issue? Also, let me know what number you see for "Cached Entries" on the dashboard.
> 
> You can also check the record in the cache. For example, check for "www.google.com" in the Cache, you should find A record for it. The record should have a `eDnsClientSubnet` with a subnet value corresponding to your client. Check the `lastUsedOn` date time which should update when the client requests for the same record which means the records is being served from cache.

If you need dns configuration, I can send you email

**Comment by ShreyasZare** [comment]
Thanks for the details. The cached records does not seem to be received for ECS. You have to query from the client and not using the DNS Client tab to test it.

Secondly, I need to understand how you have it setup. Like are you running the DNS server on a VPS/cloud server and then using it as your DNS server for clients?

**Comment by liang-hiwin** [comment]
> Thanks for the details. The cached records does not seem to be received for ECS. You have to query from the client and not using the DNS Client tab to test it.
> 
> Secondly, I need to understand how you have it setup. Like are you running the DNS server on a VPS/cloud server and then using it as your DNS server for clients?

Yes, I am running it on a public cloud server. And the domain name under the "cache" menu is requested by the client.

**Comment by liang-hiwin** [comment]
> Thanks for the details. The cached records does not seem to be received for ECS. You have to query from the client and not using the DNS Client tab to test it.
> 
> Secondly, I need to understand how you have it setup. Like are you running the DNS server on a VPS/cloud server and then using it as your DNS server for clients?

I see in logs that ecs is normal,

```
[2022-11-27 00:00:00 Local] Logging started.

[2022-11-27 00:00:08 Local] [127.0.0.1:33994] [UDP] QNAME: twitter.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [104.244.42.1, 104.244.42.65]; ECS: 113.x.x.0/24
[2022-11-27 00:00:08 Local] [127.0.0.1:40927] [UDP] QNAME: twitter.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [104.244.42.1, 104.244.42.65]; ECS: 113.x.x.0/24
.....
```

**Comment by liang-hiwin** [comment]
After running for a day, there is no obvious change in the cache. I will send the configuration to your mailbox, you can take time to see it
![U@VPYG_QYX EAE4 VZZ20U5](https://user-images.githubusercontent.com/17548936/204139753-7c71e1ba-8d67-4d3c-bf6b-3c4297bf9403.png)

**Comment by ShreyasZare** [comment]
The new update v10.0.1 is now available which fixes the EDNS Client Subnet issues. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
> The new update v10.0.1 is now available which fixes the EDNS Client Subnet issues. Do update and let me know your feedback.

OK, the cache is normal now, thank you

**Comment by liang-hiwin** [comment]
OK, the cache is normal now, thank you

Shreyas Zare ***@***.***> 于2022年12月4日周日 19:36写道：

**Comment by ShreyasZare** [comment]
You're welcome. Thanks for the feedback.
