### ISSUE TITLE
Open App Store timed out 

### ISSUE THREAD

**Issue by fogyismstar** [TechnitiumSoftware/DnsServer#502]
My English is very bad, the following content comes from Tencent translation: 
 The latest version timed out when opening the app store. The prompt is as follows: 
 Error! The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. 
How do I manually install the DNS64App.

**Comment by ShreyasZare** [comment]
Thanks for the post. You can download the DNS64 app from [here](https://download.technitium.com/dns/apps/Dns64App-v1.zip) and then use the Install button, which is next to the App Store button in the Apps section to manually install it. You will just need to enter a name i.e. `DNS64` and then browse the downloaded zip file to install it.

**Comment by fogyismstar** [comment]
Thank you. The problem has been solved successfully. It is suggested that the apps in the App Store be listed on the official website for manual download and installation.

**Comment by ShreyasZare** [comment]
Good to know that its installed. There is [archive link](https://download.technitium.com/dns/archive/10.0/Apps/) available on the website already which gives you all versions and apps that were released.

**Comment by fogyismstar** [comment]
thank you.
