### ISSUE TITLE
Multi-language support 

### ISSUE THREAD

**Issue by fogyismstar** [TechnitiumSoftware/DnsServer#503]
My mother tongue is not English, English is also very poor. In the old version I tried to translate the English on the Web UI into Chinese through the translation engine. But the new version of the Web UI will change, so everything will have to be redone. Are there plans to support multiple languages?

**Comment by ShreyasZare** [comment]
Thanks for the request. Unfortunately, there is no plan to have multi-language support at the moment. It may be considered in the future when most of the features are implemented.

For now, I would suggest that you use a translator plugin addon in the web browser itself which will translate the text in the DNS web UI.

**Comment by fogyismstar** [comment]
I have a translation plug-in installed on my browser. When I have time, I will translate the English prompt below the www file of version 10.0 into Chinese for my own convenience. Subsequent small versions will not be updated, and so on when the big version to upgrade and then manual translation.
