### ISSUE TITLE
Add a Secondary Technitium instance that automagically clones a primary node from environment variables or launch args.

### ISSUE THREAD

**Issue by Leopere** [TechnitiumSoftware/DnsServer#506]
My thought process here is that it could be really useful in the future to have Technitium be able to boot and configure a zone as a secondary zone from the Docker container invocation template.

**Comment by ShreyasZare** [comment]
Thanks for the request. There is a much better option coming up soon that is the clustering feature. With clustering enabled, all the servers in the cluster will work as a single entity. So, it would be possible to spin up a docker container and it will join the cluster and sync all settings.

**Comment by Leopere** [comment]
Redundant ticket #134 is the original.
