### ISSUE TITLE
Wishlist: External API for performing CRUD operations on DNS resource records

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#511]
Do the more recent versions of DnsServer support an external API for performing CRUD operations on DNS resource records? ...so a developer can create/update/delete resource records from code.

**Comment by ShreyasZare** [comment]
Thanks for asking. There is [HTTP API](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) available which the web panel itself uses. So, all the features you see on the web panel are done via the API and it can be called from any 3rd party app too.

**Comment by mwherman2000** [comment]
>There is [HTTP API](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) available which the web panel itself uses. 

@ShreyasZare Thank you, has it been there a long time/always been there?  ...or was it introduced in a more recent version?
