### ISSUE TITLE
OISD Block List link should be replaced

### ISSUE THREAD

**Issue by Singijeon** [TechnitiumSoftware/DnsServer#514]
https://github.com/TechnitiumSoftware/DnsServer/blob/2ea46e903d1471b68894438417537b78f5c95c6e/DnsServerCore/www/index.html#L1409
Actual URL _https://dbl.oisd.nl/_ (24 MiB) should be replaced by _https://dblw.oisd.nl/_ (5.3 MiB). Wildcards save space and traffic.

**Comment by ShreyasZare** [comment]
Thanks for the post. The wildcard block list is not supported with Technitium DNS server so even if it loads without issue, the server wont be able to block the domain names in it.

Will plan to add support for this type of block lists.

**Comment by ShreyasZare** [comment]
Yes, the file will get loaded but the wildcard matching is not implemented for block lists. Wildcard support works only for the Allowed/Blocked sections that you see in the web panel. There too blocking `*.example.com` only blocks the subdomain names and not the domain `example.com`.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which now supports Adblock Plus format that OISD has decided to support while removing support for all other formats. Do check and let me know your feedback.
