### ISSUE TITLE
Exception in obtaining client IP from ECS

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#520]
From the following log, we can see that ECS cannot obtain the client IP correctly

```
[2022-12-11 19:55:24 Local] [127.0.0.1:44665] [UDP] QNAME: XXX.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [211.99.113.247]; ECS: 0.0.0.0/24
[2022-12-11 19:55:24 Local] [127.0.0.1:54729] [UDP] QNAME: XXX.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [211.99.113.247]; ECS: 0.0.0.0/24

```

**Comment by ShreyasZare** [comment]
Thanks for the post. The log entry for the IP part is correct but the source prefix part is getting logged instead of scope prefix. So the log entry should have shown `0.0.0.0/0` instead which means that the response is valid for all subnets. Will get that logging issue fixed.

**Comment by liang-hiwin** [comment]
> Thanks for the post. The log entry for the IP part is correct but the source prefix part is getting logged instead of scope prefix. So the log entry should have shown `0.0.0.0/0` instead which means that the response is valid for all subnets. Will get that logging issue fixed.

ok, thanks ! Can the sorting order of logs be reversed? Otherwise, you need to scroll the mouse to see the last line every time.

**Comment by ShreyasZare** [comment]
> ok, thanks ! Can the sorting order of logs be reversed? Otherwise, you need to scroll the mouse to see the last line every time.

Since this is a text log, sorting it wont be feasible to implement. If you just want to check the query logs then using the Query Logs (Sqlite) app will give much better experience.

**Comment by liang-hiwin** [comment]
> > ok, thanks ! Can the sorting order of logs be reversed? Otherwise, you need to scroll the mouse to see the last line every time.
> 
> Since this is a text log, sorting it wont be feasible to implement. If you just want to check the query logs then using the Query Logs (Sqlite) app will give much better experience.

ok thanks DA shen
