### ISSUE TITLE
Technitium 10.1 doesn't work on Linux arm64

### ISSUE THREAD

**Issue by v4Lo** [TechnitiumSoftware/DnsServer#521]
Running latest Technitium 10.1 on Linux arm64 using dotnet 7.0 crashes instantly with output
`Failed to create CoreCLR, HRESULT: 0x80004005`

Technitium 8.1.4 from archive using dotnet 6.0 runs flawlessly with no further changes.

I didn't do further bisecting. I have no experience with dotnet applications.

**Comment by v4Lo** [comment]
Hardware is a Pine64 Quartz64 model A. OS is dietpi, basically Debian Bullseye with some scripts and the necessary boot files for the RK3566.

Installed directly, no docker.

For the latest 10.1 + dotnet 7.0 install I used the automated script (which downloads the correct dotnet 7.0 arm64, as far as I can tell from the install.log. A Version mismatch displays a different error).

Version 8.1.4 I installed manually by unpacking the portable archive according to blogpost
```
wget https://download.technitium.com/dns/DnsServerPortable.tar.gz
sudo mkdir -p /etc/dns/
sudo tar -zxf DnsServerPortable.tar.gz -C /etc/dns/
```
to /etc/dns and running the uninstall script beforehand. dotnet 6.0 came from Microsoft's "dotnet-install.sh". Downloading dotnet 7.0 using install-dotnet.sh and running from ~/.dotnet/dotnet changes nothing. Everything was run as root.

**Comment by ShreyasZare** [comment]
Thanks for the details. Please post the output for `dotnet --info` so that I can see if the .NET 7 runtime was installed correctly.

**Comment by v4Lo** [comment]
```
/opt/dotnet/dotnet --info

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.0 [/opt/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

However doing that I just noticed something else.

When running the command on the .dotnet installation in home I get the same error before the output. The only difference is that it has the SDK installed. (dotnet-install.sh -c 7.0) It probably isn't an issue with Technitium DNS but an issue with dotnet 7.0 on arm64.

```
.dotnet/dotnet --info
Failed to create CoreCLR, HRESULT: 0x80004005

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/root/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/root/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/root/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

I tried creating a simple helloworld app;

```
Running .dotnet/dotnet new console -o MyApp -f net7.0
Failed to create CoreCLR, HRESULT: 0x80004005
```

As a consequence I just got a free Oracle cloud instance of an arm64 based machine and Technitium DNS just works on there. No idea who or what is at fault here; Rockchip, Pine, firmware or Microsoft. Technitium DNS doesn't seem the culprit. Next I will try different SDK versions and see if any of them do not produce the error. Thank you for your time.

**Comment by v4Lo** [comment]
7.0.100 is not the preview release, it is the current security update of the SDK.
See https://dotnet.microsoft.com/en-us/download/dotnet/7.0


It doesn't matter if I use dotnet from /opt or from home. On the Oracle instance it just works.
