### ISSUE TITLE
A need for additional DHCP options

### ISSUE THREAD

**Issue by madeofpendletonwool** [TechnitiumSoftware/DnsServer#522]
Hello,

Wondering if there potentially is already a way to set additional DHCP options than that's already in the DHCP scope options. We switched over to using Technitium but realized we need option 150 for Cisco phones. I don't see option 150 in DHCP options. Is there a way to manually add options via commandline or something? If not, is this a feature that can get added? Whether it's just option 150 or ability to add additional DHCP options in general. 

Thank you! I can certainly provide additional details on anything if needed.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Currently there is no support for option 150. I will plan to add it in the next update. There is also plan to add support to add generic DHCP option such that you can enter the code and data in hex format. So, both of these can be expected in the next update.

**Comment by madeofpendletonwool** [comment]
That would be much appreciated! And thank you so much for the work on the project! We've really enjoyed using it and have moved over to it from using windows server DNS after we rebuilt our domain. It's been a much better experience and everything has gone extremely smooth. Setting the server up with docker compose was a breeze!

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which adds support for DHCP option 150 and also adds generic options. Do check and let me know your feedback.

**Comment by madeofpendletonwool** [comment]
Thank you so much! I'll try it out asap!
