### ISSUE TITLE
Serial schema

### ISSUE THREAD

**Issue by Ponkhy** [TechnitiumSoftware/DnsServer#523]
Hello,

is it possible to have the serial using the `YYYYmmddss` format on updating the zone?

Many thanks,
Ponkhy

**Comment by ShreyasZare** [comment]
Thanks for the post. Its not supported currently but will be available in future updates.

**Comment by ShreyasZare** [comment]
Keeping this open so that it can be tracked.

**Comment by lilfade** [comment]
Was there any updates on this by chance?

**Comment by ShreyasZare** [comment]
> Was there any updates on this by chance?

Will try to get this added soon.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.1 is now available that support SOA serial date scheme. Do update and let me know your feedback.
