### ISSUE TITLE
There seems to be a problem with dns

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#524]
**Here is the log.**

[2022-12-18.log](https://github.com/TechnitiumSoftware/DnsServer/files/10254063/2022-12-18.log)

**Comment by ShreyasZare** [comment]
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
```

There seems to be an issue with the forwarders that you are using from the error description. Switch to different forwarders and try again.

**Comment by liang-hiwin** [comment]
> ```
> System.Net.Http.HttpRequestException: An error occurred while sending the request.
>  ---> System.IO.IOException: The response ended prematurely.
> ```
> 
> There seems to be an issue with the forwarders that you are using from the error description. Switch to different forwarders and try again.

ok

**Comment by liang-hiwin** [comment]
> ```
> System.Net.Http.HttpRequestException: An error occurred while sending the request.
>  ---> System.IO.IOException: The response ended prematurely.
> ```
> 
> There seems to be an issue with the forwarders that you are using from the error description. Switch to different forwarders and try again.

thank you ！problem solved
