### ISSUE TITLE
Import DHCP reservations

### ISSUE THREAD

**Issue by CornHead764** [TechnitiumSoftware/DnsServer#527]
Hello,

I am looking to migrate to this project for my DNS and DHCP needs. I currently have a significant amount of DHCP reservations in my existing DHCP server. Is there an easy way to import en mass a list of DHCP reservations from csv or similar format?

Hoping to avoid typing in each one manually.

**Comment by ShreyasZare** [comment]
Thanks for the post. There is no bulk import option for it currently. You can however use something like a bash script that uses curl to call HTTP API to do the task. You can use the [Add Reserved Lease](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md#add-reserved-lease) call with a auth token that you can generate from the UI.

**Comment by CornHead764** [comment]
Thanks, that worked great!

In case someone else is going from Windows DHCP to this, here is a powershell snippet that'll import easily. This could also easily be adapted to use csv, but in my case, it was more efficient to just go direct.

```
$Subnet = "x.x.x.x" #windows dhcp scope id
$ScopeName = "Management" #name of scope in Technitium

$token = "Insert API token here (Can be generated via web ui)"

$Reservations = Get-DhcpServerv4Reservation -scopeid $Subnet
foreach ($Reservation in $Reservations) {
    $MacAddress = $Reservation.ClientId
    $IPAddress = $Reservation.IPAddress
    $HostName = $Reservation.Name
    $Description = $Reservation.Description

    $Result = Invoke-WebRequest -UseBasicParsing -Uri "http://localhost:5380/api/dhcp/scopes/addReservedLease?token=$token&name=$ScopeName&hardwareAddress=$MacAddress&ipAddress=$IPAddress&hostName=$HostName&comments=$Description"
    
    if ($Result.StatusCode -ne 200) {
        write-host Error on $IPAddress
    }
}
```

**Comment by ShreyasZare** [comment]
That's awesome. Thanks for sharing your script here.
