### ISSUE TITLE
API Security - Authentication in URL

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/DnsServer#529]
Hello,

I am getting started with the API as I want to create Ansible modules for this project.
I have noticed that with the API, all endpoints appear to be GET requests.

`http://192.168.1.2:5380/api/user/login?user=admin&pass=SuperSecretPassword`

This exposes the authentication credentials to someone sniffing on the network, I was easily able to find this using Wireshark on my client PC.
HTTPS only encrypts the body of the request, not the URL.

I propose that the API is updated to take the User, Password, and Token as headers or a JSON body.

**Comment by ShreyasZare** [comment]
Thanks for the post.

> I am getting started with the API as I want to create Ansible modules for this project. I have noticed that with the API, all endpoints appear to be GET requests.
> 
> `http://192.168.1.2:5380/api/user/login?user=admin&pass=SuperSecretPassword`
> 
> This exposes the authentication credentials to someone sniffing on the network, I was easily able to find this using Wireshark on my client PC. 

That is correct. You will see credentials on the network when using API over HTTP.

> HTTPS only encrypts the body of the request, not the URL.

That is not correct. HTTPS is basically HTTP over TLS which encrypts every data that is transmitted and received. When API is accessed over HTTPS, everything is encrypted and not exposed on the network.

> I propose that the API is updated to take the User, Password, and Token as headers or a JSON body.

Putting the data in HTTP request's body is not a fix. You can see the data using Wireshark as easily as you saw it with the GET request. The only fix is to enable HTTPS.

**Comment by djarbz** [comment]
You are correct.

I had forgotten to change my URL to https.
I also learned that HTTPS encrypts the URL in addition to the payload data, I always thought that it needed to remain unencrypted.
