### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#531]
The currently installed version is Version 10.0.1, which is installed in debian10 x64. Through the "htop" command, we can see that the single process of the dns program occupies a high CPU.

![dns](https://user-images.githubusercontent.com/17548936/211009289-20e76bdb-5e11-48db-a73e-f5a573f5fad8.png)

**Comment by liang-hiwin** [comment]
![dns2](https://user-images.githubusercontent.com/17548936/211009457-4535c4c0-9b83-4641-baf1-4215970ea75f.png)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Check the DNS logs from the web panel and let me know if there are any errors.

**Comment by liang-hiwin** [comment]
> Thanks for the feedback. Check the DNS logs from the web panel and let me know if there are any errors.

The log does not see any errors

**Comment by ShreyasZare** [comment]
Have you tried restarting the DNS server? How many queries per minute do you see on average on the dashboard?

**Comment by liang-hiwin** [comment]
> Have you tried restarting the DNS server? How many queries per minute do you see on average on the dashboard?

here 
![{AEFO`ST75Q(G_}466SF}LX](https://user-images.githubusercontent.com/17548936/211015965-b71f617d-2e59-44fd-ac5e-af0c1c48531e.png)

**Comment by ShreyasZare** [comment]
The query volume is quite low to have any such issue. However, I am seeing that most of the queries are being resolved recursively (or via forwarder). There is almost no queries answered from cache. The recursive resolution process may use CPU that will be noticeable if there are too many concurrent recursive resolutions.

Have you changed any settings related to cache?

**Comment by liang-hiwin** [comment]
From the screenshot above, you can see that there are more than 30 dns handles

**Comment by liang-hiwin** [comment]
I don't know why the cache is low. Do you need anything?

**Comment by ShreyasZare** [comment]
For some reason, it seems that your cache is not being used. Check the cache tab and see if you find any non expired records (TTL>0).

If the forwarders are responding with answers that have too low TTL value then you can set the "Cache Minimum TTL" in settings to a higher value so that the cached records do not expire quickly. Try querying to the forwarders using the DNS Client tab for any domain name and see if you are getting too low TTL value for records in the response.

**Comment by liang-hiwin** [comment]
```
"eDnsClientSubnet": "0.0.0.0/24",


```

Ecs display 0.0.0.0

**Comment by liang-hiwin** [comment]
I restarted the dns process

**Comment by ShreyasZare** [comment]
Thanks for the details over email. Responding with a solution on email that is specific to your setup.

**Comment by liang-hiwin** [comment]
> Thanks for the details over email. Responding with a solution on email that is specific to your setup.

Ok, thanks for your suggestion, I will set it

**Comment by liang-hiwin** [comment]
There is a time difference between the time recorded in "lastUsedOn" on the cache panel and the time recorded in the vps server
```

"lastUsedOn": "2023-01-06T14:05:09.4533932Z"

root@debian:~# date
Fri 06 Jan 2023 10:08:02 PM CST
root@debian:~# hwclock --show
2023-01-06 22:08:59.829868+08:00
root@debian:~# date -R
Fri, 06 Jan 2023 22:09:16 +0800


```

**Comment by ShreyasZare** [comment]
The time in "lastUsedOn" is in UTC whereas your server time is local time.

**Comment by liang-hiwin** [comment]
> The time in "lastUsedOn" is in UTC whereas your server time is local time.

Can I set it to my local time or add it in the next plan

**Comment by ShreyasZare** [comment]
> > The time in "lastUsedOn" is in UTC whereas your server time is local time.
> 
> Can I set it to my local time or add it in the next plan

There is no option to do that currently. The received json response is displayed as-is. To change it to local time will need to parse the response to update it.

**Comment by liang-hiwin** [comment]
> > > The time in "lastUsedOn" is in UTC whereas your server time is local time.
> > 
> > 
> > Can I set it to my local time or add it in the next plan
> 
> There is no option to do that currently. The received json response is displayed as-is. To change it to local time will need to parse the response to update it.

No problem, it would be better if it can support local time recording. Currently, log already supports local time

**Comment by liang-hiwin** [comment]
"Cache Minimum TTL" I set it to 3600, the current cpu has been reduced

**Comment by ShreyasZare** [comment]
> "Cache Minimum TTL" I set it to 3600, the current cpu has been reduced

Good to know that the issue is mitigated.
