### ISSUE TITLE
DHCP Scope "Enable DNS Updates" API Call

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#533]
Hi,

Is there an API call to enable/disable the option "Enable DNS Updates" in a DHCP scope? I'm seemingly unable to find it. I've got a few hundred scopes that I need to remove this setting from.

Regards,

micush

**Comment by ShreyasZare** [comment]
Thanks for the post. The API DOCS in master branch are not updated. Check out the one in the develop branch [here](https://github.com/TechnitiumSoftware/DnsServer/blob/develop/APIDOCS.md#set-dhcp-scope).

Use the call:
`http://localhost:5380/api/dhcp/scopes/set?token=x&name=Default&dnsUpdates=false`

**Comment by micush** [comment]
Worked like a charm. Saved me a lot of clicks. Thanks much.
