### ISSUE TITLE
API: Create Token

### ISSUE THREAD

**Issue by djarbz** [TechnitiumSoftware/DnsServer#534]
I am working on developing an Ansible collection to interact with your API.
If you are unfamiliar with Ansible, it is an automation platform that highly regards idempotency.

Currently, I do not see a way in the API to check if a token already exists using the `createToken` endpoint.
I would like to request that if a token with the same name for the specified user already exists, the call should fail with an error message informing of the existing token.
We should also have an API endpoint to delete a token. (This may be handled by the `logout` endpoint?)
To properly work with Ansible's idempotency, I would like to request a way to check if a token already exists, or list all of a user's named tokens.

**Comment by ShreyasZare** [comment]
Thanks for the post.

> Currently, I do not see a way in the API to check if a token already exists using the `createToken` endpoint. I would like to request that if a token with the same name for the specified user already exists, the call should fail with an error message informing of the existing token. 

The token names are not unique and are just to allow you to identify the session. Thus duplicate token names can exists.

> We should also have an API endpoint to delete a token. (This may be handled by the `logout` endpoint?) 

Yes, you can use the logout call if you have the token. There is also `/api/user/session/delete` that can be used if you have partial token.

> To properly work with Ansible's idempotency, I would like to request a way to check if a token already exists, or list all of a user's named tokens.

You can get list of all sessions/tokens for the current user with `/api/user/profile/get` call. This can be used to check if a token name already exists. You get a partial token in this call which can be used with the session delete call mentioned above.

**Comment by djarbz** [comment]
Ok, I think I can make that work. I originally thought that the sessions were just active sessions, but if that will show all named tokens I should be able to check that output and verify if a name already exists.
