### ISSUE TITLE
TCP/UDP cannot resolve while DoT or DoH are fine.

### ISSUE THREAD

**Issue by prooshani** [TechnitiumSoftware/DnsServer#535]
I love this project and the way you answer/resolve issues with perfect details and right to the point solutions.

Recently, I have installed 3 servers to resolve my DNS queries. All 3 are Technitium and have forwarder which is not public.
The forwarder I am using is a paid service and I have option to send queries on all protocols, UDP, TCP, over TLS or HTTPS.
The forwarder is set as DNS-Over-HTTPS (on technitium servers). I have NOT set any zone (I don't know anything about zoning, at all, not kidding). These servers are just resolver based on that paid service.

Technically, I assume that the structure of my servers and queries be like:
Client DNS query <--> My DNS Servers (Technitium) <--> Paid DNS service

The issue : If I set my client's DNS IPs to the Technitium servers, then the resolver wont work at all and the Internet connection will be interrupted because it cannot resolve any address using that DNS IP addresses (Technitiums). However, if I set my client's DNS Privacy based on DoT or DoH of the technitiums servers(my_server_tls:853), everything works flawlessly!!
I mean, there is no TCP/UDP resolver on my servers, while they can resolve if I use DoT or DoH!

The funny fact for me is that, if I use the DNSClient.net, and set the resolver the IP of my Technitium servers, it can resolve any request I have tested without issue!!!! (I have tested all TCP, UDP, DoT and DoH), while the servers' IP addresses cannot resolve if I set them on my client computer or my router (And no, there is no log, of any kind, when this happen while the NoError logs are there if I use DNSClient.net)

Any idea?

**Comment by prooshani** [comment]
Oh, just to mention the forwarder issue I faced,
If I opt to use DNS-Over-TLS for forwarders, after saving the setting there will be a :853 at the end of my forwarder's url which is wrong!
My forwarder do not accept port 853 requests for DoT.
I think this helper made a bug for DoT in forwarder section. Or at least I think it is a problem somehow.
Many thanks again.

**Comment by ShreyasZare** [comment]
> I love this project and the way you answer/resolve issues with perfect details and right to the point solutions.

Thanks for the compliments.

> Recently, I have installed 3 servers to resolve my DNS queries. All 3 are Technitium and have forwarder which is not public. The forwarder I am using is a paid service and I have option to send queries on all protocols, UDP, TCP, over TLS or HTTPS. The forwarder is set as DNS-Over-HTTPS (on technitium servers). I have NOT set any zone (I don't know anything about zoning, at all, not kidding). These servers are just resolver based on that paid service.
> 
> Technically, I assume that the structure of my servers and queries be like: Client DNS query <--> My DNS Servers (Technitium) <--> Paid DNS service
> 
> The issue : If I set my client's DNS IPs to the Technitium servers, then the resolver wont work at all and the Internet connection will be interrupted because it cannot resolve any address using that DNS IP addresses (Technitiums). However, if I set my client's DNS Privacy based on DoT or DoH of the technitiums servers(my_server_tls:853), everything works flawlessly!! I mean, there is no TCP/UDP resolver on my servers, while they can resolve if I use DoT or DoH!
> 
> The funny fact for me is that, if I use the DNSClient.net, and set the resolver the IP of my Technitium servers, it can resolve any request I have tested without issue!!!! (I have tested all TCP, UDP, DoT and DoH), while the servers' IP addresses cannot resolve if I set them on my client computer or my router (And no, there is no log, of any kind, when this happen while the NoError logs are there if I use DNSClient.net)
> 
> Any idea?

It seems that your Technitium DNS servers are available over public internet (probably on cloud hosting platform) so you are able to query them using the dnsclient.net website. But, for some reason, your client devices are unable to access them over the Internet. If that is correct then it seems that the DNS server is working well since its responding to public requests over UDP & TCP while it is possible that your client devices are behind a firewall, probably configured by your ISP, that is blocking these requests. A lot of ISPs block or hijack outbound DNS requests for various reasons so that is likely to be the reason.


> Oh, just to mention the forwarder issue I faced,
> If I opt to use DNS-Over-TLS for forwarders, after saving the setting there will be a :853 at the end of my forwarder's url which is wrong!
> My forwarder do not accept port 853 requests for DoT.
> I think this helper made a bug for DoT in forwarder section. Or at least I think it is a problem somehow.

Port 853 is the default port for DoT if not specified. The DNS server will add it explicitly to avoid confusion for the protocol that is configured.

> Many thanks again.

You're welcome.

**Comment by prooshani** [comment]
> > I love this project and the way you answer/resolve issues with perfect details and right to the point solutions.
> 
> Thanks for the compliments.
> 
> > Recently, I have installed 3 servers to resolve my DNS queries. All 3 are Technitium and have forwarder which is not public. The forwarder I am using is a paid service and I have option to send queries on all protocols, UDP, TCP, over TLS or HTTPS. The forwarder is set as DNS-Over-HTTPS (on technitium servers). I have NOT set any zone (I don't know anything about zoning, at all, not kidding). These servers are just resolver based on that paid service.
> > Technically, I assume that the structure of my servers and queries be like: Client DNS query <--> My DNS Servers (Technitium) <--> Paid DNS service
> > The issue : If I set my client's DNS IPs to the Technitium servers, then the resolver wont work at all and the Internet connection will be interrupted because it cannot resolve any address using that DNS IP addresses (Technitiums). However, if I set my client's DNS Privacy based on DoT or DoH of the technitiums servers(my_server_tls:853), everything works flawlessly!! I mean, there is no TCP/UDP resolver on my servers, while they can resolve if I use DoT or DoH!
> > The funny fact for me is that, if I use the DNSClient.net, and set the resolver the IP of my Technitium servers, it can resolve any request I have tested without issue!!!! (I have tested all TCP, UDP, DoT and DoH), while the servers' IP addresses cannot resolve if I set them on my client computer or my router (And no, there is no log, of any kind, when this happen while the NoError logs are there if I use DNSClient.net)
> > Any idea?
> 
> It seems that your Technitium DNS servers are available over public internet (probably on cloud hosting platform) so you are able to query them using the dnsclient.net website. But, for some reason, your client devices are unable to access them over the Internet. If that is correct then it seems that the DNS server is working well since its responding to public requests over UDP & TCP while it is possible that your client devices are behind a firewall, probably configured by your ISP, that is blocking these requests. A lot of ISPs block or hijack outbound DNS requests for various reasons so that is likely to be the reason.
> 
> > Oh, just to mention the forwarder issue I faced,
> > If I opt to use DNS-Over-TLS for forwarders, after saving the setting there will be a :853 at the end of my forwarder's url which is wrong!
> > My forwarder do not accept port 853 requests for DoT.
> > I think this helper made a bug for DoT in forwarder section. Or at least I think it is a problem somehow.
> 
> Port 853 is the default port for DoT if not specified. The DNS server will add it explicitly to avoid confusion for the protocol that is configured.
> 
> > Many thanks again.
> 
> You're welcome.

Thanks for your quick answer and kind helps.

I have tested hijacking (from your other mention on one issue submitted here), and yes for sure the ISP is hijacking!
But, if I remove the Technitium server from the middle of the stucture ( My DNS Queries <--> Paid DNS server) then everything is fine! Even TCP/UDP works fine but putting Technitium DNS server as a middle man stops the DNS resolve!

This is why I am suspect if anything is missing there.

**Comment by ShreyasZare** [comment]
> I have tested hijacking (from your other mention on one issue submitted here), and yes for sure the ISP is hijacking!
> But, if I remove the Technitium server from the middle of the stucture ( My DNS Queries <--> Paid DNS server) then everything is fine! Even TCP/UDP works fine but putting Technitium DNS server as a middle man stops the DNS resolve!

Thanks for the details. ISPs can hijack only popular public DNS resolvers and block all others. If your paid DNS server is a popular service then this scenario is possible. This kind of depends on how they have it configured.

Now that you have confirmed there are hijack attempts by the ISP, its best to use encrypted DNS protocols. Some devices like Android phones support DoT. For home network you can have a local resolver for the entire network that does DoH/DoT. For laptops you can have the DNS server running locally.

**Comment by prooshani** [comment]
> > I have tested hijacking (from your other mention on one issue submitted here), and yes for sure the ISP is hijacking!
> > But, if I remove the Technitium server from the middle of the stucture ( My DNS Queries <--> Paid DNS server) then everything is fine! Even TCP/UDP works fine but putting Technitium DNS server as a middle man stops the DNS resolve!
> 
> Thanks for the details. ISPs can hijack only popular public DNS resolvers and block all others. If your paid DNS server is a popular service then this scenario is possible. This kind of depends on how they have it configured.
> 
> Now that you have confirmed there are hijack attempts by the ISP, its best to use encrypted DNS protocols. Some devices like Android phones support DoT. For home network you can have a local resolver for the entire network that does DoH/DoT. For laptops you can have the DNS server running locally.

The paid service is not very famous or popular. However, I think if the DoT is working then the servers are well configured (am I right?).
Then I have to accept the faith and just use the DoT or DoH instead of TCP/UDP.

To clarify the situation, I was trying to find a way to resolve TCP/UDP requests to solve the Gaming issues we have recently.
Currently, I can easily handle the DoT using Asus RT Merling (my local router) but some how it looks non-practical to ask everyone to setup a DoT or HoH at home.

**Comment by ShreyasZare** [comment]
> The paid service is not very famous or popular. However, I think if the DoT is working then the servers are well configured (am I right?).

Ya, your DNS server config is working well since you independently tested it using the dnsclient.net website.

> Then I have to accept the faith and just use the DoT or DoH instead of TCP/UDP.

Since your ISP is interfering with DNS so there is no better choice than to use DoT/DoH.

> To clarify the situation, I was trying to find a way to resolve TCP/UDP requests to solve the Gaming issues we have recently. Currently, I can easily handle the DoT using Asus RT Merling (my local router) but some how it looks non-practical to ask everyone to setup a DoT or HoH at home.

Its good that your router has DoT support so you wont have to have an additional device running locally.

**Comment by prooshani** [comment]
> > The paid service is not very famous or popular. However, I think if the DoT is working then the servers are well configured (am I right?).
> 
> Ya, your DNS server config is working well since you independently tested it using the dnsclient.net website.
> 
> > Then I have to accept the faith and just use the DoT or DoH instead of TCP/UDP.
> 
> Since your ISP is interfering with DNS so there is no better choice than to use DoT/DoH.
> 
> > To clarify the situation, I was trying to find a way to resolve TCP/UDP requests to solve the Gaming issues we have recently. Currently, I can easily handle the DoT using Asus RT Merling (my local router) but some how it looks non-practical to ask everyone to setup a DoT or HoH at home.
> 
> Its good that your router has DoT support so you wont have to have an additional device running locally.

Thanks for your kind answers.
Believe me, you are a real human. I love the way you answer all issues so kindly and share your precious time and efforts with others.
Wish you the best in your life.

I assume that this issue can be set as resolved and closed.

Many thanks again.

**Comment by ShreyasZare** [comment]
> Thanks for your kind answers. Believe me, you are a real human. I love the way you answer all issues so kindly and share your precious time and efforts with others. Wish you the best in your life.

Thank your for the kind words. All the issues and feedback that I receive help me learn a lot and also helps to shape the project. Wish you the best in your life too.

> I assume that this issue can be set as resolved and closed.
> 
> Many thanks again.

You're welcome.
