### ISSUE TITLE
Perpetual CLOSE_WAIT status for hundreds of connections

### ISSUE THREAD

**Issue by shawnkhall** [TechnitiumSoftware/DnsServer#536]
Since upgrading to 10.x I'm seeing a huge number of connections choke on port 853 with a `CLOSE_WAIT` status. Even a small handful of client IP addresses can hold open several hundred active connections to Technitium DNS Server on port 853. Restarting the server fixes the problem temporarily, but it needs to be done every few hours to stabilize connections. The logs suggest that replies are being sent and there isn't any indication that they're being held open for any reason.

![image](https://user-images.githubusercontent.com/6037167/212563249-bdf829ca-8056-435e-877f-47ddc6615af7.png)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Which Windows version are you running the DNS server on? I tried it on Windows 10 and I don't see CLOSE_WAIT as the socket is getting closed for all cases.

In any case, these socket connections will time out in few minute and the socket will move from CLOSE_WAIT state and will be actually closed.

Is this issue affecting the DNS service? Like if there are too many of these sockets open, is the DNS service actually being affected such that the clients are unable to resolve domain names unless the DNS server is restarted?

**Comment by shawnkhall** [comment]
This is on a Windows Server 2012 R2 device and the connections do not always close.

DNS continues to operate for other clients and as far as I can tell the queries are returned correctly to the devices that are stuck on CLOSE_WAIT. Logs show thousands of requests for their IP addresses and the timestamps on them continue even after the connections start stalling.

I've waited hours watching netstat and tcpview to see if they cleared on their own and, when a surge of CLOSE_WAIT status connections begins, they did not close. Restarting TDNS is the only way I've found to get connections in this state to close.

**Comment by ShreyasZare** [comment]
Thanks for the details. DNS server v10 runs on new .NET 7 runtime and there have been one issue with memory usage identified with Windows 7 earlier. It possible that this is related to the runtime itself since the actual DNS server code for DoT was unmodified from the previous version.

I will test it on 2012 R2 once to try to reproduce the issue.

**Comment by shawnkhall** [comment]
I left some open for the last 8 hours to make sure that what I was seeing is what's happening. There are no correlating log entries for the same remote IP:PORT combination as those in the CLOSE_WAIT state. The log entries relating to that IP stopped hours ago, but were consistently incrementing the port in the logs until the active ports in the CLOSE_WAIT state began. 

The last entries from the logs for one sample IP address below:
```
[2023-01-21 00:00:02 Local] [x.x.x.86:5381] [TLS] QNAME: android-context-data.googleapis.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [...]
[2023-01-21 00:00:02 Local] [x.x.x.86:5381] [TLS] QNAME: android-context-data.googleapis.com; QTYPE: AAAA; QCLASS: IN; RCODE: NoError; ANSWER: [...]
[2023-01-21 05:33:46 Local] [x.x.x.86:4868] [TLS] QNAME: photosdata-pa.googleapis.com; QTYPE: AAAA; QCLASS: IN; RCODE: NoError; ANSWER: [...]
[2023-01-21 05:33:46 Local] [x.x.x.86:4868] [TLS] QNAME: photosdata-pa.googleapis.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [...]
```
And here are the current connections (8 hours later):
```
TCP    a.a.a.87:853      x.x.x.86:4865      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4866      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4869      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4872      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4874      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4878      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4879      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4880      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4881      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4882      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4885      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4887      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4888      CLOSE_WAIT
TCP    a.a.a.87:853      x.x.x.86:4893      CLOSE_WAIT
```

Here's a sample of the logs from another IP:
```
[2023-01-21 01:10:23 Local] [y.y.y.44:47596] [TLS] QNAME: mtalk.google.com; QTYPE: AAAA; QCLASS: IN; RCODE: NoError; ANSWER: [...]
[2023-01-21 01:10:24 Local] [y.y.y.44:47596] [TLS] QNAME: mtalk.google.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [...]
[2023-01-21 01:11:27 Local] [y.y.y.44:47600] [TLS] QNAME: st01vw.instabug.com; QTYPE: AAAA; QCLASS: IN; RCODE: NxDomain; ANSWER: []
...(800+ more log entries for this IP)...
[2023-01-21 05:36:24 Local] [y.y.y.44:48644] [TLS] QNAME: st01vw.instabug.com.hsd1.ca.comcast.net; QTYPE: A; QCLASS: IN; RCODE: NxDomain; ANSWER: []
[2023-01-21 05:47:19 Local] [y.y.y.44:48650] [TLS] QNAME: config.vzmessages.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [...]
[2023-01-21 05:47:19 Local] [y.y.y.44:48650] [TLS] QNAME: config.vzmessages.com; QTYPE: AAAA; QCLASS: IN; RCODE: NoError; ANSWER: []
```

And here are the current connections for that IP:
```
TCP    a.a.a.87:853      y.y.y.44:48658     CLOSE_WAIT
TCP    a.a.a.87:853      y.y.y.44:48662     CLOSE_WAIT
TCP    a.a.a.87:853      y.y.y.44:48668     CLOSE_WAIT
...(almost 100 more connections for this IP)...
TCP    a.a.a.87:853      y.y.y.44:48816     CLOSE_WAIT
TCP    a.a.a.87:853      y.y.y.44:48818     CLOSE_WAIT
TCP    a.a.a.87:853      y.y.y.44:48820     CLOSE_WAIT
```

Meanwhile, hundreds of other IP addresses successfully connect to and use the TDNS server without issue. A handful (they all appear to be Android based on a few of their requests) start stalling with CLOSE_WAIT then logged successful requests from those devices end as demonstrated above.

**Comment by shawnkhall** [comment]
Recycling the TDNS service releases all the CLOSE_WAIT connections and it goes back to normal.

**Comment by ShreyasZare** [comment]
Thanks for the details. From the logs it seems that these CLOSE_WAIT connections never made any DNS requests. 

I have found one issue in code where the SSL server handshake is done. There is no timeout configured so if a client connects and does not complete SSL handshake then it does not timeout. This may be a possible reason that explains the issue.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which has some changes that may fix this issue. Do check the latest API docs and let me know your feedback.
