### ISSUE TITLE
Empty Records Response From API Created ZONE

### ISSUE THREAD

**Issue by FliKites** [TechnitiumSoftware/DnsServer#543]
I check for zone exsistence with `${DNS_SERVER_ADDRESS}/api/zones/list?token=${DNS_SERVER_TOKEN}`

I create a new zone if it doesn't exist using: `${DNS_SERVER_ADDRESS}/api/zones/create?token=${DNS_SERVER_TOKEN}&zone=${zone}&type=Primary`

Then I create records using this: `${DNS_SERVER_ADDRESS}/api/zones/records/add?token=${DNS_SERVER_TOKEN}&domain=${domain_name}&zone=${zone_name}&ttl=60&type=A&ipAddress=${selectedIp}`

The records get created successfully and can confirm within the GUI they exist, but when I use the below API call, I get an empty "records" response. 

`${DNS_SERVER_ADDRESS}/api/zones/records/get?token=${DNS_SERVER_TOKEN}&domain=${domain_name}&zone=${zone_name}`

Am I missing an important step some where?

**Comment by FliKites** [comment]
Silly human error: 

In the end I changed the domain name to match the zone in order to pull records:
`${DNS_SERVER_ADDRESS}/api/zones/records/get?token=${DNS_SERVER_TOKEN}&domain=${zone_name}&zone=${zone_name}
`

**Comment by FliKites** [comment]
This seems to be causing me a headache with my script. 

Is their any reason why it looks for subdomains of the domain when the endpoint has a specific domain input ex. `/api/zones/records/get?domain=this.domain`  ends up looking for records that exist in this format *.this.domain

**Comment by ShreyasZare** [comment]
Thanks for the post. The Get Records API call by default returns all records in the domain and its subdomain names. Will update the API to make it optional.

**Comment by FliKites** [comment]
`http://x.1x.1x2.x:5380/api/zones/records/get?token=xxx&domain=ai.wrex&zone=wrex`

The above request shows this: 

`{"response":{"zone":{"name":"wrex","type":"Primary","internal":false,"dnssecStatus":"Unsigned","notifyFailed":false,"disabled":false},"records":[]},"status":"ok"}`

Even though I have an A record set for `ai.wrex`

**Comment by ShreyasZare** [comment]
Thanks for the details. Just checked it and its a bug. The API call is actually listing records only when the domain matches the zone name. Will get this fix in the upcoming release.

**Comment by FliKites** [comment]
Thanks bro.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11 is now available which fixes this API call issue. Do check the latest API docs and let me know your feedback.
