### ISSUE TITLE
Read Yunohost package issues

### ISSUE THREAD

**Issue by renne** [TechnitiumSoftware/DnsServer#547]
@ShreyasZare 
Please read the [Yunohost package issues](https://github.com/YunoHost-Apps/technitium-dns_ynh/issues)

**Comment by ShreyasZare** [comment]
Thanks for the post. I cannot help with issues posted on another project.

**Comment by renne** [comment]
@ShreyasZare 
Who is working on the Yunohost package?

**Comment by ShreyasZare** [comment]
I don't know, I just heard about them from you!
