### ISSUE TITLE
Auto PTR Features

### ISSUE THREAD

**Issue by rapdodge** [TechnitiumSoftware/DnsServer#548]
Example
You have `2001:db8:b00b::/48` which is the ip6.arpa is `b.0.0.b.8.b.d.0.1.0.0.2.ip6.arpa`

Requested feature is auto PTR records.

`2001:db8:b00b:b00b:ec5b:ca1e:6969:ec0e` will have answer `2001db8b00bb00bec5bca1e6969ec0e.domain.here`

Example project about auto PTR
https://github.com/vlcty/coredns-auto-ipv6-ptr

I'm really hoping that Technitium DNS can implemented auto PTR feature :)

Best regards,

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will get it added.

**Comment by drksbr** [comment]
+ 1 for this feature! Ipv4 and ipv6.

**Comment by ShreyasZare** [comment]
Technitium v11.2 is released with new Auto PTR app. Do check and let me know your feedback.

**Comment by rapdodge** [comment]
> Technitium v11.2 is released with new Auto PTR app. Do check and let me know your feedback.

Got it, will check it out

**Comment by rapdodge** [comment]
It's works perfect!

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/33513626/478097d2-1cb3-4939-8b2d-4d6e0cff09a4)
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/33513626/bcc2da6a-76a5-4369-be5a-8da9cc617ca9)

**Comment by ShreyasZare** [comment]
Thanks for the feedback!

**Comment by drksbr** [comment]
I don't know how to use the auto-ptr app. Can anyone tell me how to configure it?

**Comment by ShreyasZare** [comment]
> I don't know how to use the auto-ptr app. Can anyone tell me how to configure it?

@drksbr Thanks for asking. First, you need to create a reverse zone for which you need to generate PTR records automatically. Once you have your reverse zone, add an APP record in the zone and select the Auto PTR app with AutoPtr.App class path. You will need to edit the json config in the APP record to configure things like prefix, suffix, and IP separator to format your domain name that will be returned by the PTR record. Check the screenshot of the zone above to know how the APP record should look like. Add the record and use the DNS Client tab to test any IP address with PTR request.
