### ISSUE TITLE
DotNet requirement on Linux

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#549]
Hi,

After running many TDNS instances in production for many months, I find that I don't have too many issues related to TDNS itself. Most of my issues are seemingly related to the DotNet framework. Sometimes during OS updates (Ubuntu) it breaks, also breaking TDNS server. Because of automated OS updates, when the DotNet updates break, it breaks on all deployed servers. Not a fun situation to be in when you have to manually fix many of them. 

I could run it on Windows and the issue would probably be fixed because of native platform compatibility and all. However, we have a dynamic routing dependency, and last I looked there were no dynamic routing programs like FRR that run on Windows that would meet our needs. Internal testing also shows Linux deployments to be roughly 15% faster than Windows deployments on the same platform specs specifically for TDNS, so there's also that too.

As a home project, I recently installed the JellyFin media server on Ubuntu. It is also written with DotNet (C#). However, there is no requirement to install the DotNet framework to run the application. You simply untar the downloaded application and run it without having to install the DotNet framework. I'm guessing they bundle all the dependencies into the application, removing the possibility of DotNet breakage during updates.

Could you do this with TDNS? No external DotNet dependency would mean a more stable DNS environment for us. Thanks.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. If you are installing the DNS server using the install script then I would recommend that you install .NET 7 directly using apt package manager. The install script is actually bundling the dependencies which only gets updated when you run the install script again which may be why its breaking when OS updates.

You can check out .NET 7 install instructions for Ubuntu [here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu). With this, the packages too will get updated when OS updates are installed.

**Comment by ShreyasZare** [comment]
Closing this issue. Do reopen if needed.
