### ISSUE TITLE
Error Enabling DHCP Scope

### ISSUE THREAD

**Issue by KevinFumbles** [TechnitiumSoftware/DnsServer#550]
Hello!

ShreyasZare, first I want to say thank you for the wonderful software and I applaud you for how quickly you respond to and resolve issues here, on your website, and on Reddit. I have had Technitium running as my DNS server for years now and it is truly amazing, especially with the new features you continue to release.

Onto my issue though:
I am running v10.0.1 on a Raspberry Pi using Debian 11.6-aarch64, and I installed using the automated installer/updater. I was previously using my firewall/router as a DHCP server but I am in the process of migrating to using T-DNS for DHCP. I was able to create the scope, but it was Disabled by default and when I tried to enable it I received this error: `Error! DHCP Server requires static IP address to work correctly but the network interface was found to have a dynamic IP address [10.0.0.2] assigned by another DHCP server: 10.0.0.1`
However, I have the IP address on the Raspberry Pi set statically, according to my `/etc/network/interfaces.d/eth0` file. Here's the contents of `/etc/network/interfaces`:
```
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source /etc/network/interfaces.d/*
```
And the contents of `/etc/network/interfaces.d/eth0`:
```
auto eth0
iface eth0 inet static
    address 10.0.0.2
    netmask 255.255.255.192
    gateway 10.0.0.1
iface eth0 inet6 auto
```
In case you're wondering, it is supposed to be a `/26` as I'm setting up multiple VLANs with different scopes, though I may need to eventually modify my eth0 interface to accept traffic from multiple VLANs.
Am I correct in assuming T-DNS can be relayed DHCP requests for multiple scopes?

Ultimately, I'm not really sure what's causing it to think it's set by DHCP, though I would appreciate your input. If it helps, [this appears to be the line that's throwing that error](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/Dhcp/Scope.cs#L649).

**Comment by ShreyasZare** [comment]
Thanks for the compliments and post!

This is a known issue with Debian which causes .NET runtime to think there is a dynamic lease on the network interface. Its due to an old lease file that does not get removed in Debian causing this confusion. Take a look at [this issue](https://github.com/TechnitiumSoftware/DnsServer/issues/197) where the solution was discussed.

Let me know if that worked.

**Comment by KevinFumbles** [comment]
Hey ShreyasZare,

Wow, yep just like [this comment](https://github.com/TechnitiumSoftware/DnsServer/issues/197#issuecomment-1140387349), I deleted the file at `/var/lib/dhcp/dhclient.eth0.leases` and was able to enable the scope without even rebooting. Thanks for your time, I wish I had searched the issues better!

**Comment by ShreyasZare** [comment]
Good to know it worked for you!
