### ISSUE TITLE
Since the webui is already querying the Technitium API can those API queries be logged somewhere I can use for examples?

### ISSUE THREAD

**Issue by Leopere** [TechnitiumSoftware/DnsServer#551]
```
Web Console: The server provides a built in web console that internally uses REST API calls to configure the server. It is possible to use these REST API calls directly from any application to configure the server or to develop a similar web console.
```
From the documentation of help topics https://technitium.com/dns/help.html I'm seeing the above which to me suggests that it would potentially be feasible to present a sanitized log entry or something to a technitium console somewhere that can show me the API query formed in case I wanted to do something like submit a LetsEncrypt DNS challenge TXT record via an API call.  If this kind of thing was more obvious it would make life significantly easier for cryptography and integrations between TLS certificate issuing reverse proxies such as my favorite Traefik and another popular one like nginx-proxy-manager.

As far as I can tell its pretty difficult to view the API or to determine what exactly is happening if you're not a Go programmer.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please take a look at the API docs on GitHub: https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.mdLet me know if you have any queries on it.For certificate renewal, it would be best to use Dynamic Updates (RFC 2136). You will find certbot plugin or Traefik option for RFC 2136. You can enable dynamic updates from your zone options. With this, you wont require any script to update TXT records.

**Comment by Leopere** [comment]
I'm seeing in the list of DNS providers that there isn't a Technitium entry but there are lots for all sorts of other options.  This all said, there are a couple of options at the bottom [here. ](https://doc.traefik.io/traefik/https/acme/#providers)
![image](https://user-images.githubusercontent.com/1068374/218566765-020d4dda-0c45-4017-903d-5bd9c93143ed.png)

The only way I can imagine is either find a developer who knows go and how to work with your documentation or figure out how to feed this in a `curl` one liner to update a static record.  Dynamic updates or otherwise.

**Comment by ShreyasZare** [comment]
> I'm seeing in the list of DNS providers that there isn't a Technitium entry but there are lots for all sorts of other options. This all said, there are a couple of options at the bottom [here. ](https://doc.traefik.io/traefik/https/acme/#providers)

You can use Dynamic Updated option given in that link you mentioned. You wont need to us anything else.

![image](https://user-images.githubusercontent.com/10008172/218655878-ea8993e2-268f-420b-a3ac-62eee21291da.png)

> The only way I can imagine is either find a developer who knows go and how to work with your documentation or figure out how to feed this in a `curl` one liner to update a static record. Dynamic updates or otherwise.

If you still need to use the HTTP API then use the link example below to add the challenge TXT records for your domain:

`http://localhost:5380/api/zones/records/add?token=x&domain=_acme-challenge.example.com&zone=example.com&overwrite=true&type=TXT&ttl=60&text=<challenge-data>`
