### ISSUE TITLE
The permissions required to use GetZonePermissions need to be lowered

### ISSUE THREAD

**Issue by Djelibeybi** [TechnitiumSoftware/DnsServer#553]
I'm busy working on a Lexicon provider for Technitium and have hit the following issue when trying to validate that the provided API token has sufficient permission to perform the requested action in the specified zone.

In order to use the `GetZonePermissions` API request, a user must have _Modify_ permissions to all zones, which makes it unusable for users that only have permissions to specific zones not all of them. 

As the results of GetZonePermissions are filtered to the zones for which the token has `canView` (or higher) permissions, there should be no need for Zones level permissions.

**Comment by ShreyasZare** [comment]
Thanks for the post. The current permission required for the API call is to hide permissions from a user with lower privileges. You can use the API call and know if that token has access or not based on the returned status.

Zones level permission is required to make sure that a user can create/delete a zone. It is also used to make sure that a user has modify access to be able to change zone options.

Without this permission level, an API call which is able to add/modify a record in the zone will be able to change zone options too.

**Comment by Djelibeybi** [comment]
The `GetZonesPermission` API call is unable to add/modify anything so why is it access to it limited to users who have _Modify_ permission to all zones?

**Comment by ShreyasZare** [comment]
> The `GetZonesPermission` API call is unable to add/modify anything so why is it access to it limited to users who have _Modify_ permission to all zones?

Its to hide the permissions from users who don't have access to Zones section. You can have a user token which does not have any permission for Zones but has View/Modify on a specific zone. In this case, the token wont be able to find the zone permissions or even list zones.

A user with Zones Modify permission will be a user who has access to manage zones and thus such level of permission is required.
 
> The user would not see any permissions for any Zones to which they don't have at least `canView` permission anyway given the existing filtering. The worst case scenario is that a user may be able to see who has write permission to the zones to which they only have read, but it still doesn't let them make any actual changes.

Yes, but then its disclosing who has write permissions and thus whom to target. Which is what hiding the permissions is trying to prevent.

**Comment by Djelibeybi** [comment]
> In this case, the token wont be able to find the zone permissions or even list zones.

Yes, this is exactly the problem. A user with `canView`permission to a single zone should be able to call `getZonesPermission` and the results should only include that zone and only their permission, i.e. something like this:

```json
{
    "response": {
        "section": "Zones",
        "subItem": "lot209.xyz",
        "userPermissions": [
            {
                "username": "amiller",
                "canView": true,
                "canModify": false,
                "canDelete": false
            }
        ]
    },
    "status": "ok"
}
```

**Comment by ShreyasZare** [comment]
This is actually by design to prevent disclosing what all zones a given token has access to. When using tokens in automation scripts that will be modifying zone records, then these tokens should not have any permissions for Zones section to prevent enumeration.

The Zones section permissions and independent zone permissions are thus used in combination to provide access only to users who are managing the zones and to prevent info disclosure to user tokens which are only used for scripts.

**Comment by Djelibeybi** [comment]
While I don't fully understand your design choices, they were obviously made to prevent this use-case, so I will close this issue. Thanks for your time.

**Comment by ShreyasZare** [comment]
You're welcome. 

The design here was basically to have 2 tiers where one tier is for users that are going to manage zones and the the other lower tier is for users that will be used only for automation scripts. The lower tier is being prevented to gain any meaningful info related to permissions and to allow enumeration of zones that can be accessed to mitigate abuse of the token.
