### ISSUE TITLE
Does Technitium store a unique ID per zone record internally?

### ISSUE THREAD

**Issue by Djelibeybi** [TechnitiumSoftware/DnsServer#555]
Lexicon requires DNS providers have a unique ID for each record in a zone so that it can support updating or deleting specific records in sitations where multiple records is possible.  

If Technitium already stores something like this, can it be exposed via the API? If not, can this be considered as an enhancement request?

**Comment by Djelibeybi** [comment]
Closing because Lexicon's DDNS provider works with Technitium already, so a custom provider is unnecessary.

**Comment by ShreyasZare** [comment]
Thanks for the post. Just to let anyone looking up for this to know that there is no unique ID per zone record available.
