### ISSUE TITLE
Version date typo

### ISSUE THREAD

**Issue by prooshani** [TechnitiumSoftware/DnsServer#558]
Dear @ShreyasZare,

Good job updating this useful package.
Please consider revise the release date of the version 11.0 from Feb. 18, 2022 to Feb. 18, 2023.
I know days are passing like a wind but, man, we are in 2023, even if you don't like to believe in that :-D

Thanks and good luck

**Comment by ShreyasZare** [comment]
lol. Thanks for the feedback! Just fixed the typo.
