### ISSUE TITLE
Method not found: 'UInt32 TechnitiumLibrary.Net.Dns.ResourceRecords.DnsResourceRecord.get_TtlValue()'.

### ISSUE THREAD

**Issue by ackstorm23** [TechnitiumSoftware/DnsServer#562]
Since updating my docker container to version 11 my logs are full of this error

`[2023-02-21 00:16:37 Local] [x.x.x.x:57330] [UDP] System.MissingMethodException: Method not found: 'UInt32 TechnitiumLibrary.Net.Dns.ResourceRecords.DnsResourceRecord.get_TtlValue()'.`

This error logs  so often its causing my log files to become huge

```
grep TechnitiumLibrary.Net.Dns.ResourceRecords.DnsResourceRecord.get_TtlValue /tmp/logs/2023-02-21.log  | wc -l
127853
```

```
-rw-r--r--    1 root     root      438.4M Feb 21 10:41 2023-02-21.log
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback. It seems that you have one or more DNS apps that have failed to auto update for some reason. Do check the Apps section and manually update any app that you see has update available by clicking the "Store Update" button. This should fix the issue that you are seeing.

**Comment by ackstorm23** [comment]
Thanks that fixed it
