### ISSUE TITLE
DNS Query Logs (Sqlite) DB big

### ISSUE THREAD

**Issue by Sysadminfromhell** [TechnitiumSoftware/DnsServer#563]
Hey everyone,

after seeing that the app gets relly slow I checked the settings and saw that the auto clean is disabled and the keep logs is 0.
I changed it to 7 but the DB file is still pretty big:
413M Feb 22 21:02 querylogs.db

When the logs gets trunked? After a reboot? After 24 Hours?
Kind regards,

**Comment by Sysadminfromhell** [comment]
And on the other server its that big:
4.2G Feb 22 21:03 querylogs.db

**Comment by Sysadminfromhell** [comment]
I fixed it myself. Here are the steps (takes a long time when the DB is big):
```
> apt install sqlite3
> sqlite querylogs.db
sqlite> vacuum;
sqlite> DELETE FROM dns_logs WHERE timestamp <= date('now, '-x day');
x = day the days you want to keep in past. So if you want to keep the last 7 days you take -7 day

I would also recommend to set the following afterwards:

sqlite> pragma optimize;
sqlite> pragma auto_vacuum = incremental;
sqlite> pragma incremental_vacuum;
```

**Comment by ShreyasZare** [comment]
> Hey everyone,
> 
> after seeing that the app gets relly slow I checked the settings and saw that the auto clean is disabled and the keep logs is 0. I changed it to 7 but the DB file is still pretty big: 413M Feb 22 21:02 querylogs.db
> 
> When the logs gets trunked? After a reboot? After 24 Hours? Kind regards,

Thanks for the post. The DNS app will run a DELETE query every 15 minutes to remove any data greater than the `maxLogDays` defined in config.

**Comment by ChrisTracy** [comment]
@ShreyasZare do we know if this delete query is working? My db is at 18GB and I have my log retention set to 5 days.

**Comment by ShreyasZare** [comment]
> @ShreyasZare do we know if this delete query is working? My db is at 18GB and I have my log retention set to 5 days.

You can query from the GUI with order set to ascending and check if there is data older than 5 days.

The db file size once increased usually wont decrease for most databases out there. You may need to change the file name in the app config to start over and then delete the old file to save disk space.

**Comment by ChrisTracy** [comment]
Ah okay. I didn't even think about that. Thank you!
