### ISSUE TITLE
DNS-over-HTTP not working since 11.0

### ISSUE THREAD

**Issue by rehanone** [TechnitiumSoftware/DnsServer#566]
I am using DNS-over-HTTP behind a reverse proxy to provide DNS-over-HTTPS but as soon I upgrade to v11, that function stops working. As a workaround, I have fallen back to version `10.0.1` which is working without issue. Would really appreciate if this issue can be investigated and fixed.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The v11 has some changes regarding Optional Protocols. Earlier the protocols had fixed ports so DNS-over-HTTP used `8053` port. The new update allows changing port but its backwards compatible and will use the old port automatically. I am using the same reverse proxy setup and its working same without any change to settings.

You should just confirm the port in the settings once and check if that port is indeed open with `netstat` command. If not then check the DNS logs to see if there are any errors.

**Comment by rehanone** [comment]
Thanks for the quick response. The port is indeed `8053` in the settings and that is what I proxy using traefik. However, I get this response when I try to resolve a host using a local instance DNS-Client:

`Error! Response status code does not indicate success: 403 (Forbidden). `

The DNS-over-TLS works without any problem

**Comment by rehanone** [comment]
Also, if I open `https://my-domain.com/dns-query` in a browser, I get this error:

`DNS-over-HTTPS (DoH) queries are supported only on HTTPS.`

**Comment by ShreyasZare** [comment]
The DNS-over-HTTP option works only on private IP address. So you should use private IP in your reverse proxy config. Also make sure you have the `proxy_set_header X-Real-IP $remote_addr;` header configured.

**Comment by rehanone** [comment]
Okay, I will try to find the equivalent in traefik. Is this a change in v11? Because my reverse proxy works fine in v10.

**Comment by rehanone** [comment]
I have spent a few hours trying different settings but unfortunately DNS-over-HTTP doesn't work for me anymore. Their are two fallback options, v10 continue to work without issue. and DNS-over-TLS works without issue as well. I did try the new DNS-over-QUIC as well but it does not seem to be very stable and randomly stops working.

I am using private IP as the traefik is proxying the http connection.

**Comment by ShreyasZare** [comment]
It seems there is one bug causing this issue. Will get it fixed.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.0.2 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by rehanone** [comment]
Yes it is working now! Thanks for the quick fix!

**Comment by ShreyasZare** [comment]
Thanks for confirming!
