### ISSUE TITLE
DNS-over-HTTP and DNS-over-HTTPS with Apache proxy doesn't work on Windows 11

### ISSUE THREAD

**Issue by Grant10k** [TechnitiumSoftware/DnsServer#567]
I don't know if this is an issue with DNS Server, Windows, or Apache, but I'm pulling my hair out trying to find a solution. 

If I use Apache ProxyPass to forward a connection to either  DNS over HTTP or DNS over HTTPS, I cannot get windows to resolve a name. You ping an address, and you get "Could not find host"

If I just run DNS Server normally and connect to it on port 53, it works fine. 
If I run DNS Server DNS over HTTPS directly to port 443, it works fine. 
If I run CURL and specify using `doh` with the Apache proxy, it works fine. 
If I run CURL and specify using `doh` directly to DNS server, it works fine. 

There's just something about the exact combination of Apache proxy, DoH, and Windows that don't seem to line up, and the only feedback I can get from Windows is "Worked" or "Didn't worked"

Is there some URL or string that I can give DNS Server to give me some output? Like, if I use Postman to send something to cloudflare's dns-query I get back something weird, but DNS Server always returns empty, or a redirect to the help page where it says how to configure Firefox. 

The one thing I noticed is that while I can't really see what the content is, CURL gives the headers which appear to be slightly different between proxy and direct. 

Apache proxy adds a `Server: Apache` header (it used to say a lot more, but that's as close to removing it as you can get. I'm told Nginx does the same thing) and direct has a `Alt-Svc: h3=":443"; ma=86400`, which either doesn't show up on the proxy (if proxying Dns over http) or changes to `Alt-Svc: h3=":44353"; ma=86400` (If proxying Dns over https using 44353 as the port). 

Both ways seem to have the same content length, whatever it may be. 

Command `cls && curl -v --insecure --doh-insecure --doh-url https://dnsserver.localpc/dns-query https://test.localpc`
Direct: 
```
* Hostname 'dnsserver.localpc' was found in DNS cache
*   Trying 127.0.0.1:443...
* Connected to dnsserver.localpc (127.0.0.1) port 443 (#2)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> POST /dns-query HTTP/1.1
Host: dnsserver.localpc
Accept: */*
Content-Type: application/dns-message
Content-Length: 30

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 46
< Content-Type: application/dns-message
< Date: Sat, 25 Feb 2023 15:53:58 GMT
< Alt-Svc: h3=":443"; ma=86400
<
* Connection #1 to host dnsserver.localpc left intact
* a DoH request is completed, 1 to go
* ALPN: server accepted http/1.1
> POST /dns-query HTTP/1.1
Host: dnsserver.localpc
Accept: */*
Content-Type: application/dns-message
Content-Length: 30
```

Proxy:
```
* Hostname 'dnsserver.localpc' was found in DNS cache
*   Trying 127.0.0.1:443...
* Connected to dnsserver.localpc (127.0.0.1) port 443 (#2)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> POST /dns-query HTTP/1.1
Host: dnsserver.localpc
Accept: */*
Content-Type: application/dns-message
Content-Length: 30

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sat, 25 Feb 2023 16:31:44 GMT
< Server: Apache
< Content-Length: 46
< Content-Type: application/dns-message
<
* Connection #1 to host dnsserver.localpc left intact
* a DoH request is completed, 1 to go
* ALPN: server accepted http/1.1
> POST /dns-query HTTP/1.1
Host: dnsserver.localpc
Accept: */*
Content-Type: application/dns-message
Content-Length: 30
```

It might not have anything to do with headers, but I'm sort of grasping at straws here. My exact set of circumstances led me to this point (Other apps using 53, 443). While I'm not married to Apache, we've been dating for years now so I figured I'd ask for help before going though a difficult break up. Speaking of, here's the config file. I believe `RemoteIPHeader X-Real-IP`  is the equivilent to `proxy_set_header X-Real-IP $remote_addr;`

```
<VirtualHost *:80> 
    ServerName dnsserver.localpc
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://dnsserver.localpc$1 [L,R=301]
</VirtualHost>
<VirtualHost *:443> 
    ServerName dnsserver.localpc
    ServerSignature Off
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerExpire on
    ProxyPreserveHost On
    Protocols h2 http/1.1
    ProxyPass / http://127.0.0.1:8053/
    ProxyPassReverse / http://127.0.0.1:8053/
    SSLEngine on
    SSLCertificateFile "conf/ssl.crt/cert.crt"
    SSLCertificateKeyFile "conf/ssl.key/key.key"
    RemoteIPHeader X-Real-IP
    #RequestHeader set X-Real-IP '127.0.0.1'
</VirtualHost>
```

**Comment by ShreyasZare** [comment]
Thanks for the post. The `Alt-Svc: h3=":443"; ma=86400` header is being sent by the DNS server which is to upgrade the connection to HTTP/3. You can just ignore this if you do not want to use HTTP/3.

The DNS-over-HTTP will work only when the request comes from a private IP address else it will return `403` response. For reverse proxy, you should reverse proxy to this service and keep the DNS-over-HTTPS service off.

To test, use the DNS server's built in DNS Client tab with the DNS-over-HTTP URL. If you wish to test from another computer on the network then download the [DNS Client app](https://github.com/TechnitiumSoftware/net.dnsclient) and use it to test the DoH service. This way you will be able to test the DoH service properly which tricky to test using curl.

Both the DNS-over-HTTP and DNS-over-HTTPS will redirect to a help page when accessing via web browser. It only processes the request as a DNS request when the content type is `application/dns-message`.

I have not used Apache in many years by now so not sure about the `X-Real-IP` header but it looks good otherwise.

It seems that there is just a slight misconfig somewhere which is causing issue as rest of the stuff you mentioned looks good. Do debug it step by step once and see. I would also recommend that you run tcpdump on you apache server and try the query. The pcap file that tcpdump creates then can be inspected with Wireshark to see exactly what HTTP request is being reverse proxied and the issue should be much clear with it.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.0.2 is now available that fixes an issue related to your post which might be the reason why your setup is failing. Do update and let me know your feedback.

**Comment by Grant10k** [comment]
v11.0.2 didn't immediately fix the problem, and I have to go out of town in like, 20 minutes so I can't test it further yet. 

This is all within the same PC. I'll try the tcpdump when I get back in a couple days.

**Comment by Grant10k** [comment]
I've spent...so long on this. 

According to Wireshark and Apache's verbose logging, Windows isn't finishing the connection, to the proxy never actually activates. There's just something about the SSL handshake that it doesn't like, or maybe it takes too long. I don't know. 

The left is going though the Apache proxy (well, it doesn't actually get to the proxy part...) and the right is directly to the DNS server by shutting down Apache and enabling DNS-over-HTTPS on 443. 

![Wireshark_4GGnWPcQce](https://user-images.githubusercontent.com/949926/221926951-3a1d532c-316d-4de3-af11-f1302e1dcf5b.png)

I'd love to get this working, but I think I'm going to give up and install DNS Server on a nearby computer where port 53 is available and just use that instead.

**Comment by ShreyasZare** [comment]
Thanks for the details. It seems that the SSL handshake is failing mostly due to the ciphers that Apache server is configured with which the client does not support. It could also be TLS version issue since a lot of clients now strictly work only when you have TLS 1.2 or above.
