### ISSUE TITLE
Support for SVCB / HTTPS record types

### ISSUE THREAD

**Issue by ruifung** [TechnitiumSoftware/DnsServer#568]
Would be nice to have support for creating SVCB / HTTPS record types.

For things like DDR (Auto discovery of encrypted DNS) or HTTP/3 discovery.

Relevant Links:
https://techcommunity.microsoft.com/t5/networking-blog/making-doh-discoverable-introducing-ddr/ba-p/2887289
https://datatracker.ietf.org/doc/draft-ietf-add-ddr/

**Comment by ShreyasZare** [comment]
Thanks for the post. This is already in my to-do list and will be available with coming updates.

**Comment by ShreyasZare** [comment]
Technitium v11.2 is released which adds support for SVCB & HTTPS records. Do check and let me know your feedback.

**Comment by ruifung** [comment]
@ShreyasZare I've tried adding the SVCB records as per draft-ieft-add-ddr, and perhaps it would be a good idea to allow for custom parameters in the SVCB records? (For example, the dohpath parameter used for DDR with DNS over HTTPS)
