### ISSUE TITLE
Upgrade from 11.0 to 11.0.1 : Manually added zones disappear

### ISSUE THREAD

**Issue by PVaissiere** [TechnitiumSoftware/DnsServer#570]
Hi,

Environnement : docker
upgrade from image: 'technitium/dns-server:11.0' to 'technitium/dns-server:11.0.1'
node 1 : primary zones
node 2 : secondary zones

This morning, my watchtower has upgraded my nodes to the lastest version available.
Then, my primary and secondary zones just disappeare

And they reappeare after downgrading

**Comment by ShreyasZare** [comment]
Thanks for the post. The docker image is now using a [different path](https://github.com/TechnitiumSoftware/DnsServer/blob/master/Dockerfile#L31) for the config folder. You will just need to reconfig the container to use the new path with your volume and it will work.

**Comment by rehanone** [comment]
I know this is already in the code now but as a principal, this kind of breaking change should only happen in a major version. If I am pinning my docker tag to version 11, I expect no breaking changes and should simply be able to continue updating until version 12 comes along. However, this change does require manually adjusted path. And also know about the break. Please consider that in future releases.

**Comment by ShreyasZare** [comment]
> I know this is already in the code now but as a principal, this kind of breaking change should only happen in a major version. If I am pinning my docker tag to version 11, I expect no breaking changes and should simply be able to continue updating until version 12 comes along. However, this change does require manually adjusted path. And also know about the break. Please consider that in future releases.

Thanks for the feedback. This was one-off change which was planned with the major version but got delayed.
