### ISSUE TITLE
How to use nginx to take over web ui

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#573]
When installing dnsserver, the default web port is 5380. If I want to use 443 of nginx to reverse proxy 5380, how can it work normally?

Below is my nginx code, but can't access dnsserver web panel normally。

```
server {
        server_name example.com;
        listen 443 ssl http2;
        ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;

  location /dns {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_redirect off;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 86400;
                proxy_pass http://127.0.0.1:5380;     #DnsServer web port 
                     
        } 



```

**Comment by ShreyasZare** [comment]
Thanks for the post. By adding `/dns` its breaking the paths in the web app. Just make it as `location /` and it will work.

**Comment by liang-hiwin** [comment]
> Thanks for the post. By adding `/dns` its breaking the paths in the web app. Just make it as `location /` and it will work.

My website is already defined in ’ location / ‘

**Comment by ShreyasZare** [comment]
> > Thanks for the post. By adding `/dns` its breaking the paths in the web app. Just make it as `location /` and it will work.
> 
> My website is already defined in ’ location / ‘

Use it with a subdomain so that you can define it as another website.

**Comment by liang-hiwin** [comment]
> > > Thanks for the post. By adding `/dns` its breaking the paths in the web app. Just make it as `location /` and it will work.
> > 
> > 
> > My website is already defined in ’ location / ‘
> 
> Use it with a subdomain so that you can define it as another website.

If you add a path, how can it be used normally?

**Comment by liang-hiwin** [comment]
Adding a path can reduce the risk of being maliciously scanned

**Comment by ShreyasZare** [comment]
> > Use it with a subdomain so that you can define it as another website.
> 
> If you add a path, how can it be used normally?

The web app wont with a different path. So that is not possible to do.

**Comment by ShreyasZare** [comment]
> Adding a path can reduce the risk of being maliciously scanned

So is having a subdomain name. Someone can only scan it if they know what subdomain name you have used.

**Comment by liang-hiwin** [comment]
> > Adding a path can reduce the risk of being maliciously scanned
> 
> So is having a subdomain name. Someone can only scan it if they know what subdomain name you have used.

Thank you for your answer, I will configure a subdomain to open it only with my dns.

**Comment by ShreyasZare** [comment]
> > > > Adding a path can reduce the risk of being maliciously scanned
> > > 
> > > 
> > > So is having a subdomain name. Someone can only scan it if they know what subdomain name you have used.
> > 
> > 
> > Thank you for your answer, I will configure a subdomain to open it only with my dns.
> 
> Not going to http3??

For HTTP/3 support, make sure you have QUIC supported on your server which is the same requirement for DNS-over-QUIC. You also need to make sure that UDP port used by your DNS web panel is not blocked by firewall.

If you are using a reverse proxy then HTTP/3 should be enabled on it to work.

**Comment by liang-hiwin** [comment]
Thank you for your answer. It has been successfully configured. If anyone does not use my dns, it will not be able to open it.  @ShreyasZare

**Comment by ShreyasZare** [comment]
You're welcome. Good to know you got it working.

**Comment by liang-hiwin** [comment]
> You're welcome. Good to know you got it working.

Hello, sorry to bother you, I sent you an email, please take a look for me when you have time @ShreyasZare

**Comment by hynet-mel** [comment]
> When installing dnsserver, the default web port is 5380. If I want to use 443 of nginx to reverse proxy 5380, how can it work normally?
> 
> Below is my nginx code, but can't access dnsserver web panel normally。
> 
> ```
> server {
>         server_name example.com;
>         listen 443 ssl http2;
>         ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
>         ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
>         ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;
> 
>   location /dns {
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header Host $http_host;
>                 proxy_set_header X-NginX-Proxy true;
>                 proxy_redirect off;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_read_timeout 86400;
>                 proxy_pass http://127.0.0.1:5380;     #DnsServer web port 
>                      
>         } 
> ```

Hey, since I see you wanted to do the same as I just did. I basically just used the `sub_filter` to force it to be served in an subdirectory. But I think this is far from perfect since it has to filter it out every request. I am pretty sure this is not embraced, but this hacky solution does what I want it to do.

```
  # DNS server
  location ^~ /dns/ {
    rewrite /dns(/.*)$ $1 break;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_redirect off;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400;
    proxy_pass http://127.0.0.1:5380;
    sub_filter "favicon.ico" "dns/favicon.ico";
    sub_filter "/js" "/dns/js";
    sub_filter "/css" "/dns/css";
    sub_filter "/api" "/dns/api/";
    sub_filter "/img" "/dns/img/";
    sub_filter_types text/html text/css text/javascript;
    sub_filter_once off;
  }
```

**Comment by ShreyasZare** [comment]
> > When installing dnsserver, the default web port is 5380. If I want to use 443 of nginx to reverse proxy 5380, how can it work normally?
> > Below is my nginx code, but can't access dnsserver web panel normally。
> > ...
> 
> Hey, since I see you wanted to do the same as I just did. I basically just used the `sub_filter` to force it to be served in an subdirectory. But I think this is far from perfect since it has to filter it out every request. I am pretty sure this is not embraced, but this hacky solution does what I want it to do.
> 
> ```
>   # DNS server
>   location ^~ /dns/ {
>     rewrite /dns(/.*)$ $1 break;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host $http_host;
>     proxy_set_header X-NginX-Proxy true;
>     proxy_redirect off;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_read_timeout 86400;
>     proxy_pass http://127.0.0.1:5380;
>     sub_filter "favicon.ico" "dns/favicon.ico";
>     sub_filter "/js" "/dns/js";
>     sub_filter "/css" "/dns/css";
>     sub_filter "/api" "/dns/api/";
>     sub_filter "/img" "/dns/img/";
>     sub_filter_types text/html text/css text/javascript;
>     sub_filter_once off;
>   }
> ```

Thanks for the suggestion but doing that is not recommended. This is since some of the files needed by the webapp may change later and cause the setup to break. Then there is GUI planned for DNS Apps which will contain its own html + js code and its going to assume that the webapp is installed at the `/` path. So, if you setup it to work for `/dns/` path then later the web app or the DNS apps GUI will fail to work.

Its best to have the DNS panel setup on a subdomain name instead since it will work as expected without any issues in future.
