### ISSUE TITLE
Specified handling and displaying of zones in-addr.arpa and ip6.arpa

### ISSUE THREAD

**Issue by Singijeon** [TechnitiumSoftware/DnsServer#574]
I tried to add [reserved IP addresses](https://en.wikipedia.org/wiki/Reserved_IP_addresses) as primary zones for "bogon filtering" but it is too complicated to enter all decimal variants of binary addresses with network mask. I suggest to add a special handling and displaying of _in-addr.arpa_ and _ip6.arpa_ zones to reach a maximum performance and a facilitation of using network masks. Malformed records may be passed through for backward compatibility or optionally blocked.

**Comment by ShreyasZare** [comment]
Thanks for the post. I did not exactly understand the issue but if you are asking about an easy way to add a reverse zone then you can enter the network address like `192.168.1.0/24` as the zone name and the DNS server will create a reverse zone for it automatically. 

If you meant something else then do give a bit more details on the issue.

**Comment by ShreyasZare** [comment]
> Thank you for reply. Addresses with masks rounded by 8 (4 for IPv6) works fine as you described. But another one doesn't work: for example I try to add _100.64.0.0/10_ (ISPs shared address space) or _172.16.0.0/12_ (Class B IANA private networks) or _fc00::/7_ (ULA) but they are truncated to _100.64.0.0/16_, _172.16.0.0/16_ and _fc00::/8_ (_64.100.in-addr.arpa_, _16.172.in-addr.arpa_ and _c.f.ip6.arpa_) but all decimal variants of these networks must be added: _67.100.in-addr.arpa_, _68.100.in-addr.arpa_ … _127.100.in-addr.arpa_, _17.172.in-addr.arpa_ … _31.172.in-addr.arpa_ and _d.f.ip6.arpa_. Even if this behavior is fixed it will look ugly especially for mask 1, 9, 17 and 31 (128 records must be added).

That is since the way the reverse zone is designed, its possible to delegate the zone for steps of 8 bits at a time for ipv4 and 4 bits at a time for ipv6. 

You should check [RFC 2317](https://www.rfc-editor.org/rfc/rfc2317.html) which explains how to do classless delegation for reverse zones. You will need to write a script that uses the HTTP API to add records in the reverse zone as specified in that RFC.

**Comment by ShreyasZare** [comment]
> What I should exactly do? I tried to add _0/10 NS_ record for _64.100.in-addr.arpa_ primary zone but reverse query _100.65.0.1_ still be forwarded. Is there a simple way to solve my problem above?

Is your aim to block all of the reverse zone queries or is it to get them resolved locally via another authoritative zone that you have?

**Comment by ShreyasZare** [comment]
> I want to get _No such name PTR_ for all of the reverse zone queries of reserved networks which I sure never will be resolved. I use your program just as user-friendly DNS cache forwarder and I don't really need managing of authoritative zones.

Well in that case you do not need to create a reverse zone for different subnets. Instead for example, you can create a reverse zone for 192.168.0.0/16 of conditional forwarder type and it will catch all requests in that /16 and return NO DATA responses.

**Comment by ShreyasZare** [comment]
Thanks for sharing it here.
