### ISSUE TITLE
dotnet cannot use 200m to de-advertise files

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#575]
Yes, there is no way to use 200m files

**Comment by ShreyasZare** [comment]
Thanks for the post. I did not understand anything in the issue. Please elaborate it.

**Comment by ShreyasZare** [comment]
> > Thanks for the post. I did not understand anything in the issue. Please elaborate it.
> 
> My AD size is up to 200m, but the 200m file cannot be used as a complete AD file on dotbet

What is AD exactly? Is 200m size of file i.e. 200MB? Where you cannot use the file? Is this related to dotnet or the DNS Server?

**Comment by ShreyasZare** [comment]
> > > My AD size is up to 200m, but the 200m file cannot be used as a complete AD file on dotbet
> > 
> > 
> > What is AD exactly? Is 200m size of file i.e. 200MB? Where you cannot use the file? Is this related to dotnet or the DNS Server?
> 
> Even if the adhosts file exceeds 200m, it cannot be used normally in the dotnet program, and the number is not complete. The normal number is 600w or more
> 
> Sorry, I come from China, the translation software is not very good, there is no way to let you understand

Yes, I understand that you are using translation software so there are many problems with it. I would recommend that you use full sentences that describe the issue so that the translation is a bit better. Right now, you are entering short sentences which the translation software is screwing up with the context so its not legible.

**Comment by ShreyasZare** [comment]
> That is, the adhosts file exceeds 200M and cannot be used normally on the dotnet program, and also shows the incomplete number, and the normal number is more than 600w.
> 
> My de-ad rule has gone to 200m in size, but the 200m file can't be used on dotnet to de-advertise the full de-ad file.

> https://file-cn.trli.club:2083/ad-hosts/ad-hosts-pro/ad-hosts.txt

I tried the above host file which is 206MB in size on my laptop and its working well. I tried it using both the Settings > Blocking section options, and also using the Advanced Blocking app. In both cases its loading 6,543,191 domain names within 10-12 seconds and using around 1.1 GB memory.

What is the hardware config of your server that you are trying this on?

**Comment by liang-hiwin** [comment]
There are too many rules. There is no need for so many rules.

**Comment by ShreyasZare** [comment]
Closing this issue since the DNS server is able to load 200MB+ size hosts file without any issues.
