### ISSUE TITLE
Custom trusted certificates

### ISSUE THREAD

**Issue by ZzZombo** [TechnitiumSoftware/DnsServer#579]
I currently employ a custom DNSCrypt-proxy instance with self-signed certificate as a DoH forwarder in TDNS. However, due to a still unexplained quirk of my machine, it's root certificate gets (ir)regularly wiped from the Windows Trusted Roots storage. I have a scheduled task to import it every minute, but every so often when TDNS goes to resolve domain names the certificate is not re-imported in time so it fails with SSL exception. It would be fantastic if I could somehow mark this certificate as trusted directly in the software, so that no host name mistakenly fails due to an unrelated error.

**Comment by ShreyasZare** [comment]
Thanks for the post. You have a bigger issue that the root cert is getting removed. Adding such a feature is not useful except for your specific problem. You should rebuild your system by reinstalling OS and that should fix it.

**Comment by ZzZombo** [comment]
Reinstalling is not an option due to the required downtime at the moment, sorry. Could at least a configurable retry logic be added for this case? I figure if TDNS fails to talk to the forwarder for any reason, it should try again in the event the error is transient.

**Comment by ShreyasZare** [comment]
> Reinstalling is not an option due to the required downtime at the moment, sorry. Could at least a configurable retry logic be added for this case? I figure if TDNS fails to talk to the forwarder for any reason, it should try again in the event the error is transient.

When the DNS server fails to resolve, it saves a failure record in cache for 60 sec. Once that cached record expires, the DNS server will again try. You can reduce the failure cache time from Settings > Cache section so that it will try sooner when it receives a request again.

**Comment by ZzZombo** [comment]
That's not what I meant. I meant instead of going with the failure immediately retry right away, w/o getting back to the client and even remembering the fact there was an issue unless it fails enough times. Only then it should proceed with the error.

**Comment by ShreyasZare** [comment]
> That's not what I meant. I meant instead of going with the failure immediately retry right away, w/o getting back to the client and even remembering the fact there was an issue unless it fails enough times. Only then it should proceed with the error.

It already retries. Check the Settings > Proxy & Forwarders section for Forwarder Retries option. In your case its failing for all retries.

**Comment by ShreyasZare** [comment]
> Correct me if I'm wrong but does it really do that for SSL-related errors? I got the impression it fails as soon as one occurs.

Just checked and the retry work only for timeout issue. Making it retry for all errors wont make any difference in your case since the retries will complete within few milliseconds and will result in same error.
