### ISSUE TITLE
[Feature Request] Show Count of Block List URLs

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#58]
Please consider showing the count of Block List URLs (total lines) in the dashboard or a similar place.

Currently it's hard to determine if it has read in the correct amount of lines for the latest version of a block list. Showing a "last fetched" date and time would also be useful 🥇

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Dashboard is reserved only for statistical data and already shows total zones that are in block list. 

What you are asking is already being logged which you can check to see details like shown below:
![image](https://user-images.githubusercontent.com/10008172/61026242-80be7000-a3d0-11e9-981d-48c0a3884470.png)

**Comment by hl2guide** [comment]
Ah ok, total zones is what I was looking for 💃
