### ISSUE TITLE
Docker pull upgrade from 11.0 to 11.0.1, 11.02, or 11.03 loses all zones

### ISSUE THREAD

**Issue by pfjason** [TechnitiumSoftware/DnsServer#583]
Tried on two different servers. Both have docker volumes for /etc/dns/config in the container. After upgrade all zones are missing except for the defaults. Reverting back to 11.0 restores the zones to working. Didn't check other settings. Ubuntu 22.04 / Docker 23.0.1.

Running 11.0 did direct upgrade to 11.0.3, zones were gone, reverted to 11.0, zones were restored. From there tried 11.0 -> 11.0.1, and 11.0 -> 11.0.2 upgrades and they all do the same thing, so the problem seems to be in the changes between 11.0 and 11.0.1

**Comment by ShreyasZare** [comment]
Thanks for the post. Sorry for that but the docker volume path has been changed from /etc/dns/config to /etc/dns. Just edit the volume path in your docker-compose.yml and it will work. This is a one time breaking change since there is no way to make it work gracefully with docker.

**Comment by pfjason** [comment]
Thanks for the quick response, and thanks for the DNS Server. it succeeds for the more advanced configuration stuff where pi-hole fails, mainly in doing blocking while also allowing me to define a forwarding zone with overrides for lan services. Sorry for not reading the changelog before blowing up my network. I'm guessing you've had to answer this question enough times that you've realized you could have just left the config where it was and left /etc/dns empty except for the ./config dir? Asking as a dev who's made my own life harder in similar ways. :-p
