### ISSUE TITLE
A question not issue

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#584]
Hi,

How would i go about forwarding a dns query?

Say i want to forward all requests to www.google.com to my searxng instance on 10.0.0.100:8083?

thank you sir

**Comment by ShreyasZare** [comment]
Thanks for the post. You can do that by creating a conditional forwarding zone in Zones section for `www.google.com` and enter `10.0.0.100:8083` as the forwarder.

**Comment by ChristoffBo** [comment]
Hi Tried it, I Just get a The site cant be reached error: DNS_probe_finished_NXdomain

**Comment by ShreyasZare** [comment]
Test the domain name using the DNS Client tab on the DNS server web panel instead of testing it from the web browser. If you see NXDOMAIN as the RCODE in the DNS Client output then its the forwarder you have configured that is returning that answer which the DNS server is just caching and relaying.

**Comment by ChristoffBo** [comment]
Yea not working Rcode Server failure, what i am trying to do is that when ever anyone tries to open the google search engin i want it to open my SearXNG search engine. on that 10.0.0.100:8083 IP Address.

**Comment by ChristoffBo** [comment]
But i see if i add www.google.com to forward to my ip address i get ALOT of server failures so might not be a good idea.

thank you

**Comment by ShreyasZare** [comment]
Are you trying to do Man In The Middle (MITM) attack such that when a user enters `www.google.com` and gets redirected to another website? If yes then that is not possible without you generating a self signed root certificate and installing it on all your computers and mobile phones on your network.

The DNS server itself cannot do any kind of HTTP redirection. It can only return the IP address for your server. Rest everything you have to do by configuring the web server with your self signed certificate and installing that certificate on all clients.
