### ISSUE TITLE
Wildcards for Block List URLs?

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#59]
I've checked the documentation and tutorials.
Are wildcards implemented for blocked zones?

The rule I'm trying to create is:
Block all URLs ending with : .ac

Do I set it up as:
.ac
*.ac

or something else?

**Comment by ShreyasZare** [comment]
Thanks for the query. The blocked zones in the DNS Server will block a given domain name and all its sub domains. So, blocking example.com will block www.example.com too.

Wildcard usage is also supported wherein, if you block *.example.com then example.com is not blocked but all its sub domains are blocked.

So, if you want to block access to all websites ending with .ac then just add 'ac' to blocked zones.

**Comment by hl2guide** [comment]
I'm creating a block list, is it the same for Block List URLs?

**Comment by ShreyasZare** [comment]
Yes, this will work same if you create a block list file for all your custom domains.
