### ISSUE TITLE
Feature Request: PROXY Protocol support

### ISSUE THREAD

**Issue by rehanone** [TechnitiumSoftware/DnsServer#590]
**Abstract**

What would be required for this feature to completed:

- Add support for PROXY Protocol
- https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/
- https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

Why is this needed:

Technitium DNS supports DNS, DNS-over-TLS (DoT), DNS-over-HTTPS (DoH) and DNS-over-QUIC. But DNS-over-TLS does not  preserve the original IP address if it is proxied by a load balancer. This results in DNS server not knowing the correct IP of the client.

HAProxy, Ingress Nginx, Traefik and many other proxies are allowing to create TCP/UDP Load Balancers and allow the back-end to receive the correct IP of the client from the load balancer using a special PROXY protocol.

This inspiration for this feature came from this issue in [CoreDNS](https://github.com/coredns/coredns/issues/5544) where it is discussed in much more detail.

*Note:* Technitium DNS provides a unique DNS-over-HTTP mode that make load balancing much more robust for DNS-over-HTTPS as the proxy can directly terminate TLS connection and pass it internally over plain HTTP. So this issue in Technitium DNS is only applicable for DNS-over-TLS (DoT).

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will get this feature added in one of the next few updates.

**Comment by rehanone** [comment]
Thank you! I have found one implementation in [C#](https://github.com/OnKey/ProxyProtocol) but it does not look like it been maintained. Also it is on protocol version 2.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4 is now available that supports PROXY protocol version 1 & 2 for both UDP and TCP transports. Do update and let me know your feedback.
