### ISSUE TITLE
Looking for help with nxdomain

### ISSUE THREAD

**Issue by Code-Slave** [TechnitiumSoftware/DnsServer#591]
This is on me. Had this running fine on ver 9. Hey lets update the docker. Yea no backup. It killed all my config,dhcp etc. so starting over

i run a local dns farm.lan that i have added to the server. I set dhcp to add this for clients, and I added all my static ips in in.

My log is filling up with nx domains for farm.lan
ex:

2023-03-27 10:39:26 | 192.168.1.52 | Udp | Authoritative | NxDomain | lb._dns-sd._udp.farm.lan | PTR | IN
-- | -- | -- | -- | -- | -- | -- | --

2023-03-27 10:39:26 | 192.168.1.52 | Udp | Cached | NxDomain | lb._dns-sd._udp.2.0.0.192.in-addr.arpa | PTR | IN
-- | -- | -- | -- | -- | -- | -- | --

I also had it pulling from root servers to be authoritative? And yea forgot how i set that up nor can find the tutorial. resolution works thank god but would like to get back to a good state

**Comment by ShreyasZare** [comment]
Thanks for the post. If you still have the old docker volume intact then you just have to edit the volume path for you container from `/etc/dns/config` to `/etc/dns`.

**Comment by ShreyasZare** [comment]
Ah ok. The PTR requests look unusual and seems to be coming from some specific software probably related to load balancing.
