### ISSUE TITLE
recursive dns

### ISSUE THREAD

**Issue by Code-Slave** [TechnitiumSoftware/DnsServer#592]
Just getting some clarification. If i enable recursive queries in the config, This will then pull from the root servers yes? My goal is to not have dns  requests go outside my local net

**Comment by Code-Slave** [comment]
also need to block in.addr.arpa from top domains list

**Comment by ShreyasZare** [comment]
> Just getting some clarification. If i enable recursive queries in the config, This will then pull from the root servers yes? My goal is to not have dns requests go outside my local net

If you do not configure any forwarders then the DNS server does recursive resolution. This does not mean there wont be any outbound requests, In fact, there will be too many outbound requests, the firsts will go to the root servers, the next to the TLD servers, and further to the name servers that host the domain name.
