### ISSUE TITLE
DNS-over-HTTPS (JSON) is missing

### ISSUE THREAD

**Issue by justid** [TechnitiumSoftware/DnsServer#593]
I just upgrade DnsSserver to Version 11.0.3, and DNS-over-HTTPS (JSON) under Setting/Proxy&Forwarders is missing.
Is this option moved to somewhere or it just removed forever?
I really need this option, I am grateful for any help.

**Comment by justid** [comment]
> Yes, the protocol support for JSON transport is removed since its non-standard and badly designed protocol.

I understand that, but sometimes it's useful.
For example, It's very hard to get clean dns result in mainland china today, so i settled this path to get one:

1. Setting up a proxy
2. Setting up a cloudflare workers to redirect google dns
3. In the workers, I was setting edns_client_subnet=112.31.12.0/24 (which is nearly my public ip address)
4. Use workders url as forwarder and setting it to dns server
5. I got a clean dns server

I really need edns_client_subnet, otherwise all the dns result would be near my proxy country, and it will slow down the internet speed.

**Comment by ShreyasZare** [comment]
> > Yes, the protocol support for JSON transport is removed since its non-standard and badly designed protocol.
> 
> @ShreyasZare
> 
> I understand that, but sometimes it's useful. For example, It's very hard to get clean dns result in mainland china today, so i settled this path to get one:
> 
>     1. Setting up a proxy
> 
>     2. Setting up a cloudflare workers to redirect google dns
> 
>     3. In the workers, I was setting edns_client_subnet=112.31.12.0/24 (which is nearly my public ip address)
> 
>     4. Use workders url as forwarder and setting it to dns server
> 
>     5. I got a clean dns server
> 
> 
> I really need edns_client_subnet, otherwise all the dns result would be near my proxy country, and it will slow down the internet speed.

It seems useful but the JSON protocol fails to work when the record type is unknown to the DNS server. Which means that any query for new types like HTTPS/SVCB which are still not available in the DNS server will cause Server Failure response. When you use other transport protocols, the response is always in binary format which the DNS server can use as-is when answering queries to clients.

Yes, when using a proxy server, it will cause the responses to return IP address from the location near to the proxy server. I will check the feasibility of adding option to configure a default EDNS Client Subnet network address to make this work.
