### ISSUE TITLE
Forwarder Concurrency option clarification

### ISSUE THREAD

**Issue by HellboyPI** [TechnitiumSoftware/DnsServer#597]
I need some clarification regarding the option Forwarder Concurrency. Default value is 2.

1) Does this mean that in the Forwarders section there need to be 2 DNS resolvers for that option to work? Like, Google and Cloudflare DNS.

2) Does this option function on a first-come, first-served basis?

Technitum DNS sends the same DNS request to 2 or more DNS servers. But, only the DNS answer from the fastest responding DNS server will be forwarded to clients. Slower responses will be ignored.
Technitium DNS does that for every DNS query.
Is that correct?

**Comment by ShreyasZare** [comment]
> I need some clarification regarding the option Forwarder Concurrency. Default value is 2.

Thanks for asking.
 
>   1. Does this mean that in the Forwarders section there need to be 2 DNS resolvers for that option to work? Like, Google and Cloudflare DNS.

If you have set the value to 3 and you have less than or equal to 3 forwarders then all will be concurrently queried. By default the value is 2 so if you configure both `8.8.8.8` and `8.8.4.4` then both of them will be queried concurrently.

>   2. Does this option function on a first-come, first-served basis?

If there are more number of forwarders configured than the concurrency value then the selection is done at random.

> Technitum DNS sends the same DNS request to 2 or more DNS servers. But, only the DNS answer from the fastest responding DNS server will be forwarded to clients. Slower responses will be ignored. Technitium DNS does that for every DNS query. Is that correct?

Yes. The first positive answer that is received will be used and the resolver will stop waiting for any other concurrent requests that were made. This is done for all outbound requests to the forwarders.

**Comment by ShreyasZare** [comment]
> I noticed that it is not possible to mix DNS servers with different protocols in Forwarders. Example: Quick DNS server with DoH DNS server.

Yes, this is done by design to prevent anyone from mixing encrypted protocols with unencrypted ones.
 
> Could this be changed in a future version of Technitium DNS?

Since its by design, there is no plan to change it. However, if you still want to use different protocols, you can create a conditional forwarder zone for `.` (that is root zone) and then create FWD record for each forwarder where you can select the protocol you wish. There is also Advanced Forwarding app which you can install and use the adguard file format to use multiple forwarders with different protocols.
