### ISSUE TITLE
Request for new features

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#599]
Can different upstream resolutions be used according to the client subnet ip

**Comment by liang-hiwin** [comment]
Ok, because there is no related configuration document for advanced forwarding, I still don't know much about it

**Comment by liang-hiwin** [comment]
I also hope that the big brother can take the time to forward this advanced forwarding to a little documentation

**Comment by ShreyasZare** [comment]
With the app, you will be able to specify which forwarder to be used by which network subnet. Check out the config json once.

**Comment by liang-hiwin** [comment]
> Check out the config json once

Thanks

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.1 is now available that fixes this issue. Do update and let me know your feedback.
