### ISSUE TITLE
Leased IP is not freed after expire

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#60]
As you can see on screenshot it already expired.
![Clipboard01](https://user-images.githubusercontent.com/740757/61152390-fcafd980-a4f0-11e9-94c6-43284f653b16.jpg)
Lease time is set to 7 days. Clients with IPs 10.10.10.100 and 10.10.10.102 is not available anymore and last seen more than 1.5 week ago. And before with issue expire date was 16.07.2019.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

The lease expiry gets extended only when the client renews lease. It seems that the clients renewed leases on 12.07.2019. Lease renewal can be done when the clients reboot or when lease duration is over 50%. 

Did these clients boot or connect to the network on 12th?

**Comment by Globulopolis** [comment]
Clients have a static IP(not a 10.100 and 10.102) since end of a June. And yes, clients reboot 12.07

**Comment by ShreyasZare** [comment]
Well that's strange. I am unable to reproduce this issue on my test setup. Can you try to reproduce it again and let me know the steps?

**Comment by Globulopolis** [comment]
I'll try it.

**Comment by ShreyasZare** [comment]
@Globulopolis were you able to reproduce this issue again?

**Comment by Globulopolis** [comment]
@ShreyasZare no, I think it was misconfiguration in network.
