### ISSUE TITLE
'Allow Domain' does not work with 'Advanced Blocking' app

### ISSUE THREAD

**Issue by dannykorpan** [TechnitiumSoftware/DnsServer#601]
Hi,

with installed and configured Advanced Blocking app, the 'Allow Domain' function does not work.

Kind Regards,
Danny

**Comment by ShreyasZare** [comment]
Thanks for asking. The Advanced Blocking app works independent of the DNS server's built-in features. You need to configure the app itself to allow domain names that you wish to allow.

**Comment by dannykorpan** [comment]
Yes, but it's not consistent and I think there is room for improvement. I think it's not an outlandish feature suggestion.

**Comment by ShreyasZare** [comment]
> Yes, but it's not consistent and I think there is room for improvement. I think it's not an outlandish feature suggestion.

I understand why you would want to have it but, the apps are not part of the DNS server itself. The DNS server provides a platform to allow creating generic apps. The apps do not have access to the DNS server settings so they cannot check if a domain is allowed in the built in blocking feature. Even if there was a way invented to do so, the app has support for groups which are mapped to network subnets so it will be not logical to have it use a single allow list from the DNS server.

There is plan to have a GUI for the DNS apps so once its available, it will be as easy as using the DNS server's web panel options to configure the DNS apps. Once GUI for apps is available, it will give much better user experience and will look consistent.

**Comment by dannykorpan** [comment]
That's a very good compromise.

**Comment by dannykorpan** [comment]
@ShreyasZare Is the feature implemented, as you described in your last post?

**Comment by ShreyasZare** [comment]
> @ShreyasZare Is the feature implemented, as you described in your last post?

The GUI for DNS apps is being tracked in this [issue](https://github.com/TechnitiumSoftware/DnsServer/issues/505) already.
