### ISSUE TITLE
Request to add DNS server compatible Chinese domain name

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#602]
For example, the Chinese domain name "网站家.cn" will be like this, after transcoding, it will be "xn--9iq21t6wdw30c.cn"

![5R@59}X_DDNG88XQ1C{UR8Q](https://user-images.githubusercontent.com/17548936/230003447-5e6b5c6d-7bc9-46da-b04e-c4226e44e674.png)

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.1 is now available that adds support for Internationalized Domain Names (IDN). Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
thanks

**Comment by liang-hiwin** [comment]
> 网站家.cn

It works fine, thank you very much

**Comment by ShreyasZare** [comment]
Thanks for confirming!
