### ISSUE TITLE
How do I close this software?

### ISSUE THREAD

**Issue by zhl111** [TechnitiumSoftware/DnsServer#603]
When I had to close the software for some access, it said:
`Are you sure to close the system tray icon?`
`Closing the system tray icon will not stop Technitium DNS Server.`

I'm upset that I can't close the software. What can I do to close it?

**Comment by Hemsby** [comment]
The System Tray App is independent of the Server. If you want to stop the Server you need to stop the service (which is also possible from the tray App).  But if you only have Technitium as your DNS Client resolver then you will have no DNS resolution.

**Comment by ShreyasZare** [comment]
Like @Hemsby mentioned, the DNS server is running as a system service and the system tray app is just a small app running independently for convenience. To stop the DNS server you can stop the Technitium DNS Server from the Windows Services console or using the system tray app Service > Stop menu. Note that the service will automatically start when you restart the computer so you need to change the service startup type from the Windows Services console to manual.

**Comment by Vitalicus** [comment]
How to stop it in ubuntu?
