### ISSUE TITLE
[Feauture request] Provide option to specify log file location

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#61]
I typically store all logs on a separate drive, so should the drive become full the computer continues to operate.

At the moment there is an option to log all queries, this option comes with a warnings about the increased consumption of disk space if this option is turned on.

Given this, would it be possible to discuss providing such an option and your thoughts on an implementation likely to be accepted if a pull request was made?

Also, great work on the DHCP server, works a treat :)

**Comment by ShreyasZare** [comment]
Thanks for the compliments and feedback.

That is a good option to have. I am also adding syslog support so will add both together.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds support for specifying log file location.
