### ISSUE TITLE
openssl1.1.1f update pkg address to use for libmsquic

### ISSUE THREAD

**Issue by prooshani** [TechnitiumSoftware/DnsServer#613]
Dear @ShreyasZare,

Thank you for your recent update which I am trying to upgrade to all my DNS servers.

To be able to use Dns-over-QUIC we need to use openssl version 1.1.1f and you already guided how to install it at [this](https://blog.technitium.com/2023/02/configuring-dns-over-quic-and-https3.html) address.
However, Open SSL recently updated its package libraries and to last version (2.17) will not install anymore using local installation mentioned at the guided installation.
The last version is 2.18 and I hope you could update that page to point to correct package addresses.

The correct code snippets are:

wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.18_amd64.deb
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.18_amd64.deb
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.18_amd64.deb
sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2.18_amd64.deb
sudo dpkg -i openssl_1.1.1f-1ubuntu2.18_amd64.deb

Hope you could implement it inside your installation to resolve later issues and easier installation and usage.

Thank you again for this valuable service.

**Comment by ShreyasZare** [comment]
Thanks for the post. I have update the blog post with new code snippet.

> Hope you could implement it inside your installation to resolve later issues and easier installation and usage.

This was not implemented in the installer since the `libmsquic` library will soon support the `openssl v3.x` version.

> Thank you again for this valuable service.

You're welcome.
