### ISSUE TITLE
[App Feature Request] Wildcard Blocklists in Advanced Blocking App

### ISSUE THREAD

**Issue by devipasigner** [TechnitiumSoftware/DnsServer#615]
Hello, I would like to be able to add wildcard blocklists when using the advanced blocking app. Right now I have to choose between using standard blocking with no regex blocklists and advanced blocking without wildcard and only adblock. This is more of an enhancement and not super important but it would be great if you could add it. Thanks for all your work!

**Comment by ShreyasZare** [comment]
Thanks for the post. Wildcard blocklists are supported in Advanced Blocking app too.
