### ISSUE TITLE
DnsServer starts but immediately fails - Event ID 1026

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#616]
When I try to start the DnsServer from the DNS Server App (Service > Start), I get the service started message but the service immediately fails (stops).
DNS Server is being installed with compiled DnsServerSetup supplied with the project.

![image](https://user-images.githubusercontent.com/6101736/235813533-d3369b88-74e4-4d3b-886c-f5ecc803d0a5.png)

```
Application: DnsService.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'TechnitiumLibrary.Net, Version=8.2.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'TechnitiumLibrary.Net, Version=8.2.1.0, Culture=neutral, PublicKeyToken=null'
   at DnsServerCore.DnsWebService.StopAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DnsServerCore.DnsWebService.StopAsync()
   at DnsServerCore.DnsWebService.DisposeAsync() in C:\Web7\DnsServer\DnsServerCore\DnsWebService.cs:line 153
   at TechnitiumLibrary.TaskExtensions.Sync(ValueTask task) in C:\Web7\TechnitiumLibrary\TechnitiumLibrary\TaskExtensions.cs:line 66
   at DnsServerCore.DnsWebService.Dispose() in C:\Web7\DnsServer\DnsServerCore\DnsWebService.cs:line 172
   at DnsServerWindowsService.DnsServiceWorker.Dispose() in C:\Web7\DnsServer\DnsServerWindowsService\DnsServiceWorker.cs:line 60
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>g__DisposeAsync|16_0(Object o)
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at DnsServerWindowsService.Program.Main(String[] args) in C:\Web7\DnsServer\DnsServerWindowsService\Program.cs:line 29
```

cc: @ruskpr

**Comment by mwherman2000** [comment]
This is a fresh installation of DnsServer 11.1.1 on a Windows 11 Pro laptop.  DnsServer has never been installed on the machine previously.

**Comment by mwherman2000** [comment]
`start.bat` works properly

**Comment by ShreyasZare** [comment]
Thanks for the post. It seems that you have missed pulling the latest code for `TechnitiumLibrary` repo. Pull the code for it and then follow the steps to generate the windows setup.

**Comment by mwherman2000** [comment]
We pulled it around noon today

**Comment by ShreyasZare** [comment]
Ok then it seems that for some reason, an older version of the DLL file is being installed. Try to compile both the solutions again in release mode and publish the system tray app and the windows service projects again.

**Comment by mwherman2000** [comment]
K

**Comment by mwherman2000** [comment]
No luck

> Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'TechnitiumLibrary.Net, Version=8.2.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Is this a problem with `TechnitiumLibrary.Net` missing or being the wrong version? ...or if `TechnitiumLibrary.Net` has a dependency on another assembly, can this also be part of the problem?

I need to leave this for this evening but we still need to figure this out.

**Comment by ShreyasZare** [comment]
> No luck
> 
> > Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'TechnitiumLibrary.Net, Version=8.2.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
> Is this a problem with `TechnitiumLibrary.Net` missing or being the wrong version? ...or if `TechnitiumLibrary.Net` has a dependency on another assembly, can this also be part of the problem?

The error message comes same for both conditions. Check if the file exists in the installation folder. If it exists then its the wrong version issue.

> I need to leave this for this evening but we still need to figure this out.
> 
> What is the correct/most recent version of `TechnitiumLibrary.Net`?

The recent version is `8.2.1` which the DNS server process is expecting.

**Comment by mwherman2000** [comment]
This looks all correct...
![image](https://user-images.githubusercontent.com/6101736/235839560-ed679730-e7ba-4931-bdb8-5c18bd0357ac.png)

**Comment by ShreyasZare** [comment]
I am not exactly sure why its not working. However, there are some extra Technitium Library DLLs in the screenshot you posted that should not exists in the installation folder. You should have only the following DLLs files shown below:

![image](https://user-images.githubusercontent.com/10008172/235843105-f4b0c308-abf6-47e7-a6ae-038bf427b03f.png)

Have you copied all the DLL files from the library project's bin folder here?

Are you using the exact output files generated when you publish both the `DnsServerSystemTrayApp` and `DnsServerWindowsService` projects from the `DnsServer\DnsServerWindowsSetup\publish` folder?

**Comment by mwherman2000** [comment]
I've fixed the problem and it may have been my "user error" all along.  My apologies for the _firedrill_.

We're about to add about a dozen custom resource records for our Web 7.0 project and in the past versions (from years ago), we'd link the TechnitiumLibrary projects into the DNSServer.sln solution so that we could compile and edit both sets of projects from the DNSServer solution.  I think this messed things up.  So we're back to keeping the 2 solutions completely separate.

My apologies.

**Comment by mwherman2000** [comment]
Closed

**Comment by ShreyasZare** [comment]
Good to know you got it working.
