### ISSUE TITLE
Account lockout when "Session Timeout" set to "0"

### ISSUE THREAD

**Issue by Sp00kje** [TechnitiumSoftware/DnsServer#618]
When i change the "Session Timeout" to "0" to disable the session timeout, i get logged-out.
when i login again i get to dashboard, but every action after that will result in getting logged-out again.

this wail the text next to the Session Timeout failed is: "valid range 0-604800; default 1800; set 0 to disable"

**Server:**
Debian 11.7, originally installed & updated using the "curl -sSL https://download.technitium.com/dns/install.sh | sudo bash" command.
Technitium DNS Server - Version 11.1.1

Client:
Debian 11.7
- Firefox 102.10.0esr (64-bit)
- Chromium 113.0.5672.63
there is no differences between "normal" and "private" browsing

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I checked it in two different installations and its working well without any issues. Can you provide exact steps to reproduce this issue?

**Comment by Sp00kje** [comment]
I just tried it on on my secondary server, and is was working as expected.
after i did an Password recovery en check my account (which was "lockout") i found the problem.
The session timeout was set to 1 second (which probably happened thru me using the scroll-wheel on my mouse in that number field).

so it was just an user error (Whoops, sorry).
But just an an feature request, is it possible to set the minimum possible Timeout to say 60 or 120 second's?

either way, thanks for checking.

**Comment by ShreyasZare** [comment]
Thanks for those details. Yes, it makes sense to have a minimum value set to avoid such issues. Will get that implemented in the next release.

**Comment by ShreyasZare** [comment]
Technitium v11.2 is released that fixes this issue. Do check and let me know your feedback.
