### ISSUE TITLE
Quad9: Add Secondary IPs

### ISSUE THREAD

**Issue by ztheory** [TechnitiumSoftware/DnsServer#622]
For Google, Cloudflare, etc, the secondary IPv4 and IPv6 addresses are included, but not for Quad9.

Secondary IPv4 (Secured): 149.112.112.112
Secondary IPv6 (Secured): 2620:fe::9

Secondary IPv4 (Unsecured): 149.112.112.10
Secondary IPv6 (Unsecured): 2620:fe::fe:10

Source: https://quad9.net/service/service-addresses-and-features

**Comment by ShreyasZare** [comment]
Thanks for pointing that out. Will get it updated in next release.

**Comment by ShreyasZare** [comment]
Technitium v11.2 is released that adds those addresses. Do check and let me know your feedback.
