### ISSUE TITLE
CPU overload, dotnet problems?

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#628]
![Screenshot_2023-05-20-11-41-53-801_com.termux.jpg](https://github.com/TechnitiumSoftware/DnsServer/assets/28734349/09218e21-51b5-4c66-80bb-8154d9285982)

**Comment by ShreyasZare** [comment]
Thanks for the post. Check the DNS logs and post any errors that you see in there.

**Comment by ShreyasZare** [comment]
> Can I send it to your email? I checked the upstream DNS and it's normal. Is there any way to do your domain name? Can you set CloudFlasle CDN

Yes sure, send an email with details. There is no issue with the Technitium website and things are working as expected.

**Comment by ShreyasZare** [comment]
> It's over, there is no way for the Chinese side to visit go.technitium.com

If you visit https://go.technitium.com then its going to return 404 since its just a URL redirection service. The service will redirect to a specific URL in its database based on the `id` parameter it receives in the URL. For example, try https://go.technitium.com/?id=1.

**Comment by ShreyasZare** [comment]
> > > It's over, there is no way for the Chinese side to visit go.technitium.com
> > 
> > 
> > If you visit https://go.technitium.com then its going to return 404 since its just a URL redirection service. The service will redirect to a specific URL in its database based on the `id` parameter it receives in the URL. For example, try https://go.technitium.com/?id=1.
> 
> Yes, are you anti-proxy github? 

I don't know what that means. The `id=1` URL will redirect to the main website which you see in the screenshot.

**Comment by ShreyasZare** [comment]
> The email address has been submitted

I have not received any email till now. Do check again once at your end.

**Comment by ShreyasZare** [comment]
> > > The email address has been submitted
> > 
> > 
> > I have not received any email till now. Do check again once at your end.
> 
> Isn't this one? You look at trash cans and the like? 

Did not receive the email. Checked spam and also quarantine on my server. Did you get any bounce email? Try sending it again.

**Comment by ShreyasZare** [comment]
Have not received email yet. Try sending it from another email id.

**Comment by ShreyasZare** [comment]
I got the email this time. Checked the logs and there are several errors like below:

`
Web Service failed to start: System.BadImageFormatException: The signature is incorrect. The format of the file '/opt/dotnet/shared/Microsoft.AspNetCore.App/7.0.5/Microsoft.Extensions.Options.dll' is invalid.
`

Which seems to indicate that the files on the disk are corrupt. Try to take a complete backup of the DNS server's config from the Settings > Backup Settings option and then uninstall the DNS server and reinstall it again. This should reinstall the dotnet files and fix any file corruption issues.

**Comment by ShreyasZare** [comment]
> Can the Internet solve this problem in China? I can't update the app now, or do I have any other mirrors

You can disable IPv6 on your server that is running the DNS server and try again. This will force all requests to use IPv4 so if there are any issues with IPv6 then it would get resolved.
