### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#629]
DND sometime don't showing page and get an DNS_PROBE_FINISHED_NXDOMAIN error ?

Linux : 18.04
Windows Client : 10
DNS : 11.1.1

**Comment by ShreyasZare** [comment]
Thanks for that post. Check the DNS logs from the web panel and post any errors that you see there.

**Comment by AkbarAsghari** [comment]
11.1.1 look likes wrong 
check out this 1.1.1.1
