### ISSUE TITLE
Logging - "Use Local Time" has no effect

### ISSUE THREAD

**Issue by michael-pellegrini** [TechnitiumSoftware/DnsServer#630]
Hi Shreyas,
The "Use Local Time" check box does not affect the actual time in the latest docker image.
![LocalTime](https://github.com/TechnitiumSoftware/DnsServer/assets/47049792/dd6e0c4c-3f11-473d-9a05-e5bc6e569ad2)

**Comment by ShreyasZare** [comment]
Thanks for the post. This seems to be the same issue we discussed earlier in #374. The solution is to configure timezone for the docker container as [discussed here](https://github.com/TechnitiumSoftware/DnsServer/issues/426#issuecomment-1204915197).

**Comment by michael-pellegrini** [comment]
Selecting the check box to "use local time" worked on version 10.0.1


On the Latest version 11.1.1 I have to set ENV and symlink Timezone to local time on dockerfile like on version 8 
`ENV TZ=America/New_York`
`ln -sf /usr/share/zoneinfo/$TZ /etc/localtime`

**Comment by ShreyasZare** [comment]
> Selecting the check box to "use local time" worked on version 10.0.1
> 
> On the Latest version 11.1.1 I have to set ENV and symlink Timezone to local time on dockerfile like on version 8 `ENV TZ=America/New_York` `ln -sf /usr/share/zoneinfo/$TZ /etc/localtime`

From code perspective nothing has changed between these two versions regarding the "use local time" option. The code just uses the local time that the .NET runtime returns which in turn depends on what timezone is set at the OS level. So, in case of docker, its what timezone the docker container is using. There is nothing that can be done in code to change this behavior.

**Comment by michael-pellegrini** [comment]
Thank you for the update. Can mark this one closed.
