### ISSUE TITLE
DNS over HTTP anti-proxy issues

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#635]
Technitium ip is 192.168.2.3 DNS over http is http://192.168.2.3/dns-query
 but using DNS over http is problematic.
This is the image of DNS over HTTP inspection
![1684813382740](https://github.com/TechnitiumSoftware/DnsServer/assets/28734349/4ec01bfd-7551-467a-9f6d-02851db7f787)

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS-over-HTTP URL that you have will work only when you send it the correct DoH request. When you just use the URL with curl or enter it on web browser then its going to redirect to the base URL which displays the DoH info web page.

To test it, use the built-in DNS Client tab where you should enter the DoH URL as the server, select the protocol as DNS-over-HTTPS and then use any domain name to do the test.

**Comment by ShreyasZare** [comment]
> The way I set it up, it's direct feedback to the home page.

Your reverse proxy config looks correct. And like I said earlier, if you visit the URL with a web browser, its going to get 302 redirect to the home page which is how its expected to work.

The URL will work for DoH only and only when it received a proper DoH request. Which is why you should not use curl or web browser to test it. You must use the DNS Client tab to test it.

**Comment by ShreyasZare** [comment]
Thanks for the details. Looks like the `AuroraDNSC` DoH client that you are using is sending the content type as a `ct=application/dns-message` query string value in the URL which is not defined the DoH standard. 

The DNS server expects a `Accept: application/dns-message` header in the request and only then the DNS server will consider it as a valid DoH request.

Test the URL with DNS Client and see if that works.

**Comment by ShreyasZare** [comment]
> > Thanks for the details. Looks like the `AuroraDNSC` DoH client that you are using is sending the content type as a `ct=application/dns-message` query string value in the URL which is not defined the DoH standard.
> > The DNS server expects a `Accept: application/dns-message` header in the request and only then the DNS server will consider it as a valid DoH request.
> > Test the URL with DNS Client and see if that works.
> 
> Got it, but what software supports application/dns-message?

What are you trying to achieve here? It depends on that.

**Comment by ShreyasZare** [comment]
> > What are you trying to achieve here? It depends on that.
> 
> Because I am on Android, I can't connect, but it's normal to rely on certificates on ios14 systems.

You can use DoT with Android directly instead of DoH.

Also, I am updating the DNS server to allow accepting DoH request without the `Accept` header. So that should make it work for the DoH client you tried.

**Comment by ShreyasZare** [comment]
Technitium v11.2 is released that will allow DoH request without the `Accept` header. Do check and let me know your feedback.

**Comment by ShreyasZare** [comment]
> > Technitium v11.2 is released that will allow DoH request without the `Accept` header. Do check and let me know your feedback.
> 
> The relevant video has been sent, the anti-proxy code is on it, there is no change.

Received the video in email. I tested the DoH URL that you have configured in that mobile app from my Internet connection and its working well as expected. I do not see any issues with it. Check the DNS logs to see if there are any errors logged for the time you used the Android app.

**Comment by ShreyasZare** [comment]
Instead of using 3rd party app, use the built in DoT support in Android which works well.

**Comment by ShreyasZare** [comment]
> > Instead of using 3rd party app, use the built in DoT support in Android which works well.
> 
> I know that DOT is normal, but not with third-party software on Android, iOS DOH is normal, and parsing is normal. I really don't understand Android

You should try android Private DNS option in settings. Its very straight forward to use.
