### ISSUE TITLE
Windows 7 test is required

### ISSUE THREAD

**Issue by JeanPaulLucien** [TechnitiumSoftware/DnsServer#638]
Did you launch this software in Windows 7 before to share? It needs to be checked that works correctly.

I mean Windows 7 64-bit SP1. Server version is 11.1.

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS server is tested on Windows 7 SP1. If you have any issues then make sure you have installed the [prerequisites](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70#additional-deps) needed for Windows 7 and Windows Server 2012 R2.
