### ISSUE TITLE
Spelling Error: "Till" should be "Until"

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#643]
Sorry, not trying to be pedantic. 

Settings > Blocking > Temporary Blocking Disabled Till

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/20692314/b19b91b3-47ae-4483-be3f-92d9acf570cd)

**Comment by ShreyasZare** [comment]
Thanks for the post. "Until" and "Till" both mean the same thing and can be used interchangeably.

Source: 
https://www.merriam-webster.com/words-at-play/should-you-use-until-or-till-or-til
https://www.grammarly.com/blog/until-till-til/

**Comment by pricerc** [comment]
Have you not heard the phrase "Till death do us part" ?
