### ISSUE TITLE
URI Record

### ISSUE THREAD

**Issue by firestrife23** [TechnitiumSoftware/DnsServer#647]
Since URI records are needed for FreeIPA, I don't see an option to add them to the zone.

https://www.rfc-editor.org/rfc/rfc7553.html

**Comment by ShreyasZare** [comment]
Thanks for the request. Will get URI record type support added soon.

Meanwhile, you can use the `Unknown` option in the Add Record which allows you to be able to add generic records that are not supported directly by the DNS server. To do that, you will have to enter the RR type code manually and also generate a hex string corresponding to the URI record's RDATA wire format that is described in the RFC. To make it easy, use any hex editor software to generate the RDATA and then enter the hex codes from it when adding the generic record.

**Comment by ShreyasZare** [comment]
You have to encode the priority and weight as 16 bit signed integer in hex (big-endian). Take a look at the hex editor screenshot below:

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/10008172/afff446a-0cda-4b1c-bde9-ff76db6be662)

So, your final hex string that you need to enter as the value will be:
`000000646b7262357372763a6d3a7564703a6970612e6578616d706c652e636f6d`

**Comment by firestrife23** [comment]
Thank you, and that's really helpful!

**Comment by ShreyasZare** [comment]
Good to know you got the generic record added.

Keeping this issue open so that I can post update here when the URI record support is available.

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which adds support for URI record type. Do update and let me know your feedback.

**Comment by firestrife23** [comment]
No problems, everything is operating as it should! Thank you very much!

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
