### ISSUE TITLE
List of available downloads?

### ISSUE THREAD

**Issue by coolaj86** [TechnitiumSoftware/DnsServer#650]
I'd like to get this up on https://webinstall.dev/, but I don't see any Releases page or Downloads page that has a list of available downloads for various platforms to be able to select a specific version for a specific platform.

I tried https://download.technitium.com/dns/ and https://download.technitium.com/, but they both 403.

Is there such a page?

**Comment by ShreyasZare** [comment]
Thanks for the post. Yes, there is archive page [here](https://download.technitium.com/dns/archive/) which lists all available downloads.

**Comment by ShreyasZare** [comment]
> > Thanks for the post. Yes, there is archive page [here](https://download.technitium.com/dns/archive/) which lists all available downloads.
> 
> Are there other apps to download the tarball?

There is apps folder inside each version folder where apps updated for that version are available.
