### ISSUE TITLE
When will quic v2 be updated?

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#655]
When will quic v2 be updated?

https://www.rfc-editor.org/rfc/rfc9369.html
https://www.rfc-editor.org/rfc/rfc9368.html

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS server uses `libmsquic` library for QUIC support. So, QUIC v2 will be available whenever `libmsquic` adds support for it.
