### ISSUE TITLE
Feature Request: Date/Timestamp on Backups

### ISSUE THREAD

**Issue by vengent** [TechnitiumSoftware/DnsServer#656]
Currently backups are named DnsServerBackup.zip  

Could you add a date/timestamp to the filename to make it easier to keep and track multiple backups?

**Comment by ShreyasZare** [comment]
Thanks for that feedback. Will make those changes in next release.

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which updates the backup file name. Do update and let me know your feedback.
