### ISSUE TITLE
[Auto PTR] "Reverse zone is not a primary zone."

### ISSUE THREAD

**Issue by MaffooClock** [TechnitiumSoftware/DnsServer#659]
My reverse zones are setup as Conditional Forwarder so that requests can be forwarded to my router's DNS service to resolve DHCP clients (as DHCP is handled by my router).  I also intend to add records into the reverse zones directly for static hosts.

Thus, it is my expectation that queries to these reverse zones will first be handled locally if a record exists, or forwarded to the router otherwise.  This seems to work just fine.

However, the Auto PTR feature throws "Error! Reverse zone '2.16.172.in-addr.arpa' is not a primary zone." when I have the Add reverse (PTR) record option checked.  But I can add the PTR record in the zone manually.

So it seems that this check isn't actually necessary, and Auto PTR should automatically create records in non-primary zones.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get that check removed in the next update.

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which fixes this issue. Do update and let me know your feedback.
