### ISSUE TITLE
New records for reverse zones should default to PTR type

### ISSUE THREAD

**Issue by MaffooClock** [TechnitiumSoftware/DnsServer#660]
When adding a new record to a zone having a name that matches the pattern for a reverse zone, it would be nice if the Type field were automatically set to PTR so that I'm not forced to set it myself every time.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get it done in the next update.

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which fixes this issue. Do update and let me know your feedback.
