### ISSUE TITLE
Feature Request: Allow changing between primary and secondary zones

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#665]
Please have some sort of toggle to allow changing from a primary zone to a secondary zone and then also the reverse from secondary to primary. This would make server migrations super simple. Yes, the DNS client allows for the domain transfer then import, but if the primary is not responsive for whatever reason it would simply be easier to promote the zones on a different secondary server to primary status.

**Comment by ShreyasZare** [comment]
Thanks for the request. Will get this added soon.

**Comment by ShreyasZare** [comment]
Version 11.3 is now available which adds the feature to allow changing zone type. Do update and let me know your feedback.
