### ISSUE TITLE
[Feauture request] Add option to download backup of server config

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#67]
I've been messing around quite a bit with the settings and built up a large number of settings that I would need to reconfigure if I were to have to reinstall the DHCP server.

I imagine I can backup the config by simply making a copy of the config folder, but others may not be aware they can do this. Would it be worthwhile therefore adding an option to be able to download the config in zip format from the web console?

**Comment by Matthew-Bonner** [comment]
And an option to restore the configuration from the backup, naturally.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. This will be useful feature to have.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds backup/restore options in setting tab.
