### ISSUE TITLE
Proxy configuration doesn't seem to work

### ISSUE THREAD

**Issue by osorionicolas** [TechnitiumSoftware/DnsServer#673]
Hi,

I have a proxy in a cloud server, when I configure the proxy on my computer network settings it works properly (HTTP/S) but when I set the proxy on the DNS Server it's not routing the outbound network request through it. 

Why would that happend? 

Let me know what info do you need as context.

Thanks!

**Comment by ShreyasZare** [comment]
Thanks for the post. When you configure the DNS server to use a proxy from Settings > Proxy & Forwarders section, all the outbound requests that the DNS server makes will be send via the proxy server. 

You can test this by running packet capture tool like Wireshark and inspect the outbound traffic. If you find that the DNS server is not using proxy then do share the config screenshots and the packet capture pcap file.

Note that configuring proxy for the DNS Server will not cause outbound request that other apps on your computer make to go via the proxy server.
