### ISSUE TITLE
DHCP not leasing

### ISSUE THREAD

**Issue by damjankumin** [TechnitiumSoftware/DnsServer#674]
I have manual installation on Ubuntu 22.04 VM (using provided script from page). The installation itself is default install, after that done the `apt update` and` apt upgrade` - all successful.
Once running, I checked if the needed ports are listening and they are. The configuration itself was made simple - handle out IP in network, that the DHCP was connected to, given it a 100 IP addresses.

Regardless of what type of VM/service is requesting IP on the network, the DHCP is not responding and handling out IPs. I disabled the DHCP on the network from the router completely - still no DHCP leases. From logs, no errors reported no nothing - just sits there idling.

Any idea what could instigate such behaviour? I am looking into replacing the DNS and DHCO (manly) in my completely on my network and now this is like a true blocker.

Thank you!
D

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Please share your DHCP scope config (screenshots) and your network config on which the DNS server is running. You can also email them to support@technitium.com instead of posting here if you wish to.

**Comment by damjankumin** [comment]
sorry for late reply - this is the DHCP page. I disabled my existing DHCP again, tried it out - one machine rebooted (even tried to renew before that) and now machine is not available on network at all.
Screenshot is attached.

<img width="1130" alt="Screenshot 1" src="https://github.com/TechnitiumSoftware/DnsServer/assets/21099756/1f5286eb-2852-4b09-8d73-a30f72e701ec">
<img width="1142" alt="Screenshot 2" src="https://github.com/TechnitiumSoftware/DnsServer/assets/21099756/dae7483b-f906-493b-8e30-b1bc3b303aea">
<img width="1151" alt="Screenshot 3" src="https://github.com/TechnitiumSoftware/DnsServer/assets/21099756/d0cdeb3f-c32b-46b1-9a2f-c794a07797b1">
<img width="934" alt="Screenshot 4" src="https://github.com/TechnitiumSoftware/DnsServer/assets/21099756/6a77c8c6-e76e-48d9-84ca-9292cc95f67c">

**Comment by ShreyasZare** [comment]
Thanks for the details. You need to set `255.255.255.0` as the subnet mask. Also, specify the DNS server address manually since loopback address is getting detected which wont work for clients. Try again after making the changes and see if that works.

**Comment by ShreyasZare** [comment]
> Made the changes to reflect your suggested settings. For now, still nothing.. I am trying to get some logs bot for now I see nothing - as if the server is not even doing or trying anything

In the list of DHCP scopes in the GUI, do you see "0.0.0.0" as the Interface value or the IP address of your network adapter?

Also, do you have firewall? If yes then have you created rule to allow inbound UDP port 67?

**Comment by damjankumin** [comment]
it is in-fact, 127.0.0.1
No FW for now as I am getting it to work first, then security comes into play

**Comment by Hemsby** [comment]
You cant use a local loopback address for DHCP.  Looking at your screenshot, you would need to set it to something in the 172.21.8.x range outside of the lease scope addresses.  172.21.8.2 would be good as the router is .1

**Comment by damjankumin** [comment]
I understand about the 127.0.0.1 - but - how to set it correctly? I see no option to set the interface or the interface address. I have lease range from 172.21.8.231 to 234. The router or the GW is set to 172.21.8.1 as there is the actual GW. So where to set the IP you mention of .2?

**Comment by Hemsby** [comment]
.32 is dynamic or static on the ubuntu vm?  It would need to be static.

**Comment by damjankumin** [comment]
it is static

**Comment by Hemsby** [comment]
And you are able to enable the scope?  or you receive an error?

**Comment by ShreyasZare** [comment]
> it is in-fact, 127.0.0.1 No FW for now as I am getting it to work first, then security comes into play

It should show your interface address i.e. "172.21.8.45". Check again if the subnet mask value is correct. Disable and enable the scope once manually and see if it shows the expected Interface address.

**Comment by damjankumin** [comment]
in actuality, I rebooted the server, disabled and enable the scope and now it is working. It is literately "have you tried to turning it off and on again?"

**Comment by ShreyasZare** [comment]
> in actuality, I rebooted the server, disabled and enable the scope and now it is working. It is literately "have you tried to turning it off and on again?"

Good to know that you got it working.
