### ISSUE TITLE
DHCP leases lost when updating

### ISSUE THREAD

**Issue by zpxp** [TechnitiumSoftware/DnsServer#675]
Updated from 11.1 to 11.3 and it lost existing DHCP leases so devices connected to the network could no longer connect. This may also happen when restarting idk. If it does perhaps persist leases to disk so they are persistent during restarts.

Im running this in a docker container if that makes a difference.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The DHCP lease data is stored on disk in the .scope files so they are expected to be persistent and restarting or upgrade should not have any effect on it.

Since you are using docker, was only the lease data lost or all config got reset?

**Comment by zpxp** [comment]
All config got reset. I didnt change the volume path or any docker compose config
