### ISSUE TITLE
Restore of settings fails

### ISSUE THREAD

**Issue by jho1670** [TechnitiumSoftware/DnsServer#677]
1. Do backup of settings on 9.x
2. Upgrade to 11.3
3. Restore of settings fails "Error! Multipart body length limit 134217728 exceeded."

a) Backup of server ( no logs ) was 373MB. This seems excessively large. I left default settings, and did not include logging.
b) Backup function should not generate backup archive that does not restore.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The DNS server does not impose any upload size limits. It could be that you have a reverse proxy configured to access the DNS server web panel which has default config for upload size.

**Comment by EHRETic** [comment]
Hi there,

I got the same issue today by trying to migrate one of my instances from a VM to a docker instance.
I also thought about reverse proxy in the first place so I disabled it (so no RP to download nor to upload backup file)

Yesterday I moved another instance successfully with the same method but backup file was a lot smaller.
(Here: https://github.com/TechnitiumSoftware/DnsServer/discussions/691)

Could there be any size limit somewhere in a component (not the DNS server itself)?
Thx in advance😉

**Comment by jho1670** [comment]
1. I don't have a reverse proxy in front of the DNS server web panel. I am accessing port :5380 directly.
2. As a workaround, I opened the ZIP file and deleted a pile of unnecessary logs, and the restore worked successfully.

**Comment by EHRETic** [comment]
> 2. As a workaround, I opened the ZIP file and deleted a pile of unnecessary logs, and the restore worked successfully.

I'll try that later on, I'll let you know. Thx 😉

**Comment by EHRETic** [comment]
Well, was a bit sketchy, but I created 2 backups files, one without stats and logs and one with. 😉👌

I extracted the files and copied them with WinSCP directly in Docker volume folder, that worked fine.

**Comment by ShreyasZare** [comment]
> Well, was a bit sketchy, but I created 2 backups files, one without stats and logs and one with. 😉👌
> 
> I extracted the files and copied them with WinSCP directly in Docker volume folder, that worked fine.

This is fine. The restore process essentially does the same thing. Only difference is that you will need to stop the DNS server when manually restoring the files while with the Restore option does it without restarting.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4 is now available that fixes this issue by setting the upload limit to 2GB. Do update and let me know your feedback.

**Comment by ShreyasZare** [comment]
Thanks for confirming.
