### ISSUE TITLE
Forwarder Protocol can check multiple protocols

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#678]
At present, Forwarder Protocol can only choose one protocol. If you choose dns-over-https, dns-over-quic cannot be selected

**Comment by ShreyasZare** [comment]
Thanks for the post. Please check #564.

**Comment by liang-hiwin** [comment]
> Thanks for the post. Please check #564.

thanks, If the . zone is configured, can Forwarder not fill in any forwarder ip?

**Comment by ShreyasZare** [comment]
> > Thanks for the post. Please check #564.
> 
> thanks, If the . zone is configured, can Forwarder not fill in any forwarder ip?

Yes, you can enter the forwarder's IP address too. The address syntax will be the same that you use with the forwarder config in the Settings > Proxy & Forwarders section.

**Comment by liang-hiwin** [comment]
ok 。understand
