### ISSUE TITLE
When dns is running as doh and dot server, add support for ocsp

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#679]
Add support for ocsp, doh can be implemented through nginx anti-proxy, but dot cannot. 

Eliminating the need for clients to contact the CA, with the aim of improving both security and performance.

**Comment by ShreyasZare** [comment]
Thanks for the post OCSP is a HTTP client feature and thus implementing support for it in the server is not possible.

**Comment by liang-hiwin** [comment]
> Thanks for the post OCSP is a HTTP client feature and thus implementing support for it in the server is not possible.

You misunderstood, the meaning is supports OCSP stapling for DNS over HTTPS and DNS over TLS

**Comment by liang-hiwin** [comment]
Here are some examples, you can look at https://dnsdist.org/advanced/ocsp-stapling.html

**Comment by ShreyasZare** [comment]
> > Thanks for the post OCSP is a HTTP client feature and thus implementing support for it in the server is not possible.
> 
> You misunderstood, the meaning is supports OCSP stapling for DNS over HTTPS and DNS over TLS

Ok, thanks for the feature request. There is already code changes coming up in next release for [this issue here](https://github.com/TechnitiumSoftware/DnsServer/issues/610#issuecomment-1616704883). So, will enable OCSP stapling along with it.

**Comment by liang-hiwin** [comment]
> > > Thanks for the post OCSP is a HTTP client feature and thus implementing support for it in the server is not possible.
> > 
> > 
> > You misunderstood, the meaning is supports OCSP stapling for DNS over HTTPS and DNS over TLS
> 
> Ok, thanks for the feature request. There is already code changes coming up in next release for [this issue here](https://github.com/TechnitiumSoftware/DnsServer/issues/610#issuecomment-1616704883). So, will enable OCSP stapling along with it.

hei hei , thank you for understanding what I mean.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4 is now available that enables OCSP stapling. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
> Technitium DNS Server v11.4 is now available that enables OCSP stapling. Do update and let me know your feedback.

Enabling the following options will automatically enable ocsp?
Enable DNS-over-TLS
Enable DNS-over-HTTPS

**Comment by ShreyasZare** [comment]
> Enabling the following options will automatically enable ocsp? 
> Enable DNS-over-TLS 
> Enable DNS-over-HTTPS

Yes, as per the Microsoft documentation, the server will send OCSP details.
