### ISSUE TITLE
Inconsistent API in that DnsServer does not require a config directory path to be passed but DhcpServer does

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#68]
Inconsistent API in that DnsServer does not require a config directory path to be passed but DhcpServer does. See the following...

```csharp

var dnsServer = new DnsServer();
dnsServer.LogManager = logManager;
dnsServer.Start();

var dhcpServer = new DhcpServer(configDirectory);
dhcpServer.LogManager = logManager;
dhcpServer.Start();
```

Could this be changed so that both require the config directory to be passed?

**Comment by ShreyasZare** [comment]
The reason DHCP server requires config folder path is that persistent storage is one of the first important thing a DHCP server needs to have to store lease data immediately after allocation. 

DNS Server is really working with Zone that manages data in memory. Zone is independently managed via the web api using the console. The DNS Server in itself is not updating any zone data and thus is effectively working in read-only mode. 

This may change later when DNS Server will be able to host secondary zones with zone transfer being the way the data is updated from the master server.
