### ISSUE TITLE
allow-update-forwarding

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#680]
Hi,

Maybe I'm missing it, but it appears TDNS doesn't have allow-update-forwarding like BIND does. This feature allows dynamic updates sent to a secondary DNS server to be forwarded to the primary DNS server for processing.

Is it possible to add this feature?

Regards,
micush

**Comment by ShreyasZare** [comment]
Thanks for the post. The secondary zones forward update requests to primary zones by default. Do try it again and let me know if there is any issue. Do check logs once to see if there were any errors when you tried it.

**Comment by micush** [comment]
This was my bad. It works as expected. Thanks for the info.  -m
