### ISSUE TITLE
FailureCache

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#683]
I saw such an error in the cache menu

```
[
  {
    "name": "interface3.music.163.com.163jiasu.com",
    "type": "CNAME",
    "ttl": "216 (3 mins 36 sec)",
    "rData": {
      "cname": "interface3.music.163.com.bsclink.cn"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "2408:xxx::/56",
    "lastUsedOn": "2023-07-20T11:42:32.9315757Z"
  },
  {
    "name": "interface3.music.163.com.163jiasu.com",
    "type": "AAAA",
    "ttl": "216 (3 mins 36 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Server exception for interface3.music.163.com.163jiasu.com. AAAA IN"
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-07-20T11:42:32.9318225Z"
  }
]
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Failure cache is a feature where the DNS server caches any error to avoid retrying frequently. In your case there is "Server exception" mentioned so please check the DNS Logs and see if there is any error logged for this domain name. Post any error you see in the logs here.

**Comment by liang-hiwin** [comment]
> interface3.music.163.com.163jiasu.com

Sorry, the log was closed before

**Comment by ShreyasZare** [comment]
> > interface3.music.163.com.163jiasu.com
> 
> Sorry, the log was closed before

Ok. Do post if you see the error again.

**Comment by liang-hiwin** [comment]
I have now opened the log, and cleared the cache, and I will send the corresponding log when it reappears

**Comment by liang-hiwin** [comment]
> > > interface3.music.163.com.163jiasu.com
> > 
> > 
> > Sorry, the log was closed before
> 
> Ok. Do post if you see the error again.

The problem reappeared, the log has been sent to your mailbox

**Comment by liang-hiwin** [comment]
I know how to reproduce this bug.

The first step is to enter this domain name in the Dns client menu: api.smoot.apple.cn, and click resolve.

The second step is to search for this domain name value in the cache menu: api.smoot.apple.cn, ok, you will see the phenomenon of cache failure, here is such an error report.

```


[
  {
    "name": "api.smoot.apple.cn",
    "type": "A",
    "ttl": "3576 (59 mins 36 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Server exception for api.smoot.apple.cn. A IN"
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-07-21T04:27:39.034445Z"
  }
]

```

**Comment by liang-hiwin** [comment]
Sometimes a domain name cannot be resolved using this Dns program.
For example, if you use this Dns program to forward all requests to 8.8.8.8, sometimes certain domain names cannot be resolved, but you use the dig command to test and find that 8.8.8.8 resolves this domain name normally. Therefore, there are loopholes in the dns program.

**Comment by ShreyasZare** [comment]
> The problem reappeared, the log has been sent to your mailbox

Thanks for the email. The log file does not contain any error logs so I cannot find out the reason for this error. Check your logs again and see if there are any errors being logged and share them.

**Comment by ShreyasZare** [comment]
> I know how to reproduce this bug.
> 
> The first step is to enter this domain name in the Dns client menu: api.smoot.apple.cn, and click resolve.
> 
> The second step is to search for this domain name value in the cache menu: api.smoot.apple.cn, ok, you will see the phenomenon of cache failure, here is such an error report.

I tried it and the domain resolves without any issues. So, the issue seems something related to network or forwarder.

**Comment by ShreyasZare** [comment]
> Sometimes a domain name cannot be resolved using this Dns program. For example, if you use this Dns program to forward all requests to 8.8.8.8, sometimes certain domain names cannot be resolved, but you use the dig command to test and find that 8.8.8.8 resolves this domain name normally. Therefore, there are loopholes in the dns program.

If you are not using encrypted DNS protocol then do use it and test it again. The domain resolves without any issues when using 8.8.8.8 forwarder too.

**Comment by liang-hiwin** [comment]
My network is normal, and I still have problems forwarding to encrypted doh.

> > Sometimes a domain name cannot be resolved using this Dns program. For example, if you use this Dns program to forward all requests to 8.8.8.8, sometimes certain domain names cannot be resolved, but you use the dig command to test and find that 8.8.8.8 resolves this domain name normally. Therefore, there are loopholes in the dns program.
> 
> If you are not using encrypted DNS protocol then do use it and test it again. The domain resolves without any issues when using 8.8.8.8 forwarder too.

**Comment by liang-hiwin** [comment]
I record a video, wait

**Comment by ShreyasZare** [comment]
> I record a video, wait

Thanks for being persistent and the video. There is a bug which occurs only in this specific condition when the domain being resolved is synthesized using DNAME. The issue is not with the DNAME record or the resolution but with the way the concurrent resolution is done when you have more than one FWD records in the forwarder zone. This fix will be available in the next update.

For now, since all the 4 forwarders you are using have the same DoH protocol, I would recommend that you use them from the Settings > Proxy & Forwarders section instead of creating the root zone with FWD records till the fix is available.

**Comment by liang-hiwin** [comment]
Thank you for the currently feasible solution, but by adding root to
forward dns, in addition to encrypted dns, the same problem will also occur
with conventional udp/tcp

Shreyas Zare ***@***.***> 于2023年7月23日周日 19:31写道：

**Comment by ShreyasZare** [comment]
> Thank you for the currently feasible solution, but by adding root to forward dns, in addition to encrypted dns, the same problem will also occur with conventional udp/tcp

Yes, this issue will come for any protocol you select for the FWD records in your root forwarder zone. So, do use the forwarders from the Settings section till the next update is available.

**Comment by liang-hiwin** [comment]
The same problem occurs when using Forwarders by testing

Shreyas Zare ***@***.***> 于2023年7月23日周日 19:39写道：

**Comment by ShreyasZare** [comment]
> The same problem occurs when using Forwarders by testing

Thanks again for the feedback. It seems to be an issue with the same domain name with single forwarder too due to DNAME. Will get it fixed too.

**Comment by liang-hiwin** [comment]
> > The same problem occurs when using Forwarders by testing
> 
> Thanks again for the feedback. It seems to be an issue with the same domain name with single forwarder too due to DNAME. Will get it fixed too.

Hello, I wonder if the problem can be fixed now?

**Comment by ShreyasZare** [comment]
> > > The same problem occurs when using Forwarders by testing
> > 
> > 
> > Thanks again for the feedback. It seems to be an issue with the same domain name with single forwarder too due to DNAME. Will get it fixed too.
> 
> Hello, I wonder if the problem can be fixed now?

Yes, the issue is fixed and the update should be available in few days once a pending feature is complete.

**Comment by liang-hiwin** [comment]
> > > > The same problem occurs when using Forwarders by testing
> > > 
> > > 
> > > Thanks again for the feedback. It seems to be an issue with the same domain name with single forwarder too due to DNAME. Will get it fixed too.
> > 
> > 
> > Hello, I wonder if the problem can be fixed now?
> 
> Yes, the issue is fixed and the update should be available in few days once a pending feature is complete.

Brother did a fantastic job.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
> Technitium DNS Server v11.4 is now available that fixes this issue. Do update and let me know your feedback.

Seeing normal now. a good job

**Comment by liang-hiwin** [comment]
> Technitium DNS Server v11.4 is now available that fixes this issue. Do update and let me know your feedback.

```

[
  {
    "name": "almalinux.mirror.shastacoe.net",
    "type": "CNAME",
    "ttl": "3595 (59 mins 55 sec)",
    "rData": {
      "cname": "mirror02.shastacoe.net"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-12T16:14:37.9154269Z"
  },
  {
    "name": "almalinux.mirror.shastacoe.net",
    "type": "AAAA",
    "ttl": "3595 (59 mins 55 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Resolver exception for almalinux.mirror.shastacoe.net. AAAA IN: The SSL connection could not be established, see inner exception."
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-08-12T16:14:37.7677178Z"
  }
]
```

**Comment by liang-hiwin** [comment]
@ShreyasZare

**Comment by ShreyasZare** [comment]
> ```
> 
> [
>   {
>     "name": "almalinux.mirror.shastacoe.net",
>     "type": "CNAME",
>     "ttl": "3595 (59 mins 55 sec)",
>     "rData": {
>       "cname": "mirror02.shastacoe.net"
>     },
>     "dnssecStatus": "Disabled",
>     "eDnsClientSubnet": "0.0.0.0/0",
>     "lastUsedOn": "2023-08-12T16:14:37.9154269Z"
>   },
>   {
>     "name": "almalinux.mirror.shastacoe.net",
>     "type": "AAAA",
>     "ttl": "3595 (59 mins 55 sec)",
>     "rData": {
>       "dataType": "DnsSpecialCacheRecordData",
>       "data": "FailureCache: ServerFailure; Other: Resolver exception for almalinux.mirror.shastacoe.net. AAAA IN: The SSL connection could not be established, see inner exception."
>     },
>     "dnssecStatus": "Unknown",
>     "lastUsedOn": "2023-08-12T16:14:37.7677178Z"
>   }
> ]
> ```

From the error description in there, it seems like there was an network issue related to SSL connection when resolving the domain name using encrypted DNS forwarders. Try again and see if that error goes away.

**Comment by liang-hiwin** [comment]
> > ```
> > 
> > [
> >   {
> >     "name": "almalinux.mirror.shastacoe.net",
> >     "type": "CNAME",
> >     "ttl": "3595 (59 mins 55 sec)",
> >     "rData": {
> >       "cname": "mirror02.shastacoe.net"
> >     },
> >     "dnssecStatus": "Disabled",
> >     "eDnsClientSubnet": "0.0.0.0/0",
> >     "lastUsedOn": "2023-08-12T16:14:37.9154269Z"
> >   },
> >   {
> >     "name": "almalinux.mirror.shastacoe.net",
> >     "type": "AAAA",
> >     "ttl": "3595 (59 mins 55 sec)",
> >     "rData": {
> >       "dataType": "DnsSpecialCacheRecordData",
> >       "data": "FailureCache: ServerFailure; Other: Resolver exception for almalinux.mirror.shastacoe.net. AAAA IN: The SSL connection could not be established, see inner exception."
> >     },
> >     "dnssecStatus": "Unknown",
> >     "lastUsedOn": "2023-08-12T16:14:37.7677178Z"
> >   }
> > ]
> > ```
> 
> From the error description in there, it seems like there was an network issue related to SSL connection when resolving the domain name using encrypted DNS forwarders. Try again and see if that error goes away.

I have updated the current observation is normal, if there is another problem, I will let you know.

**Comment by liang-hiwin** [comment]
hello ,Currently I see there are 2 issues. Currently using Version 11.4.1

```
[
  {
    "name": "bedro.cloud",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Resolver exception for bedro.cloud. A IN: Invalid response was received: EDNS Client Subnet mismatch."
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-08-13T22:43:16.0661899Z"
  },
  {
    "name": "bedro.cloud",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "173.249.201.201"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-14T12:52:38.251552Z"
  },
  {
    "name": "bedro.cloud",
    "type": "AAAA",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "NegativeCache: NoError; bedro.cloud. SOA IN 0 1-you.njalla.no. you.can-get-no.info. 2308061221 21600 7200 1814400 86400"
    },
    "dnssecStatus": "Unknown",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-14T18:56:39.1894423Z"
  },
  {
    "name": "bedro.cloud",
    "type": "AAAA",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Resolver exception for bedro.cloud. AAAA IN: Invalid response was received: EDNS Client Subnet mismatch."
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-08-14T18:56:39.1603972Z"
  }
]
```

```
[
  {
    "name": "dango.ai",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "54.67.93.101"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-14T00:15:37.3377284Z"
  },
  {
    "name": "dango.ai",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "52.8.134.32"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-14T00:15:37.3377284Z"
  },
  {
    "name": "dango.ai",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "54.67.42.145"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-14T00:15:37.3377284Z"
  },
  {
    "name": "dango.ai",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Resolver exception for dango.ai. A IN: Invalid response was received: EDNS Client Subnet mismatch., Other: Resolver exception for dango.ai. A IN: The SSL connection could not be established, see inner exception."
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-08-14T00:15:37.2876313Z"
  },
  {
    "name": "dango.ai",
    "type": "AAAA",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "NegativeCache: NoError; dango.ai. SOA IN 0 ns1.dyna-ns.net. hostmaster.dango.ai. 1691254244 16384 2048 1048576 2560"
    },
    "dnssecStatus": "Unknown",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-08-14T00:15:37.276371Z"
  },
  {
    "name": "dango.ai",
    "type": "AAAA",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Resolver exception for dango.ai. AAAA IN: The SSL connection could not be established, see inner exception."
    },
    "dnssecStatus": "Unknown",
    "lastUsedOn": "2023-08-14T00:15:37.2623991Z"
  }
]
```

**Comment by ShreyasZare** [comment]
> hello ,Currently I see there are 2 issues. Now I am using Version 11.4.1, these errors reappeared after I updated the latest version and cleared all caches

`Resolver exception for bedro.cloud. A IN: Invalid response was received: EDNS Client Subnet mismatch.`

This error is due to the upstream DNS server responding with a different ECS client subnet than was requested. This will cause this mismatch error to get cached. These errors are caused by the upstream server and should get resolved automatically after a while.

**Comment by liang-hiwin** [comment]
> > hello ,Currently I see there are 2 issues. Now I am using Version 11.4.1, these errors reappeared after I updated the latest version and cleared all caches
> 
> `Resolver exception for bedro.cloud. A IN: Invalid response was received: EDNS Client Subnet mismatch.`
> 
> This error is due to the upstream DNS server responding with a different ECS client subnet than was requested. This will cause this mismatch error to get cached. These errors are caused by the upstream server and should get resolved automatically after a while.

haode
