### ISSUE TITLE
unable to open dns query on https

### ISSUE THREAD

**Issue by anantsparrow** [TechnitiumSoftware/DnsServer#684]
Hey there, i installed this software but unable to open in https

**Comment by ShreyasZare** [comment]
Thanks for the post. Please describe the issue in details.

**Comment by Hemsby** [comment]
Please, would need more information.  OS, https web admin or Doh requests.  Did you successfully add the certificate and enable the Https?

**Comment by anantsparrow** [comment]
i am using ubuntu 20.04 , and opening my url dns.sparrowdns.com/dns-query is not working on https://dns.sparrowdns.com/dns-query

**Comment by Hemsby** [comment]
Did you enable the protocol
![Screenshot_20230722_111042_com microsoft emmx](https://github.com/TechnitiumSoftware/DnsServer/assets/36005402/2ae8ef03-bb7a-4609-84ca-e4a858a9c3d8)

**Comment by anantsparrow** [comment]
can it be done via lets encrypt ssl?

**Comment by Hemsby** [comment]
Yes....

https://blog.technitium.com/2023/03/how-to-auto-renew-ssl-certificates-with.html?m=1

**Comment by anantsparrow** [comment]
hi i tried this failed to do, should i share my root login with you over email so you can do a quick setup for this?

**Comment by anantsparrow** [comment]
thanks managed to fix.
