### ISSUE TITLE
Request to support Openssl3.0

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#687]
After investigation, libssl1.1 has been removed from the warehouse since ubuntu18.04 (debian 12), so when using Ubuntu22.04 or debian 12 new system, sudo apt update cannot install and update libss1.1 anyway, So if some software still depends on this library, it will not work properly.

**Comment by liang-hiwin** [comment]
> Thanks for the post. If you have updated the `libmsquic` to latest version then it will support both openssl 1.x and openssl 3.x versions.

The deb downloaded through this website, the error prompts libss1.1---------https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/

**Comment by ShreyasZare** [comment]
> > Thanks for the post. If you have updated the `libmsquic` to latest version then it will support both openssl 1.x and openssl 3.x versions.
> 
> The deb downloaded through this website, the error prompts libss1.1---------https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/

Are you using the latest `libmsquic` version `2.2.2`? I have tested it and it works with both openssl 1.x and openssl 3.x versions.

**Comment by liang-hiwin** [comment]
> > > Thanks for the post. If you have updated the `libmsquic` to latest version then it will support both openssl 1.x and openssl 3.x versions.
> > 
> > 
> > The deb downloaded through this website, the error prompts libss1.1---------https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/
> 
> Are you using the latest `libmsquic` version `2.2.2`? I have tested it and it works with both openssl 1.x and openssl 3.x versions.

yes by libmsquic_2.2.2_amd64.deb

**Comment by ShreyasZare** [comment]
> > > > Thanks for the post. If you have updated the `libmsquic` to latest version then it will support both openssl 1.x and openssl 3.x versions.
> > > 
> > > 
> > > The deb downloaded through this website, the error prompts libss1.1---------https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/
> > 
> > 
> > Are you using the latest `libmsquic` version `2.2.2`? I have tested it and it works with both openssl 1.x and openssl 3.x versions.
>
> yes by libmsquic_2.2.2_amd64.deb

That is strange. I have the same version working on both Ubuntu 18.04 and Ubuntu 22.04 without any issues. Try installing it as mentioned in [this blog post](https://blog.technitium.com/2023/02/configuring-dns-over-quic-and-https3.html) instead of directly installing the deb.

**Comment by liang-hiwin** [comment]
> > > > > Thanks for the post. If you have updated the `libmsquic` to latest version then it will support both openssl 1.x and openssl 3.x versions.
> > > > 
> > > > 
> > > > The deb downloaded through this website, the error prompts libss1.1---------https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/
> > > 
> > > 
> > > Are you using the latest `libmsquic` version `2.2.2`? I have tested it and it works with both openssl 1.x and openssl 3.x versions.
> > 
> > 
> > yes by libmsquic_2.2.2_amd64.deb
> 
> That is strange. I have the same version working on both Ubuntu 18.04 and Ubuntu 22.04 without any issues. Try installing it as mentioned in [this blog post](https://blog.technitium.com/2023/02/configuring-dns-over-quic-and-https3.html) instead of directly installing the deb.

The following resources do not support debian12

curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt-add-repository https://packages.microsoft.com/debian/11/prod
sudo apt-get update

**Comment by liang-hiwin** [comment]
Err:5 https://packages.microsoft.com/debian/11/prod bookworm Release
  404  Not Found [IP: 13.75.64.135 443]

**Comment by ShreyasZare** [comment]
> The following resources do not support debian12
> 
> curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add - sudo apt-add-repository https://packages.microsoft.com/debian/11/prod sudo apt-get update

The example given in the blog post was for Debian 11. So, you need to change the URL for Debian 12 as shown below.

```
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt-add-repository https://packages.microsoft.com/debian/12/prod
sudo apt-get update
```
Try and see if that works.

**Comment by liang-hiwin** [comment]
Can't. debian12 removed libss1.1

**Comment by liang-hiwin** [comment]
Debian 12 Microsoft's download library (https://packages.microsoft.com/debian/12/prod) does not have libmsquic

**Comment by ShreyasZare** [comment]
> Debian 12 Microsoft's download library (https://packages.microsoft.com/debian/12/prod) does not have libmsquic

Ohh ok. It seems Microsoft has not made it available for Debian 12 yet. So, you need to wait for a while or use the DNS server on something like Ubuntu or docker untill then. In any case, since `libmsquic` is developed by Microsoft, there is nothing much that can be done here.

**Comment by liang-hiwin** [comment]
> > Debian 12 Microsoft's download library (https://packages.microsoft.com/debian/12/prod) does not have libmsquic
> 
> Ohh ok. It seems Microsoft has not made it available for Debian 12 yet. So, you need to wait for a while or use the DNS server on something like Ubuntu or docker untill then. In any case, since `libmsquic` is developed by Microsoft, there is nothing much that can be done here.

yes
