### ISSUE TITLE
Devices with no hostname cause DHCP server not to bind on server restart

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#69]
An exception is thrown when enabling the default scope after a reboot of the physical server when devices with no hostname have already been offered a lease that is now saved to the config.

I've tracked it down to the following:

```csharp
DnsClient.IsDomainNameValid(name, true);
```
![image](https://user-images.githubusercontent.com/7858744/61665579-4193f700-accd-11e9-836e-0c86a14c0aca.png)

![image](https://user-images.githubusercontent.com/7858744/61665637-64261000-accd-11e9-96b5-d4d56b12a778.png)

The lease hostname is null when saved...

![image](https://user-images.githubusercontent.com/7858744/61665834-f5958200-accd-11e9-948c-e61d07079c1f.png)

As you can see in the following, I have two devices on my network which don't have a hostname, not sure if this is normal or not:

![image](https://user-images.githubusercontent.com/7858744/61666179-be73a080-acce-11e9-9287-75c599ed8050.png)

**Comment by Matthew-Bonner** [comment]
The following suggests that the domain if empty is the root zone, but in this cause the same method is being used to test hostnames for devices.

```csharp
if (domain.Length == 0)
  return true; //domain is root zone
```

So I'm not really sure how you want to fix this as I'm not sure the following is really valid either.

```
if (domain == null)
  return **???**;
```

Setting `HostName` to an empty string would be a hack as it is null as there is no hostname.

So I propose the following fixes:

Change:

```csharp
_authoritativeZoneRoot.SetRecords(lease.HostName, DnsResourceRecordType.A, scope.DnsTtl, new DnsResourceRecordData[] { new DnsARecord(lease.Address) });
```

to:

```csharp
if (lease.HostName != null)
  _authoritativeZoneRoot.SetRecords(lease.HostName, DnsResourceRecordType.A, scope.DnsTtl, new DnsResourceRecordData[] { new DnsARecord(lease.Address) });
```

And change:

```csharp
_authoritativeZoneRoot.SetRecords(Scope.GetReverseZone(lease.Address, 32), DnsResourceRecordType.PTR, scope.DnsTtl, new DnsResourceRecordData[] { new DnsPTRRecord(lease.HostName) });
```

to:

```csharp
if (lease.HostName != null)
  _authoritativeZoneRoot.SetRecords(Scope.GetReverseZone(lease.Address, 32), DnsResourceRecordType.PTR, scope.DnsTtl, new DnsResourceRecordData[] { new DnsPTRRecord(lease.HostName) });
```

You might want to check this first to make sure it doesn't break anything as my knowledge of network technology is rubbish.

**Comment by ShreyasZare** [comment]
Thanks for the debugging. This can be fixed in UpdateDnsAuthZone() with below check:

```
if (string.IsNullOrEmpty(lease.HostName))
                return;
```

**Comment by Matthew-Bonner** [comment]
Just tested, the fix you proposed works for me, much simpler than my solution.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v4.1 is now available that fixes this issue.
