### ISSUE TITLE
DHCP Static Routes.

### ISSUE THREAD

**Issue by arturpragacz** [TechnitiumSoftware/DnsServer#690]
There is a bug in the behavior of the DHCP Static Routes (option 121).
When setting the route for 0.0.0.0/0 (default route) it works at first, but after the restart of the Technitium server the route is not restored properly, instead being restored as 0.0.0.0/32. This obviously breaks the networking everywhere.

**Comment by ShreyasZare** [comment]
Thanks for reporting this bug. Will get it fixed in the next update that will mostly be available by next weekend.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4 is now available that fixes this issue. Do update and let me know your feedback.
