### ISSUE TITLE
Create DNS entries with PHP (API, etc.)

### ISSUE THREAD

**Issue by GChester** [TechnitiumSoftware/DnsServer#7]
We have many domains that we need to test in our local environment and would ike to add these automatically with PHP from our database?

I see you seem to use JSON in a few places. Is there a way to pass JSON to set up the DNS entry?

Or possibly another method?

**Comment by ShreyasZare** [comment]
The DNS Server has API in place already that you can use. The DNS Server web panel itself is just a static HTML + JS single page that calls the API for doing all tasks.

However, there is no documentation available for the API at the moment but, you can just open browser developer tools and observe the API calls and follow the same method in your PHP code. The API is really simple in its design and with a couple of calls you see in the dev tools, you will get enough info to understand it.

The response format is standard JSON for all the API calls, you only need to find the query string parameters and the url being used. And in case you need to check, just see the [DnsWebService ](https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/DnsWebService.cs)implementation.

**Comment by GChester** [comment]
Ok, great... I'll have my devs take a look..  I was going to suggest an API but sounds like you are on top of things already.

**Comment by GChester** [comment]
@ShreyasZare we are moving forward on a PHP script to create a new zone for each domain in our database.

We have found the URLs used for the API but we do not know how to get the token that is passed to each request.  I am assuming this token is used for authentication.

Can you offer any help?

**Comment by ShreyasZare** [comment]
The token needed is used for authentication as you guessed. To get that token, just call the login api with username & password and you will get json response with the token to be used with other api calls.

Login API call: http://localhost:5380/api/login?user=admin&pass=password
Response example: {"token":"tokenstring","status":"ok"}
