### ISSUE TITLE
If an exception is thrown at a certain point, the DHCP server is partially bound

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#70]
If an exception is thrown at a certain point, the DHCP server is partially bound.

Consider the following:

```csharp
if (!interfaceAddress.Equals(IPAddress.Any))
  BindUdpListener(dhcpEP); // Bound

lock (_activeScopeLock)
{
  if (_activeScopeCount < 1)
    BindUdpListener(_dhcpDefaultEP); // Exception thrown here, not bound

  _activeScopeCount++;
}
```

This leaves the server in an unexpected state.

I would have expected that if an error occurs during any part of this code, all DHCP listeners are unbound.

**Comment by Matthew-Bonner** [comment]
I should state that the reason this is a problem is that if you try to enable the scope again, an exception is thrown because the address is already bound to due to the previous exception, and this can lead to a lot of confusion when reviewing the logs.

**Comment by ShreyasZare** [comment]
Thanks, will update it to unbind listener in such case.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v4.1 is now available that fixes this issue.
