### ISSUE TITLE
Backups no longer works

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#700]
Hi i have 3 instances running 2x that does the blocking and my dhcp servers which connects to my 3rd instance which is my root server that connects through a vpn for some extra privacy. All three wont backup after the last update. 

The first two are dockers running on Unraid and Homeassistant, the root server is installed on a raspberry pi 4 that only runs technitium. 

Below is the error:

{"status":"error","errorMessage":"Value cannot be null. (Parameter \u0027path2\u0027)","stackTrace":"   at System.ArgumentNullException.Throw(String paramName)\n   at System.IO.Path.Combine(String path1, String path2)\n   at DnsServerCore.DnsWebService.ConvertToAbsolutePath(String path) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\DnsWebService.cs:line 196\n   at DnsServerCore.WebServiceSettingsApi.BackupSettingsAsync(HttpContext context) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\WebServiceSettingsApi.cs:line 1496\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at DnsServerCore.DnsWebService.WebServiceApiMiddleware(HttpContext context, RequestDelegate next) in Z:\\Technitium\\Projects\\DnsServer\\DnsServerCore\\DnsWebService.cs:line 581\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.\u003CInvoke\u003Eg__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)"}

**Comment by ShreyasZare** [comment]
Thanks for reporting this issue. Will get that fixed soon.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.4.1 has been released that fixes this issue. Do update and let me know your feedback.

**Comment by ChristoffBo** [comment]
Works perfectly. Thank you sir.

**Comment by ShreyasZare** [comment]
> Works perfectly. Thank you sir.

Thanks for the feedback.
