### ISSUE TITLE
is can create a dns server name?

### ISSUE THREAD

**Issue by mixserrm999** [TechnitiumSoftware/DnsServer#703]
I want change my ip server to dns named.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please describe your question with more details.

**Comment by mixserrm999** [comment]
I can change my ip server to domain dns?

**Comment by ShreyasZare** [comment]
What do you mean when you say "ip server" and "domain dns"?

**Comment by mixserrm999** [comment]
Can Technitium change from ip server on my vps to dns domain, it's like accessing website via ip instead of dns access?

**Comment by ShreyasZare** [comment]
If you mean to have a local domain name that resolves to your LAN IP address then yes you can do that with it. You will need to create a zone for example "home" and in the zone you can add your record for "server1.home" with your LAN IP address.

**Comment by mixserrm999** [comment]
i do it in vps
