### ISSUE TITLE
Devices with a space in the host name cause DHCP server not to bind on server restart

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#71]
I have two lifx bulbs, they both share the same hostname:

> lifx bulb

This causes an exception to be thrown when starting the DHCP server after a reboot of the physical server.

To help you in the right direction I need to spend some more time debugging, but in order to ensure I don't forget to log this as a bug I'm logging it anyway.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. If multiple devices have same hostname then its expected behavior that the last one to get lease will overwrite the DNS entries with its address. If there is any exception then do share the stack trace.

**Comment by Matthew-Bonner** [comment]
Seems this is an issue others have had to deal with too:
https://community.ui.com/questions/Hostname-Display-Inconsistency-With-UniFi/f2dad1ad-0ca0-442b-a020-ea810b6d402e

You would think that Lifx would know better.

**Comment by ShreyasZare** [comment]
> You would think that Lifx would know better.

Well, what to expect from IoT devices. I will just add a line to replace space with hyphen.

**Comment by Matthew-Bonner** [comment]
> I will just add a line to replace space with hyphen.

I patched it by doing the same, was a quick and easy fix.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v4.1 is now available that fixes this issue.
