### ISSUE TITLE
Feature request: Two more columns in Zone list -- SOA serial and last modification time

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#718]
I just had a discussion with a manager of a rather large DNS collection. His first question about the zone list was: "I'm missing the current serial and the last modification time".

He's right; in the case of zones with dynamic updates or secondaries these are the really interesting facts in most cases.

Request: Is is possible to log the time in the internal structures and also display the SOA serial number in the list?

It might be a good idea for a Dashboard widget, too: "Last zone updates" listing Domain, time and SOA

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will get those added in future updates.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that adds the columns for zone list. Do update and let me know your feedback.

**Comment by noseshimself** [comment]
Working as expected. Thank you!

**Comment by ShreyasZare** [comment]
Thanks for the feedback.
