### ISSUE TITLE
Feature request: Sort TSIG keys by Key Name

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#727]
The list of TSIG keys is sorted by order of entering them. That's not convenient if the list is getting longer. This is also valid for pull-down-lists with keys (and is even worse there).

Bonus problem: It might be necessary to differentiate by Keys to update zones ("in") and keys used to access external name servers ("out").

**Comment by ShreyasZare** [comment]
Thanks for the request. Will get that done in next update. The keys are not marked for "in" or "out" and can be used for any purpose so wont be feasible to sort them accordingly.

**Comment by noseshimself** [comment]
> The keys are not marked for "in" or "out" and can be used for any purpose so wont be feasible to sort them accordingly.

If I want to add  keys for your own outgoing connections (which I currently miss -- I would like to authorize to other servers  using keys) you don't want to have anything but applicable keys in the pull-down menus...

**Comment by ShreyasZare** [comment]
> > The keys are not marked for "in" or "out" and can be used for any purpose so wont be feasible to sort them accordingly.
> 
> If you want to add keys for your own outgoing connections to secondary servers you don't want to have anything but applicable keys in the pull-down menus...

I understand that but currently the TSIG keys do not have usage option to configure. This is similar to how TSIG keys are defined in BIND.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that sorts TSIG keys by name. Do update and let me know your feedback.

**Comment by noseshimself** [comment]
Working as intended and very helpful with a list of 400 keys.

**Comment by ShreyasZare** [comment]
Thanks for the feedback.
