### ISSUE TITLE
Feature request: Global default setting for "Use Serial Date Scheme" of domains.

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#728]
I just imported about 100 domains when I noticed that all of them started with version 1 again instead of using the number in the SOA of the source. The secondaries were not amused.

**Comment by ShreyasZare** [comment]
> I just imported about 100 domains when I noticed that all of them started with version 1 again instead of using the number in the SOA of the source. The secondaries were not amused.

Thanks for the feedback. I just tested the Import option with AXFR and the SOA serial remains exactly the same and did not reset to 1.

How was the import done in your setup?

Will get the global "Use Serial Date Scheme" option added.

**Comment by noseshimself** [comment]
> Thanks for the feedback. I just tested the Import option with AXFR and the SOA serial remains exactly the same and did not reset to 1.
> 
> How was the import done in your setup?

By being stupid and using ANY. That was probably not the brightest moment in my career...

**Comment by ShreyasZare** [comment]
> > Thanks for the feedback. I just tested the Import option with AXFR and the SOA serial remains exactly the same and did not reset to 1.
> > How was the import done in your setup?
> 
> By being stupid and using ANY. That was probably not the brightest moment in my career...
> 
> Still... After importing it I was hoping for the "natural" date-as-serial scheme to continue when I finely discovered AXFR.

If you import again using AXFR then all records are again synced and the serial will match exact. I just tested it and its working as expected.

**Comment by noseshimself** [comment]
Worked. Thanks!

Maybe AXFR should get a separate button or move to the top of the strangely ordered list...
