### ISSUE TITLE
Feature request: Status badges in the zone list should be links/buttons

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#729]
The status badges should be turned into buttons if they are flagging errors (e. g. "Notify Failed" -- hover over and see which secondary did not accept the update, click on it and get a pop-up or a window with details/or  relevant information from the log).

**Comment by ShreyasZare** [comment]
Thanks for the request. This info is already available when you edit the zone. The "Notify Failed" label is shown against the NS records to indicate which secondary failed to accept the notification.

Also, turning the badges into buttons wont look obvious so it wont be noticeable unless you know that it can be clicked.

**Comment by noseshimself** [comment]
> This info is already available when you edit the zone

--- and scroll until you found them all (luckily NS entries are at the top).

I guess I'll have to add another feature request. Entering the zone is cumbersome as you can't get to the position you came from by using the browser's back button so whatever you do means scrolling back to the top, using the back button there and get to the top of the zone listing so I try to avoid that as much as possible...
