### ISSUE TITLE
Feature Request - Option to set Block List Update Frequency

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#73]
Please consider an option to customize the update frequency for block list update checks.
Currently it's set to every 24 hours.

Please allow us to set it to every: 6, 8, 10, 12, 14, 16, 18, 20, 22 or 24 hours.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I will add this option to set any arbitrary value in hours.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds option to set block list update frequency in hours.
