### ISSUE TITLE
Feature request: Several UI improvements in zone list

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#732]
Please support the browser's back button after editing zone data.

Entering the zone is cumbersome as you can't return to the position you came from by using the browser's back button.
This is forcing you to scroll back to the top, using the back button there and get to the top of the zone listing. A floating back button that is always reachable or even a fixed menu header above the scrolling area might also be a good solution (sorry, I never was a good UI designer).

**Comment by ShreyasZare** [comment]
Thanks for the post. This feature is already requested in #572. This will use bookmarks in links to allow using browser navigation buttons.
