### ISSUE TITLE
Feature request (low priority): Expand the DNSSEC pull-down menu by more features

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#738]
(I have read https://blog.technitium.com/2022/07/how-to-secure-your-domain-name-with-.html)

Would it be possible to get cut&paste information about the public parts of KSK and ZSK without having to find the ZSK in the list? The "Properties" pop-up might be a good place. (For some reasons unknown to me Gandi would like to know the KSK, too... That was a bit harder exercise.)

Your hinting at DNSviz is quite a good idea; you might add a button there to open https://dnsviz.net/d/<domain.name>/dnssec/ in that tab. Or add a button on top of the page; it is solving quite a lot of problems if you need to know about your domain propagation.

**Comment by ShreyasZare** [comment]
Thanks for the request. Ya, having a UI which will clearly show the details to add DS record for the zone will be much useful. The DNSSEC Properties popup has limited space to put in all the details. So, having another popup can be added that will show all relevant details to make it easier.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that adds DS Info menu to list all details. Do update and let me know your feedback.

**Comment by noseshimself** [comment]
Providing the information I need. And Gandi repaired their UI, too, so I don't need both but who knows who else wants to get the public key...
