### ISSUE TITLE
Feature Request: More customizable forwarder.

### ISSUE THREAD

**Issue by rikyotei** [TechnitiumSoftware/DnsServer#74]
Hi,

I am going to use this software as a forwarder to instead Microsoft DNS server which is does not support DNS over https.

But this software does not inlcludes conditional forwarder, can you consider to add it?

My images is, I can add domains into group first and then set the forwarder for the group,
For example:

a.com
b.com
c.com
in Group A, and forward by Forwarder A, by CloudFlare DNS HTTPS.

d.com
e.com
in Group B, and forward by Forwarder B, by Local ISP's DNS over UDP.

Why I ask for this feature is because I live in China, DNS pollution is very serious here.

If you can add this feature, it is really helps. Because It helps people fix DNS pollution and can setup local DNS at same time by one software. Thank you.

**Comment by ShreyasZare** [comment]
Thanks for the interesting feedback. This is a very different scenario and it does makes sense to have these advance options.

At the moment, you can create stub zones which work similar to conditional forwarders but they use only DNS-over-UDP. You can read how to use them [here](https://technitium.com/dns/help.html#conditional-forwarding).

I will try to add more specific conditional forwarding feature with support for all the protocols available in future update.

**Comment by rikyotei** [comment]
Thank you for your advise, cannot wait to see the fulture update. Thanks

**Comment by ShreyasZare** [comment]
The new version now supports conditional forwarder zones which can utilize any DNS provider with all the protocol options including DNS-over-TLS and DNS-over-HTTPS.
