### ISSUE TITLE
DHCP server constantly gives out wrong IP addresses despite reservations

### ISSUE THREAD

**Issue by Zorlin** [TechnitiumSoftware/DnsServer#740]
this is driving me absolutely batty.

* I create a new host, as a DHCP static reservation based on its MAC address
* I boot that host
* It gets the right IP address
* I come back minute later
* There are TWO DHCP leases, one for the right IP and one for the wrong IP
* Resolving this situation involves staring at the moon and the stars and doing a dance and removing all the records and setting everything back up again 3 times until it finally consistently works
* Rinse and repeat

Please fix this! It's a critical bug that stops me from using Technitium effectively...

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/1369772/36a22c74-d746-4a04-86a2-88186794c3eb)

**Comment by Zorlin** [comment]
Details: Technitium Version 11.4.1, Ubuntu 22.04. Everything else works perfectly :(

**Comment by Zorlin** [comment]
Maybe part of it is that when I go to create the record, I'm using Proxmox style MAC addresses (0F:FF:CC) that get converted to a format like 4E-90-67-0B-19-CD - perhaps as part of that conversion it doesn't properly set the record somewhere?

**Comment by ShreyasZare** [comment]
Thanks for the post. This is a know issue which you can read about [here](https://github.com/TechnitiumSoftware/DnsServer/issues/606) to know how to fix it. 

Let me know if that worked.

**Comment by Zorlin** [comment]
> Thanks for the post. This is a know issue which you can read about [here](https://github.com/TechnitiumSoftware/DnsServer/issues/606) to know how to fix it.
> 
> Let me know if that worked.

Huh! Okay, so it's just terrible dhcp clients being terrible. :) I'll test out the fix, thank you!

**Comment by ShreyasZare** [comment]
> > Thanks for the post. This is a know issue which you can read about [here](https://github.com/TechnitiumSoftware/DnsServer/issues/606) to know how to fix it.
> > Let me know if that worked.
> 
> Huh! Okay, so it's just terrible dhcp clients being terrible. :) I'll test out the fix, thank you!

Ya, its kind of common issue with clients like Ubuntu as you can see [here](https://superuser.com/questions/1338510/wrong-ip-address-from-dhcp-client-on-ubuntu-18-04). The issue comes since the client resets its client-identifier for some reasons causing the DHCP server to think that its a different client so cannot give it the existing non-expired lease.

**Comment by Zorlin** [comment]
Ah, these are freshly deployed machines, and the deployment process sees
them as different clientIDs (or rather the deployment process uses MAC for
DHCP)

So that makes sense
