### ISSUE TITLE
Return code for synthesized CNAME records (from wildcards and DNAMEs)

### ISSUE THREAD

**Issue by SivaKesava1** [TechnitiumSoftware/DnsServer#747]
Hi,

This is related to if 'A CNAME B' (even for a synthesized CNAME) exists in a zone, but B (related to the same zone) does not exist, then the return code should be NXDOMAIN.  [RFC 6604](https://tools.ietf.org/html/rfc6604#section-3) mentions that 
> When chains are followed the RCODE in the ultimate DNS response MUST BE set based on the final query cycle leading to that
>       response.

Consider the following zone file.

|  	|  	|  	|  	|
|-	|-	|-	|-	|
| www. 	| 500 | SOA 	| ns1.outside.edu. root.campus.edu. 3 604800 86400 2419200 604800 	|
| www. 	| 500 | NS 	| ns1.outside.com.  	|
| foo.www.	| 500 | DNAME | example.fnni.*.www.	|

For the query _<example.bank.foo.www., NS>_, the Technitium server returns the following response:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA RA",
          ";QUESTION",
          "example.bank.foo.www. IN NS",
          ";ANSWER",
          "foo.www. 500 IN DNAME example.fnni.*.www.",
          "example.bank.foo.www. 500 IN CNAME example.bank.example.fnni.*.www.",
          ";AUTHORITY",
          "www. 500 IN SOA ns1.outside.edu. root.campus.edu. 3 604800 86400 2419200 604800",
          ";ADDITIONAL"
```

**What you expected to happen**: The expected response is the same as above except that the `rcode` should be `NXDOMAIN`. This is using the [test case 23](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ExpectedResponses/23.json#L13) from the [FerretDataset](https://github.com/dns-groot/FerretDataset).

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get this fixed soon.

**Comment by SivaKesava1** [comment]
I forgot to add another record that was present in the original [test case 23](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ZoneFiles/23.txt) when I copied it over into the bug report. I think that affects as it involves wildcards. I am not using the UI client. I am running the DnsServer in a container on a remote machine. 
Here are the details. Please let me know if you need any additional info. 

```
{
  "displayName": "Administrator",
  "username": "admin",
  "token": "36333e221d591435e484672322d0a1b4cd8a6019f8d92408d07b62fbe25b2b95",
  "info": {
    "version": "11.4.1",
    "uptimestamp": "2023-09-28T17:44:17.9557199Z",
    "dnsServerDomain": "e8de0a8edfb2",
    "defaultRecordTtl": 3600,
    "permissions": {
     ....
    }
  },
  "status": "ok"
}
```

```
{
  "response": {
    "zone": {
      "name": "www",
      "type": "Primary",
      "internal": false,
      "dnssecStatus": "Unsigned",
      "notifyFailed": false,
      "notifyFailedFor": [],
      "disabled": false
    },
    "records": [
      {
        "name": "www",
        "type": "NS",
        "ttl": 500,
        "disabled": false,
        "rData": {
          "nameServer": "ns1.outside.edu"
        },
        "dnssecStatus": "Unknown",
        "lastUsedOn": "0001-01-01T00:00:00"
      },
      {
        "name": "www",
        "type": "SOA",
        "ttl": 500,
        "disabled": false,
        "rData": {
          "primaryNameServer": "ns1.outside.edu",
          "responsiblePerson": "root@campus.edu",
          "serial": 10,
          "refresh": 604800,
          "retry": 86400,
          "expire": 2419200,
          "minimum": 604800,
          "useSerialDateScheme": false
        },
        "dnssecStatus": "Unknown",
        "lastUsedOn": "2023-09-28T17:50:38.3494543Z"
      },
      {
        "name": "*.www",
        "type": "A",
        "ttl": 500,
        "disabled": false,
        "rData": {
          "ipAddress": "1.1.1.1"
        },
        "dnssecStatus": "Unknown",
        "lastUsedOn": "0001-01-01T00:00:00"
      },
      {
        "name": "foo.www",
        "type": "DNAME",
        "ttl": 500,
        "disabled": false,
        "rData": {
          "dname": "example.fnni.*.www"
        },
        "dnssecStatus": "Unknown",
        "lastUsedOn": "2023-09-28T17:50:38.3460811Z"
      }
    ]
  },
  "status": "ok"
}
```
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/11771739/d221cca1-2625-45e1-b854-a6bb36cf4802)

**Comment by ShreyasZare** [comment]
> I forgot to add another record that was present in the original [test case 23](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ZoneFiles/23.txt) when I copied it over into the bug report. I think that affects as it involves wildcards.

Ohk ok. Will test it again on my setup again.

> I am not using the UI client. I am running the DnsServer in a container on a remote machine.

The UI is available on the same HTTP API URL itself. Just try it on any web browser.

**Comment by ShreyasZare** [comment]
Thanks again for the report. Technitium DNS Server v11.5.2 is now available that fixes this issue. Do update and let me know your feedback.
