### ISSUE TITLE
Improper handling of non-terminal wildcard 

### ISSUE THREAD

**Issue by SivaKesava1** [TechnitiumSoftware/DnsServer#748]
Hi @ShreyasZare,

The following discrepancy is from the [test case 133](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ExpectedResponses/133.json). 

The test [zone file](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ZoneFiles/133.txt) is:

```
bankcard.bar.				      500 IN SOA	ns1.outside.edu. root.campus.edu. 3 604800 86400 2419200 604800
bankcard.bar.				      500 IN NS		ns1.outside.edu.
*.bankcard.bar.				      500 IN CNAME	mybankcard.www.bar.bar.
campus.*.bankcard.bar.			      500 IN NS		bar.
```

The response for the query `<campus.email.bankcard.bar., NS>` from Technitium server is:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR",
          ";QUESTION",
          "campus.email.bankcard.bar. IN NS",
          ";ANSWER",
          ";AUTHORITY",
          "campus.*.bankcard.bar. 500 IN NS bar.",
          ";ADDITIONAL"
```

whereas the response from others was:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "campus.email.bankcard.bar. IN NS",
          ";ANSWER",
          "campus.email.bankcard.bar. 500 IN CNAME mybankcard.www.bar.bar.",
          ";AUTHORITY",
          ";ADDITIONAL"
```

When you match a query against this record, you should treat the `*` in `campus.*.bankcard.bar.` as a literal character `*`, not a wildcard. Therefore, the query should not match this record.  If you think of the domain names in the zone as a tree., then at the `email` label in the query, there is no exact match. So, the wildcard record `*.bankcard.bar.` captures it.

--Siva

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get this fixed soon.

**Comment by ShreyasZare** [comment]
Thanks again for the report. Technitium DNS Server v11.5.2 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by SivaKesava1** [comment]
I don't think it handles empty non-terminal wildcards correctly still. 

Zone file is:
```
test.   500     IN      SOA     ns1.outside.edu. root.campus.edu. 8 6048 4000 2419200 6048
test.   500     IN      NS      ns1.outside.edu.
a.*.*.test.     500     IN      CNAME   some.domain.
```

For the query `<a.a.test., CNAME>` the response from Technitium is:
```
           "rcode NXDOMAIN",
          "flags QR AA RA",
          ";QUESTION",
          "a.a.test. IN CNAME",
          ";ANSWER",
          ";AUTHORITY",
          "test. 500 IN SOA ns1.outside.edu. root.campus.edu. 8 6048 4000 2419200 6048",
          ";ADDITIONAL"
```

The response from others is same except that the RCODE is `NOERROR`. The empty wildcard will capture the query so the name is considered as existing, so it should not be `NXDOMAIN`.
