### ISSUE TITLE
Records below delegation are not ignored

### ISSUE THREAD

**Issue by SivaKesava1** [TechnitiumSoftware/DnsServer#749]
Hello,

This issue was discovered with [test case 156](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ExpectedResponses/156.json)

The test [zone file](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ZoneFiles/156.txt) is:

```
www.www.				      500 IN SOA	ns1.outside.edu. root.campus.edu. 3 604800 86400 2419200 604800
www.www.				      500 IN NS		ns1.outside.edu.
bar.www.www.				      500 IN NS		bankcard.net.mybankcard.email.
*.bar.www.www.				      500 IN CNAME	uni.www.
uni.bar.www.www.			      500 IN DNAME	www.www.
```

The response for the query `<example.bar.www.www., DNAME>` from Technitium server is:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA RA",
          ";QUESTION",
          "example.bar.www.www. IN DNAME",
          ";ANSWER",
          "example.bar.www.www. 500 IN CNAME uni.www.",
          ";AUTHORITY",
          ";ADDITIONAL"
```
whereas the response from others was:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR",
          ";QUESTION",
          "example.bar.www.www. IN DNAME",
          ";ANSWER",
          ";AUTHORITY",
          "bar.www.www. 500 IN NS bankcard.net.mybankcard.email.",
          ";ADDITIONAL"
```

According to RFC 2181, any data below the zone cut should not appear on the parent side. The records below the delegation cut should be ignored. This issue has been fixed by other implementations.

- https://gitlab.nic.cz/knot/knot-dns/-/issues/713
- https://github.com/NLnetLabs/nsd/issues/174
- https://github.com/yadifa/yadifa/issues/12

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get this fixed soon.

**Comment by ShreyasZare** [comment]
Thanks again for the report. Technitium DNS Server v11.5.2 is now available that fixes this issue. Do update and let me know your feedback.
