### ISSUE TITLE
Dns API

### ISSUE THREAD

**Issue by sekhuat** [TechnitiumSoftware/DnsServer#75]
Hi,
     Is there any api for developer to programatically create zone and all dns record (e.g. A, Mx, NS, etc) via node js?

Thanks,
Sek Huat

**Comment by ShreyasZare** [comment]
Yes, there already is an API for all tasks which is being used by the web console html + js code. However, there is no documentation for it yet.

For now, you can use web browser's developer tools network tab to see the API calls that the web console makes for actions. You can also see the [javascript code](https://github.com/TechnitiumSoftware/DnsServer/tree/master/DnsServerCore/www/js) that make the API calls. Using this info you can make calls from your node js code.

**Comment by sekhuat** [comment]
Noted and thanks. :)

**Comment by ShreyasZare** [comment]
API documentation is now available [here](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md).
