### ISSUE TITLE
Behavior Difference in following CNAME rewrite

### ISSUE THREAD

**Issue by SivaKesava1** [TechnitiumSoftware/DnsServer#750]
Hi @ShreyasZare,

Ferret discovered a difference in behavior from Bind, NSD and Knot that is probably not a bug, but might be interesting to know.

This is using [test case 320](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ZoneFiles/320.txt).

Zone file is:
```
campus.					      500 IN SOA	ns1.outside.edu. root.campus.edu. 3 604800 86400 2419200 604800
campus.					      500 IN NS		ns1.outside.edu.
*.campus.				      500 IN CNAME	example.uni.email.campus.
```

Response from Technitium:
```
          "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA RA",
          ";QUESTION",
          "mybankcard.campus. IN NS",
          ";ANSWER",
          "mybankcard.campus. 500 IN CNAME example.uni.email.campus.",
          ";AUTHORITY",
          ";ADDITIONAL"
```

Response from [Bind, Knot and NSD](https://github.com/dns-groot/FerretDataset/blob/main/ValidZoneFileTests/ExpectedResponses/320.json) is:
```
           "opcode QUERY",
          "rcode NOERROR",
          "flags QR AA",
          ";QUESTION",
          "mybankcard.campus. IN NS",
          ";ANSWER",
          "mybankcard.campus. 500 IN CNAME example.uni.email.campus.",
          "example.uni.email.campus. 500 IN CNAME example.uni.email.campus.",
          ";AUTHORITY",
          ";ADDITIONAL"
```

They all use the `CNAME` record again to rewrite the new query, and then they notice that both the query name and the target are the same, so they stop.  `CNAME` chains should be followed, so the expected response is to have both the records.

--Siva

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Yes this is due to CNAME checks added which prevents another CNAME record being added if it points to same domain. Will check this implementation once again.

**Comment by ShreyasZare** [comment]
Thanks again for the report. Technitium DNS Server v11.5.2 is now available that fixes this issue. Do update and let me know your feedback.
