### ISSUE TITLE
(Bug) Server permits adding RRs that should not be acceptable

### ISSUE THREAD

**Issue by noseshimself** [TechnitiumSoftware/DnsServer#751]
Simply put: It is possible to add RRs that result in having CNAME and other RRs for the same name without any error messages.

While I do not really care about the results of lookups for these names but other servers are complaining about the zone; secondaries running BIND are not accepting the zone data (but only complaining about the fact "CNAME and other data" without giving the name -- lovely) and other servers just drop the result reporting NXDOMAIN for ANY queries.

Please add a CNAME sanity check.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get the validation added.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that adds CNAME validation check. Do update and let me know your feedback.

**Comment by noseshimself** [comment]
Working as expected. Thank you!

**Comment by ShreyasZare** [comment]
Thanks for the feedback.
