### ISSUE TITLE
Feature request: Classless IN-ADDR.ARPA delegation (RFC 2317) support

### ISSUE THREAD

**Issue by kunimitsukada** [TechnitiumSoftware/DnsServer#752]
I think this RFC implementation is essential for authoritative servers operating with IPv4 addresses.

**Comment by ShreyasZare** [comment]
Thanks for the post. For this, you have to manually create those records since the DNS server does not know how your IP space is subnetted. I would suggest using a script to generate those records and then using the HTTP API to insert those records in the relevant zones.
