### ISSUE TITLE
Where is TSIG key?

### ISSUE THREAD

**Issue by CRASH-Tech** [TechnitiumSoftware/DnsServer#753]
Hello, it's a great product!
But I can not find the TSIG key, only shared secret. Thanks!

**Comment by ShreyasZare** [comment]
Thanks for asking. If by TSIG key you mean the password used then its the Shared Secret which is to be used. Shared Secret is the correct term to be used as per the TSIG standard.

**Comment by CRASH-Tech** [comment]
Oh, thanks. My mistake.
