### ISSUE TITLE
Feature Request: Allow to set subnets fo AXFR&RFC2136

### ISSUE THREAD

**Issue by CRASH-Tech** [TechnitiumSoftware/DnsServer#756]
This is useful feature to use it with kubernetes and external-dns, where nsupdate may be sended from any node.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will get that added.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available that allows configuring network address for zone transfer and dynamic updates. Do update and let me know your feedback.
