### ISSUE TITLE
[HOWTO] Add a top-level/root domain and subdomain?

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#76]
I want to be able to resolve a server called `neoserver1.neonation.did`

1. I can add the top level domain `did` as it's own zone with no problem.  I can add `A` records to the `did` zone/domain and they resolve OK.
2. I added the second level domain `neonation` as it's own zone (on the same physical DNS server) and underneath it, an `A` record for `neoserver1`.
3. I added

`neonation | NS | 3600 | desktop-u8p7e0q`

to the `did` zone file.

4. I added 

`neoserver1 | A | 3600 | 1.2.3.4`

to the `neonation` zone file.

`neoserver1.neonation.did `doesn't resolve.

What am I missing?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I recreated the zones you mentioned above in exact same steps and the server is able to resolve `neoserver1.neonation.did` correctly.

Another thing is that if you wish to host `neonation.did` zone then you do not require creating `did` zone. In fact, this will potentially block all other valid second level zones not hosted on your server from being resolved (if `did` zone is a valid Internet TLD).

Also, even if you add NS record into `did` zone for `neonation`, it would get automatically added into `neonation.did` zone since that zone exists on the server.

**Comment by mwherman2000** [comment]
Perfect.  I prefer the idea of having separately managed `neonation.did`, f`oo.did`, and `bar.did`, etc. zones.

I'll also try re-running my test case with a completely fresh set of "bib" domains (as an example).

Thank you for the prompt reply,
Michael

**Comment by mwherman2000** [comment]
Follow-up question if I may: I like the idea of having separately managed `neonation.did`, `foo.did`, and `bar.did`, etc. domains ...each in its own zone ...possibly each on its own separate physical DNS servers.

If I still want to have some sort of capability for querying against the top-level `did` level to find out which second level subdomains exists (e.g. `neonation.did`, `foo.did`, and `bar.did`, etc.), what do you recommend? 
...even if it took some manual effort for each subdomain.

Best regards,
Michael Herman

**Comment by ShreyasZare** [comment]
> Follow-up question if I may: I like the idea of having separately managed `neonation.did`, `foo.did`, and `bar.did`, etc. domains ...each in its own zone ...possibly each on its own separate physical DNS servers.

This is pretty much the only way to do this. You create multiple zones for each individual non related domain names and manage them independently.

The only other way to do this would be to create a single zone `did` and then create all records under this zone. So, if you want to create an A record for `neoserver1.neonation.did` then you can add the record with name field set to `neoserver1.neonation`.
 
> If I still want to have some sort of capability for querying against the top-level `did` level to find out which second level subdomains exists (e.g. `neonation.did`, `foo.did`, and `bar.did`, etc.), what do you recommend?
> ...even if it took some manual effort for each subdomain.

DNS system does not provide a way to query the server to enumerate all possible sub domains. There is a similar query that uses type ANY which would return all records under the queried domain name. But you cannot find out all sub domain names by querying the DNS.

If you want to do this for management purposes then you can use the same HTTP API that the DNS Server user interface calls using the javascript code in the web browser. This HTTP API is not documented as of now so you will need to lookup the calls using web browser's developer tools network tab.

> UPDATE: The only hack I could come up with was the add the following `TXT` record
> to the `did` top-level domain. There must be something better than this? :-)
> 
> `udidservers | TXT | 3600 | sov.did:desktop-u8p7e0q;neonation.did:desktop-u8p7e0q`

I am not sure what you are trying to achieve. I can suggest you better options if you can describe your requirements.

**Comment by mwherman2000** [comment]
I went with something similar to your earlier suggestion...  thank you.  

The bigger picture is that I'm adapting your DNS Server to also support Digital/Decentralized Identifiers per this W3C draft community specification: https://w3c-ccg.github.io/did-spec/

![image](https://user-images.githubusercontent.com/6101736/63131037-9b5ca980-bf79-11e9-9645-49644049a134.png)

**Comment by mwherman2000** [comment]
RE: `DNS system does not provide a way to query the server to enumerate all possible sub domains. There is a similar query that uses type ANY which would return all records under the queried domain name. But you cannot find out all sub domain names by querying the DNS.`

Which record types does or should ANY return for a given domain? ...for example, it doesn't appear to return A records? ...I've also created some custom resource record types and it doesn't return those either.

I'VE GOT IT: DNS resource type ANY only returns the resource types for the specific queried parameter (specific domain, subdomain, or server name, etc.). ...not everything in the zone file.  Make sense.

Correct?

**Comment by ShreyasZare** [comment]
Thanks for the details. It looks quite interesting.

Ya, like you found out, ANY query returns all resource records for a given domain name in the query. No sub domain records are returned.
