### ISSUE TITLE
Logs rotation

### ISSUE THREAD

**Issue by razametal** [TechnitiumSoftware/DnsServer#763]
Hi, I've a server with version v11.4.1.

The directory /etc/dns/logs are growing and filling the hard disk space.

Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/pve-vm--503--disk--0  118G  112G     0 100% /

How can I prevent it?

Best regards,

**Comment by razametal** [comment]
I have found on the web admin GUI.

Under Settings / Logging

And it works !

Best regards,

**Comment by ShreyasZare** [comment]
Thanks for the post. Good to know you found out the option.
