### ISSUE TITLE
[Feature request] Description text for "Blocking Bypass List"

### ISSUE THREAD

**Issue by brokoler** [TechnitiumSoftware/DnsServer#765]
Hello,

I discovered the feature "Blocking Bypass List" after updating to 11.5.
Feature description in the changelog:
`Added option to configure IP/network addresses[...]`

Could a short description be added that describes which formats are allowed and how to seperate entries (new line, comma)?
I entered one IP manually and it worked. But which formats would work for network adresses or multiple IP adresses?

Such a great and handy feature, I don't have to disable adblocking now when one device needs more access at a time.
Thanks so much for your work!

**Comment by ShreyasZare** [comment]
Thanks for the post. I will update the description on the GUI to make it clearer.

The text area boxes on the GUI will take one entry per line in all places. And since the GUI code converts it into a comma separated list to send it to the DNS server, you can also use comma separated entries. 

So, to answer your question, both new line and comma separated entries would work.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v11.5.2 is now available which updated the description for Blocking Bypass List option. Do update and let me know your feedback.

**Comment by brokoler** [comment]
@ShreyasZare 
Thanks for adding a descritpion with 11.5.2.

I'm still unsure about different formats to enter for network adresses.
Could you tell which of following would work?

1. 192.168.1.0/24
2. 192.168.1.0 255.255.255.0
3. 192.168.1.100-192.168.1.200

Thanks so much!

**Comment by ShreyasZare** [comment]
> I'm still unsure about different formats supported for network adresses. Could you tell which of following would work?
> 
>   1. 192.168.1.0/24
> 
>   2. 192.168.1.0 255.255.255.0
> 
>   3. 192.168.1.100-192.168.1.200

The network address is always in CIDR format in all places in the GUI. So the first option will work.

> Thanks so much!

You're welcome!
