### ISSUE TITLE
* is taken as litteral in zone

### ISSUE THREAD

**Issue by michelsup** [TechnitiumSoftware/DnsServer#766]
If I add a * as the subdomain like

```New record was added to authoritative zone 'example.org' successfully {record: *.example.org.  3600      IN  A             xx.xx.xx.xx}```

the server is answering with an NX with ie. test.example.org, but gives an answer with *.example.org as the question, like the * is taken as a literal character.

What I'm doing wrong ?

**Comment by ShreyasZare** [comment]
Thanks for the post. I tried this on my test setup with v11.5.1 and the wildcard record is working as expected. 

Please test it again and post more details i.e. output from DNS client tab for the queries, screenshot of the zone records, etc. You can share the details on email too if you do not wish to post them here.

**Comment by michelsup** [comment]
I somewhat messed up between Authoritative and Conditional Forwarder Zone setups. 20 years of DNS'ing is still not enough for me. Sorry to disturb and thank you for your time and quick reply @ShreyasZare. (and obviously your software)

**Comment by ShreyasZare** [comment]
> I somewhat messed up between Authoritative and Conditional Forwarder Zone setups. 20 years of DNS'ing is still not enough for me. Sorry to disturb and thank you for your time and quick reply @ShreyasZare. (and obviously your software)

Ya, that happens some times with everyone. Good to know its working well.
