### ISSUE TITLE
Provide apt packages

### ISSUE THREAD

**Issue by brainfish** [TechnitiumSoftware/DnsServer#768]
Have you given any thought to providing `apt` packages? I guess some might care about `yum` as well. ASP.NET is already available via apt, and this would not only simplify the install process, but *greatly* simplify the update process. I manage TDNS via Ansible and right now automated updates requires maintaining, and periodically rotating, an API key to query TDNS for updates so I'm not re-downloading and -extracting the tarball unnecessarily on every ansible run. This additionally complicates the ansible playbook since we have to handle the case where Technitium isn't installed yet and can't be queried. With OS packages, users would get updates for free just by running e.g. `apt update && apt upgrade -y`, which would enhance the overall security posture of the TDNS user community and be a positive for Technitium overall.

I'd be interested in Debian 12 packages primarily but I'm sure Ubuntu would also be a common request, although the two should be virtually identical for the most recent versions of each distro.

We've considered moving to hosting Technitium in Docker for simpler updates but the overhead of running Docker on every DNS VM for this one feature is gross, and problematic for already-resource-constrained platforms like Raspberry Pi, NUC, etc. It seems like providing OS packages could really help drive adoption of Technitium.

**Comment by ShreyasZare** [comment]
Thanks for the post. The issue with having OS packages is with resources i.e. time. It would be quite difficult for me to be able to manage multiple packages for each distro. The install script currently available works for all distros and does not need any kind of maintenance. There are already a lot of features planned that are to be implemented so may be once most of the planned features are done and there is time available that I can plan for having packages.

**Comment by medaminezghal** [comment]
@ShreyasZare I think it's the time to provide `apt` package. isn't? Also you can provide only `apt` and `rpm` packages, the majority of Linux distribution are based on them.

**Comment by ShreyasZare** [comment]
@medaminezghal There are limits to how much a single person can manage things.

**Comment by medaminezghal** [comment]
@ShreyasZare For example, a CI that is triggered every new release and using `aptly` will make it easy to provide the `apt` packages.

**Comment by ShreyasZare** [comment]
@medaminezghal All such tasks are easy, except that its not feasible to maintain huge number of these easy things.

**Comment by medaminezghal** [comment]
@ShreyasZare I know it’s very hard to maintain huge numbers of easy things, but if the process doesn’t need regular maintenance, the process can be unaccountable.
