### ISSUE TITLE
Feature request: allow-list NOTIFY addresses/networks

### ISSUE THREAD

**Issue by liamdawson** [TechnitiumSoftware/DnsServer#769]
I have a bit of a weird network setup where I add several IP addresses to a single interface, so I can put things like Technitium DNS on its own IP and bind the "primary" ports.

The weird part is that it means that incoming vs. outgoing IP addresses don't always align. In my case, I have the DNS server accessible at 192.168.4.53, but notifies are sent from the primary IP address for the interface, which is 192.168.1.12. However, nothing is bound to serve DNS requests at that address, so I don't think it makes sense to list it as a nameserver.

It would be nice to allow-list addresses that are permitted to send NOTIFYs, in the same style as the "Zone Transfer Allowed Networks" setting.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will plan to add an option for such cases.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that adds option to specify Notify Allowed Networks. Do update and let me know your feedback.
