### ISSUE TITLE
Bulk add/modify?

### ISSUE THREAD

**Issue by bcookatpcsd** [TechnitiumSoftware/DnsServer#772]
I've been using this personally on and off for a while.. and I found a use case where I can use it in a work environment.. 

Is there a way to, from a txt file, populate anything? 

I'm migrating something where they have *a lot* of hosts entries.. so I'm building forward zones and adding hosts.. 

But I feel this could be a job for a bulk import.. this may also help people get started.. (people that might be scared/confused of the zone tab) 

I'm sure nothing can be done to help this migration.. but I think it might be a worthwhile task.

**Comment by ShreyasZare** [comment]
Thanks for asking. Yes, the latest update has Import Zone option that you will find under the Options drop down button in the Zone Edit view. All you need to do is have all records you want to import in standard BIND zone file format. This feature can be used to add records or overwrite existing records. Let me know if you have any more queries.
