### ISSUE TITLE
Feature Request: Update Source

### ISSUE THREAD

**Issue by micush** [TechnitiumSoftware/DnsServer#773]
Hi Shreyas,

I run TDNS on some hosts with multiple NICs. When doing this, the DNS notify messages are sourced with the outgoing interface IP instead of the listening interface IP. The notify messages and zone transfers to secondaries fail because of this.

In the networking world I am able to specify a source IP for a specific service to prevent this type of thing, kind of like 'dns source ip address 1.2.3.4.' 

Could an option like this be added to the GUI for this type of setup? So that DNS transfers and notifies come from a specific source IP address instead of the outgoing interface IP to prevent these types of failures?

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/20692314/842a08fc-27c2-42cd-93fd-f779981a4bf5)

Regards,

Michael

**Comment by ShreyasZare** [comment]
Thanks for the feature request. I had a couple of similar issues over email and I am already planning to have a couple of options to fix couple of similar issues. So will get that option added in next update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that supports specifying one or more source addresses or networks to use for outbound DNS requests. Do update and let me know your feedback.
