### ISSUE TITLE
quic with NextDNS problems; server timeouts

### ISSUE THREAD

**Issue by bcookatpcsd** [TechnitiumSoftware/DnsServer#774]
TLS 853 is working without issue.. Switching to quic causes server timeouts.

I've used quic with AdGuardHome and NextDNS and have not seen timeouts..

Technitum and NextDNS just fine with DoT and DoH..

If you are interested in more detail, please let me know..

**Comment by ShreyasZare** [comment]
Thanks for the post. Request timeout means that the DNS server tried to send the request but did not receive a response. So, it could be due to many reasons of which most common is intermittent network issues. Try using [dnsclient.net](https://dnsclient.net/) website to see if you are able to make requests to the same server over QUIC.

**Comment by bcookatpcsd** [comment]
(server 1)
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/8601ec52-92ae-498f-85a9-397be9fefeef)

(server 2)
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/4a7e3253-ad05-495b-98c7-d1a5a9b56f8c)

I built two new servers yesterday before the ride home from work.. single family house, 40-50 devices.. and wg vpn to the house, two vultr cloud servers in docker with wg links back to the house.. and the trip home was terrible.. when I got home at 5 I switched back to tls and the problems went away..  

the syntax of the dnsclient.net site looked different than Technitium server {server-name (ip.ad.dr.es:853)} but that syntax didn't seem to matter when I pasted my server name/ip.. and it worked in the site.. I made the change in my instances again.. and will see what happens. 

Thank you for the response..

**Comment by bcookatpcsd** [comment]
Spoke too soon.. 

ten minutes.. 

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/00fc0c88-def9-48eb-91e2-0d3fcdb4f494)

It doesn't need to be quic, and it might be NextDNS..

**Comment by ShreyasZare** [comment]
Thanks for the details. Check the DNS logs from the admin web panel and look for the error description in there to know what went wrong. Post any errors you see here if you need help with them.
