### ISSUE TITLE
inconsistent problem enabling web service https 

### ISSUE THREAD

**Issue by bcookatpcsd** [TechnitiumSoftware/DnsServer#776]
I have moved to the docker image on several machines.  Docker hosts include Void (glibc), Alpine (musl), Arch (glibc).. 

(as I type this.. maybe it's esxi related..) 

I have machines that I cannot enable the https webif.. when I try to, I am left with:

127.0.0.1:5380             0.0.0.0:*    users:(("dotnet",pid=2222430,fd=204))    

Loopback running 5380 and I have to ssh tunnel to disable the https setting to get the regular 5380 back.. (regardless of selecting http to https redirection) 

for example:

```
ssh -L 127.0.0.1:5380:127.0.0.1:5380 user@remote.machine
```

Then I can http://127.0.0.1:5380 and see the Technitium login page.. 

When I enable https or http/3 only on what (now) appears to be these esxi VMs.. regardless of the OS I have this issue.. 

I also cannot see anything in any logs regarding the creation of the tls cert and the acknowledgement that these tls services are being started.. 

Thank you in advance.

**Comment by ShreyasZare** [comment]
Thanks for the post. The DNS admin web service will listen on loopback interface as backup only when it was unable to listen on the provided local address and port. There will be a log entry in such case that will indicate the issue. Do check the DNS server logs from the admin panel once. 

If you are using latest update then the DNS server will check if the local address and port for web service is available before saving settings to prevent such issues.
