### ISSUE TITLE
.Net 8.0 and unsatisfied dependencies  

### ISSUE THREAD

**Issue by SoftExpert** [TechnitiumSoftware/DnsServer#779]
.Net 8.0 is out and AUR packages have already picked the new version. 
Since the update (which removed the previous .NET 7.x), technitium-dns-server.service will not start (complains about the missing .NET 7.x dependencies).
Can you, please, release a build compiled with .NET 8.0 ?
Thank you in advance !

Best regards,
SoftExpert

**Comment by ShreyasZare** [comment]
Thanks for the post. The AUR package is not officially provided by Technitium. So, you need to contact the package maintainer to fix this issue. The next update for Technitium DNS server will run on .NET 8 but it will take some time and wont be available soon.Also, note that .NET major versions are not a replacement for previous major versions. Thus removing .NET 7 when installing .NET 8 is not correct way to do that.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that uses .NET 8 runtime.
