### ISSUE TITLE
There is a problem with ecs cache

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#783]
In the ceche cache, we see that the IP address of the cache subnet client is 0.0.0.0/0, so all ecs are messed up. I don’t know why the subnet IP 0.0.0.0/0 is cached in the cache. When 0.0.0.0/0 is cached, it means that the parsing answer is suitable for all client IPs. This is wrong.

**Comment by liang-hiwin** [comment]
> Thanks for the post. If you see cached entry with `0.0.0.0/0` as the ECS subnet then its there because the upstream server responded that way. Technitium DNS will just cache the records with the ECS subnet as per response it received from the upstream. So there is nothing that can be done to fix this.
> 
> If you think this is a bug then let me know a specific domain name to test to replicate the issue. If the issue is able to replicate then it can be fixed.

```

[
  {
    "name": "loon-gallery.vercel.app",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "76.76.21.22"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-11-21T12:01:07.1691485Z"
  },
  {
    "name": "loon-gallery.vercel.app",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "76.76.21.93"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-11-21T12:01:07.1691485Z"
  }
]
```

**Comment by liang-hiwin** [comment]
```

[
  {
    "name": "40489a.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "18.163.213.203"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "171.105.40.0/24",
    "lastUsedOn": "2023-11-22T10:13:21.1017967Z"
  },
  {
    "name": "40489a.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "18.163.224.54"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "171.105.40.0/24",
    "lastUsedOn": "2023-11-22T10:13:21.1017967Z"
  },
  {
    "name": "40489a.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "18.162.226.181"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "171.105.40.0/24",
    "lastUsedOn": "2023-11-22T10:13:21.1017967Z"
  },
  {
    "name": "40489a.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "18.163.213.203"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-11-22T13:45:30.1866621Z"
  },
  {
    "name": "40489a.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "18.163.224.54"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-11-22T13:45:30.1866621Z"
  },
  {
    "name": "40489a.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "ipAddress": "18.162.226.181"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-11-22T13:45:30.1866621Z"
  },
  {
    "name": "40489a.com",
    "type": "AAAA",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "NegativeCache: NoError; 40489a.com.           3600      IN  SOA           clint.ns.cloudflare.com. dns.cloudflare.com. 2324846564 10000 2400 604800 1800"
    },
    "dnssecStatus": "Unknown",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2023-11-22T13:45:30.1577088Z"
  }
]
```

**Comment by ShreyasZare** [comment]
Thanks for the details. This is normal and not an issue. The DNS server will respond with correct records as per the ECS option in the received request. 

So, in your above cache example, if the request comes from `171.105.40.0/24` subnet then those records marked with that subnet will be used else those marked with `0.0.0.0/0` will be used in the response.

**Comment by liang-hiwin** [comment]
> Thanks for the details. This is normal and not an issue. The DNS server will respond with correct records as per the ECS option in the received request.
> 
> So, in your above cache example, if the request comes from `171.105.40.0/24` subnet then those records marked with that subnet will be used else those marked with `0.0.0.0/0` will be used in the response.

Maybe my cache time setting is too long, causing clients in different subnets to respond to the 0.0.0.0/0 IP cached by ECS when requesting resolution.

**Comment by ShreyasZare** [comment]
> Maybe my cache time setting is too long, causing clients in different subnets to respond to the 0.0.0.0/0 IP cached by ECS when requesting resolution.

Its not an issue with your settings. The domain's name servers are returning `0.0.0.0/0` subnet which means that they want the records to be used by all client subnets. Its something that the domain owners are choosing and nothing can be done about it on the client side.

**Comment by liang-hiwin** [comment]
> > Maybe my cache time setting is too long, causing clients in different subnets to respond to the 0.0.0.0/0 IP cached by ECS when requesting resolution.
> 
> Its not an issue with your settings. The domain's name servers are returning `0.0.0.0/0` subnet which means that they want the records to be used by all client subnets. Its something that the domain owners are choosing and nothing can be done about it on the client side.

My upstream is unbound dns (forwarding google dns). Is it an unbound problem?

**Comment by ShreyasZare** [comment]
> My upstream is unbound dns (forwarding google dns). Is it an unbound problem?

I am not sure about that since I have not tested it with unbound. If unbound is forwarding the ECS from the incoming request then it should work. Also, since the request finally ends with Google DNS, they can manipulate ECS as per their policy. For example, Cloudflare DNS does not support ECS deliberately for privacy reasons.

**Comment by liang-hiwin** [comment]
> > My upstream is unbound dns (forwarding google dns). Is it an unbound problem?
> 
> I am not sure about that since I have not tested it with unbound. If unbound is forwarding the ECS from the incoming request then it should work. Also, since the request finally ends with Google DNS, they can manipulate ECS as per their policy. For example, Cloudflare DNS does not support ECS deliberately for privacy reasons.

Can I manually edit the cdn cname value used by a domain name?

**Comment by liang-hiwin** [comment]
For example, this domain name app-site-association.cdn-apple.com uses many CDNs, but some CDN service providers do not have my local nodes, but other CDN service providers have my local nodes.
So I want to directly edit the cname specifying this domain name to the cdn service provider that has my node.

**Comment by ShreyasZare** [comment]
There is no option to manually edit cache entries. But, you can create Conditional Forwarder zone with "This Server" as the forwarder and add your custom CNAME entry as required which will work as you expect.

**Comment by liang-hiwin** [comment]
> There is no option to manually edit cache entries. But, you can create Conditional Forwarder zone with "This Server" as the forwarder and add your custom CNAME entry as required which will work as you expect.

It seems to have been successful, but can I use the Geo Distance library to meet the conditions before using the cname I defined?

**Comment by ShreyasZare** [comment]
You got the conditional forwarder zone configured right.

> but can I use the Geo Distance library to meet the conditions before using the cname I defined?

Yes, you can create an APP record and use Geo Distance app with it. But, the client making requesting the must have a public IP address so that the app can figure out its current geo coordinates to calculate the distance between the multiple servers and the client.

**Comment by liang-hiwin** [comment]
> You got the conditional forwarder zone configured right.
> 
> > but can I use the Geo Distance library to meet the conditions before using the cname I defined?
> 
> Yes, you can create an APP record and use Geo Distance app with it. But, the client making requesting the must have a public IP address so that the app can figure out its current geo coordinates to calculate the distance between the multiple servers and the client.

There seems to be no tutorial on Geo Continent, Geo Country, and Geo Distance. Can you provide one?

**Comment by ShreyasZare** [comment]
> There seems to be no tutorial on Geo Continent, Geo Country, and Geo Distance. Can you provide one?

All these apps need MaxMind IP to location database to work and a Lite version of db is included in the app as example which works but may not be accurate. 

To understand them, you need to take a look at the JSON app record data. Since you need CNAME, you need to select the Class Path for the app which ends with CNAME.

The continent and country apps will just find the continent or country of the client IP address and return the CNAME as per the app record JSON config array.

The Distance app is a bit different and requires you to provide an approximate latitude and longitude for each of the server you specify in the app record JSON. It will find out the lat and long for the client request IP address and match with all the entries you have in the APP record JSON and return the server closest to the client location.

Just click on the "More Details" link in the Apps list to see the sample JSON record data templates to understand the APP record config.

**Comment by liang-hiwin** [comment]
> > There seems to be no tutorial on Geo Continent, Geo Country, and Geo Distance. Can you provide one?
> 
> All these apps need MaxMind IP to location database to work and a Lite version of db is included in the app as example which works but may not be accurate.
> 
> To understand them, you need to take a look at the JSON app record data. Since you need CNAME, you need to select the Class Path for the app which ends with CNAME.
> 
> The continent and country apps will just find the continent or country of the client IP address and return the CNAME as per the app record JSON config array.
> 
> The Distance app is a bit different and requires you to provide an approximate latitude and longitude for each of the server you specify in the app record JSON. It will find out the lat and long for the client request IP address and match with all the entries you have in the APP record JSON and return the server closest to the client location.
> 
> Just click on the "More Details" link in the Apps list to see the sample JSON record data templates to understand the APP record config.

```
{
   "IN": [
     "1.1.1.1",
     "2.2.2.2"
   ],
   "default": [
     "3.3.3.3"
   ]
} ,


```
What does IN refer to, and default.

**Comment by ShreyasZare** [comment]
> What does IN refer to, and default.

Its ISO country code IN for India. Default refers to a case when the MaxMind db fails to find out the country for the client IP address.

**Comment by liang-hiwin** [comment]
> > What does IN refer to, and default.
> 
> Its ISO country code IN for India. Default refers to a case when the MaxMind db fails to find out the country for the client IP address.

Thank you for your guidance. Can I make a feature request in this post?

**Comment by ShreyasZare** [comment]
> Thank you for your guidance. Can I make a feature request in this post?

You're welcome. If its related then post here otherwise a new issue for it will be good for tracking.

**Comment by liang-hiwin** [comment]
> > Thank you for your guidance. Can I make a feature request in this post?
> 
> You're welcome. If its related then post here otherwise a new issue for it will be good for tracking.

I want to add location based on different carriers. Currently there are Geo Continent, Geo Country, and Geo Distance, I just want to make the geo partitioning of the app more detailed

**Comment by ShreyasZare** [comment]
> I want to add location based on different carriers.

Do you mean to do that using ASN? or some other parameter?

**Comment by liang-hiwin** [comment]
yes, for example, this website has some ASN IP segments of our operator, we can use it to carry out more detailed regional partitioning https://www.pdflibr.com/countries/cn/1

**Comment by liang-hiwin** [comment]
We can first mark the country and then the region, and then mark the network ASN IP segment used in this region. If the above requirements are met, use this cname, etc.

**Comment by ShreyasZare** [comment]
> We can first mark the country and then the region, and then mark the network ASN IP segment used in this region. If the above requirements are met, use this cname, etc.

An app for ASN can be planned. If you wish to combine multiple parameters then chaining these apps with the APP record CNAME can be done as per requirements.

**Comment by liang-hiwin** [comment]
> > We can first mark the country and then the region, and then mark the network ASN IP segment used in this region. If the above requirements are met, use this cname, etc.
> 
> An app for ASN can be planned. If you wish to combine multiple parameters then chaining these apps with the APP record CNAME can be done as per requirements.

Through the Geo Distance geographical distance setting, I found that the cname I set did not work.
For example, you can see from the screenshot that huanan-guangzhou, the cname I set is iosapps.itunes.apple.com.m.alikunlun.net.
But when I use dig to append the IP of the huanan-guangzhou region for resolution, cname does not use the value I set.


![{{ _$5@GOW~3Z@~{RZQBR)H](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/8dedc022-2d83-405f-9672-41f05c97fe40)


![image](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/ce0003df-f1d8-4e30-b879-b5a31b4437f7)

**Comment by liang-hiwin** [comment]
> > Through the Geo Distance geographical distance setting, I found that the cname I set did not work.
> 
> Have you downloaded new copy of MaxMind database? Also a full copy of the db is needed for these apps too work correctly.

I updated GeoLite2-City.mmdb, downloaded from this open source project https://github.com/P3TERX/GeoLite.mmdb,
They provide GeoLite2-ASN.mmdb, GeoLite2-City.mmdb, GeoLite2-Country.mmdb, among which GeoLite2-ASN.mmdb can support subsequent support for ASN.

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/02042316-83d4-4e6f-a43f-179fddc975d5)

**Comment by ShreyasZare** [comment]
> I updated GeoLite2-City.mmdb, downloaded from this open source project https://github.com/P3TERX/GeoLite.mmdb,

I just tried the same database with same APP record json and the app is selecting `guangzhou` location correctly. The old db file included in the app selects the `shanxi` location.

If you have just replaced the mmdb file on disk directly then you need to restart the DNS server. The correct method to update the mmdb files is to zip then and then use the app's Update button on the GUI to update the db which loads without need for server restart.

**Comment by ShreyasZare** [comment]
> Yes, I have unzipped it, replaced the GeoLite2-City.mmdb file, and restarted the dns program

Try testing it again. Since, here its working as expected for the same database file that you are using.

**Comment by liang-hiwin** [comment]
> > Yes, I have unzipped it, replaced the GeoLite2-City.mmdb file, and restarted the dns program
> 
> Try testing it again. Since, here its working as expected for the same database file that you are using.

Ok, the problem is solved. Due to the lack of ASN support, different IP requests through the ASN operator cannot be allocated normally.

**Comment by liang-hiwin** [comment]
> > We can first mark the country and then the region, and then mark the network ASN IP segment used in this region. If the above requirements are met, use this cname, etc.
> 
> An app for ASN can be planned. If you wish to combine multiple parameters then chaining these apps with the APP record CNAME can be done as per requirements.

Hello brother. Can you support this plan in the future?

**Comment by ShreyasZare** [comment]
> Hello brother. Can you support this plan in the future?

Sure, will get a new app with ASN support added.

**Comment by liang-hiwin** [comment]
> > Hello brother. Can you support this plan in the future?
> 
> Sure, will get a new app with ASN support added.

thanks

**Comment by liang-hiwin** [comment]
There is a problem with ecs. I have to ask here. 5300 is the port of DnsServe @ShreyasZare 
```
With the same upstream, I run
**q www.akamai.com a -s "https://xxxxxx.cloudflare-gateway.com/dns-query" --subnet=106.75.245.0/24|nali**
e2915.dscca.s.tl88.net. 20s A 106.4.158.41 [China Jiangxi Jingdezhen]

**dig a +subnet=106.75.245.0/24 @127.0.0.1 -p 5300 www.akamai.com**

e2915.dscx.akamaiedge.net. 42726 IN     A       2.17.61.103



```

**Comment by ShreyasZare** [comment]
> There is a problem with ecs. I have to ask here. 5300 is the port of DnsServe @ShreyasZare

Cloudflare does not support ECS so it wont work.

**Comment by liang-hiwin** [comment]
> > There is a problem with ecs. I have to ask here. 5300 is the port of DnsServe @ShreyasZare
> 
> Cloudflare does not support ECS so it wont work.

cf's gateway dns supports ecs

**Comment by ShreyasZare** [comment]
> > > There is a problem with ecs. I have to ask here. 5300 is the port of DnsServe @ShreyasZare
> > 
> > 
> > Cloudflare does not support ECS so it wont work.
> 
> cf's gateway dns supports ecs

No. It does not support ECS. I have just tested it.

**Comment by liang-hiwin** [comment]
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/6526a97e-c4bc-40c5-a2d3-eed924f41875)

**Comment by liang-hiwin** [comment]
Obviously, the results of DnsServer ecs on port 5300 and direct request to doh are different.

**Comment by liang-hiwin** [comment]
> > Obviously, the results of DnsServer ecs on port 5300 and direct request to doh are different.
> 
> I tested it again. When the DNS server is using Cloudflare Gateway upstream then its not working. I can see that there is no ECS data in the response. However, if I set Google DNS as the upstream then its working as expected and I can see the exact same IP address in response as from your screenshot. It does not seems to be any bug in code.
> 
> The next update will add ECS option in the DNS Client tool so it will become easy to test it out.

So I don't know why this is happening

**Comment by ShreyasZare** [comment]
> So I don't know why this is happening

Can you double check your settings? Check if the ECS option is enabled in the DNS server's Setting. Also check if the requests you make to port 5300 is actually being received by the DNS server by checking the query logs (or using the Query Logs app).

Also, are you using Advanced Forwarding app? In that case, ECS wont work since the app does not support it.

**Comment by liang-hiwin** [comment]
> > So I don't know why this is happening
> 
> Can you double check your settings? Check if the ECS option is enabled in the DNS server's Setting. Also check if the requests you make to port 5300 is actually being received by the DNS server by checking the query logs (or using the Query Logs app).
> 
> Also, are you using Advanced Forwarding app? In that case, ECS wont work since the app does not support it.

I have configured and checked ecs. I have not installed this app for advanced forwarding, and I have seen the domain name of the corresponding request in the log.

**Comment by liang-hiwin** [comment]
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/4aafd152-7f0e-4e9c-94d5-9a7fd902e2d9)
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/17548936/87507dd7-8eaa-41ae-afe3-2b92d6ef63c6)

```
[2024-03-09 19:41:42 Local] [127.0.0.1:56011] [UDP] QNAME: www.akamai.com; QTYPE: A; QCLASS: IN; RCODE: NoError; ANSWER: [www.akamai.com.edgekey.net., www.akamai.com.edgekey.net.globalredir.akadns.net., e2915.dscx.akamaiedge.net., 2.17.61.103]; ECS: 106.75.245.0/0

```

**Comment by ShreyasZare** [comment]
Thanks for the details. Check the DNS server's cache for `www.taobao.com.danuoyi.tbcache.com` records and see what `eDnsClientSubnet` is listed there. Post the cache records here.

**Comment by liang-hiwin** [comment]
> Thanks for the details. Check the DNS server's cache for `www.taobao.com.danuoyi.tbcache.com` records and see what `eDnsClientSubnet` is listed there. Post the cache records here.

```
[
  {
    "name": "www.taobao.com.danuoyi.tbcache.com",
    "type": "A",
    "ttl": "36644 (10 hours 10 mins 44 sec)",
    "rData": {
      "ipAddress": "111.31.37.214"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2024-03-09T12:51:02.2779165Z"
  },
  {
    "name": "www.taobao.com.danuoyi.tbcache.com",
    "type": "A",
    "ttl": "36644 (10 hours 10 mins 44 sec)",
    "rData": {
      "ipAddress": "111.31.37.215"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2024-03-09T12:51:02.2779165Z"
  },
  {
    "name": "www.taobao.com.danuoyi.tbcache.com",
    "type": "HTTPS",
    "ttl": "34798 (9 hours 39 mins 58 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "NegativeCache: NoError; danuoyi.tbcache.com.  43200     IN  SOA           danuoyins7.tbcache.com. root.taobao.com. 2012031100 3600 3600 604800 300"
    },
    "dnssecStatus": "Unknown",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "2024-03-09T12:20:16.2481697Z"
  }
]
```

**Comment by liang-hiwin** [comment]
The problem is eDnsClientSubnet": "0.0.0.0/0

**Comment by ShreyasZare** [comment]
Thanks for the details. The `"eDnsClientSubnet": "0.0.0.0/0"` in there means that the DNS server did not receive ECS in the response.

Wait for the next update which will add ECS option for DNS Client and also adds more details in the cache entries. That will make it clear to understand the issue.

**Comment by liang-hiwin** [comment]
See from this that the ecs I attached are sent correctly  https://github.com/TechnitiumSoftware/DnsServer/issues/783#issuecomment-1986848183

**Comment by liang-hiwin** [comment]
But DnsServer, doesn't seem to send my attached ecs to the upstream

**Comment by ShreyasZare** [comment]
> See from this that the ecs I attached are sent correctly [#783 (comment)](https://github.com/TechnitiumSoftware/DnsServer/issues/783#issuecomment-1986848183)

I am not familiar with the command line too that you are using so not sure how its working with it.

> But DnsServer, doesn't seem to send my attached ecs to the upstream

With the DNS server, its working the the tests with Google DNS from there so does not seem to be a bug. The next update will help with this though which should be available by next weekend.

**Comment by liang-hiwin** [comment]
> > See from this that the ecs I attached are sent correctly [#783 (comment)](https://github.com/TechnitiumSoftware/DnsServer/issues/783#issuecomment-1986848183)
> 
> I am not familiar with the command line too that you are using so not sure how its working with it.
> 
> > But DnsServer, doesn't seem to send my attached ecs to the upstream
> 
> With the DNS server, its working the the tests with Google DNS from there so does not seem to be a bug. The next update will help with this though which should be available by next weekend.

ok, Thank you for your answer and hard work.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.1 is now available that adds the ECS options for DNS Client and also adds response meta data for cache entries. This should help in debugging the ECS issues that you have. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
Great job, the parsing results are the same after the update.

**Comment by liang-hiwin** [comment]
How to use ASN database?

**Comment by ShreyasZare** [comment]
> Great job, the parsing results are the same after the update.

I am not sure what is the reason for this. It does work though if you try with something like Google DNS. You can do the same tests using the dnsclient.net website (which is hosted outside your country) to see if that works from another location.

**Comment by ShreyasZare** [comment]
> How to use ASN database?

If you are asking for the Geo apps then they have sample ASN database with them. Those apps will use it to find the client's network based on the ASN database and then use the correct scope prefix value in the ECS option in the response. There is no config required for it to work.

**Comment by liang-hiwin** [comment]
> > Great job, the parsing results are the same after the update.
> 
> I am not sure what is the reason for this. It does work though if you try with something like Google DNS. You can do the same tests using the dnsclient.net website (which is hosted outside your country) to see if that works from another location.

The results are different, the position deviation is very large.

**Comment by ShreyasZare** [comment]
> > > Great job, the parsing results are the same after the update.
> > 
> > 
> > I am not sure what is the reason for this. It does work though if you try with something like Google DNS. You can do the same tests using the dnsclient.net website (which is hosted outside your country) to see if that works from another location.
> 
> The results are different, the position deviation is very large.

The response is generated by the upstream server so there is nothing that can be done from the client side in this case. Try using a different upstream provider and see if that works.

**Comment by liang-hiwin** [comment]
> > > > Great job, the parsing results are the same after the update.
> > > 
> > > 
> > > I am not sure what is the reason for this. It does work though if you try with something like Google DNS. You can do the same tests using the dnsclient.net website (which is hosted outside your country) to see if that works from another location.
> > 
> > 
> > The results are different, the position deviation is very large.
> 
> The response is generated by the upstream server so there is nothing that can be done from the client side in this case. Try using a different upstream provider and see if that works.

I wrote cf gateway doh for testing. The test command is the same as here, but the results are different   https://private-user-images.githubusercontent.com/17548936/311438358-de8da194-c9bf-4cd8-946d-30b1ad804311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODY1NDEsIm5iZiI6MTcxMDY4NjI0MSwicGF0aCI6Ii8xNzU0ODkzNi8zMTE0MzgzNTgtZGU4ZGExOTQtYzliZi00Y2Q4LTk0NmQtMzBiMWFkODA0MzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0MzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjVhYTcwNmExNzExNjExMWY2ZTczY2VjNWViNmFhNDUzMmQ5MWJhMjhmNmU2M2M3ZTBlZTYzMTIxMzI1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kRhjotwkEZuVVdZUYH_qnc08YhFBoNP0r8o7PfnCo3k

**Comment by liang-hiwin** [comment]
```
  "Question": [
    {
      "Name": "www.taobao.com",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [
    {
      "Name": "www.taobao.com",
      "Type": "CNAME",
      "Class": "IN",
      "TTL": "600 (10 mins)",
      "RDLENGTH": "33 bytes",
      "RDATA": {
        "Domain": "www.taobao.com.danuoyi.tbcache.com"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "www.taobao.com.danuoyi.tbcache.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "60 (1 min)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "218.77.200.194"
      },
      "DnssecStatus": "Disabled"
    },
    {
      "Name": "www.taobao.com.danuoyi.tbcache.com",
      "Type": "A",
      "Class": "IN",
      "TTL": "60 (1 min)",
      "RDLENGTH": "4 bytes",
      "RDATA": {
        "IPAddress": "218.77.200.195"
      },
      "DnssecStatus": "Disabled"
    }
  ],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": "1232",
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}
```

**Comment by ShreyasZare** [comment]
> > > > > Great job, the parsing results are the same after the update.
> > > > 
> > > > 
> > > > I am not sure what is the reason for this. It does work though if you try with something like Google DNS. You can do the same tests using the dnsclient.net website (which is hosted outside your country) to see if that works from another location.
> > > 
> > > 
> > > The results are different, the position deviation is very large.
> > 
> > 
> > The response is generated by the upstream server so there is nothing that can be done from the client side in this case. Try using a different upstream provider and see if that works.
> 
> I wrote cf gateway doh for testing. The test command is the same as here, but the results are different https://private-user-images.githubusercontent.com/17548936/311438358-de8da194-c9bf-4cd8-946d-30b1ad804311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODY1NDEsIm5iZiI6MTcxMDY4NjI0MSwicGF0aCI6Ii8xNzU0ODkzNi8zMTE0MzgzNTgtZGU4ZGExOTQtYzliZi00Y2Q4LTk0NmQtMzBiMWFkODA0MzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0MzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjVhYTcwNmExNzExNjExMWY2ZTczY2VjNWViNmFhNDUzMmQ5MWJhMjhmNmU2M2M3ZTBlZTYzMTIxMzI1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kRhjotwkEZuVVdZUYH_qnc08YhFBoNP0r8o7PfnCo3k

The image is not loading here. Try to upload it again.

I am not sure what the test command you use is doing. The DNS Server is sending ECS option in the request but the response does not have ECS for your case for some reason.

**Comment by ShreyasZare** [comment]
> ```
>   "Question": [
>     {
>       "Name": "www.taobao.com",
>       "Type": "A",
>       "Class": "IN"
>     }
>   ],
>   "Answer": [
>     {
>       "Name": "www.taobao.com",
>       "Type": "CNAME",
>       "Class": "IN",
>       "TTL": "600 (10 mins)",
>       "RDLENGTH": "33 bytes",
>       "RDATA": {
>         "Domain": "www.taobao.com.danuoyi.tbcache.com"
>       },
>       "DnssecStatus": "Disabled"
>     },
>     {
>       "Name": "www.taobao.com.danuoyi.tbcache.com",
>       "Type": "A",
>       "Class": "IN",
>       "TTL": "60 (1 min)",
>       "RDLENGTH": "4 bytes",
>       "RDATA": {
>         "IPAddress": "218.77.200.194"
>       },
>       "DnssecStatus": "Disabled"
>     },
>     {
>       "Name": "www.taobao.com.danuoyi.tbcache.com",
>       "Type": "A",
>       "Class": "IN",
>       "TTL": "60 (1 min)",
>       "RDLENGTH": "4 bytes",
>       "RDATA": {
>         "IPAddress": "218.77.200.195"
>       },
>       "DnssecStatus": "Disabled"
>     }
>   ],
>   "Authority": [],
>   "Additional": [
>     {
>       "Name": "",
>       "Type": "OPT",
>       "Class": "1232",
>       "TTL": "0 (0 sec)",
>       "RDLENGTH": "0 bytes",
>       "RDATA": {
>         "Options": []
>       },
>       "DnssecStatus": "Disabled"
>     }
>   ]
> }
> ```

The output is incomplete but the OPT record does not have any options so there is ECS option missing in response.

If you can share your DoH endpoint URL privately over email to support then I can test it again from my location and see what output it gives.

**Comment by liang-hiwin** [comment]
Sent to gmail.com

**Comment by liang-hiwin** [comment]
> > ```
> >   "Question": [
> >     {
> >       "Name": "www.taobao.com",
> >       "Type": "A",
> >       "Class": "IN"
> >     }
> >   ],
> >   "Answer": [
> >     {
> >       "Name": "www.taobao.com",
> >       "Type": "CNAME",
> >       "Class": "IN",
> >       "TTL": "600 (10 mins)",
> >       "RDLENGTH": "33 bytes",
> >       "RDATA": {
> >         "Domain": "www.taobao.com.danuoyi.tbcache.com"
> >       },
> >       "DnssecStatus": "Disabled"
> >     },
> >     {
> >       "Name": "www.taobao.com.danuoyi.tbcache.com",
> >       "Type": "A",
> >       "Class": "IN",
> >       "TTL": "60 (1 min)",
> >       "RDLENGTH": "4 bytes",
> >       "RDATA": {
> >         "IPAddress": "218.77.200.194"
> >       },
> >       "DnssecStatus": "Disabled"
> >     },
> >     {
> >       "Name": "www.taobao.com.danuoyi.tbcache.com",
> >       "Type": "A",
> >       "Class": "IN",
> >       "TTL": "60 (1 min)",
> >       "RDLENGTH": "4 bytes",
> >       "RDATA": {
> >         "IPAddress": "218.77.200.195"
> >       },
> >       "DnssecStatus": "Disabled"
> >     }
> >   ],
> >   "Authority": [],
> >   "Additional": [
> >     {
> >       "Name": "",
> >       "Type": "OPT",
> >       "Class": "1232",
> >       "TTL": "0 (0 sec)",
> >       "RDLENGTH": "0 bytes",
> >       "RDATA": {
> >         "Options": []
> >       },
> >       "DnssecStatus": "Disabled"
> >     }
> >   ]
> > }
> > ```
> 
> The output is incomplete but the OPT record does not have any options so there is ECS option missing in response.
> 
> If you can share your DoH endpoint URL privately over email to support then I can test it again from my location and see what output it gives.

Hello, I have to ask again, there is indeed a problem with ecs.

The test through the DNS Client that comes with the program is normal, but the test using dig is not normal. The following are the test results.

I set the value of Cache Minimum TTL to 10, and ecs is now normal. If this value is set too long, different subnet IPs will have the same result through dig test.

**Comment by ShreyasZare** [comment]
> Hello, I have to ask again, there is indeed a problem with ecs.

> I set the value of Cache Minimum TTL to 10, and ecs is now normal. If this value is set too long, different subnet IPs will have the same result through dig test.

The Cache Minimum TTL value does not have any interaction with ECS. It just sets the minimum value for the records in cache. Any difference you saw in your tests are just coincidences.
