### ISSUE TITLE
Pac File Question

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#785]
Hi How exactly would I point my DHCP Clients to a pac file?

Say my pac files is at http://10.0.0.1/proxy.pac

Not an issues just a question.

kind regards

**Comment by Hemsby** [comment]
If Im not mistaken you would do it like this.  I have used your path in my example.
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/36005402/afc20859-7db2-4023-88ec-34975d8cfd17)

The other option is to use DNS and just create an A Record with the hostname WPAD and set the IP to 10.0.0.1.

The WPAD protocol uses DHCP or DNS to locate the PAC file. The browser used in endpoints search for a web server on startup to find information on the PAC file location. The web browser sends the local DHCP server a query to find the PAC file location. If the proxy auto discovery is not successful with DHCP, the browser then uses DNS to detect the PAC file location.

**Comment by ChristoffBo** [comment]
Hi Thank you.

My address for the pac file is actuallt http://10.0.0.100:8080/media/proxy.pac

it wont let me add it into an a record. 

but i did as above and converted my url to a hex string. will give it some time and see what happens.

Thank you sir.
