### ISSUE TITLE
Clear all activity on dashboard

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#79]
Please consider adding the ability to clear all activity on the dashboard; maybe a button in settings.

Related Question: is flushing the cache the equivalent of this?

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I can add delete stats option that will delete stats for the current scope from disk. This will be permanent deletion.

Cache Flush is entirely different option. Cache is completely in memory and is lost when server restarts. Flushing option allows clearing cache if its needed for testing purposes without requiring server restart.

**Comment by ShreyasZare** [comment]
DNS server version 5.6 adds delete all stats option in Logs tab.
