### ISSUE TITLE
Nested wildcards not handled properly

### ISSUE THREAD

**Issue by SivaKesava1** [TechnitiumSoftware/DnsServer#794]
Hello,

I think this relates to some of the prior issues I filed earlier but want to make sure there is a simple example to follow. 

Consider the zone file:
```
test.     500     IN      SOA     ns1.outside.edu. root.campus.edu. 3 6048 4000 2419200 6048
test.     500     IN      NS      ns1.outside.edu.
*.test.   500     IN      A       11.1.1.1
*.*.test. 500     IN      A       12.2.2.2
```

For the query `foo.*.test`, the Technitium server returns `11.1.1.1`, but ideally it should return the `12.2.2.2` address. 

Detail description of wildcard closest encloser can be found in the RFC - https://www.rfc-editor.org/rfc/rfc4592#section-2.2.1

Thanks,
Siva

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that fixes this issue. Do update and let me know your feedback.
