### ISSUE TITLE
recursion allowed with NO DATA plugin?

### ISSUE THREAD

**Issue by bcookatpcsd** [TechnitiumSoftware/DnsServer#797]
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/11a16cbf-507c-4c84-8ee2-f2adfabbec47)

only the pixelated host is allowed to relay.. 

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/f30f4820-e029-4020-8028-9ea7eb9b4a02)

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/7d149078-8f4c-4f1f-a7b0-d6ca7053428d)

Going to disable the plugin.. 

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/483f7b70-f0e6-476a-afeb-e25fcf217fac)

Is there a configuration problem? 

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/55087301/af62eb91-81f7-416c-9a75-91e67f0e9afb)

Thank you in advance..

**Comment by ShreyasZare** [comment]
Thanks for the details. I tested with the same config you have and its working as expected. The `ServerFailure` responses you see are probably not related to the APP record. 

Do check the DNS logs for any errors which should give better idea as to why there was ServerFailure response. Post any errors you see in the logs here.
