### ISSUE TITLE
[Bug] DNS-Over-QUIC not work in debian12

### ISSUE THREAD

**Issue by lrinQVQ** [TechnitiumSoftware/DnsServer#798]
Hey
In the latest releases/develop branch , DNS Over QUIC can not work normally
OS: Debian 12
Log:

> [QUIC] System.OperationCanceledException: The operation was canceled.
>    at System.Net.Quic.ValueTaskSource.TryComplete(Exception exception)
>    at System.Net.Quic.ValueTaskSource.<>c.<TryInitialize>b__10_0(Object obj, CancellationToken cancellationToken)
>    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
>    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
>    at System.Threading.TimerQueue.FireNextTimers()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> --- End of stack trace from previous location ---
>    at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Quic.QuicListener.PendingConnection.StartHandshake(QuicConnection connection, SslClientHelloInfo clientHello, Func`4 connectionOptionsCallback)
>    at System.Net.Quic.QuicListener.PendingConnection.DisposeAsync()
>    at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)
>    at DnsServerCore.Dns.DnsServer.AcceptQuicConnectionAsync(QuicListener quicListener) in /root/TechnitiumSoftware/DnsServer/DnsServerCore/Dns/DnsServer.cs:line 723

**Comment by ShreyasZare** [comment]
Thanks for the details. I am running DoQ on Debian 11 and is working fine. If possible, do try on another distro and see if that is working. Note that QUIC is quite nascent protocol and thus the libraries (libmsquic) may still have issues on some platforms.
