### ISSUE TITLE
Blacklisting

### ISSUE THREAD

**Issue by ScriptTiger** [TechnitiumSoftware/DnsServer#8]
Feature request to directly support importing/linking static and dynamic blacklists containing wild cards and REGEX rather than simply manually creating A records with black hole addressing.

As far as clear development goals, the minimum request here would be to first add at least an easy way to import/link a static list of A records that can be used for black hole addressing. The complete feature goal would be total support for importing/linking blacklists containing wild cards and REGEX.

I would also say the open-source Privoxy project offers a lot in the way of ready-to-go REGEX blocking. Since Privoxy is a proxy server and not a DNS server, it obviously has full URL path REGEX, but those REGEX strings applying to only fully qualified domain names can be easily filtered out and would be a good place to start.

I'll also plug Steven Black's Hosts repo as a good example for static blocking, which is used by Paul Vixie, one of the authors to the DNS RPZ standard (https://github.com/StevenBlack/hosts/issues/451 ):
https://github.com/StevenBlack/hosts
The hosts file format is simply the oldest and most common format accepted by the widest range of software and devices, but the project can be easily converted to other formats, as well, including, hopefully, a format that works best with the Technitium DNS server:
https://scripttiger.github.io/alts/

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will try to implement this in next release.

**Comment by ScriptTiger** [comment]
Just as an added note if it applies, I'm not sure if it will, but the Steven Black repo is also in the early stages of implementing commented wild cards (https://github.com/StevenBlack/hosts/pull/490). We have also discussed commented REGEX, but we will just stick to wild cards for now. So a small portion of the Steven Black hosts files can be converted to dynamic blacklisting, as well, should you decide to use it.
