### ISSUE TITLE
Auto Cleanup of old+unused blocklists in "config\blocklists"

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#80]
Please consider adding auto-clean up of old+unused blocklists, that are download into: _config\blocklists_

Currently from what I can tell unused lists stay and take up space.

From my testing I added an 8MB text list. Then decided to remove it from the block lists.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. This is really a feature to keep copy of block list downloaded from a url with file name as a hash of the url. This allows DNS Server to load the block list even when the url fails to download a new list. The file is not removed to allow using it again if same url is used.

**Comment by hl2guide** [comment]
ah ok, thanks for clearing that up 💃

**Comment by ShreyasZare** [comment]
welcome :) closing the issue.
