### ISSUE TITLE
[Bug] "Enabling" DNSSEC on a zone with APP records

### ISSUE THREAD

**Issue by Tivin-i** [TechnitiumSoftware/DnsServer#801]
I tried to click on "Sign zone" on a zone with APP records, to which I get the error that you can't sign APP records - understandable.

However, it did create RRSIG records for the unique name TXT records (_dmarc,x._domainkey).
These do not have the option to be removed, and I can't see to query it, meaning the records don't actually exist outside the UI?

![CleanShot 2023-12-07 at 21 46 17](https://github.com/TechnitiumSoftware/DnsServer/assets/53348536/1e3564f1-0fbf-46bb-9989-fd9ed57076e8)

**Comment by ShreyasZare** [comment]
Thanks for reporting this. Will get this tested and fixed.

Meanwhile, try to restart the DNS server and see if those RRSIG records go away. If they are still there then other option to remove them is to export the zone using the Options > Export Zone menu, edit the exported zone file to remove the RRSIG records, and then import them into a new zone that is created after deleting the old one. Note to take a backup from the Setting > Backup Settings option just in case there is any issue.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that fixes this issue. Do update and let me know your feedback.
