### ISSUE TITLE
Resolver exception

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#803]
```
[
  {
    "name": "r5---sn-i3b7knld.googlevideo.com",
    "type": "A",
    "ttl": "0 (0 sec)",
    "rData": {
      "dataType": "DnsSpecialCacheRecordData",
      "data": "FailureCache: ServerFailure; Other: Resolver exception for r5---sn-i3b7knld.googlevideo.com. A IN: The SSL connection could not be established, see inner exception."
    },
    "dnssecStatus": "Unknown",
    "eDnsClientSubnet": "113.87.50.0/24",
    "lastUsedOn": "0001-01-01T00:00:00"
  },
  {
    "name": "r5---sn-i3b7knld.googlevideo.com",
    "type": "CNAME",
    "ttl": "0 (0 sec)",
    "rData": {
      "cname": "r5.sn-i3b7knld.googlevideo.com"
    },
    "dnssecStatus": "Disabled",
    "eDnsClientSubnet": "0.0.0.0/0",
    "lastUsedOn": "0001-01-01T00:00:00"
  }
]

```

Is this a problem?  ```FailureCache: ServerFailure; Other: Resolver exception for r5---sn-i3b7knld.googlevideo.com. A IN: The SSL connection could not be established, see inner exception.```

**Comment by liang-hiwin** [comment]
> Thanks for the post. This error suggest that you are using encrypted DNS protocol with forwarder and that the connection failed to establish. Any resolution failure gets cached this way and the DNS server will retry only once the failure cache record expires.

The network is normal, why is this prompt displayed?

**Comment by ShreyasZare** [comment]
> The network is normal, why is this prompt displayed?

The error exists because there was some issue with network. A more detailed error log would be available in the DNS logs that will explain the reason in more details. Do check if there are any error logs related to this.

**Comment by liang-hiwin** [comment]
> > The network is normal, why is this prompt displayed?
> 
> The error exists because there was some issue with network. A more detailed error log would be available in the DNS logs that will explain the reason in more details. Do check if there are any error logs related to this.

There is no network error message in the log.

**Comment by ShreyasZare** [comment]
> There is no network error message in the log.

Check if you have "Ignore Resolver Error Logs" option enabled in Settings > Logging section. This option will prevent from logging such resolver errors.

**Comment by liang-hiwin** [comment]
> > There is no network error message in the log.
> 
> Check if you have "Ignore Resolver Error Logs" option enabled in Settings > Logging section. This option will prevent from logging such resolver errors.

I have unchecked it, I will post the log again when problems arise.
