### ISSUE TITLE
(not an issue - simple question): REGEX

### ISSUE THREAD

**Issue by EstherMoellman** [TechnitiumSoftware/DnsServer#81]
Hi!

I'm interested on @hl2guide (Dean) project (https://github.com/hl2guide/All-in-One-Customized-Adblock-List), which tries to build an ad-tracker-etc-blocker using your DnsServer. He (@hl2guide Dean) already was in contact with you: https://github.com/TechnitiumSoftware/DnsServer/issues/59). This project seems fantastic to me in terms of browser performance point of view.

Please, I have two simple questions:

1) I know your DnsServer' block-lists/zones allow wildcards. But what about REGEX? If not, please can you consider the possibility of this feature? I'm not an expert, but in my humble opinion, if REGEX can be used, then your DnsServer might be the best ad-tracker-etc-blocker in the market.

2) Today I'm using SimpleDSNCrypt to encrypt DNS while blocking garbage (ads, tracking etc). It allows wildcards but not REGEX. Comparing your DnsServer VS SimpleDNSCrypt, by chance do you know which one will be better in terms of browser or system performance (RAM, CPU etc)? The idea is to have both: The best performance browser/system tool + REGEX.

Thanks in advance!

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

Ya, the server currently supports using block lists (hosts files) with wildcard support. Regex is not supported but I can plan for it. The only issue with regex that I can think of as of now is that it has potential to hit the server's performance as the server will need to check each query against the entire list of regex rules. I will however try to measure performance hit before implementing it.

I have not used SimpleDNSCrypt but just tried it for a few mins in a VM. It seems to be a good DNS proxy but the domain name blocking rule didn't work when I tried. The UI didn't have any option to manage blocking domains apart from a button to block a domain from the query logs. I am not sure about its performance as I have not used it.

For DNS Server that I am using on my Raspberry Pi 3 at home, it currently has 111,032 domain names blocked using multiple block lists. It takes around ~350MB of memory as it keeps all the data in memory and responds within ~10ms over WiFi network. It would work much faster if installed on laptop/desktop as Raspberry Pi has low powered CPU. DNS Server also has advance caching features like serve stale, prefetching and auto prefetching that improves performance and stability. It does not support DNSCrypt though but supports DNS-over-HTTPS and DNS-over-TLS for forwarders which are quite popular now. By default it does recursive resolution by itself when no forwarder is configured.

You can try both and see which performs better for your setup.

**Comment by EstherMoellman** [comment]
@ShreyasZare thanks for your answer... and congrats for DnsServer.

Today I gave it a try, my first time, zero previous reading... installation was perfect, no problems at all, simple, clean and quick.
I took a general view of the UI, lot of stuff I saw I have no knowledge about it (so I didn't touch it), and basically I used default settings. I installed it just for a simple test, so I was not so interested at this moment in the settings/options. I will wait @hl2guide (Dean)' tutorial, in order to make optimal configurations.
But it was very easy to upload blocking list, and my own blocking list.

DnsServer' performance is very good.
SimpleDNSCrypt has better performance, but it has not all the options DnsServer has.
Tomorrow I will continue doing more performance tests.

So in general, DnsServer is very very nice... congrats!

If you find a way to incorporate REGEX' capabilities without hurting performance, it will be great.
And also it will be fantastic if in the near future DnsServer can support DNSCrypt.

If there is something I can do for help, count with me!

Thank you!

**Comment by ShreyasZare** [comment]
> @ShreyasZare thanks for your answer... and congrats for DnsServer.
> 
> Today I gave it a try, was my first time, zero previous reading/instructions... installation was perfect, no problems at all, simple, clean and quick (no computer restart was needed).
> I took a general view of the UI, lot of stuff I saw I have no knowledge about it (so I didn't touch it), and basically I used default settings. I installed it just for a simple test, so I was not so interested at this moment in the settings/options. I will wait @hl2guide (Dean)' tutorial, in order to make optimal configurations.
> But it was very easy to upload blocking list, and my own blocking list.
> 
> DnsServer' performance is very good.
> SimpleDNSCrypt has better performance, but it has not all the options DnsServer has.
> Tomorrow I will continue doing more performance tests.
> 
> So in general, DnsServer is very very nice... congrats!

Thank you for the compliments. Easy of use was one of the first thing I had in mind while building this server. It was designed to be easy to install and work with zero configurations.

There are many options you get, but do try the forwarders settings if you wish to encrypt DNS traffic.

Do let me know results of your performance tests. It will be useful for me to improve the software.

> If you find a way to incorporate REGEX' capabilities without hurting performance, it will be great.
> And also it will be fantastic if in the near future DnsServer can support DNSCrypt.
> DnsServer has the potential to be the best blocker in the market.
> 
> If there is something I can do for helping you, count on me!
> 
> Thank you!

There are lot of features in pipeline for the server. Will try to get regex in a few months as a couple of major features are added. 

Do let me know your feedback or feature requests that you think would be useful.

**Comment by EstherMoellman** [comment]
Hi @ShreyasZare ,

Step by step, I'm going deeper and deeper over DnsServer, reading more stuff, testing more different settings, and specially testing blocking lists.

DnsServer' performance (browsing speed) improved a lot when I changed to cloudflare, reducing latency.
But RAM continues high (800MB for a 4.4MB blocking list), DNSCrypt uses just 40MB for the same list. RAM is not really an issue for me, because I have plenty, but it may be an issue for users with low RAM. In the other hand, uploading all the data into memory... is a plus for DnsServer, because it can be faster. It is a kind of trade, it consumes much more RAM, but at the same time it can be faster.

I hope in the future you will be able to add REGEX, because this will dramatically reduce the size of the blocking lists, reducing DnsServer' RAM consumption.

Instead REGEX, I tried to use wildcards ("*", "?", "/"), but DnsServer rejected my lists with wildcards. I didn't find documentation, so I don't know where I can read about DnsServer' wildcards. Please, can you help me here? Can you tell me where I can read about DnsServer' wildcards? What are the DnsServer' rules for wildcards?

Thank you!

**Comment by ShreyasZare** [comment]
> DnsServer' performance (browsing speed) improved a lot when I changed to cloudflare, reducing latency.

By default, the DNS Server does recursive resolution on its own. That means, when you query for google.com, its going to find out name servers for google.com and then ask those servers for records. This means for each domain name, it has to find and query their respective servers and if the servers are located geographically far away then there will be added delays due to the distance.

All, ISP DNS Servers and public resolvers like Cloudflare do the same the only difference is that due to large number of users querying them, they have most of the common domain names in cache already and thus it seems that these servers respond quickly. Thus you get good performance when you configure DNS server with forwarders.

If you keep Technitium DNS Server running 24x7 on network then after a few days, it too would have cached most common domain names used on the network and you will get better performance than when the server's cache is empty.

> But RAM continues high (800MB for a 4.4MB blocking list), DNSCrypt uses just 40MB for the same list. RAM is not really an issue for me, because I have plenty, but it may be an issue for users with low RAM. In the other hand, uploading all the data into memory... is a plus for DnsServer, because it can be faster. It is a kind of trade, it consumes much more RAM, but at the same time it can be faster.

The initial RAM usage will be high and after some time, the .NET process will do garbage collection and the memory usage will go down to 300-400MB levels. 

As you figured it out, the server keeps data in RAM so that its readily available and provides high performance. Considering how much RAM web browsers like Google Chrome or Firefox use just with a few tabs open, the DNS Server's RAM usage looks modest!

> I hope in the future you will be able to add REGEX, because this will dramatically reduce the size of the blocking lists, reducing DnsServer' RAM consumption.

True, but you would still need to use block lists in current format since creating REGEX is easier said than done. It can potentially block too many domain names that were not really indented to be blocked.

> Instead REGEX, I tried to use wildcards ("*", "?", "/"), but DnsServer rejected my lists with wildcards. I didn't find documentation, so I don't know where I can read about DnsServer' wildcards. Please, can you help me here? Can you tell me where I can read about DnsServer' wildcards? What are the DnsServer' rules for wildcards?

The DNS Server currently supports wildcard only for sub domain names. So, you can create something like "\*.example.com" but not "w\*.example.com". Only "*" character is recognized.

**Comment by EstherMoellman** [comment]
... fantastic explanation @ShreyasZare ... I loved it! Thank you.
Yeah, most of your explanations, yesterday I already realized by my own. But today was great to read your teachings, because you confirmed my conclusions. Yesterday I just had "wild guesses", but today I have "confirmations" thanks to your explanations.

Please @ShreyasZare , two more things:

1) Just to be clear, and correct me if I am wrong: DnsServer doesn't accept all wildcards, right? It just accepts "*" (asterisk - I write the word because GitHub is not accepted the symbol), right? And also, it accepts asterisk in a limited way, right? (sub domains)... the only wildcard DnsServer accepts is asterisk at "asterisk.YYYYYYY.ZZZ", right? So, no "asteriskYYYY", nor "YYYYasterisk", nor "asteriskYYYYasterisk", nor "YYYYY.asterisk" etc, right? DnsServer' wildcard works only for sub domains, not for words, right? For example, I can't block "asteriskads*" for any domain, right? (asteriskads, adsasterisk, asteriskadsasterisk etc)
In the other hand, DnsServer doesn't need wildcard to block "XXX.example.com", just "example.com" will be enough and will include everything, right?
Here I am confused, because it is not clear what wildcard I can use, where, etc. Please, if you can, help me.

2) Considering that I am not an expert, and I tend to use DnsServer' default settings because I have no idea what the other settings are, I wonder if you can share with me other "tweaks" (changes to default settings) where I can have potential performance gains. For example, as I mentioned you yesterday, by changing to cloudfllare instead default settings, I gain a lot of DnsServer' performance... do you have any other simple tweaks like this, where I can gain more performance?

I apologize for abusing from your time and patience.
I did my homework, I read DnsServer' documentation & articles, but the language of some explanations is behind my knowledge, behind my user-level, "too techy" for me. It is not a problem with the English. It is a problem that I don't understand many tech terminologies at DnsServer' documentation.
I totally agree that DnsServer is a kind of "plug-and-play" even for newbies. It doesn't require any tech knowledge. However, dealing with DnsServer' settings and documentation, in my opinion is not so easy for average users like me.

So, if you can help me, it will be great!
But if you can't help me, please, don't worry at all, it is fine, I perfectly understand.

Thanks in advance! :)

PS1: REGEX for trackers, you're right, it is not enough and normally demands a blocking-list addition. But REGEX for ads, believe me, simple few REGEX' rules are able to block 80% of ads garbage. So for ads, REGEX are incredible efficient, and makes ad-blocking-lists to have a microscopic size. I still hope that in the future DnsServer will able to handle. Or at least, it will great if DnsServer can handle more wildcards ("?", "/" etc).

PS2: Feel free to close the issue if you want.

**Comment by ShreyasZare** [comment]
> ... fantastic explanation @ShreyasZare ... I loved it! Thank you.
> Yeah, most of your explanations, yesterday I already realized by my own. But today was great to read your teachings, because you confirmed my conclusions. Yesterday I just had "wild guesses", but today I have "confirmations" thanks to your explanations.

You're welcome :)
 
> Please @ShreyasZare , two more things:
> 
>     1. Just to be clear, and correct me if I am wrong: DnsServer doesn't accept all wildcards, right? It just accepts "_" (asterisk - I write the word because GitHub is not accepted the symbol), right? And also, it accepts asterisk in a limited way, right? (sub domains)... the only wildcard DnsServer accepts is asterisk at "asterisk.YYYYYYY.ZZZ", right? So, no "asteriskYYYY", nor "YYYYasterisk", nor "asteriskYYYYasterisk", nor "YYYYY.asterisk" etc, right? DnsServer' wildcard works only for sub domains, not for words, right? For example, I can't block "asteriskads_" for any domain, right? (asteriskads, adsasterisk, asteriskadsasterisk etc)
>        In the other hand, DnsServer doesn't need wildcard to block "XXX.example.com", just "example.com" will be enough and will include everything, right?
>        Here I am confused, because it is not clear what wildcard I can use, where, etc. Please, if you can, help me.

You have got it right. The wildcard support exists just because block list use the same zone code that is used to host domain names. In a zone, you can create an type A record entry with \* and set an IP address which will work for any sub domain name. Thus, if you block \*.example.com then you will be able to access example.com but all sub domains will be blocked, which is not really much useful feature in current form.

>     2. Considering that I am not an expert, and I tend to use DnsServer' default settings because I have no idea what the other settings are, I wonder if you can share with me other "tweaks" (changes to default settings) where I can have potential performance gains. For example, as I mentioned you yesterday, by changing to cloudfllare instead default settings, I gain a lot of DnsServer' performance... do you have any other simple tweaks like this, where I can gain more performance?

You can use forwarders option to use Cloudflare or Google DNS and that will give you good performance if your DNS Server is not running 24x7. I personally use the default mode that does recursion by itself and it gives almost similar performance as I run the DNS Server 24x7 on my Raspberry Pi connected to the router.

> I apologize for abusing from your time and patience.
> I did my homework, I read DnsServer' documentation & articles, but the language of some explanations is behind my knowledge, behind my user-level, "too techy" for me. It is not a problem with the English. It is a problem that I don't understand many tech terminologies at DnsServer' documentation.
> I totally agree that DnsServer is a kind of "plug-and-play" even for newbies. It doesn't require any tech knowledge. However, dealing with DnsServer' settings and documentation, in my opinion is not so easy for average users like me.

True, there are many technical concepts that are required to change the settings. Some settings are easy and some require a bit in-depth understanding. The only difference here is that you can see what the settings are in a friendly GUI rather than some complex config file which most users would not be able to even open in a text editor. That said, the documentation for DNS Server will get updated as I get time and eventually will cover most options in settings.

> So, if you can help me, it will be great!
> But if you can't help me, please, don't worry at all, it is fine, I perfectly understand.
> 
> Thanks in advance! :)
> 
> PS1: REGEX for trackers, you're right, it is not enough and normally demands a blocking-list addition. But REGEX for ads, believe me, simple few REGEX' rules are able to block 80% of ads garbage. So for ads, REGEX are incredible efficient, and makes ad-blocking-lists to have a microscopic size. I still hope that in the future DnsServer will able to handle. Or at least, it will great if DnsServer can handle more wildcards ("?", "/" etc).

True. Wont be an issue for use with personal or home network. But it will block any website which contains "ads" in its name and so may not be suitable for large networks where users wont be able to update the settings when a website is blocked.

> PS2: Feel free to close the issue if you want.

We can keep this issue open till I explore the regex feature.

**Comment by ShreyasZare** [comment]
New version 7.0 is now available with a new Advanced Blocking DNS App that support blocking using REGEX.

**Comment by EstherMoellman** [comment]
@ShreyasZare this is a great, great... great news! Congrats and thanks for messaging me.
I'll test again your DnsServer.
It's been a while since our last conversation (Aug 2019). I have a lot of reread in your Wiki. But in a very quick search I couldn't find any explanation about REGEXPs. Sorry if that was my fault, and sorry for bothering you, but please could you tell me where I can read about DnsServer & REGEXPs? If there is no tutorial, please can you write me very few lines just explaining the basic of how to use REGEXPs with DenServer?
Thank in advance!

**Comment by ShreyasZare** [comment]
> 
> 
> @ShreyasZare this is a great, great... great news! Congrats and thanks for messaging me. 

You're welcome.

> I'll test again your DnsServer. It's been a while since our last conversation (Aug 2019). I have to update myself by rereading your Wiki. But in a very quick search I couldn't find any explanation about REGEXPs. Sorry if that was my fault, and sorry for bothering you, but please could you tell me where I can read about DnsServer & REGEXPs? If there is no tutorial, please can you write me very few lines just explaining the basic of how to use REGEXPs with DenServer? Thank you in advance!

There is no documentation available for these new features yet. I will try to guide you in brief. Just get the latest version installed, go to Apps tab, and install Advanced Blocking app from the DNS App Store. Once you have that app installed, click on the Config button which will show the app's config in json format.

The json config allows you to define one or more groups and then configure options for each group. Use the `networkGroupMap` array to map an IP address or a network address to a group name that you have created. You can map multiple IP addresses or network addresses to a single group too.

In the group json object, you can define the `blockedRegex` with multiple patterns. Since this pattern is inside a json value, you will need to escape '\' character in the regex. If you have too many regex patterns, then its best to put all of them in a text file, put the text file on a web server or use the DNS web panel's web server and put its url in the `regexBlockListUrls` array which will auto update itself with `blockListUrlUpdateIntervalHours` frequency.

Do let me know if you have any queries with getting the config to work.

**Comment by EstherMoellman** [comment]
Hi @ShreyasZare,

Today I started to test your wonderful Technitium DnsServer for wildcards and Regex.
Long time ago I mentioned to you that I'm using DNSCrypt. And it has a Wiki with instructions explaining almost every step, setting, configuration etc... so I can follow it. DNSCrypt works with wildcards, but unfortunately it doesn't work with Regex. That's the main reason I'm interested on your DnsServer.
The big problem is my ignorance, I have a very basic knowledge about dns servers, so I wasn't capable to configure your DnsServer.

[Here you can see](https://pastebin.com/GxX4ZZXf) a list with a mix of wildcards and regex I would like to test on your DnsServer (I want to block these regex and domains with wildcards in the attached list).
I don't know if it is easy or complicated to test on your DnsServer. But if it is easy, then please I ask you to help me.
I already installed the Apps tab => Advanced Blocking app. And I can see the Config button => app's config in json format. I just don't know how to insert my wildcards and regex to be blocked by DnsServer.

@ShreyasZare, if you can't help me... don't worry!, I understand.
Thank you anyway

**Comment by ShreyasZare** [comment]
> [Here you can see](https://pastebin.com/GxX4ZZXf) a list with a mix of wildcards and regex I would like to test on your DnsServer (I want to block these regex and domains with wildcards in the attached list). I don't know if it is easy or complicated to test on your DnsServer. But if it is easy, then please I ask you to help me. I already installed the Apps tab => Advanced Blocking app. And I can see the Config button => app's config in json format. I just don't know how to insert my wildcards and regex to be blocked by DnsServer.
> 
> @ShreyasZare, if you can't help me... don't worry!, I understand. Thank you anyway

Thanks for asking. The regex implementation in the DNS server is based on .NET and thus I would recommend you to check this [quick reference guide](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference). The wildcard character (*) in regex has a different meaning than the one expected for matching a domain name so you need to create a regex pattern that mimics the wildcard matching correctly.

The easier way is to create a text file that lists all the regex like you have in that paste bin. Put the file in the `www` folder on the DNS server and then access it from the DNS server's web service using like this `http://localhost:5380/my-regex.txt`. Use this local URL to configure as the `regexBlockListUrls` in the Advanced Blocking app's config.

The benefit of using the above method is that you don't have to escape the regex pattern to put it in the json config which can be very tedious. And it becomes easier to update the text file independently and also share it between multiple DNS server instances.

**Comment by dannykorpan** [comment]
Any updates on regex support as PiHole does?

**Comment by ShreyasZare** [comment]
> Any updates on regex support as PiHole does?

There is already support for regex which you can use with the Advanced Blocking app.

**Comment by dannykorpan** [comment]
Yes, thank you, but the Advanced Blocking app has several disadvantages like not working collected block lists, disabling blocking for a specific time etc.

**Comment by ShreyasZare** [comment]
> Yes, thank you, but the Advanced Blocking app has several disadvantages like not working collected block lists, disabling blocking for a specific time etc.

I did not get the meaning for "collected block lists", can you elaborate it? 

Yes, there is no option to stop blocking temporary for given time in the app. This option is available if you use the blocking feature that is built in the DNS server though.

**Comment by dannykorpan** [comment]
> > Yes, thank you, but the Advanced Blocking app has several disadvantages like not working collected block lists, disabling blocking for a specific time etc.
> 
> I did not get the meaning for "collected block lists", can you elaborate it?
> 
> Yes, there is no option to stop blocking temporary for given time in the app. This option is available if you use the blocking feature that is built in the DNS server though.

https://github.com/TechnitiumSoftware/DnsServer/issues/600

**Comment by ShreyasZare** [comment]
> > > Yes, thank you, but the Advanced Blocking app has several disadvantages like not working collected block lists, disabling blocking for a specific time etc.
> > 
> > 
> > I did not get the meaning for "collected block lists", can you elaborate it?
> > Yes, there is no option to stop blocking temporary for given time in the app. This option is available if you use the blocking feature that is built in the DNS server though.
> 
> #600

For that I already provided you with a solution to use a bash script to perform automation using the HTTP API.
