### ISSUE TITLE
Domains show as blocked in Top Blocked Domains but blocking disabled

### ISSUE THREAD

**Issue by CartCaved** [TechnitiumSoftware/DnsServer#810]
I'm trying out technitium, great piece of software so far!

However, I'm having a strange issue with blocking. I have blocking disabled under Settings, Blocking, Enable Blocking unchecked. There are also nothing under Allow/Block List URLs or anything else set on that page, except Allow TXT Blocking Report checked.

I'm still seeing eight domains on the dashboard, Top Blocked Domains widget. Does it mean they are blocked or can they end up on the list for any other reason. If they are blocked, how can I find the reason for that and unblock them. Or is it a bug?

**Comment by alexhorner** [comment]
I also noticed this. @ShreyasZare Is the trigger condition for this detection the upstream server returning `0.0.0.0`?

**Comment by ShreyasZare** [comment]
> I also noticed this. @ShreyasZare Is the trigger condition for this detection the upstream server returning `0.0.0.0`?

Yes, that is one type of condition. It also checks for the Extended DNS Error codes in response if the upstream server supports it.
