### ISSUE TITLE
How to return custom ip for nxdomains

### ISSUE THREAD

**Issue by amirhosseinds** [TechnitiumSoftware/DnsServer#812]
Hello i want to return custom ip for Nx Domains (non exists domains). any one know how to do this?

**Comment by Hemsby** [comment]
Create A Conditional Forward zone for "." and tick use this server and disable DNSSEC for this zone.
Then create a "*" A Record and point to the IP of the desired custom IP.

**Comment by Hemsby** [comment]
> Create A Conditional Forward zone for "." and tick use this server and disable DNSSEC for this zone. Then create a "*" A Record and point to the IP of the desired custom IP.

Actually I just tested this and it does not work.  Sorry.

**Comment by ShreyasZare** [comment]
Thanks for the post. There is no option to do that. Can you let me know the use-case for such a requirement so that I can understand it better to decide on implementing such an option.

**Comment by ShreyasZare** [comment]
> i have a v2ray vpn server ( i dont know you heard of this protocol) and its designed to bypass censorship. any way i have routed multiple servers with this and i used the dns server in highest level server. the response dns server is return for nx domain servers cannot be read and filtered in v2ray and i just to change this empty value to something like 127.0.0.1 to block all nxdomains in first level. thats all

Thanks for the description but its still not clear to me. Why do you want to block NXDOMAIN response when it just means that the domain does not exists and thus there is nothing to block?

**Comment by ShreyasZare** [comment]
> there is something is my mind and i cant tell it here. so if its possible its good to have this feature.Thanks

If you cannot share it publicly then you can email it to support@technitium.com.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available which includes NX Domain Override DNS app that allows returning custom IP.
