### ISSUE TITLE
[Feature request] App/Configuration to return a webpage on NXDomain

### ISSUE THREAD

**Issue by Tivin-i** [TechnitiumSoftware/DnsServer#824]
Heya! Similar to a different feature request I saw here I have a proposal.

As TDNS already has a webserver, it would be nice to have the option to serve a webpage on NXDomain, such as a 404 page.
This is instead of having "* IN xxx.xxx.xxx.xxx" record that would reroute the request some place else / reverse proxy.

**Comment by Tivin-i** [comment]
I am also aware I can just put the IP of the DNS server there, but the reverse proxy on it seems to be a catchall and would require me to manually change all servers and domains.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will try to add this option in the next update. There will be an option in settings to specify the custom IP address to be returned for NXDOMAIN cases. You can then use the Block Page app, which now supports running more than one web server, to handle the request that come for NXDOMAIN cases.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available that includes NX Domain Override DNS app which will allow you to override NXDOMAIN response with custom A/AAAA record.
