### ISSUE TITLE
No DDNS on Conditional Forwarder Zone 

### ISSUE THREAD

**Issue by alexhorner** [TechnitiumSoftware/DnsServer#826]
It appears that zones configured as a Conditional Forwarder Zone do not have an option to configure DDNS. This means you cannot use DDNS with something like acme.sh in order to issue certificates for subdomains.

I recognise that a DNS server configured as a Conditional Forwarder Zone server will not be authoritative for an entire domain to a third party like Letsencrypt, and therefore ACME TXT records created on it would not be read and respected by those third parties, but in scenarios (such as the one myself and someone else are in) where you're running your own ACME server like step-ca, which can be configured to check Technitium for ACME TXT records, having DDNS available would be very useful.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will check this once and try to get it added in next update.

**Comment by echodreamz** [comment]
Agreed, this is a must.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12 is now available which supports dynamic updated for conditional forwarder zones.
