### ISSUE TITLE
[Feature Request] - Resolve blocked DNS requests to custom domain instead of blackhole

### ISSUE THREAD

**Issue by aconn21** [TechnitiumSoftware/DnsServer#829]
For blocked requests, I'm wanting to resolve the DNS query to a webserver I've setup with a blocked webpage. (I'd prefer users to know websites/domains have been blocked). Happy to modify the code myself if you could point me to the lines/section of code I'd need to change. I'd need this for CNAME and A records.

**Comment by ShreyasZare** [comment]
Thanks for the post. You can already do that using the Custom Address option and set the IP address of your web server.

**Comment by aconn21** [comment]
Yep sorry, I found the option. This works fine:

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/7642455/ef298743-e17f-4c46-b7d9-f65e02cbf614)
