### ISSUE TITLE
DNS Server failed to notify name server

### ISSUE THREAD

**Issue by Sysadminfromhell** [TechnitiumSoftware/DnsServer#832]
Hello everyone,

I have a problem that the notify to the other name servers always fail.
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/78756354/5bc4b798-8278-46f5-a1c1-1dae75a77d06)
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/78756354/efb53548-7bd2-4a24-a7f0-ed4ab1b73f1d)

I just dont know why the error code is REFUSED:
`[2024-01-15 09:13:00 Local] DNS Server failed to notify name server 'dns02.fritz.box' (RCODE=Refused) for zone: fritz.box
[2024-01-15 09:13:00 Local] DNS Server failed to notify name server 'dns02.fritz.box' (RCODE=Refused) for zone: 178.168.192.in-addr.arpa`
There is no Firewall in between.
On both servers the Zones are primary and the SOA is, as you can see, DNS01.

Kind regards,

**Comment by Sysadminfromhell** [comment]
The funny part: Even dns02 says the notify failed for dns02. How does this work?

**Comment by ShreyasZare** [comment]
Thanks for the post. The issue is as you state:

> On both servers the Zones are primary

There must be only one primary zone and the other zone on the second server must be secondary zone. The notify mechanism is to alert secondary zones to start zone transfer when primary zone has any updates.

Since, both your zones are primary, both are sending notify requests to each other and thus both will refuse to accept them.

**Comment by Sysadminfromhell** [comment]
Okay, but in a secondary Zone I cannot make any changes, right?
So It´s not really failover...

**Comment by ShreyasZare** [comment]
> Okay, but in a secondary Zone I cannot make any changes, right? So It´s not really failover...

Yes. Secondary zone is read only and will get updates only from primary zone. When primary server is down for any reason, the secondary will respond to queries but you wont be able to update the zone until your primary is back up or that you use the Convert Zone option to change the zone from secondary to primary manually.

**Comment by Sysadminfromhell** [comment]
But as far As I understand any other DNS Server the SOA detemerm which is the primary (master) and which not.
Changes should be able to be done on all NS Servers.

**Comment by Sysadminfromhell** [comment]
> Yes. Secondary zone is read only and will get updates only from primary zone. When primary server is down for any reason, the secondary will respond to queries but you wont be able to update the zone until your primary is back up or that you use the Convert Zone option to change the zone from secondary to primary manually.

Its nor really failover / loadbalancing then in my opinion. I I can´t make changes on both DNS Servers the DHCP Server won´t be able to update the DynDNS Names to both Servers because the DNS02 can't accept these changes.

**Comment by ShreyasZare** [comment]
> But as far As I understand any other DNS Server the SOA detemerm which is the primary (master) and which not. 

The SOA specified the primary name server which holds the primary zone. Note that its not necessary that the SOA record specified the actual server that holds the primary zone.

> Changes should be able to be done on all NS Servers.

Changes are permitted only on primary zone which in DNS is only a single server unless the DNS server has some kind of non-standard/proprietary clustering feature.

**Comment by Sysadminfromhell** [comment]
Okay, so the non-standard clustering Feature, for example, from Microsoft in a Windows Domain is non-standard.
As far as I'm aware DNS is not failover this is true, but as far as I know even BIND9 has some kind of feature for that? At least in the company I work in you can send Update requests to both DNS Servers and it will be transfered successfully.
I will see if I can find a documentation for it and maybe create a FR?

**Comment by ShreyasZare** [comment]
> Its nor really failover / loadbalancing then in my opinion. I I can´t make changes on both DNS Servers the DHCP Server won´t be able to update the DynDNS Names to both Servers because the DNS02 can't accept these changes.

In DNS, load balancing is just having more than one name server. Failover too is same from client's perspective. In your case, its that when primary zone is down, your DHCP updates would fail.

The standard model is that primary zone can only update records. This becomes even more strict when the zone is signed since the primary zone holds the private keys for the zone.

**Comment by ShreyasZare** [comment]
> Okay, so the non-standard clustering Feature, for example, from Microsoft in a Windows Domain is non-standard. As far as I'm aware DNS is not failover this is true, but as far as I know even BIND9 has some kind of feature for that? At least in the company I work in you can send Update requests to both DNS Servers and it will be transfered successfully. I will see if I can find a documentation for it and maybe create a FR?

Secondary zone server will automatically forward the Dynamic Updates RFC 2136 requests to primary server so its not that the secondary zone is being updated directly.

**Comment by Sysadminfromhell** [comment]
Alright, so even when the RFC2136 request comes to dns02 he will forward the request. Good to know I wasn't aware of that.

**Comment by Sysadminfromhell** [comment]
Is there a way to change the Zone type from primary to secondary?

**Comment by ShreyasZare** [comment]
> Alright, so even when the RFC2136 request comes to dns02 he will forward the request. Good to know I wasn't aware of that.

Yes, its just being forwarded to primary zone as specified in the RFC.

**Comment by ShreyasZare** [comment]
> Is there a way to change the Zone type from primary to secondary?

Yes, you will find it in Options > Convert Zone when you edit the zone.

**Comment by Sysadminfromhell** [comment]
> > Is there a way to change the Zone type from primary to secondary?
> 
> Yes, you will find it in Options > Convert Zone when you edit the zone.

no can do:
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/78756354/7bfd3eb2-68c6-4dc3-b8ba-10ebc27e483d)

**Comment by ShreyasZare** [comment]
> no can do

Ohh right. Convert works from secondary to primary. In your case, you have to delete the primary zone on the second server and use Add Zone option to add secondary zone where you will need to specify the primary server's IP address and it will sync immediately.

**Comment by Sysadminfromhell** [comment]
Yea I just did that 👍 
Thanks for the Input tho :)

**Comment by ShreyasZare** [comment]
You're welcome :)
