### ISSUE TITLE
Cleanup Zone

### ISSUE THREAD

**Issue by Sysadminfromhell** [TechnitiumSoftware/DnsServer#835]
Hello, me again :)

Got a quick question, is there a "Cleanup" Function?
I mean I got a DHCP which gives out the Ip Addresses and register via DDNS the names of the clients but the "old" names always remains in the Zone. So that means if the client disconnects more then 1 Day the name still can be resolved after the 24 Hours (DHCP Lease time). Is there a function to call that (even via DHCP)?

Kind regards,

**Comment by ShreyasZare** [comment]
Thanks for the post. The DHCP server that you are using is supposed to do the "cleanup" by removing the DNS entry when a lease expires. The DNS server does not know anything about the client lease so it cannot take any action on its own.

> In additional question is which DDNS Style is allowed?
I am not sure about it.

**Comment by Sysadminfromhell** [comment]
I guess the cleanup isnt working properly due the fact of interm maybe. I will switch it to standard and see if it works or not.
