### ISSUE TITLE
[Feature Request] Hide elements based off Selected Roles

### ISSUE THREAD

**Issue by johnnyq** [TechnitiumSoftware/DnsServer#841]
There should be an option to choose the roles of the server for the following roles:

- Resolver / Caching DNS 
- Authoritative DNS
- DHCP

Options and menus should be **hidden** based off the the roles selected
This will prevent **UI fatigue** greatly

**Comment by ShreyasZare** [comment]
Thanks for the feature request. While DHCP is a separate thing, the DNS part is very much common for both running Authoritative and Recursive mode. So, its kind of tough to separate options since a lot of them overlap. Will give this more thought once and see how feasible it is.

**Comment by ShreyasZare** [comment]
Another option is to create a user with specific role so that the user only sees the relevant section when login. Does that work for you?

**Comment by johnnyq** [comment]
excellent suggestion I didn't know that, it seems I passed that option up
Thank you !! =]

**Comment by ShreyasZare** [comment]
Good to know that this works for you.
