### ISSUE TITLE
[Feature Request] Support CNAME flattening

### ISSUE THREAD

**Issue by ChenhaoShen** [TechnitiumSoftware/DnsServer#844]

**Comment by ChenhaoShen** [comment]
> Thanks for the post. CNAME flattening is already available using ANAME records in your zone.

I've found that ANAME records cannot be resolved to A records when querying recursively from other DNS servers. An empty query was returned

**Comment by ShreyasZare** [comment]
> > Thanks for the post. CNAME flattening is already available using ANAME records in your zone.
> 
> I've found that ANAME records cannot be resolved to A records when querying recursively from other DNS servers. An empty query was returned

Thanks for the response. It could be some config issue that you may have. Share the details of your config here or via email to support so that I can help you with the config.
