### ISSUE TITLE
Upgrade to 12.0 breaks wildcard A records

### ISSUE THREAD

**Issue by Dakazan** [TechnitiumSoftware/DnsServer#845]
On my setup I have multiple zones like this: `subdomain.example.com`

Inside that zone I have A records with names `*.lab.test`, with the full domain being `*.lab.test.subdomain.example.com`

This works fine and resolves on 11.5.3, but not on version 12

Environment:
* RHEL 9.2 VM
* 5.14.0-284.48.1.el9_2.x86_64

Here's an example of what I use on 11.5.3
```bash
bash> dig test.lab.test.subdomain.example.com

; <<>> DiG 9.16.23-RH <<>> test.lab.test.subdomain.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58575
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;test.lab.test.subdomain.example.com. IN A

;; ANSWER SECTION:
test.lab.test.subdomain.example.com. 60 IN A <redacted>

;; Query time: 110 msec
;; SERVER: <redacted>#53(<redacted>)
;; WHEN: Tue Feb 06 23:43:25 MST 2024
;; MSG SIZE  rcvd: 95
```

**Comment by ShreyasZare** [comment]
Thanks for reporting this. Will get this fixed soon.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.0.1 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by Dakazan** [comment]
Works great, thanks!

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
