### ISSUE TITLE
[Feature Request] DNS Catalog Zones (RFC 9432)

### ISSUE THREAD

**Issue by pinocc01** [TechnitiumSoftware/DnsServer#847]
https://datatracker.ietf.org/doc/html/rfc9432.html

**Comment by ShreyasZare** [comment]
Thanks for the request. Catalog zones is already planned and will be part of the clustering feature that is being designed.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 adds support for Catalog Zones. Do update and let me know your feedback.
