### ISSUE TITLE
Debian 12: Graph problem

### ISSUE THREAD

**Issue by kirush0280** [TechnitiumSoftware/DnsServer#849]
Technitium DNS Server
Version 12.0.1

OS: Debian 12

Have problem with graph. On default "Last hour" graph is visible:
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/13412942/64cd7f4b-2031-4a3d-82a8-d10e40752cce)

When I change something else - no data.
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/13412942/8e4fbe1a-3fe0-40d9-bfd2-a4178d81e114)
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/13412942/ebc367d8-5c63-4691-80bb-e302c414f708)

**Comment by ShreyasZare** [comment]
Thanks for the post. Have you enabled "In-Memory Stats" option in settings?

**Comment by kirush0280** [comment]
Yes, sorry. Resolved. Thanks
