### ISSUE TITLE
Technitium DNS just freezes sometimes

### ISSUE THREAD

**Issue by honeyfairy** [TechnitiumSoftware/DnsServer#85]
I have Technitium DNS Server running and working correctly on a Ubuntu VM, and a Windows 7 VM. I think its good.
They are serving around 5 million queries per day. (Dashboard stats in attached pic)

### The problem:

Sometimes it just freezes. It just does not respond. Then I have to restart the  Technitium DNS Service. It happens more frequently on Ubuntu than it does on Windows 7.

This morning, I had to restart the Windows 7 VM twice, then only the  Technitium DNS Service started again. What can be the cause of this issue?
How can I make it more stable?

![Capture](https://user-images.githubusercontent.com/17691989/64485320-6ca3bd00-d21f-11e9-887f-f779d0bd431d.PNG)

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

Please elaborate what the server freezes exactly is. Is it that the web portal does not load or display stats? Or is it that the server does not respond to any DNS queries? 

Did you try to query the server using nslookup command when it seems like the server is freezed? If you get response to nslookup query then the server is working but the web portal is not responding.

When it freezes does it return back in few minutes or does it requires force restart?

I would also suggest that you check the RAM usage in both Windows and Ubuntu VMs when it seems that the server is freezing. It may be that the system memory is low and the server is unable to allocate more memory to serve requests. Also, check CPU usage during such events. When system is low on memory, the OS will start using swap memory and thus disk drive usage will peak as it starts memory swapping to disk. In case, you observe low system memory then increasing RAM will solve the issue.

**Comment by ShreyasZare** [comment]
Also, please let me know the hardware config for both the VMs.

**Comment by honeyfairy** [comment]
Thank you for the response, much appreciated.

1. The server stops responding to DNS queries.
2. Yes it goes down, and comes back up, as per Attached screenshot
3. Stats in attached pic 

I will check the stats if/ when 
![2](https://user-images.githubusercontent.com/17691989/64490077-d8a31700-d259-11e9-8982-1372e5fa713e.PNG)
![Capture](https://user-images.githubusercontent.com/17691989/64490078-d9d44400-d259-11e9-837c-79a025a233f7.PNG)

it goes down again

**Comment by honeyfairy** [comment]
> Also, please let me know the hardware config for both the VMs.

4 cores and 4gb RAM and about 40gb disk drive.

**Comment by ShreyasZare** [comment]
@honeyfairy did you find any more details?

**Comment by ShreyasZare** [comment]
Version 5 is now available which has fixed multiple issues causes by thread contention when the server gets load above certain levels. This update should fix this issue. Feel free to open this issue again if the issue still persists.
