### ISSUE TITLE
[Feature Request] "Ignore Client ID" toggle

### ISSUE THREAD

**Issue by UntouchedWagons** [TechnitiumSoftware/DnsServer#850]
Please add an option for ignoring the client ID in DHCP requests. Some distrobutions like Ubuntu use a client ID in place of a MAC address for requesting IP addresses. This makes provisioning Ubuntu machines difficult since dhcp reservations are by MAC address.

**Comment by ShreyasZare** [comment]
Thanks for the feature request. Will get the option added in coming updates.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.1 is now available that adds the "Ignore Client Identifier Option" in DHCP scopes. Do update and let me know your feedback.

**Comment by UntouchedWagons** [comment]
Yup it works fine. Thanks!

**Comment by ShreyasZare** [comment]
Thanks for the feedback.

**Comment by UntouchedWagons** [comment]
Okay there's something weird going on. I turned on the option on my main VLAN last night to do some testing and this morning I woke up to numerous duplicate DHCP leases which broke near everything

![firefox_2zHkSlLSIL](https://github.com/TechnitiumSoftware/DnsServer/assets/160996/b8c77ed0-73f9-47dd-acb5-a4047acf400e)

**Comment by ShreyasZare** [comment]
> Okay there's something weird going on. I turned on the option on my main VLAN last night to do some testing and this morning I woke up to numerous duplicate DHCP leases which broke near everything

Yes, that is expected since old leases were based on Client Identifier. You will need to delete those old leases manually so that the client is assigned the correct reserved lease.
