### ISSUE TITLE
DHCP scope using wrong ip for "Use This DNS Server" when "DNS Server Local End Points" has been set

### ISSUE THREAD

**Issue by tannyl** [TechnitiumSoftware/DnsServer#851]
When defining a DHCP scope and using the **DNS Servers** setting and toggling on the **This DNS Server** option for this setting
it uses the ip address of the interface with the default gateway and/or the ip of eth0 even if you have defined other ip addresses under the **DNS Server Local End Points** setting.
![image](https://github.com/TechnitiumSoftware/DnsServer/assets/11209600/3e73e04f-f5f9-4caa-86e6-f43bf9c88d39)

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/11209600/ac5fb29c-b474-40e4-86bf-a731c62db3b3)

Note that this is running inside a Docker container.

**Comment by ShreyasZare** [comment]
Thanks for the feedback, Will update the code to select the specific address the DNS server is listening on.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.1 is now available that fixes this issue. Do update and let me know your feedback.
