### ISSUE TITLE
Any Idea to change my remote ip to dns ip

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#863]
Any Idea to change my ip address to local dns server ip and Domain Name ?

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/31727156/902bd81a-d1a2-4fd6-9410-194340f46c05)

**Comment by ShreyasZare** [comment]
Thanks for the post. Your IP address is no way related to DNS. Your IP will stay same unless you use VPN or Tor.

**Comment by Hemsby** [comment]
I dont really understand the question.  Agree fully with @ShreyasZare , but if you are asking to use your own DNS server while using Mobile Data and not wifi, then you need to either host the server on a cloud provider or use port forwarding on your router and use DDNS
