### ISSUE TITLE
Blocking with android not working ?

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#865]
My Phone : Redmi note 9 pro
Browsers : Chrome
DNS Version : 12.0.1

Android Don't Blocking the ads just in my PC

**Comment by ShreyasZare** [comment]
Thanks for the post. You need to verify if your phone is using the local DNS server. Make sure that your DHCP config is giving the IP address of only your local DNS server for all clients.

**Comment by muhanadali100** [comment]
> Thanks for the post. You need to verify if your phone is using the local DNS server. Make sure that your DHCP config is giving the IP address of only your local DNS server for all clients.

I give my phone static address with local dns server and not working

**Comment by ShreyasZare** [comment]
In my local setup, blocking is working well on devices including multiple Android phones. Can you provide steps to reproduce this issue?

**Comment by older-fox** [comment]
> > Thanks for the post. You need to verify if your phone is using the local DNS server. Make sure that your DHCP config is giving the IP address of only your local DNS server for all clients.
> 
> I give my phone static address with local dns server and not working

Can you take an screen shot of the dns settings page of your phone?

**Comment by Hemsby** [comment]
I just want to add here, my family android and iphone all have no issues using the local DNS block lists.

Kind Regards,

Roy Hagland

**Comment by older-fox** [comment]
@ShreyasZare This issue is able to close now.
