### ISSUE TITLE
[Feature Request] Blocking type custom address: port support

### ISSUE THREAD

**Issue by Meganitrospeed** [TechnitiumSoftware/DnsServer#872]
Hello,

Currently the blocking type custom address doesnt support adding a custom port.

For systems that already have an 80 - 443 on the same server, without going info default routes and stuff It would be interesting to be able to declare a port for Blocking Page serving, the Blocking Page app would also need to have a Port option (unless its docker)

**Comment by ShreyasZare** [comment]
Thanks for the request. This is however not possible to achieve with DNS. Port in the URL is at HTTP protocol level and the DNS server only gets a query to resolve the domain name in the URL.

If you have an issue with port conflict then you will need to assign an additional IP address to your server and use that one with the Block Page app while configuring your existing web server listen only on the current IP address.

Another option is to just not use Block Page app and just use the existing web server on the same server or run one on another server. The Block Page app is just for convenience reasons and can be easily substituted with any web server that you have.

**Comment by Meganitrospeed** [comment]
I totally forgot we're dealing with DNS here and that you just cannot do this unless its something like a SRV record

Thank you for the prompt response!

**Comment by ShreyasZare** [comment]
You're welcome!
