### ISSUE TITLE
Feature Request: Add a Docker Environment Variable for the Web Server Listening Address

### ISSUE THREAD

**Issue by anonhostpi** [TechnitiumSoftware/DnsServer#877]
When running the DNS server in host mode (to support DHCP deployments), the Web Server port is also exposed and not protected by Docker's NAT.

This can be a problem when trying to protect the web console with a docker-based reverse/oauth-proxy.

To prevent unauthorized/unproxied access, you can set the listening address. As far as I am aware, the only place to configure this is on the web server, once it is already running:

![image](https://github.com/TechnitiumSoftware/DnsServer/assets/130698314/b147a8a0-09e4-4d70-b5f5-75efd7924194)

Ideally in a Docker environment, this should be configurable from the docker compose file prior to starting the web server.

EDIT: Potential solution: https://github.com/TechnitiumSoftware/DnsServer/issues/877#issuecomment-1982246204

**Comment by anonhostpi** [comment]
Doing a code search for how this text field is handled...

Element ID: txtWebServiceLocalAddresses

That element gets sanitized for saving here:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/www/js/main.js#L1302-L1307

relevant HTTP request:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/www/js/main.js#L1733-L1752

and it is retrieved here:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/www/js/main.js#L958-L962

relevant HTTP request:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/www/js/main.js#L924-L937

**Comment by anonhostpi** [comment]
Settings API source code:

https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/WebServiceSettingsApi.cs

**Comment by anonhostpi** [comment]
Relevant lines for setting the web addresss:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/WebServiceSettingsApi.cs#L570

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/WebServiceSettingsApi.cs#L703-L730

Note this line from the above blob:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/WebServiceSettingsApi.cs#L722

The restart of the server (and the application of the new listening address), starts here:

https://github.com/TechnitiumSoftware/DnsServer/blob/master/DnsServerCore/WebServiceSettingsApi.cs#L1344

**Comment by anonhostpi** [comment]
It is appears that while running, the webserver uses _dnsWebService._webServiceLocalAddresses for storing the listening address

**Comment by anonhostpi** [comment]
This appears to be where the config is read from:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/DnsWebService.cs#L1144

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/DnsWebService.cs#L1151-L1166

Which is wrapped by this method:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/DnsWebService.cs#L1108-L1142

Which is called by this method:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/DnsWebService.cs#L858

Which loads the config file with this snippet:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/DnsWebService.cs#L860-L875

**Comment by anonhostpi** [comment]
Config file (for the DnsWebService class) appears to be defined here on Linux:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerApp/Program.cs#L54

Which is pulled from the arguments passed to the executable:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerApp/Program.cs#L32-L33

Which for docker, is defined in the service file:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerApp/systemd.service#L6

**Comment by anonhostpi** [comment]
Next thing I need to do is to determine if I can even interact with that binary file (dns.config). When I try to cat it on ubuntu, I got a bunch of garbage in the output, so it does not appear to be plain text

**Comment by anonhostpi** [comment]
Looks like it should be easy to set it with the LoadConfigFile() method:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/DnsWebService.cs#L896-L910

You would just have to transpile the sanitization scripts and place them in the above blob

frontend:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/www/js/main.js#L1302-L1307

backend:

https://github.com/TechnitiumSoftware/DnsServer/blob/05ec6a5da4d7d05102c473974f6b0559b384de67/DnsServerCore/WebServiceSettingsApi.cs#L703-L730

**Comment by anonhostpi** [comment]
It looks like it might not even need to be that complicated, since cleanTextList just replaces newlines and removes additional commas

```csharp
// Replace newlines with commas
string webServiceLocalAddresses = input.Replace("\n", ",")

// Replace duplicate commas with single commas
webServiceLocalAddresses = Regex.Replace(webServiceLocalAddresses, ",{2,}", ",");

// Trim the string of starting/trailing whitespace and commas
webServiceLocalAddresses = Regex.Replace(webServiceLocalAddresses, "(?:^[, ]+)|(?:[, ]+$)", ",");

// insert above snippet from DnsServerCore/WebServiceSettingsApi.cs (lines L703-L730)
// ...
```

**Comment by ShreyasZare** [comment]
Thanks for the request. Will get the environment variable added in the upcoming update.

**Comment by anonhostpi** [comment]
How is your release schedule? I'd like to know when I should check back.

**Comment by ShreyasZare** [comment]
> How is your release schedule? I'd like to know when I should check back.

The next update is planned for upcoming weekend but it may get a bit delayed too. I will post here when its available so that you are notified.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.1 is now available that adds the environment variable. Do update and let me know your feedback.

**Comment by anonhostpi** [comment]
Will do. Have inspections this weekend, so this will likely get implemented later this week

**Comment by anonhostpi** [comment]
New environment variable (DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES) will need to be added to the docker compose file.

Testing out the change now. Give me a bit

**Comment by anonhostpi** [comment]
Works for singular listening address. Rebuilding it for 2 addresses

**Comment by anonhostpi** [comment]
It did not like the comma-delimited address

**Comment by anonhostpi** [comment]
Here are the logs:

```
dns-dhcp-test  | System.FormatException: An invalid IP address was specified.
dns-dhcp-test  |  ---> System.Net.Sockets.SocketException (22): Invalid argument
dns-dhcp-test  |    --- End of inner exception stack trace ---
dns-dhcp-test  |    at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
dns-dhcp-test  |    at TechnitiumLibrary.StringExtensions.Split[T](String value, Func`2 parse, Char[] separator) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary\StringExtensions.cs:line 34
dns-dhcp-test  |    at DnsServerCore.DnsWebService.LoadConfigFile() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 898
dns-dhcp-test  |    at DnsServerCore.DnsWebService.StartAsync() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 2540
dns-dhcp-test  |    at TechnitiumLibrary.TaskExtensions.Sync(Task task) in Z:\Technitium\Projects\TechnitiumLibrary\TechnitiumLibrary\TaskExtensions.cs:line 56
dns-dhcp-test  |    at DnsServerCore.DnsWebService.Start() in Z:\Technitium\Projects\DnsServer\DnsServerCore\DnsWebService.cs:line 2668
dns-dhcp-test  |    at DnsServerApp.Program.Main(String[] args) in Z:\Technitium\Projects\DnsServer\DnsServerApp\Program.cs:line 55
dns-dhcp-test  | 
dns-dhcp-test  | Technitium DNS Server is stopping...
dns-dhcp-test  | Technitium DNS Server was stopped successfully.
dns-dhcp-test exited with code 0
```

**Comment by anonhostpi** [comment]
Got it. The compose file did not like the quotes, so in YAML you can use:

```yml
- DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES=172.18.0.1,172.17.0.1
```

**Comment by ShreyasZare** [comment]
Thanks for the feedback and for the PR. Had missed updating the docker compose file to add it.
