### ISSUE TITLE
Feature Request: Docker ENV Variable for Zone files

### ISSUE THREAD

**Issue by wawall99** [TechnitiumSoftware/DnsServer#878]
A way of passing in zone files to save to the config on first start... or even every time, and then choosing whether you want it to overwrite the zone or not every time it starts.

**Comment by ShreyasZare** [comment]
Thanks for the request. The environment variables are intended to be used just to initialize some of the required settings on first start. If you need to do any thing more elaborate then its recommended to use something like a bash script that uses the [HTTP API](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) with curl and jq.
