### ISSUE TITLE
ZeuS Tracker is dead

### ISSUE THREAD

**Issue by Globulopolis** [TechnitiumSoftware/DnsServer#88]
https://zeustracker.abuse.ch/byebye.php?download=domainblocklist return # ZeuS Tracker has been discontinued on Jul 8th, 2019
So we need to an updated list of predefined URLs.

**Comment by ShreyasZare** [comment]
Yes. In next release this url will be replaced with ransomeware tracker: https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt

**Comment by Globulopolis** [comment]
Ok.
And one more question. How about to remove `# Basic tracking list by Disconnect`. This list contain only 34 domains.

**Comment by ShreyasZare** [comment]
Ya, will review that list too.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v4.1 is now available that fixes this issue. If you have this old URL in settings then it will remain until it is manually removed.
