### ISSUE TITLE
Install script missing default exception handler

### ISSUE THREAD

**Issue by gh3597** [TechnitiumSoftware/DnsServer#881]
I'm no expert on scripts but it seems there's no default exception handler as I had this earlier:

```
===============================
Technitium DNS Server Installer
===============================

Updating ASP.NET Core Runtime...
curl: (28) Failed to connect to dotnet.microsoft.com port 443 after 265934 ms: Couldn't connect to server
ASP.NET Core Runtime was updated successfully!

Downloading Technitium DNS Server...
```
I don't think it should continue when it hasn't done anything!

**Comment by ShreyasZare** [comment]
Thanks for the post. The .NET runtime is installed by another script provided by Microsoft. So the install script does not exactly know if it succeeded. It just check if the .NET runtime is installed by running `dotnet --list-runtimes` command and in your case, it seems that there is already .NET 8.0.x runtime available so it proceeded with the installation.

**Comment by gh3597** [comment]
> in your case, it seems that there is already .NET 8.0.x runtime available so it proceeded with the installation.

I'm not so sure about that, it did say initially "updating" so must have checked the version and decided it needed updating then the curl command failed at which point it carried on with the script. I don't think it ever got as far as even installing anything as the installer was never downloaded. 

I suppose adding some sort of exception handler to catch the curl errors won't be that simple if the dotnet installer doesn't return anything. 

Ironically the curl command failed because of DNS configuration issues on the Technitium host!

**Comment by ShreyasZare** [comment]
> I suppose adding some sort of exception handler to catch the curl errors won't be that simple if the dotnet installer doesn't return anything.

The .NET installer script is maintained by Microsoft so there is no way to may any changes for it. It does provide verbose logs which can be checked to understand the failure reason.

If there was no .NET runtime found then the installer would anyway stop. If any .NET runtime v8.0.x was available it would proceed and would work without issues.
