### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#883]
Completely stopped working on Raspberry install and docker containers.

Will not do any resolving with udp, tcp, tls or https.

Dns lookup error: network error.

Also wont do zone transfers anymore. No SOA.

Uninstalled and inatalled adguard home for testing. Adguard home works perfectly with mixed tls and https lookup servers.  So not an issue on my network.

Was working fine on previus versions. Will install older versions and test.

**Comment by ChristoffBo** [comment]
Tested with older 12.0 doing the same. Will go to Adguard Home for a few versions and test again then.

**Comment by ShreyasZare** [comment]
Thanks for the post. From the description it looks like some config issue. You need to check the Logs section from the admin panel to see what errors are logged. That will help you identify the issue correctly. Do post the error logs you see in there if you need help understanding them.

**Comment by ChristoffBo** [comment]
Hi, thank you both dns servers had no config changes just stopped working. Will wait a few version updates and test again.
