### ISSUE TITLE
Query Logs on Musl/Alpine not working

### ISSUE THREAD

**Issue by gitfoohub** [TechnitiumSoftware/DnsServer#884]
When using technitium on Alpine/Musl the Query Logs App seems to use the linux-x64 binary and not linux-musl-x64 (The log shows the error: "fcntl64: symbol not found"). After deleting the linux-x64 folder in the config/apps/Query Logs (Sqlite)/runtimes folder and copying the linux-musl-x64 to linux-x64 everything worked fine.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Please share the complete error log so that I can try to reproduce same here.

**Comment by ShreyasZare** [comment]
Also, let me know the exact OS version that you are using.

**Comment by ShreyasZare** [comment]
Thanks for the details. Will get this fixed in the next update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.2.1 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by gitfoohub** [comment]
Everything works fine. Thank you for your great work!

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
