### ISSUE TITLE
[ Feature Request ] ECS Based Client Configuration

### ISSUE THREAD

**Issue by mbah-dukun** [TechnitiumSoftware/DnsServer#894]
I have at least 3 different ISP upstreams, and there are client side optimizations to use one of those upstreams, can I add ECS Override based on client configuration to that one upstream?

**Comment by ShreyasZare** [comment]
Thanks for the post. You can configure ECS override option and set the subnet for one of your ISP. But that will cause all other clients too get DNS responses which are "closer" to that specific ISP and may increase delays especially of your other ISPs have peering setup for popular CDN providers.

It would be best that you setup 3 different DNS server instances and then assign clients the DNS server IP address that you wish they should use.

**Comment by mbah-dukun** [comment]
> Thanks for the post. You can configure ECS override option and set the subnet for one of your ISP. But that will cause all other clients too get DNS responses which are "closer" to that specific ISP and may increase delays especially of your other ISPs have peering setup for popular CDN providers.
> 
> It would be best that you setup 3 different DNS server instances and then assign clients the DNS server IP address that you wish they should use.

I've used ECS Override, but ECS fails to send the /24 prefix. If the IP address is filled in /32 it works, I hope that the ECS override can use the prefix /24 or lower.

**Comment by ShreyasZare** [comment]
> I've used ECS Override, but ECS fails to send the /24 prefix. If the IP address is filled in /32 it works, I hope that the ECS override can use the prefix /24 or lower.

Thanks for the details. How did you find out that its not sending ECS when /24 subnet is set? I would suggest that you use Wireshark/tcpdump and check the request and post details here.

**Comment by mbah-dukun** [comment]
> > I've used ECS Override, but ECS fails to send the /24 prefix. If the IP address is filled in /32 it works, I hope that the ECS override can use the prefix /24 or lower.
> 
> Thanks for the details. How did you find out that its not sending ECS when /24 subnet is set? I would suggest that you use Wireshark/tcpdump and check the request and post details here.

I have rebooted the system, at this time I entered 0.0.0.0/0 and it works fine, I have also tried using a lower prefix  from /1 to /32 and everything works fine.
sorry for the problem that shouldn't exist 🙏
