### ISSUE TITLE
I've already turned the intercept off. Why can I still intercept?

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#896]
![图片](https://github.com/TechnitiumSoftware/DnsServer/assets/28734349/9330bffd-6f98-4aa0-bfb4-2c1abc0710dc)
![图片](https://github.com/TechnitiumSoftware/DnsServer/assets/28734349/765cfe44-f7dd-4f05-9efa-0f4ad91cbf4c)

**Comment by ShreyasZare** [comment]
Thanks for the post. Do you have Advanced Blocking app installed?

Another possibility is that your upstream/forwarder is blocking these domain names. The DNS server is capable to understand upstream blocked response and will log it.

**Comment by liang-hiwin** [comment]
I know how this problem occurs because my local dns has also had this problem before, and the result is that the upstream used has blocking ads. The solution is to delete the upstream that has ad blocking

**Comment by liang-hiwin** [comment]
> > I know how this problem occurs because my local dns has also had this problem before, and the result is that the upstream used has blocking ads. The solution is to delete the upstream that has ad blocking
> 
> This and the 360 doh problem?

In fact, this is also a bug in the program, because as long as the upstream response to the requested domain name is 0.0.0.0 or 127.0.0.1, the web panel will show that the domain name has been intercepted.v

**Comment by liang-hiwin** [comment]
> > In fact, this is also a bug in the program, because as long as the upstream response to the requested domain name is 0.0.0.0 or 127.0.0.1, the web panel will show that the domain name has been intercepted. @ShreyasZare @Potterli20
> 
> Oh, oh, I just feel weird, when there is no intercept upstream of me. I wonder if it's a 360 doh intercept. But there's no problem.

You can test it yourself. It looks like the 0.0.0.0 given by 360

**Comment by liang-hiwin** [comment]
I tested the response of 360, and the result was exactly what I thought.
```
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"m.aixdzs.com.","type":1}],"Answer":[{"name":"m.aixdzs.com.","type":1,"TTL":600,"data":"0.0.0.0"}]}
```

**Comment by ShreyasZare** [comment]
As mentioned, the dashboard stats will list the domain as blocked only if it was locally blocked using the built-in blocking feature or if one of the upstream/forwarder blocked it. If you still have issues then do test all your forwarders using DNS Client and check the response IP address and also the Extended DNS Errors in response.

**Comment by liang-hiwin** [comment]
> As mentioned, the dashboard stats will list the domain as blocked only if it was locally blocked using the built-in blocking feature or if one of the upstream/forwarder blocked it. If you still have issues then do test all your forwarders using DNS Client and check the response IP address and also the Extended DNS Errors in response.

ok, i know.

**Comment by ShreyasZare** [comment]
> My advice is that, with or without the block, it shouldn't be here, because I don't feel like it fits the block page

This is actually a feature so that you know that a domain name is being blocked by upstream instead of wondering why a website is not working. The Query Logs app lists it as Upstream Blocked and also the DNS Client response will include Extended DNS Error that will indicate the same info.

**Comment by liang-hiwin** [comment]
> > My advice is that, with or without the block, it shouldn't be here, because I don't feel like it fits the block page
> 
> This is actually a feature so that you know that a domain name is being blocked by upstream instead of wondering why a website is not working. The Query Logs app lists it as Upstream Blocked and also the DNS Client response will include Extended DNS Error that will indicate the same info.

I agree with you.

**Comment by ShreyasZare** [comment]
> If upstream intercepts, can we not change the value to 0.0.0.0? Local ip addresses other than 0.0.0.0 are used only after rules are used.

Its not a standard signal that the upstream blocked the domain. So, the DNS server cannot modify the answer based on just the detection mechanism.
