### ISSUE TITLE
How does DnsServer ui counterproxy web pages

### ISSUE THREAD

**Issue by Potterli20** [TechnitiumSoftware/DnsServer#897]
I am using nginx but I have two DNSServers and also want to use nginx to counter-proxy the DnsServer web ui separately

**Comment by ShreyasZare** [comment]
Thanks for the post. I am not sure what the query is. Can you explain the "counter-proxy" terminology and give more details on what you wish to achieve?

**Comment by ShreyasZare** [comment]
> > Thanks for the post. I am not sure what the query is. Can you explain the "counter-proxy" terminology and give more details on what you wish to achieve?
> 
> proxy_pass configuration of nginx

Ok it seems that you mean reverse proxy. Yes, it works but it wont work under a "folder" path in the URL.

**Comment by ShreyasZare** [comment]
> The main thing is that js and css have no way to reverse proxy. I need separate ui and configuration. I configured but the other one could not reverse proxy. That's what's bothering me.

You will need to use a subdomain for using with reverse proxy so that it works well as expected.
