### ISSUE TITLE
certain manual block entries not working

### ISSUE THREAD

**Issue by tkpaul92** [TechnitiumSoftware/DnsServer#898]
hello!

I am currently looking into an issue where I just cant block certain domains (manually, i think only affects subdomains) on the latest Technitium DNS Server version on Windows 10 x64.
One logical explanation here would of course be that an allow entry for the domain above it overrides it, but I only found that to be like that in one case, deleted that allow entry, but the subdomain remained not blocked.
What could this be caused by, how could I further diagnose this?
Flushed the cache in DNS Server and all involved systems, restarted the DNS service, but the situation did not change.
Thanks in advance for any suggestions.

**Comment by ShreyasZare** [comment]
Thanks for the post. The blocking feature has nothing to do with cache so, flushing it or restarting will have no effect.

As you said, if the domain is in allowed list, it and all its subdomain names too will be allowed. This overrides any blocking attempt using block lists.

If the domain is still not being blocked after you remove it from allowed list then test it using the DNS Client tab once and share the result here.

**Comment by tkpaul92** [comment]
hello!

Thank you for your fast reply. Sorry for wasting your time, I figured it out.
It was quite some time ago already that I set this server up and there was an external allow list configured that caused this.
It is resolved now, thank you.
