### ISSUE TITLE
Query Logs Proplem

### ISSUE THREAD

**Issue by muhanadali100** [TechnitiumSoftware/DnsServer#899]
Error! The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.

**Comment by ShreyasZare** [comment]
Thanks for the post. Please share the full error entry that you will find in the Logs section on the panel.

**Comment by ShreyasZare** [comment]
Thanks for the details. Also share the exact OS name and version on which you are running the DNS server.

**Comment by muhanadali100** [comment]
Ubuntu 18.04.6 LTS 64Bit

DNS 12.1

**Comment by ShreyasZare** [comment]
> Ubuntu 18.04.6 LTS 64Bit
> 
> DNS 12.1

Thanks for the details. The problem is that the Sqlite library that the latest Query Logs app uses, no longer supports Ubuntu 18.04 for some unknown reasons. I have same issue on one of the servers and the known fix right now is to upgrade OS.
