### ISSUE TITLE
Opera can't open DNS GUI but Chrome can

### ISSUE THREAD

**Issue by nbctcp** [TechnitiumSoftware/DnsServer#90]
I can open http://localhost:5380/ using Chrome but not Opera
Its like empty page
Can anyone try using Opera?
tq

UPDATE1:
-using Opera Portable fix the problem
localhost is common problem in Opera Standard

**Comment by ShreyasZare** [comment]
The DNS web console is tested to work with Chrome, Firefox and Edge. Older/other browsers may not have implemented all CSS and JS features and that will cause the web console to fail to load.
