### ISSUE TITLE
Why does Technitium DNS Server create and keep so many connections to public dns server?

### ISSUE THREAD

**Issue by eplusresearch** [TechnitiumSoftware/DnsServer#900]
Hi Team,

My Technitium DNS Server is configured forwarder:
8.8.4.4
1.0.0.1
208.67.220.220
9.9.9.9

My Technitium DNS Server create and keep about 38k connect to above public dns. Is this unusual?

**Comment by mbah-dukun** [comment]
> Hai tim,
> 
> Server DNS Technitium saya dikonfigurasi penerusnya: 8.8.4.4 1.0.0.1 208.67.220.220 9.9.9.9
> 
> Server DNS Technitium saya membuat dan menyimpan sekitar 38k koneksi ke dns publik di atas. Apakah ini tidak biasa?

If you feel that there are too many simultaneous connections running, you should turn off the auto prefetch feature on the settings page

**Comment by ShreyasZare** [comment]
> If you feel that there are too many simultaneous connections running, you should turn off the auto prefetch feature on the settings page

This is nothing related to prefetch feature so it should not be changed.
