### ISSUE TITLE
There is a bug in filling in the doh in ip format in zone

### ISSUE THREAD

**Issue by liang-hiwin** [TechnitiumSoftware/DnsServer#903]
```

"data": "FailureCache: ServerFailure; Other: Resolver exception for dl.ghpig.top. A IN: Address must be a domain name: 101.101.101.101 (Parameter 'address')"
```

**Comment by ShreyasZare** [comment]
Thanks for the post. It looks like the DoH URL that you used is not in correct format. Please share the DoH URL that you tried.

**Comment by liang-hiwin** [comment]
> Thanks for the post. It looks like the DoH URL that you used is not in correct format. Please share the DoH URL that you tried.

https://101.101.101.101/dns-query

**Comment by ShreyasZare** [comment]
> https://101.101.101.101/dns-query

Thanks for the URL. Its working well as expected. Can you share a screenshot of your config so that it is clear how you are using it?

**Comment by ShreyasZare** [comment]
Thanks for the details. Will get this fixed in the next update.

**Comment by liang-hiwin** [comment]
> Thanks for the details. Will get this fixed in the next update.

OK, as long as you can reproduce the bug.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.2.1 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by liang-hiwin** [comment]
> Technitium DNS Server v12.2.1 is now available that fixes this issue. Do update and let me know your feedback.

Thanks for your reminder, there is no problem now.
