### ISSUE TITLE
Error allocating DHCP Addresses

### ISSUE THREAD

**Issue by rednus** [TechnitiumSoftware/DnsServer#908]
I have couple of devices that restart every night, and the next morning they are not on the network (ping fails) with below error repeating on the logs.  Not sure if this is an issue with the device, router (I use Nest Wifi Pro) or Technitium. Help please. 

[2024-04-22 11:45:59 Local] [0.0.0.0:68] DHCP Server offered IP address [192.168.1.33] to CAMERA [XX-XX-XX-XX-XX-XX] for scope: Default
[2024-04-22 11:46:00 Local] DHCP Server cannot allocate reserved lease [192.168.1.33] to XX-XX-XX-XX-XX-XX for scope 'Default': The IP address is already allocated.
[2024-04-22 11:46:00 Local] DHCP Server cannot allocate reserved lease [192.168.1.33] to XX-XX-XX-XX-XX-XX for scope 'Default': The IP address is already allocated.
[2024-04-22 11:46:00 Local] DHCP Server cannot allocate reserved lease [192.168.1.33] to XX-XX-XX-XX-XX-XX for scope 'Default': The IP address is already allocated.

Additional info: 
- I have a lot of my devices with fixed leases setup in the scope
- Most devices like mobiles & cars are not on network continuously
- Some devices are setup to reboot at each night
- Some devices can not be restarted easily to get new IP (like home power gateway or solar inverter)
- I have 3 nest wifi pro devices spread around the house (they use .252, .253 and .254)
- When the above error occurs the only way to resolve is to restart the network/router

**Comment by ShreyasZare** [comment]
Thanks for the post. I am assuming that the MAC addresses in these log entries are all same. Do you have the "Ignore Client Identifier (Option 61)" option enabled in your Default scope? Usually this issue comes up since some devices generate a new client identifier when they reboot and thus making it not possible to assign same IP address to them. Enabling the "Ignore Client Identifier (Option 61)" option fixes these kind of issues.

**Comment by rednus** [comment]
Hi Shreyas, 

I have enabled this option now. Will let you know if this has been resolved. 

Thanks

**Comment by ShreyasZare** [comment]
> I have enabled this option now. Will let you know if this has been resolved.

Since it was not enabled earlier, the existing reserved leases will need to be deleted manually otherwise existing clients wont receive these lease until they expire and would get a dynamic lease assigned till then.

**Comment by rednus** [comment]
Thanks. I only have 1 or 2 dynamic leases in the network all others are Reserved leases. 

I will restart the network when I get a chance.
