### ISSUE TITLE
TIP: Here's how to run (and debug) DnsServer as a Windows console app...

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#91]
Checkout https://alastaircrabtree.com/how-to-run-a-dotnet-windows-service-as-a-console-app/

I tried it.  It worked for me.

Best regards,
Michael Herman
Self-Sovereign Blockchain Architect
Hyperonomy Digital Identity Lab
Parallelspace Corporation

**Comment by ShreyasZare** [comment]
Thanks for the info. The DNS Server is already available as a console app so that you can directly run it for debugging or testing.
