### ISSUE TITLE
Use a combination of Cloudflare and Google DNS forwarders

### ISSUE THREAD

**Issue by hanxue** [TechnitiumSoftware/DnsServer#910]
I have been using Technitium for a while and appreciate how it resolves a lot of previous DNS lookup issues, thank you for making this piece of software open source!

I use Tchnitium as a DNS server to Windows 11, with DNS lookup forwarded to either Cloudflare or Google. There are some sites that do not work with Google DNS (most China sites, for example http://[szyyj.gd.gov.cn](http://szyyj.gd.gov.cn/zyyfw/ysbj/content/post_4004019.html)/zyyfw/ysbj/content/post_4004019.html) and some sites that do not work for Cloudflare (e.g. archive.today domains such as archive.is or archive.ph)

I have tried setting the forwarders to Cloudflare and Google, i.e. 

```
dns.google (8.8.8.8:853)
cloudflare-dns.com (1.1.1.1:853)
```

But the first DNS forwarder will always work. Therefore, in the example above, the szyyj.gd.gov.cn domain failed to be resolved by Technitium, despite having Cloudflare as the secondary forwarder. 

Is there a way to use **both** Cloudflare and Google DNS servers as forwarders?

**Comment by ShreyasZare** [comment]
Thanks for the post and compliments. 

When you use multiple forwarders, they are concurrently queries and the one which responds fastest is used.

If you wish to make a specific domain name use a specific forwarder then you need to create Conditional Forwarder Zone for that domain name. If there are too many domain names then use the Advanced Forwarding app.

**Comment by hanxue** [comment]
Hi @ShreyasZare , appreciate your quick response. Thanks, configuring a Conditional Forwarder Zone works!
