### ISSUE TITLE
Help, Looking for DHCP scope config file location

### ISSUE THREAD

**Issue by mikesiwer** [TechnitiumSoftware/DnsServer#919]
Help, Looking for DHCP config file location

I have done setup a scope. 
I checked /etc/dhcp. I couldn't find my scope settings.

I want to copy my current scope code to create another scope, just change name and subnet.
If I can find it , I will do automation later , much easier for devops .

**Comment by ShreyasZare** [comment]
Thanks for the post. The config files are in binary format and not recommended to be managed manually. Its recommended to use the [HTTP API](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md) to do all kinds of tasks or automation.

**Comment by mikesiwer** [comment]
thank you , I am use API now
