### ISSUE TITLE
FYI: DnsServer Logical Architecture Diagram

### ISSUE THREAD

**Issue by mwherman2000** [TechnitiumSoftware/DnsServer#92]
I'm starting with the DnsServer code as a baseline to create what I call a Universal Digital Identity (UDID) Server (UDIDServer) ...where what is considered a Domain in DNS becomes a Digital Subject in the world of Digital Identity.  My work is a fork off of the W3C Decentralized Identifier specification (https://w3c-ccg.github.io/did-spec/).

More specifically related to DnsServer, I have about a dozen new/custom resource records (RR) to add (primarily corresponding to the elements of a DID Document - see the did-spec above).  ...and I'm about half way done this task. DnsServer has been a great code base but it is a little tedious/error-prone when it comes to adding a new RR ...the code needs to be touched/adapted in many places ...soooo, I created the following DnsServer Logical Architecture Diagram to remind me where I need to make each of the changes for each new RR type.  Hope someone else finds this useful.  Caveat: Some of the elements in the diagram are specific to the changes I've made to the original DnsServer code base.

Best regards,
Michael Herman
Self-Sovereign Blockchain Architect
Hyperonomy Digital Identity Lab
Parallelspace Corporation

![image](https://user-images.githubusercontent.com/6101736/66501187-edf5a600-ea90-11e9-905b-378e406d8ab6.png)

**Comment by mwherman2000** [comment]
There are about 17 places in the code that have to be updated to add a new resource code to the server  (and client)...

![image](https://user-images.githubusercontent.com/6101736/66500139-095fb180-ea8f-11e9-8873-d9d3ba76698b.png)

**Comment by ShreyasZare** [comment]
Thanks for the detailed info.
