### ISSUE TITLE
Mixed Forwarders

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#920]
Is there a way to setup mixed forwarders like adguard?

Say use tls from google
HTTPS from cloudflare?

**Comment by ShreyasZare** [comment]
Thanks for asking. There is no option to mix protocols in the Settings so as to prevent misconfiguration when someone may configure an unencrypted transport with an encrypted one. But, you can still use mixed protocols using conditional forwarder zones. You just have to create a root zone (using `.` as the zone name) and then add more FWD records in it with different protocol.

The other option is to use the Advanced Forwarding app and configure it to use mixed forwarders that you define in the json config.

**Comment by ChristoffBo** [comment]
Thank you, makes adding different dns servers harder. Thank you for the
answer.
