### ISSUE TITLE
HTTP to HTTPS redirection using wrong hostname

### ISSUE THREAD

**Issue by Ninjadude101** [TechnitiumSoftware/DnsServer#922]
I'm using a Let's Encrypt certificate that has multiple subjects (certificate is shared with several docker containers) and I've noticed that with HTTP -> HTTPS redirection enabled, it's redirecting me to one of the other subjects from the certificate.
Rather than reading the certificate to determine where to redirect to, I think what should actually happen is one of the following:
1. Take the current hostname from headers and prefix with https:// 
2. Take the hostname from Settings > General > DNS Server Domain, and prefix with https://

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will test this and see how it can be improved.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v12.2.1 is now available that fixes this issue. Do update and let me know your feedback.
