### ISSUE TITLE
how to support nslookup to another network

### ISSUE THREAD

**Issue by sbjw** [TechnitiumSoftware/DnsServer#924]
The local DNS server is set up using technitium/dns-server, external computers can access the DNS server through VPN, but cannot perform normal DNS resolution after setting DNS, is it a problem with the DNS server? how to config it.

本地dns服务器是通过technitium/dns-server搭建的，外部电脑通过vpn可以访问通dns服务器，但是设置dns之后，不能进行正常的dns解析，是dns server的问题吗?  要如何配置才可以实现以上功能。

**Comment by ShreyasZare** [comment]
Thanks for the post. Its not clear how the network is setup but the known issue with VPN clients is that they enforce the DNS server that was assigned by the VPN server. This means, once VPN is connected, only the DNS servers provided by the VPN work and if you try to query any other DNS server on your local network, it would fail. This is done to prevent DNS leaks when using a VPN connection.
