### ISSUE TITLE
Allow / Block List URLs do not work as expected

### ISSUE THREAD

**Issue by cryptolukas** [TechnitiumSoftware/DnsServer#927]
Hi, i added google adservices to `Settings --> Blocking` but w/o any effect.
What I have to do to allow google ad services?

Content:
```
!https://www.googleadservices.com/
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
```

**Comment by ShreyasZare** [comment]
Thanks for the post. The Settings > Blocking option expects block list URLs and not the URLs that you want to block/allow.

So, you need to remove the URL from the settings to revert it back and instead add `googleadservices.com` in the Allowed section on the admin panel. This will allow the domain name and all its subdomain names to resolve.

**Comment by cryptolukas** [comment]
How can I exclude a specific domain if that is not the correct way?

**Comment by ShreyasZare** [comment]
> How can I exclude a specific domain if that is not the correct way?

I already mentioned how to exclude/allow domain by adding it in the Allowed section on the admin panel.

**Comment by cryptolukas** [comment]
Thank you. Now I got it.
