### ISSUE TITLE
[Feature Request] Allow specific domains/records to bypass cache 

### ISSUE THREAD

**Issue by NebulaMods** [TechnitiumSoftware/DnsServer#928]
It would be cool if Technitium could disable caching for a specific domain, record, or even zone.

This came to my mind for doing ACME DNS challenges for wildcard certificates, cache can cause some issues on the TXT records. So having the ability to whitelist said record, would make things simpler, and Adguard Home also has this ability if I am not mistaken.

**Comment by Hemsby** [comment]
I set the TTL for this to 0 for this reason.  Only for this records.  Stops clients and others caching it.

**Comment by NebulaMods** [comment]
> I set the TTL for this to 0 for this reason. Only for this records. Stops clients and others caching it.

Ah, this is smart. I didn't think of that.

> Thanks for the request. Adding such an option will actually be too complex to add and configure. Instead, I would suggest that you use the [HTTP API](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md#delete-cached-zone) to delete cache for specific domain name in your cert renewal process/script. You will need to generate a auth token from the admin panel to use with that HTTP GET call.

Oh okay, thanks for the tip.
