### ISSUE TITLE
question (DHCP Error)

### ISSUE THREAD

**Issue by j-roeber** [TechnitiumSoftware/DnsServer#93]
Hi,

great work your dns-server. I install Version 4 under Windows 10 (1809) and it seems that the dhcp-server is not working. The dhcp scope is added and configured but no client getting an ip-address. Perhaps and error or misconfiguration by myself? Scope is active and bind to interface.

With kind regards

J.Roeber

**Comment by ShreyasZare** [comment]
Thanks for the details. Your config seems to be good. It may be that you have not configured firewall to allow inbound udp port 67. Also do check the logs for any DHCP related error or events.

**Comment by j-roeber** [comment]
Hi,
that it was. The windows firewall have the corenetwork DHCP port (68) inbound open but not port 67. I opened it and it works. Thank for help.

J. Roeber

**Comment by muhanadali100** [comment]
My friend if your ip of your dns-server is 192.168.2.1 
and the gateway is 192.168.2.254
range ip : 192.168.2.10 - 192.168.2.190
for example the client is 192.168.2.10 
The client from where he will get internet ??

**Comment by Globulopolis** [comment]
@muhanadali100 from you gateway

**Comment by ShreyasZare** [comment]
> My friend if your ip of your dns-server is 192.168.2.1
> and the gateway is 192.168.2.254
> range ip : 192.168.2.10 - 192.168.2.190
> for example the client is 192.168.2.10
> The client from where he will get internet ??

You always setup default gateway for your clients to the IP address of your router. So, in this case your clients should be configured with 192.168.2.254 as gateway and your DHCP configuration must also use the same IP address for router option.
