### ISSUE TITLE
SOA Record Root

### ISSUE THREAD

**Issue by ChristoffBo** [TechnitiumSoftware/DnsServer#938]
Hi, when trying to add the root transfer i get an error DNS server failed to find SOA record for: <root>

Is there a way to add this record manually?

Kind regards

**Comment by ShreyasZare** [comment]
Thanks for the post. This error usually means that your network/ISP is blocking the SOA request to root servers. Try using the DNS Client tab to manually query for root `.` SOA record and see if you get any response. You can also set type to AXFR and see if you are able to do zone transfer for root zone using the DNS Client tab using your network.

**Comment by ChristoffBo** [comment]
Hi, Yes via the DNS app i can query root and get an answer, via AXFR and dns client i get Rcode=Server failure.

**Comment by ShreyasZare** [comment]
> Hi, Yes via the DNS app i can query root and get an answer, via AXFR and dns client i get Rcode=Server failure.

I did not get what you meant by "DNS app". Please you share some screenshots or DNS client output json text here.

**Comment by ChristoffBo** [comment]
Hi the dns Client
