### ISSUE TITLE
Sort logs by newest to older?

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#94]
The ability to display log results (log text) as newest to oldest would be useful.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Since the logs are stored as text files, it would be a bit difficult to reverse listing order. May be some sort of pagination option would help. I will look at options that can be implemented to make this possible.

**Comment by ShreyasZare** [comment]
This feature can be combined with #103. So closing this one here.
