### ISSUE TITLE
How to setup DNS name resolver using Technitium first, if not find, then use 8.8.8.8

### ISSUE THREAD

**Issue by mikesiwer** [TechnitiumSoftware/DnsServer#940]
Hi, 
I am new, this is a basic question.
I want to find domain name using [Technitium] DNS first, and if not found then use 8.8.8.8
I tried forwarders and it doesn't work, I may misconfig something.
<img width="1001" alt="Screenshot 2024-05-31 at 7 53 52 PM" src="https://github.com/TechnitiumSoftware/DnsServer/assets/20307652/95d53632-4b9e-4145-9a87-d7ff018598aa">
I find youtube video, but it only use 10 sec about forwarder part.
https://www.youtube.com/watch?v=o3hu7Lty7cY&ab_channel=YeehawItsJake

Please help.

**Comment by ShreyasZare** [comment]
Thanks for asking. The config looks right. What errors do you see in the DNS logs from the admin panel? Try using the DNS Client tab on the panel to test any domain and share the output here.

**Comment by mikesiwer** [comment]
Thanks a lot , problem solved.   I checked the log , I believe is my network provider DNS problem , I fix it.

**Comment by mikesiwer** [comment]
thank you so much. works

**Comment by mikesiwer** [comment]
thank you so much. works
