### ISSUE TITLE
IP Address Hints for both SVCB and HTTPS records

### ISSUE THREAD

**Issue by Kofl** [TechnitiumSoftware/DnsServer#947]
Hi,

really awesome work on IP Address Hints for both SVCB and HTTPS records in the latest release, really appreciated.

It tested over one hour every possible combination including zone transfers to 3rd party DNS servers and direct client lookup via dig and it works out really fine.

Only in one scenario there is a little inconstancy:

When on the DNS server the used A record for the IPv4 Hint is disabled, it stays in the https record. Its only removed in that case, when I edit the https record and just save it.

In all other cases (changed or deleted A record), its reflected automatically in the https record.

Thanks again.

**Comment by ShreyasZare** [comment]
Thanks for reporting this. The web app code for enable/disable buttons is missing one parameter which is causing the auto hints feature to be skipped at the backend. Will get this fixed in the next update.

**Comment by Kofl** [comment]
Great, no hurry from my side

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 is now available that fixes this issue. Do update and let me know your feedback.
