### ISSUE TITLE
[Feature Request] Api endpoint to enable/disable ad blocking 

### ISSUE THREAD

**Issue by Amateur-God** [TechnitiumSoftware/DnsServer#953]
would it be possible to add an API endpoint which can be used to enable and disable ad blocking

**Comment by ShreyasZare** [comment]
Thanks for asking. There is already HTTP API for all options. All the option that you see in the admin portal use HTTP API itself.

For disabling blocking, just use the following API call:
`http://localhost:5380/api/settings/set?token=x&enableBlocking=false`

You can read more about this call [here](https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md#set-dns-settings).

**Comment by Amateur-God** [comment]
Thank you, i thought i remembered seeing the api call in the docs but when i read them again to find it i must have missed that
