### ISSUE TITLE
IPv6 issue on technitium domain breaks apps

### ISSUE THREAD

**Issue by Jimbo5431** [TechnitiumSoftware/DnsServer#960]
I was trying to access the apps store, and it kept timing out. It was trying to access via the IPv6 for the domain.
Disabling IPv6 on the host, restarting the server, loading the app store and installing "Filter AAAA" has allowed me to bypass it.

The AAAA record for technitium.com is pointing to 2400:6180:100:d0::b3c:c001, which is not pingable.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. The website and the DNS App Store backend is working well over IPv6 and there are no other reports. 

The IPv6 address also responds to ping:
```
C:\Users\shrey>ping -6 download.technitium.com

Pinging technitium.com [2400:6180:100:d0::b3c:c001] with 32 bytes of data:
Reply from 2400:6180:100:d0::b3c:c001: time=68ms
Reply from 2400:6180:100:d0::b3c:c001: time=90ms
Reply from 2400:6180:100:d0::b3c:c001: time=65ms
Reply from 2400:6180:100:d0::b3c:c001: time=76ms

Ping statistics for 2400:6180:100:d0::b3c:c001:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 65ms, Maximum = 90ms, Average = 74ms
```

It probably was some ipv6 network issue at your ISP end which caused this issue. Do check again and see if its working. If not, you need to raise a ticket to your ISP.

**Comment by Jimbo5431** [comment]
All working now. It was tracing as far as digital-ocean in NL, so it was probably an issue in the NOC.
