### ISSUE TITLE
Can DHCP Server detect client windows version?

### ISSUE THREAD

**Issue by javad9505** [TechnitiumSoftware/DnsServer#962]
I have a DHCP server and several clients, some running Windows 10 and some Windows 7. I wuant the DHCP server to be able to identify the Windows version of the clients using the vendor class and assign the settings I've specified accordingly. Also, I don't want to configure anything on the clients; I want the DHCP server to be able to detect the Windows version by itself. Is there a way to do this?

**Comment by ShreyasZare** [comment]
Thanks for asking. The DHCP server currently does not support the feature to provide different options based on vendor class identifier. But, this is something planned and will be implemented in later releases.

Also, Windows does not send anything specific that can be used to identify its version so I don't think this would be possible even if the DHCP server supported the feature.
