### ISSUE TITLE
Not resolved some websites

### ISSUE THREAD

**Issue by Alex-cmd1** [TechnitiumSoftware/DnsServer#967]
First I want to thank you for your wonderful product, I love it so much

I have a problem that I can't solve. I installed Technitium DNS and all my settings are default as they were right after installation, I didn't change anything. Everything is working fine, but there is a problem that two sites https://www.dns-shop.ru/ and https://www.citilink.ru/ are not opening. When I check these sites through DNS Client they are resolved normally and there are no errors in the logs, but in fact they do not open in any browser and the browser gives errors **NS_BINDING_ABORTED** or **NS_ERROR_NET_INTERRUPT**, screenshots are attached

It is quite possible that there are many more such sites, but so far I've only come across two

I'm using Technitium DNS for Linux

https://www.dns-shop.ru/ 
![T001](https://github.com/user-attachments/assets/8b2f3ccd-5ba0-4f76-876d-a7917632de83)

https://www.citilink.ru/ 
![T002](https://github.com/user-attachments/assets/e0bfc7cb-6192-4974-82e8-703de027b0de)

**Comment by ShreyasZare** [comment]
Thanks for the post. If you can see that these domain names are resolving using the DNS Client tool in the admin panel then DNS is working well. These issues seem to be something else and not related to DNS.

Try changing your web browser and see if that works since a few references on the Internet claim that there is bug in Firefox that can cause this errors if the website has HTTP/3 enabled.

**Comment by Alex-cmd1** [comment]
> Thanks for the post. If you can see that these domain names are resolving using the DNS Client tool in the admin panel then DNS is working well. These issues seem to be something else and not related to DNS.
> 
> Try changing your web browser and see if that works since a few references on the Internet claim that there is bug in Firefox that can cause this errors if the website has HTTP/3 enabled.

Unfortunately it is not browser dependent, the same thing happens in Chrome but with a different **ERR_CONNECTION_CLOSED** error, moreover, the mobile app that https://www.dns-shop.ru/ and https://www.citilink.ru/ have is also partially loaded. The problem is solved when I enable Forwarders on Cloudflare's DoH

Chrome
![T003](https://github.com/user-attachments/assets/1aeb004e-0d5c-42d9-a8dc-a45c7fb6d8df)

**Comment by ShreyasZare** [comment]
> Unfortunately it is not browser dependent, the same thing happens in Chrome but with a different **ERR_CONNECTION_CLOSED** error, moreover, the mobile app that https://www.dns-shop.ru/ and https://www.citilink.ru/ have is also partially loaded. The problem is solved when I enable Forwarders on Cloudflare's DoH

Thanks for the details. It looks like some kind of transient network issue. Probably Cloudflare is returning out different IP address which may be why its working.

**Comment by Alex-cmd1** [comment]
> > Unfortunately it is not browser dependent, the same thing happens in Chrome but with a different **ERR_CONNECTION_CLOSED** error, moreover, the mobile app that https://www.dns-shop.ru/ and https://www.citilink.ru/ have is also partially loaded. The problem is solved when I enable Forwarders on Cloudflare's DoH
> 
> Thanks for the details. It looks like some kind of transient network issue. Probably Cloudflare is returning out different IP address which may be why its working.

I solved the problem, I just added the root server 192.112.36.4 (g.root-servers.net) to the Primary Zone and everything worked fine. I don't understand why it didn't work with the default server :)

**Comment by Alex-cmd1** [comment]
> > Unfortunately it is not browser dependent, the same thing happens in Chrome but with a different **ERR_CONNECTION_CLOSED** error, moreover, the mobile app that https://www.dns-shop.ru/ and https://www.citilink.ru/ have is also partially loaded. The problem is solved when I enable Forwarders on Cloudflare's DoH
> 
> Thanks for the details. It looks like some kind of transient network issue. Probably Cloudflare is returning out different IP address which may be why its working.

I solved the problem, I just added the root server 192.112.36.4 (g.root-servers.net) to the Primary Zone and everything worked fine. I don't understand why it didn't work with the default server :) 

From a security standpoint, doesn't this compromise the security of my DNS server?

**Comment by Alex-cmd1** [comment]
> > Unfortunately it is not browser dependent, the same thing happens in Chrome but with a different **ERR_CONNECTION_CLOSED** error, moreover, the mobile app that https://www.dns-shop.ru/ and https://www.citilink.ru/ have is also partially loaded. The problem is solved when I enable Forwarders on Cloudflare's DoH
> 
> Thanks for the details. It looks like some kind of transient network issue. Probably Cloudflare is returning out different IP address which may be why its working.

I noticed one pattern that when I click Flush Cache in Technitium DNS, the problem with loading these sites disappears and they load normally. But after some time the problem repeats and these sites do not load again. Is it possible that this is somehow connected with the cache?

**Comment by Alex-cmd1** [comment]
> > Unfortunately it is not browser dependent, the same thing happens in Chrome but with a different **ERR_CONNECTION_CLOSED** error, moreover, the mobile app that https://www.dns-shop.ru/ and https://www.citilink.ru/ have is also partially loaded. The problem is solved when I enable Forwarders on Cloudflare's DoH
> 
> Thanks for the details. It looks like some kind of transient network issue. Probably Cloudflare is returning out different IP address which may be why its working.

I solved the problem, I just added the root server 192.112.36.4 (g.root-servers.net) to the Primary Zone and everything worked fine. I don't understand why it didn't work with the default server :) 

From a security standpoint, doesn't this compromise the security of my DNS server?

**Comment by ShreyasZare** [comment]
It seems that there is DNS hijacking being deployed by your ISP. 

Try to run `nslookup google.com. 1.2.3.4` in CMD and see if you get a response. If there is a response then there is DNS hijack setup. If no response then it does not rule out other types of hijack techniques.

You can also try the DNS Client tool on the DNS admin panel and select `Recursive Query {recursive-resolver}` as the Server and run query for any domain name. Inspect the response to see which name server is answering it. If you see root servers answering directly then that is also a hijack.

In any case, if using encrypted DNS forwarders makes things work then use them instead of running recursive resolver.

**Comment by hkof** [comment]
I had the same issue for a different site, and after some digging, I found out (using **dig**) that the website was blocked by my blocking lists. Most likely, this is what is happening here. DNS Client (I think) goes through the blocking lists, and you will see the same behavior across all DNS providers.

```
dig ***.com

; <<>> DiG 9.**** <<>> ***.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26285
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 15 (Blocked): (source=block-list-zone; blockListUrl=https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt; domain=dev)
; EDE: 15 (Blocked): (source=block-list-zone; blockListUrl=https://github.com/uBlockOrigin/uAssets/blob/master/filters/lan-block.txt; domain=dev)
;; QUESTION SECTION:
;***.com.              IN      A
......
```
