### ISSUE TITLE
Automatic propagation

### ISSUE THREAD

**Issue by amirmnoohi** [TechnitiumSoftware/DnsServer#968]
Hi,

I have four servers. One of them acts as a Primary Zone, and the rest act as a Secondary Zone.

The problem I have is that I want to add a domain only in the primary zone, and all other servers automatically add this domain as a secondary zone and get synchronized.

Would you happen to know how I can do this?

**Comment by ShreyasZare** [comment]
Thanks for asking. Its not possible to do that in the current release. But, the next release will include [Catalog Zones [RFC 9432]](https://www.rfc-editor.org/rfc/rfc9432.html) feature which will allow you to automatically create/delete secondary zones when you add/delete them on primary server. This is the same feature that is available in [BIND](https://bind9.readthedocs.io/en/v9.18.13/chapter6.html#catalog-zones). Work on this is already underway.

**Comment by FlossFarrier** [comment]
That is really awesome @ShreyasZare 

Thank you.

**Comment by amirmnoohi** [comment]
Thanks @ShreyasZare I love this feature.
Then, I close this issue.
