### ISSUE TITLE
Some domain names resolve the wrong IP address, which is correct if you use public DNS

### ISSUE THREAD

**Issue by oular** [TechnitiumSoftware/DnsServer#979]
For example, g.csdnimg.cn

**Comment by ShreyasZare** [comment]
Thanks for the post. A domain name can return different IP addresses and its not an issue. Usually this is done by CDN networks to optimize content delivery such that end users always connect to the closest servers.

So, you are bound to get different answers if you resolve directly and resolve via public DNS servers.
