### ISSUE TITLE
Configure Technitium DNS To Cloudflare

### ISSUE THREAD

**Issue by ikhsankudir** [TechnitiumSoftware/DnsServer#981]
Hello Everyone
sorry to disturb your time

I have a VM, then in the VM there is my WordPress website, so to access my WordPress server online, I connect to Cloudflare using the Cloudflare Docker tunnel, so I want when a user accesses my website, Cloudfalre will send it to Technitium and I can see who only those who can access it, is this kosnep possible?

Thank you very much

**Comment by ShreyasZare** [comment]
Thanks for the post. Technitium DNS Server can host only your domain name. It does not transport your website's traffic.
