### ISSUE TITLE
Rootless docker container

### ISSUE THREAD

**Issue by xlemassacre** [TechnitiumSoftware/DnsServer#989]
The current docker container needs full root permissions.
I tried to change the user / limit the permissions in my kubernetes setup, but then the container is not able to start any ports. The application itself was working (also the webinterface).

For security reasons it would be nice to run the container rootless

**Comment by ShreyasZare** [comment]
Thanks for the post. This is not an issue with the docker container itself but a security requirement under Linux to be able to listen on port less than 1024. You will need to manually configure your host to allow the container to use lower numbered ports without need to run as root. Take a look at [this post](https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443) for clues.

**Comment by ShreyasZare** [comment]
> Thanks for the post. This is not an issue with the docker container itself but a security requirement under Linux to be able to listen on port less than 1024. You will need to manually configure your host to allow the container to use lower numbered ports without need to run as root. Take a look at [this post](https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443) for clues. This [another post](https://serverfault.com/questions/1108735/how-to-allow-a-docker-container-to-bind-a-privileged-port-as-another-user) gives docker specific answer.

**Comment by xlemassacre** [comment]
Thanks for the quick response.
I was able now to start the container as a non-root user. Instead port 53 now a port >1024 is used, and kubernetes does a mapping from 53 to that port.
