### ISSUE TITLE
* wildcard does not seem to block all sites?

### ISSUE THREAD

**Issue by hl2guide** [TechnitiumSoftware/DnsServer#99]
The asterisk (*) does not seem to block all sites when added in the Blocked Zones section.

I'm trying to test DnsServer in a whitelist-only mode.

When I tried I got:

`
[
  {
    "name": "*",
    "type": "A",
    "ttl": "60 (1 min)",
    "rData": {
      "value": "0.0.0.0"
    }
  },
  {
    "name": "*",
    "type": "SOA",
    "ttl": "60 (1 min)",
    "rData": {
      "masterNameServer": "dpc",
      "responsiblePerson": "hostmaster.dpc",
      "serial": 1,
      "refresh": 28800,
      "retry": 7200,
      "expire": 604800,
      "minimum": 600
    }
  },
  {
    "name": "*",
    "type": "TXT",
    "ttl": "60 (1 min)",
    "rData": {
      "value": "blockList=custom"
    }
  },
  {
    "name": "*",
    "type": "AAAA",
    "ttl": "60 (1 min)",
    "rData": {
      "value": "::"
    }
  }
]
`

**Comment by ShreyasZare** [comment]
Thanks for the feedback. I just did a test by entering \* into Blocked Zones and then tested it by querying the server using DNS Client tab and it is working well. When a specific domain name is entered into Allowed Zones then that domain name was resolving correctly while any other domain are blocked.

The json data that you have posted is the zone details for the blocked zone and is not DNS response.

Try querying using the built in DNS Client or use command line tools like nslookup to test.

Do let me know if it worked.

**Comment by ShreyasZare** [comment]
closing this issue as no bug was found.
