### ISSUE TITLE
REQUEST: Forwarder sequental/strict order

### ISSUE THREAD

**Issue by chmichael** [TechnitiumSoftware/DnsServer#997]
Details https://github.com/TechnitiumSoftware/DnsServer/discussions/993

**Comment by ShreyasZare** [comment]
Thanks for posting it here. Will get this option added in the upcoming update.

**Comment by chmichael** [comment]
Is it also possible to add query from Root Servers if all Forwarders fail ? (Like Windows DNS Server has)

**Comment by ShreyasZare** [comment]
Thanks for asking. This is already implemented with Conditional Forwarder zone and will be available in the upcoming update where you will be able to specify priority for forwarders and also have `this-server` as a low priority forwarder.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 is now available that gives an option to disable concurrent forwarding which will enable sequential use of forwarders. Do update and let me know your feedback.

**Comment by chmichael** [comment]
Testing atm and works like charm!

Thank you!

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
