### ISSUE TITLE
Query Logs breaks if your session expires

### ISSUE THREAD

**Issue by alexhorner** [TechnitiumSoftware/DnsServer#998]
If you're logged in and on the Query Logs page, then click the Query button after your session expires, you'll be sent back to the login page. However, once you have logged in again the Query button becomes unclickable until you refresh the page entirely.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. Will get this fixed in the upcoming update.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v13 is now available that fixes this issue. Do update and let me know your feedback.

**Comment by alexhorner** [comment]
@ShreyasZare Looks to be working fine now!

**Comment by ShreyasZare** [comment]
Thanks for the feedback!
